using Agro360.Application.Contracts;
using Agro360.Domain.Commercial;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class Commercial360Service(DatabaseExecutor db,ITenantContext tenant) : ICommercial360Service
{
 private static readonly Dictionary<string,string> Resources=new(StringComparer.OrdinalIgnoreCase){
  ["customers"]="agro360.crm_customers",["segments"]="agro360.crm_customer_segments",["contacts"]="agro360.crm_contacts",["representatives"]="agro360.sales_representatives",["opportunities"]="agro360.sales_opportunities",["activities"]="agro360.sales_activities",["price-tables"]="agro360.sales_price_tables",["orders"]="agro360.sales_orders",["contracts"]="agro360.sales_contracts",["commissions"]="agro360.sales_commissions",["splits"]="agro360.sales_split_agreements",["targets"]="agro360.sales_targets",["products"]="agro360.inventory_products"};

 public Task<CommercialPage<CommercialRecord>> ListAsync(string resource,string? search,string? status,int page,int pageSize,CancellationToken ct)=>db.InTenantTransactionAsync<CommercialPage<CommercialRecord>>(async(c,t)=>{
  var table=Table(resource);page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var offset=(page-1)*pageSize;
  var name=resource switch{"orders"=>"order_number","commissions"=>"coalesce(status,'EXPECTED')","splits"=>"name",_=>"name"};
  var amount=resource switch{"opportunities"=>"estimated_value","orders"=>"total_amount","contracts"=>"contracted_value","commissions"=>"amount","splits"=>"0",_=>"0"};
  var sql=$"select id,{name} name,status,cast(null as text) detail,{amount} amount,updated_at updatedat from {table} where tenant_id=@TenantId and deleted_at is null and (@Search is null or {name} ilike '%'||@Search||'%') and (@Status is null or status=@Status) order by updated_at desc limit @PageSize offset @Offset; select count(*) from {table} where tenant_id=@TenantId and deleted_at is null and (@Search is null or {name} ilike '%'||@Search||'%') and (@Status is null or status=@Status)";
  using var multi=await c.QueryMultipleAsync(sql,new{tenant.TenantId,Search=string.IsNullOrWhiteSpace(search)?null:search,Status=string.IsNullOrWhiteSpace(status)?null:status,PageSize=pageSize,Offset=offset},t);var rows=(await multi.ReadAsync<CommercialRecord>()).ToArray();var total=await multi.ReadSingleAsync<int>();return new(rows,page,pageSize,total);},ct);

 public Task<IReadOnlyList<CommercialLookup>> LookupAsync(string resource,string? search,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{
  var table=Table(resource);var name=resource=="orders"?"order_number":"name";return (IReadOnlyList<CommercialLookup>)(await c.QueryAsync<CommercialLookup>($"select id,{name} label,status from {table} where tenant_id=@TenantId and deleted_at is null and (@Search is null or {name} ilike '%'||@Search||'%') order by {name} limit 30",new{tenant.TenantId,Search=string.IsNullOrWhiteSpace(search)?null:search},t)).ToArray();},ct);

 public Task<Guid> SaveCustomerAsync(Guid? id,CustomerCommand command,CancellationToken ct){CommercialRules.ValidateTaxDocument(command.TaxDocument);return db.InTenantTransactionAsync(async(c,t)=>{var entityId=id??Guid.CreateVersion7();var n=await c.ExecuteAsync(id is null?"insert into agro360.crm_customers(id,tenant_id,segment_id,representative_id,name,type,tax_document,email,phone,status,notes,created_by,updated_by) values(@Id,@TenantId,@SegmentId,@RepresentativeId,@Name,@Type,@TaxDocument,@Email,@Phone,'ACTIVE',@Notes,@UserId,@UserId)":"update agro360.crm_customers set segment_id=@SegmentId,representative_id=@RepresentativeId,name=@Name,tax_document=@TaxDocument,email=@Email,phone=@Phone,notes=@Notes,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and deleted_at is null",new{Id=entityId,tenant.TenantId,command.SegmentId,command.RepresentativeId,command.Name,Type=command.Type.ToUpperInvariant(),command.TaxDocument,command.Email,command.Phone,command.Notes,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Cliente não encontrado.");return entityId;},ct);}

 public Task<Guid> SaveOpportunityAsync(Guid? id,OpportunityCommand command,CancellationToken ct){CommercialRules.ValidateOpportunity(command.Stage,command.EstimatedValue,command.LossReason);if(command.ExpectedClose is not null&&command.ExpectedClose<DateOnly.FromDateTime(DateTime.UtcNow))throw new ArgumentException("A data prevista não pode estar no passado.");return db.InTenantTransactionAsync(async(c,t)=>{var entityId=id??Guid.CreateVersion7();string? old=null;if(id is not null)old=await c.ExecuteScalarAsync<string?>("select stage from agro360.sales_opportunities where id=@Id and tenant_id=@TenantId",new{Id=entityId,tenant.TenantId},t);var n=await c.ExecuteAsync(id is null?"insert into agro360.sales_opportunities(id,tenant_id,customer_id,product_id,representative_id,name,estimated_value,stage,probability,expected_close,source,next_action,loss_reason,created_by,updated_by) values(@Id,@TenantId,@CustomerId,@ProductId,@RepresentativeId,@Name,@EstimatedValue,@Stage,@Probability,@ExpectedClose,@Source,@NextAction,@LossReason,@UserId,@UserId)":"update agro360.sales_opportunities set customer_id=@CustomerId,product_id=@ProductId,representative_id=@RepresentativeId,name=@Name,estimated_value=@EstimatedValue,stage=@Stage,probability=@Probability,expected_close=@ExpectedClose,source=@Source,next_action=@NextAction,loss_reason=@LossReason,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and deleted_at is null",new{Id=entityId,tenant.TenantId,command.CustomerId,command.ProductId,command.RepresentativeId,command.Name,command.EstimatedValue,Stage=command.Stage.ToUpperInvariant(),command.Probability,command.ExpectedClose,command.Source,command.NextAction,command.LossReason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Oportunidade não encontrada.");if(id is null||old!=command.Stage)await c.ExecuteAsync("insert into agro360.sales_opportunity_history(id,tenant_id,opportunity_id,from_stage,to_stage,changed_by) values(gen_random_uuid(),@TenantId,@Id,@Old,@Stage,@UserId)",new{tenant.TenantId,Id=entityId,Old=old,Stage=command.Stage.ToUpperInvariant(),tenant.UserId},t);return entityId;},ct);}

 public Task<Guid> SaveActivityAsync(Guid? id,ActivityCommand command,CancellationToken ct){if(command.Status=="COMPLETED"&&string.IsNullOrWhiteSpace(command.Result))throw new ArgumentException("Atividade concluída exige resultado.");if(command.Status=="CANCELLED"&&string.IsNullOrWhiteSpace(command.CancellationReason))throw new ArgumentException("Cancelamento exige motivo.");return db.InTenantTransactionAsync(async(c,t)=>{var entityId=id??Guid.CreateVersion7();var n=await c.ExecuteAsync(id is null?"insert into agro360.sales_activities(id,tenant_id,customer_id,representative_id,name,type,scheduled_at,status,channel,result,next_action,notes,cancellation_reason,created_by,updated_by) values(@Id,@TenantId,@CustomerId,@RepresentativeId,@Type,@Type,@ScheduledAt,@Status,@Channel,@Result,@NextAction,@Notes,@CancellationReason,@UserId,@UserId)":"update agro360.sales_activities set customer_id=@CustomerId,representative_id=@RepresentativeId,type=@Type,name=@Type,scheduled_at=@ScheduledAt,status=@Status,channel=@Channel,result=@Result,next_action=@NextAction,notes=@Notes,cancellation_reason=@CancellationReason,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId",new{Id=entityId,tenant.TenantId,command.CustomerId,command.RepresentativeId,Type=command.Type.ToUpperInvariant(),command.ScheduledAt,Status=command.Status.ToUpperInvariant(),command.Channel,command.Result,command.NextAction,command.Notes,command.CancellationReason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException();return entityId;},ct);}

 public Task<Guid> CreateOrderAsync(SalesOrderCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(command.ExpectedDelivery is not null&&command.ExpectedDelivery<DateOnly.FromDateTime(DateTime.UtcNow))throw new ArgumentException("A data de entrega não pode estar no passado.");var customer=await c.ExecuteScalarAsync<string?>("select status from agro360.crm_customers where id=@CustomerId and tenant_id=@TenantId and deleted_at is null",new{tenant.TenantId,command.CustomerId},t)??throw new KeyNotFoundException("Cliente não encontrado.");CommercialRules.CustomerCanOrder(customer,false);var total=CommercialRules.ValidateOrder(command.Items.Select(i=>(i.Quantity,i.UnitPrice,i.DiscountPercentage,i.MaximumDiscount)));var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.sales_orders(id,tenant_id,customer_id,representative_id,property_id,contract_id,order_number,status,total_amount,freight,payment_terms,expected_delivery,notes,created_by,updated_by) values(@Id,@TenantId,@CustomerId,@RepresentativeId,@PropertyId,@ContractId,'PED-'||nextval('agro360.sales_order_number_seq'),'DRAFT',@Total,@Freight,@PaymentTerms,@ExpectedDelivery,@Notes,@UserId,@UserId)",new{Id=id,tenant.TenantId,command.CustomerId,command.RepresentativeId,command.PropertyId,command.ContractId,Total=total+command.Freight,command.Freight,command.PaymentTerms,command.ExpectedDelivery,command.Notes,tenant.UserId},t);foreach(var i in command.Items)await c.ExecuteAsync("insert into agro360.sales_order_items(id,tenant_id,order_id,product_id,lot_id,quantity,unit,unit_price,discount_percentage,total_amount) values(gen_random_uuid(),@TenantId,@OrderId,@ProductId,@LotId,@Quantity,@Unit,@UnitPrice,@DiscountPercentage,round(@Quantity*@UnitPrice*(1-@DiscountPercentage/100),2))",new{tenant.TenantId,OrderId=id,i.ProductId,i.LotId,i.Quantity,i.Unit,i.UnitPrice,i.DiscountPercentage},t);return id;},ct);

 public Task ChangeOrderStatusAsync(Guid id,StatusCommand command,bool mayOverrideBlock,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(command.Status=="CANCELLED"&&string.IsNullOrWhiteSpace(command.Reason))throw new ArgumentException("Cancelamento exige motivo.");if(command.Status=="APPROVED"){var status=await c.ExecuteScalarAsync<string?>("select c.status from agro360.sales_orders o join agro360.crm_customers c on c.id=o.customer_id and c.tenant_id=o.tenant_id where o.id=@Id and o.tenant_id=@TenantId",new{Id=id,tenant.TenantId},t)??throw new KeyNotFoundException();CommercialRules.CustomerCanOrder(status,mayOverrideBlock);if(!await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.sales_order_items where order_id=@Id and tenant_id=@TenantId)",new{Id=id,tenant.TenantId},t))throw new ArgumentException("Pedido sem itens.");}var n=await c.ExecuteAsync("update agro360.sales_orders set status=@Status,cancellation_reason=@Reason,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and deleted_at is null",new{Id=id,tenant.TenantId,Status=command.Status.ToUpperInvariant(),command.Reason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException();await c.ExecuteAsync("insert into agro360.sales_commercial_events(id,tenant_id,event_type,aggregate_id,payload,created_by) values(gen_random_uuid(),@TenantId,@Type,@Id,jsonb_build_object('status',@Status),@UserId)",new{tenant.TenantId,Type=$"ORDER_{command.Status.ToUpperInvariant()}",Id=id,Status=command.Status.ToUpperInvariant(),tenant.UserId},t);if(command.Status=="CANCELLED")await c.ExecuteAsync("update agro360.sales_commissions set status='CANCELLED',updated_at=now() where tenant_id=@TenantId and order_id=@Id and status not in('PAID','REVERSED'); update agro360.sales_split_entries set status='CANCELLED',updated_at=now() where tenant_id=@TenantId and order_id=@Id and status='EXPECTED'",new{tenant.TenantId,Id=id},t);},ct);

 public Task<Guid> CalculateCommissionAsync(CommissionCommand command,CancellationToken ct){var amount=CommercialRules.Commission(command.Basis,command.Percentage,command.FixedValue);return db.InTenantTransactionAsync(async(c,t)=>{if(await c.ExecuteScalarAsync<string?>("select status from agro360.sales_orders where id=@OrderId and tenant_id=@TenantId",new{tenant.TenantId,command.OrderId},t)!="APPROVED")throw new ArgumentException("A comissão só pode ser calculada para pedido aprovado.");var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.sales_commissions(id,tenant_id,order_id,rule_id,representative_id,basis,percentage,fixed_value,amount,status,created_by,updated_by) values(@Id,@TenantId,@OrderId,@RuleId,@RepresentativeId,@Basis,@Percentage,@FixedValue,@Amount,'EXPECTED',@UserId,@UserId)",new{Id=id,tenant.TenantId,command.OrderId,command.RuleId,command.RepresentativeId,command.Basis,command.Percentage,command.FixedValue,Amount=amount,tenant.UserId},t);return id;},ct);}
 public Task ChangeCommissionStatusAsync(Guid id,StatusCommand command,CancellationToken ct)=>ChangeStatus("agro360.sales_commissions",id,command,true,ct);
 public Task<Guid> SaveSplitAsync(SplitAgreementCommand command,CancellationToken ct){CommercialRules.ValidateSplit(command.Participants.Select(p=>(p.ParticipantId,p.Percentage,p.FixedValue)));return db.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.sales_split_agreements(id,tenant_id,order_id,contract_id,name,status,release_rule,created_by,updated_by) values(@Id,@TenantId,@OrderId,@ContractId,@Name,'DRAFT',@ReleaseRule,@UserId,@UserId)",new{Id=id,tenant.TenantId,command.OrderId,command.ContractId,command.Name,command.ReleaseRule,tenant.UserId},t);foreach(var p in command.Participants)await c.ExecuteAsync("insert into agro360.sales_split_participants(id,tenant_id,agreement_id,participant_id,participant_type,percentage,fixed_value,priority) values(gen_random_uuid(),@TenantId,@AgreementId,@ParticipantId,@ParticipantType,@Percentage,@FixedValue,@Priority)",new{tenant.TenantId,AgreementId=id,p.ParticipantId,p.ParticipantType,p.Percentage,p.FixedValue,p.Priority},t);return id;},ct);}
 public Task ChangeSplitStatusAsync(Guid id,StatusCommand command,CancellationToken ct)=>ChangeStatus("agro360.sales_split_agreements",id,command,false,ct);
 private Task ChangeStatus(string table,Guid id,StatusCommand command,bool reasonRequired,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var status=command.Status.ToUpperInvariant();if(reasonRequired&&status is ("BLOCKED" or "REVERSED")&&string.IsNullOrWhiteSpace(command.Reason))throw new ArgumentException("Informe a justificativa.");var n=await c.ExecuteAsync($"update {table} set status=@Status,status_reason=@Reason,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and deleted_at is null",new{Id=id,tenant.TenantId,Status=status,command.Reason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException();},ct);

 public Task<CommercialDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync<CommercialDashboard>(async(c,t)=>{var sql="select count(*) filter(where status='ACTIVE') activecustomers,count(*) filter(where status='BLOCKED') blockedcustomers from agro360.crm_customers where tenant_id=@TenantId and deleted_at is null; select count(*) from agro360.sales_contracts where tenant_id=@TenantId and status='ACTIVE' and deleted_at is null; select coalesce(sum(estimated_value),0) from agro360.sales_opportunities where tenant_id=@TenantId and stage not in('WON','LOST') and deleted_at is null; select coalesce(sum(total_amount),0) from agro360.sales_orders where tenant_id=@TenantId and status not in('CANCELLED','DELIVERED') and deleted_at is null; select coalesce(sum(amount) filter(where status='EXPECTED'),0),coalesce(sum(amount) filter(where status='PAID'),0) from agro360.sales_commissions where tenant_id=@TenantId and deleted_at is null; select coalesce(sum(amount),0) from agro360.sales_split_entries where tenant_id=@TenantId and status='EXPECTED';";using var m=await c.QueryMultipleAsync(sql,new{tenant.TenantId},t);var customers=await m.ReadSingleAsync<(int ActiveCustomers,int BlockedCustomers)>();var contracts=await m.ReadSingleAsync<int>();var pipeline=await m.ReadSingleAsync<decimal>();var forecast=await m.ReadSingleAsync<decimal>();var commissions=await m.ReadSingleAsync<(decimal Expected,decimal Paid)>();var splits=await m.ReadSingleAsync<decimal>();var opp=(await ListAsync("opportunities",null,null,1,6,ct)).Items;var orders=(await ListAsync("orders",null,null,1,6,ct)).Items;return new(customers.ActiveCustomers,customers.BlockedCustomers,contracts,pipeline,forecast,commissions.Expected,commissions.Paid,splits,opp,orders);},ct);
 private static string Table(string resource)=>Resources.TryGetValue(resource,out var table)?table:throw new KeyNotFoundException("Recurso comercial não encontrado.");
}
