using System.Text;
using Agro360.Application.Contracts;
using Agro360.Domain.Compliance;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class ComplianceService(DatabaseExecutor db, ITenantContext tenant) : IComplianceService
{
    public Task<IReadOnlyList<ComplianceDocument>> DocumentsAsync(string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<ComplianceDocument>)(await c.QueryAsync<ComplianceDocument>("select d.id,d.type,d.number,s.name subjectname,d.issued_on issuedon,d.expires_on expireson,u.name responsiblename,case when d.expires_on<current_date then 'EXPIRED' when d.expires_on<=current_date+30 then 'EXPIRING' else d.status end status,(select count(*) from agro360.compliance_evidence e where e.entity_type='DOCUMENT' and e.entity_id=d.id) evidencecount from agro360.compliance_documents d join agro360.compliance_subjects s on s.id=d.subject_id join agro360.identity_users u on u.id=d.responsible_id where d.tenant_id=@TenantId and (@Status is null or (case when d.expires_on<current_date then 'EXPIRED' when d.expires_on<=current_date+30 then 'EXPIRING' else d.status end)=@Status) order by d.expires_on",new{tenant.TenantId,Status=status},t)).ToArray(),ct);
    public Task<Guid> SaveDocumentAsync(Guid? id,DocumentCommand x,CancellationToken ct){if(x.ExpiresOn<x.IssuedOn)throw new ArgumentException("Vencimento deve ser posterior à emissão.");return Upsert(id,"documents",new{id=id??Guid.NewGuid(),tenant.TenantId,x.Type,x.Number,x.SubjectId,x.IssuedOn,x.ExpiresOn,x.ResponsibleId,x.Notes},"type,number,subject_id,issued_on,expires_on,responsible_id,notes","@Type,@Number,@SubjectId,@IssuedOn,@ExpiresOn,@ResponsibleId,@Notes",ct);}
    public Task<IReadOnlyList<ProductRule>> RulesAsync(Guid? productId,string? market,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<ProductRule>)(await c.QueryAsync<ProductRule>("select r.id,p.name productname,r.market,r.name,r.mandatory,r.blocks_sale blockssale,r.blocks_export blocksexport,r.required_documents requireddocuments,r.status from agro360.compliance_product_rules r join agro360.inventory_products p on p.id=r.product_id where r.tenant_id=@TenantId and (@ProductId is null or r.product_id=@ProductId) and (@Market is null or r.market=@Market) order by p.name,r.market",new{tenant.TenantId,ProductId=productId,Market=market},t)).ToArray(),ct);
    public Task<Guid> SaveRuleAsync(Guid? id,ProductRuleCommand x,CancellationToken ct)=>Upsert(id,"product_rules",new{id=id??Guid.NewGuid(),tenant.TenantId,x.ProductId,x.Market,x.Name,x.Mandatory,x.BlocksSale,x.BlocksExport,x.RequiredDocuments},"product_id,market,name,mandatory,blocks_sale,blocks_export,required_documents","@ProductId,@Market,@Name,@Mandatory,@BlocksSale,@BlocksExport,@RequiredDocuments",ct);
    public Task SetLotBlockAsync(Guid lotId,bool blocked,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo é obrigatório.");return db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("insert into agro360.compliance_lot_decisions(id,tenant_id,lot_id,blocked,reason,decided_by) values(gen_random_uuid(),@TenantId,@LotId,@Blocked,@Reason,@UserId); update agro360.storage_lots set status=case when @Blocked then 'BLOCKED' else 'AVAILABLE' end where tenant_id=@TenantId and id=@LotId",new{tenant.TenantId,lotId,blocked,reason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Lote não encontrado.");},ct);}
    public Task<IReadOnlyList<Certification>> CertificationsAsync(string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<Certification>)(await c.QueryAsync<Certification>("select x.id,x.type,s.name holdername,x.scope,x.valid_until validuntil,case when x.valid_until<current_date then 'EXPIRED' else x.status end status,(select count(*) from agro360.compliance_evidence e where e.entity_type='CERTIFICATION' and e.entity_id=x.id) evidencecount from agro360.compliance_certifications x join agro360.compliance_subjects s on s.id=x.holder_id where x.tenant_id=@TenantId and (@Status is null or (case when x.valid_until<current_date then 'EXPIRED' else x.status end)=@Status) order by x.valid_until",new{tenant.TenantId,Status=status},t)).ToArray(),ct);
    public Task<Guid> SaveCertificationAsync(Guid? id,CertificationCommand x,CancellationToken ct){if(x.ValidUntil<x.ValidFrom)throw new ArgumentException("Validade final deve ser posterior à inicial.");return Upsert(id,"certifications",new{id=id??Guid.NewGuid(),tenant.TenantId,x.Type,x.HolderId,x.Scope,x.ValidFrom,x.ValidUntil,x.Requirements},"type,holder_id,scope,valid_from,valid_until,requirements","@Type,@HolderId,@Scope,@ValidFrom,@ValidUntil,@Requirements",ct);}
    public Task DecideCertificationAsync(Guid id,bool approve,string reason,CancellationToken ct)=>Transition("certifications",id,approve?"APPROVED":"REJECTED",reason,ct);
    public Task<IReadOnlyList<ChainAudit>> AuditsAsync(string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<ChainAudit>)(await c.QueryAsync<ChainAudit>("select a.id,a.scope,s.name entityname,a.scheduled_on scheduledon,a.status,a.score,(select count(*) from agro360.compliance_non_conformities n where n.audit_id=a.id) nonconformities from agro360.compliance_audits a join agro360.compliance_subjects s on s.id=a.entity_id where a.tenant_id=@TenantId and (@Status is null or a.status=@Status) order by a.scheduled_on",new{tenant.TenantId,Status=status},t)).ToArray(),ct);
    public Task<Guid> SaveAuditAsync(Guid? id,AuditCommand x,CancellationToken ct)=>Upsert(id,"audits",new{id=id??Guid.NewGuid(),tenant.TenantId,x.Scope,x.EntityId,x.TemplateId,x.ScheduledOn,x.ResponsibleId},"scope,entity_id,template_id,scheduled_on,responsible_id","@Scope,@EntityId,@TemplateId,@ScheduledOn,@ResponsibleId",ct);
    public Task CompleteAuditAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var score=await c.ExecuteScalarAsync<decimal?>("select round(coalesce(sum(q.weight) filter(where a.compliant),0)*100/nullif(sum(q.weight),0),2) from agro360.compliance_audit_answers a join agro360.compliance_audit_questions q on q.id=a.question_id where a.tenant_id=@TenantId and a.audit_id=@Id",new{tenant.TenantId,id},t)??0;var n=await c.ExecuteAsync("update agro360.compliance_audits set status='COMPLETED',score=@Score,completed_at=now() where tenant_id=@TenantId and id=@Id and status<>'COMPLETED'",new{tenant.TenantId,id,score},t);if(n==0)throw new KeyNotFoundException("Auditoria não encontrada ou concluída.");},ct);
    public Task<IReadOnlyList<NonConformity>> NonConformitiesAsync(string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<NonConformity>)(await c.QueryAsync<NonConformity>("select n.id,n.title,n.classification,n.severity,n.origin,s.name entityname,n.status,n.due_on dueon,(n.due_on<current_date and n.status not in('CLOSED','CANCELLED')) overdue from agro360.compliance_non_conformities n join agro360.compliance_subjects s on s.id=n.entity_id where n.tenant_id=@TenantId and (@Status is null or n.status=@Status) order by n.due_on",new{tenant.TenantId,Status=status},t)).ToArray(),ct);
    public Task<Guid> SaveNonConformityAsync(Guid? id,NonConformityCommand x,CancellationToken ct)=>Upsert(id,"non_conformities",new{id=id??Guid.NewGuid(),tenant.TenantId,x.Title,x.Classification,x.Severity,x.Origin,x.EntityType,x.EntityId,x.RootCause,x.CorrectiveAction,x.PreventiveAction,x.ResponsibleId,x.DueOn},"title,classification,severity,origin,entity_type,entity_id,root_cause,corrective_action,preventive_action,responsible_id,due_on","@Title,@Classification,@Severity,@Origin,@EntityType,@EntityId,@RootCause,@CorrectiveAction,@PreventiveAction,@ResponsibleId,@DueOn",ct);
    public Task CloseNonConformityAsync(Guid id,string reason,CancellationToken ct)=>Transition("non_conformities",id,"CLOSED",reason,ct);
    public Task AttachEvidenceAsync(string entityType,Guid entityId,EvidenceCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{await c.ExecuteAsync("insert into agro360.compliance_evidence(id,tenant_id,entity_type,entity_id,file_name,storage_url,sha256,uploaded_by) values(gen_random_uuid(),@TenantId,@EntityType,@EntityId,@FileName,@StorageUrl,@Sha256,@UserId)",new{tenant.TenantId,entityType,entityId,x.FileName,x.StorageUrl,x.Sha256,tenant.UserId},t);},ct);
    public Task<IReadOnlyList<ExportDossier>> DossiersAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<ExportDossier>)(await c.QueryAsync<ExportDossier>("select d.id,d.certificate_code certificatecode,l.code lotname,p.name productname,b.name buyername,d.market,d.status,d.generated_at generatedat from agro360.compliance_export_dossiers d join agro360.storage_lots l on l.id=d.lot_id join agro360.inventory_products p on p.id=l.product_id join agro360.compliance_buyers b on b.id=d.buyer_id where d.tenant_id=@TenantId order by d.generated_at desc",new{tenant.TenantId},t)).ToArray(),ct);
    public Task<Guid> CreateDossierAsync(DossierCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var missing=await c.ExecuteScalarAsync<int>("select count(*) from agro360.compliance_product_rules r join agro360.storage_lots l on l.product_id=r.product_id where r.tenant_id=@TenantId and l.id=@LotId and r.market=@Market and r.mandatory and not exists(select 1 from agro360.compliance_lot_requirements q where q.tenant_id=r.tenant_id and q.lot_id=l.id and q.rule_id=r.id and q.compliant)",new{tenant.TenantId,x.LotId,x.Market},t);if(missing>0)throw new InvalidOperationException("Lote não atende aos requisitos obrigatórios do mercado.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.compliance_export_dossiers(id,tenant_id,lot_id,buyer_id,market,certificate_code,public_token_hash,status,generated_by) values(@Id,@TenantId,@LotId,@BuyerId,@Market,upper(substr(encode(gen_random_bytes(10),'hex'),1,20)),encode(digest(gen_random_uuid()::text,'sha256'),'hex'),'ISSUED',@UserId)",new{id,tenant.TenantId,x.LotId,x.BuyerId,x.Market,tenant.UserId},t);return id;},ct);
    public async Task<byte[]> ExportDossierAsync(Guid id,CancellationToken ct){var item=(await DossiersAsync(ct)).SingleOrDefault(x=>x.Id==id)??throw new KeyNotFoundException("Dossiê não encontrado.");return Encoding.UTF8.GetBytes($"AGRO 360 - DOSSIÊ DE CONFORMIDADE\nCertificado: {item.CertificateCode}\nLote: {item.LotName}\nProduto: {item.ProductName}\nComprador: {item.BuyerName}\nMercado: {item.Market}\nStatus: {item.Status}\nEmitido: {item.GeneratedAt:O}\n");}
    public Task<PublicDossier?> PublicDossierAsync(string certificate,CancellationToken ct)=>db.InSystemTransactionAsync((c,t)=>c.QuerySingleOrDefaultAsync<PublicDossier>("select certificate_code certificatecode,product,lot,origin,status,issued_at issuedat,verification_hash verificationhash from agro360.compliance_verify_public_dossier(@Certificate)",new{Certificate=certificate.ToUpperInvariant()},t),ct);
    public Task<ComplianceDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<ComplianceDashboard>("select (select count(*) from agro360.compliance_documents where tenant_id=@TenantId and expires_on<current_date) expireddocuments,(select count(*) from agro360.compliance_documents where tenant_id=@TenantId and expires_on between current_date and current_date+30) expiringdocuments,(select count(*) from agro360.storage_lots where tenant_id=@TenantId and status='BLOCKED') blockedlots,(select count(*) from agro360.storage_lots where tenant_id=@TenantId and status='AVAILABLE') eligiblelots,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and status not in('CLOSED','CANCELLED')) opennonconformities,(select count(*) from agro360.compliance_audits where tenant_id=@TenantId and status='PLANNED') pendingaudits,coalesce((select round(avg(value),2) from agro360.esg_indicators where tenant_id=@TenantId and period>=current_date-365),0) esgscore,(select count(*) from agro360.compliance_certifications where tenant_id=@TenantId and status='APPROVED' and valid_until>=current_date) validcertifications,(select count(*) from agro360.compliance_certifications where tenant_id=@TenantId and valid_until<current_date) expiredcertifications,(select count(distinct lot_id) from agro360.compliance_export_dossiers where tenant_id=@TenantId and status='ISSUED') exporteligibleproducts,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and severity='CRITICAL' and status not in('CLOSED','CANCELLED')) criticalrisks",new{tenant.TenantId},t),ct);
    private Task<Guid> Upsert(Guid? original,string table,object p,string columns,string values,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var id=(Guid)p.GetType().GetProperty("id")!.GetValue(p)!;var sql=original is null?$"insert into agro360.compliance_{table}(id,tenant_id,{columns}) values(@id,@TenantId,{values})":$"update agro360.compliance_{table} set ({columns})=({values}),updated_at=now() where id=@id and tenant_id=@TenantId";var n=await c.ExecuteAsync(sql,p,t);if(n==0)throw new KeyNotFoundException("Registro não encontrado.");return id;},ct);
    private Task Transition(string table,Guid id,string status,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo é obrigatório.");return db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync($"update agro360.compliance_{table} set status=@Status,decision_reason=@Reason,decided_by=@UserId,decided_at=now() where id=@Id and tenant_id=@TenantId",new{tenant.TenantId,id,status,reason,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Registro não encontrado.");},ct);}
}

public sealed class EsgService(DatabaseExecutor db,ITenantContext tenant) : IEsgService
{
 public Task<IReadOnlyList<EsgIndicator>> IndicatorsAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<EsgIndicator>)(await c.QueryAsync<EsgIndicator>("select id,pillar,name,value,unit,period,methodology from agro360.esg_indicators where tenant_id=@TenantId order by period desc,pillar,name",new{tenant.TenantId},t)).ToArray(),ct);
 public Task<Guid> AddIndicatorAsync(EsgIndicatorCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.esg_indicators(id,tenant_id,pillar,name,value,unit,period,methodology,recorded_by) values(@Id,@TenantId,@Pillar,@Name,@Value,@Unit,@Period,@Methodology,@UserId)",new{id,tenant.TenantId,x.Pillar,x.Name,x.Value,x.Unit,x.Period,x.Methodology,tenant.UserId},t);return id;},ct);
 public Task<IReadOnlyList<CarbonEntry>> CarbonAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<CarbonEntry>)(await c.QueryAsync<CarbonEntry>("select id,source,practice,activity_amount activityamount,unit,factor_kg_co2e factorkgco2e,sequestration_kg_co2e sequestrationkgco2e,round((activity_amount*factor_kg_co2e-sequestration_kg_co2e)/1000,4) nettonnesco2e,period,methodology from agro360.esg_carbon_inventory where tenant_id=@TenantId order by period desc",new{tenant.TenantId},t)).ToArray(),ct);
 public Task<Guid> AddCarbonAsync(CarbonCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SustainabilityCalculations.CarbonTonnes(x.ActivityAmount,x.FactorKgCo2e,x.SequestrationKgCo2e);var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.esg_carbon_inventory(id,tenant_id,source,practice,activity_amount,unit,factor_kg_co2e,sequestration_kg_co2e,period,methodology,recorded_by) values(@Id,@TenantId,@Source,@Practice,@ActivityAmount,@Unit,@FactorKgCo2e,@SequestrationKgCo2e,@Period,@Methodology,@UserId)",new{id,tenant.TenantId,x.Source,x.Practice,x.ActivityAmount,x.Unit,x.FactorKgCo2e,x.SequestrationKgCo2e,x.Period,x.Methodology,tenant.UserId},t);return id;},ct);
}
