using System.Text;
using Agro360.Application.Contracts;
using Agro360.Domain.Compliance;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class ComplianceService(DatabaseExecutor db, ITenantContext tenant) : IComplianceService
{
    public Task<IReadOnlyList<ComplianceDocument>> DocumentsAsync(string? status, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<ComplianceDocument>)(await c.QueryAsync<ComplianceDocument>("select d.id,d.type,d.number,s.name subjectname,d.issued_on issuedon,d.expires_on expireson,u.name responsiblename,case when d.expires_on<current_date then 'EXPIRED' when d.expires_on<=current_date+30 then 'EXPIRING' else d.status end status,(select count(*) from agro360.compliance_evidence e where e.entity_type='DOCUMENT' and e.entity_id=d.id) evidencecount from agro360.compliance_documents d join agro360.compliance_subjects s on s.id=d.subject_id join agro360.identity_users u on u.id=d.responsible_id where d.tenant_id=@TenantId and (@Status is null or (case when d.expires_on<current_date then 'EXPIRED' when d.expires_on<=current_date+30 then 'EXPIRING' else d.status end)=@Status) order by d.expires_on", new { tenant.TenantId, Status = status }, t)).ToArray(), ct);
    public Task<Guid> SaveDocumentAsync(Guid? id, DocumentCommand command, CancellationToken ct) { if (command.ExpiresOn < command.IssuedOn) throw new ArgumentException("Vencimento deve ser posterior à emissão."); return Upsert(id, "documents", new { id = id ?? Guid.NewGuid(), tenant.TenantId, command.Type, command.Number, command.SubjectId, command.IssuedOn, command.ExpiresOn, command.ResponsibleId, command.Notes }, "type,number,subject_id,issued_on,expires_on,responsible_id,notes", "@Type,@Number,@SubjectId,@IssuedOn,@ExpiresOn,@ResponsibleId,@Notes", ct); }
    public Task<IReadOnlyList<ProductRule>> RulesAsync(Guid? productId, string? market, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<ProductRule>)(await c.QueryAsync<ProductRule>("select r.id,p.name productname,r.market,r.name,r.mandatory,r.blocks_sale blockssale,r.blocks_export blocksexport,r.required_documents requireddocuments,r.status from agro360.compliance_product_rules r join agro360.inventory_products p on p.id=r.product_id where r.tenant_id=@TenantId and (@ProductId is null or r.product_id=@ProductId) and (@Market is null or r.market=@Market) order by p.name,r.market", new { tenant.TenantId, ProductId = productId, Market = market }, t)).ToArray(), ct);
    public Task<Guid> SaveRuleAsync(Guid? id, ProductRuleCommand command, CancellationToken ct) => Upsert(id, "product_rules", new { id = id ?? Guid.NewGuid(), tenant.TenantId, command.ProductId, command.Market, command.Name, command.Mandatory, command.BlocksSale, command.BlocksExport, command.RequiredDocuments }, "product_id,market,name,mandatory,blocks_sale,blocks_export,required_documents", "@ProductId,@Market,@Name,@Mandatory,@BlocksSale,@BlocksExport,@RequiredDocuments", ct);
    public Task SetLotBlockAsync(Guid lotId, bool blocked, string reason, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(reason)) throw new ArgumentException("Motivo é obrigatório.");
        return db.InTenantTransactionAsync(async (c, t) =>
        {
            var lockedLot = await c.ExecuteScalarAsync<Guid?>("select id from agro360.storage_lots where tenant_id=@TenantId and id=@LotId for update", new { tenant.TenantId, lotId }, t);
            if (lockedLot is null) throw new KeyNotFoundException("Lote não encontrado.");

            if (blocked)
            {
                await c.ExecuteAsync("insert into agro360.compliance_lot_restrictions(id,tenant_id,lot_id,type,reason,applied_by) values(gen_random_uuid(),@TenantId,@LotId,'BLOCK_LOT',@Reason,@UserId)", new { tenant.TenantId, lotId, reason, tenant.UserId }, t);
                await c.ExecuteAsync("update agro360.storage_lots set status='BLOCKED' where tenant_id=@TenantId and id=@LotId", new { tenant.TenantId, lotId }, t);
            }
            else
            {
                var released = await c.ExecuteAsync("update agro360.compliance_lot_restrictions set released_at=now(),released_by=@UserId,release_reason=@Reason,version=version+1 where tenant_id=@TenantId and lot_id=@LotId and non_conformity_id is null and type='BLOCK_LOT' and released_at is null", new { tenant.TenantId, lotId, reason, tenant.UserId }, t);
                if (released == 0) throw new InvalidOperationException("Não existe bloqueio manual ativo para liberar.");
                await c.ExecuteAsync("update agro360.storage_lots set status='AVAILABLE' where tenant_id=@TenantId and id=@LotId and not agro360.compliance_lot_has_active_restriction(@TenantId,@LotId,'USE')", new { tenant.TenantId, lotId }, t);
            }

            await c.ExecuteAsync("insert into agro360.compliance_lot_decisions(id,tenant_id,lot_id,blocked,reason,decided_by) values(gen_random_uuid(),@TenantId,@LotId,@Blocked,@Reason,@UserId)", new { tenant.TenantId, lotId, blocked, reason, tenant.UserId }, t);
        }, ct);
    }
    public Task<IReadOnlyList<Certification>> CertificationsAsync(string? status, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<Certification>)(await c.QueryAsync<Certification>("select x.id,x.type,s.name holdername,x.scope,x.valid_until validuntil,case when x.valid_until<current_date then 'EXPIRED' else x.status end status,(select count(*) from agro360.compliance_evidence e where e.entity_type='CERTIFICATION' and e.entity_id=x.id) evidencecount from agro360.compliance_certifications x join agro360.compliance_subjects s on s.id=x.holder_id where x.tenant_id=@TenantId and (@Status is null or (case when x.valid_until<current_date then 'EXPIRED' else x.status end)=@Status) order by x.valid_until", new { tenant.TenantId, Status = status }, t)).ToArray(), ct);
    public Task<Guid> SaveCertificationAsync(Guid? id, CertificationCommand command, CancellationToken ct) { if (command.ValidUntil < command.ValidFrom) throw new ArgumentException("Validade final deve ser posterior à inicial."); return Upsert(id, "certifications", new { id = id ?? Guid.NewGuid(), tenant.TenantId, command.Type, command.HolderId, command.Scope, command.ValidFrom, command.ValidUntil, command.Requirements }, "type,holder_id,scope,valid_from,valid_until,requirements", "@Type,@HolderId,@Scope,@ValidFrom,@ValidUntil,@Requirements", ct); }
    public Task DecideCertificationAsync(Guid id, bool approve, string reason, CancellationToken ct) => Transition("certifications", id, approve ? "APPROVED" : "REJECTED", reason, ct);
    public Task<IReadOnlyList<ChainAudit>> AuditsAsync(string? status, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<ChainAudit>)(await c.QueryAsync<ChainAudit>("select a.id,a.scope,s.name entityname,a.scheduled_on scheduledon,a.status,a.score,(select count(*) from agro360.compliance_non_conformities n where n.audit_id=a.id) nonconformities from agro360.compliance_audits a join agro360.compliance_subjects s on s.id=a.entity_id where a.tenant_id=@TenantId and (@Status is null or a.status=@Status) order by a.scheduled_on", new { tenant.TenantId, Status = status }, t)).ToArray(), ct);
    public Task<Guid> SaveAuditAsync(Guid? id, AuditCommand command, CancellationToken ct) => Upsert(id, "audits", new { id = id ?? Guid.NewGuid(), tenant.TenantId, command.Scope, command.EntityId, command.TemplateId, command.ScheduledOn, command.ResponsibleId }, "scope,entity_id,template_id,scheduled_on,responsible_id", "@Scope,@EntityId,@TemplateId,@ScheduledOn,@ResponsibleId", ct);
    public Task CompleteAuditAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { var score = await c.ExecuteScalarAsync<decimal?>("select round(coalesce(sum(q.weight) filter(where a.compliant),0)*100/nullif(sum(q.weight),0),2) from agro360.compliance_audit_answers a join agro360.compliance_audit_questions q on q.id=a.question_id where a.tenant_id=@TenantId and a.audit_id=@Id", new { tenant.TenantId, id }, t) ?? 0; var n = await c.ExecuteAsync("update agro360.compliance_audits set status='COMPLETED',score=@Score,completed_at=now() where tenant_id=@TenantId and id=@Id and status<>'COMPLETED'", new { tenant.TenantId, id, score }, t); if (n == 0) throw new KeyNotFoundException("Auditoria não encontrada ou concluída."); }, ct);
    public Task<IReadOnlyList<NonConformity>> NonConformitiesAsync(string? status, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<NonConformity>)(await c.QueryAsync<NonConformity>("select n.id,n.title,n.classification,n.severity,n.origin,s.name entityname,n.status,n.due_on dueon,(n.due_on<current_date and n.status not in('CLOSED','CANCELLED')) overdue from agro360.compliance_non_conformities n join agro360.compliance_subjects s on s.id=n.entity_id where n.tenant_id=@TenantId and (@Status is null or n.status=@Status) order by n.due_on", new { tenant.TenantId, Status = status }, t)).ToArray(), ct);
    public Task<Guid> SaveNonConformityAsync(Guid? id, NonConformityCommand command, CancellationToken ct) => Upsert(id, "non_conformities", new { id = id ?? Guid.NewGuid(), tenant.TenantId, command.Title, command.Classification, command.Severity, command.Origin, command.EntityType, command.EntityId, command.RootCause, command.CorrectiveAction, command.PreventiveAction, command.ResponsibleId, command.DueOn }, "title,classification,severity,origin,entity_type,entity_id,root_cause,corrective_action,preventive_action,responsible_id,due_on", "@Title,@Classification,@Severity,@Origin,@EntityType,@EntityId,@RootCause,@CorrectiveAction,@PreventiveAction,@ResponsibleId,@DueOn", ct);
    public Task CloseNonConformityAsync(Guid id, string reason, long expectedVersion, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(reason)) throw new ArgumentException("Motivo é obrigatório.");
        return db.InTenantTransactionAsync(async (c, t) =>
        {
            var current = await c.QuerySingleOrDefaultAsync<NcCloseRow>("select n.status,n.version,n.root_cause rootcause,exists(select 1 from agro360.compliance_evidence e where e.tenant_id=n.tenant_id and e.entity_type='NONCONFORMITIES' and e.entity_id=n.id) hasevidence,not exists(select 1 from agro360.compliance_nc_actions a where a.tenant_id=n.tenant_id and a.non_conformity_id=n.id and a.mandatory and a.status<>'COMPLETED') actionscompleted,(select v.result from agro360.compliance_nc_verifications v where v.tenant_id=n.tenant_id and v.non_conformity_id=n.id and v.deleted_at is null order by v.decided_at desc limit 1) verificationresult from agro360.compliance_non_conformities n where n.tenant_id=@TenantId and n.id=@Id and n.deleted_at is null for update", new { tenant.TenantId, id }, t);
            if (current is null) throw new NotFoundException("Não conformidade", id);
            if (current.Version != expectedVersion) throw new ConflictException("O registro mudou. Recarregue as pendências antes de encerrar.");
            QualityComplianceRules.EnsureNonConformityCanClose(current.RootCause, current.HasEvidence, reason, [current.ActionsCompleted]);
            QualityComplianceRules.EnsureTransition(current.Status, "CLOSED", reason, current.ActionsCompleted, current.VerificationResult);
            var changed = await c.ExecuteAsync("update agro360.compliance_non_conformities set status='CLOSED',decision_reason=@Reason,decided_by=@UserId,decided_at=now(),updated_at=now(),version=version+1 where tenant_id=@TenantId and id=@Id and version=@ExpectedVersion", new { tenant.TenantId, id, reason, tenant.UserId, expectedVersion }, t);
            if (changed == 0) throw new ConflictException("O registro mudou durante o encerramento.");
            await c.ExecuteAsync("insert into agro360.compliance_nc_events(id,tenant_id,non_conformity_id,event_type,from_status,to_status,reason,snapshot,actor_id) values(gen_random_uuid(),@TenantId,@Id,'STATUS_TRANSITION',@FromStatus,'CLOSED',@Reason,jsonb_build_object('version',@ExpectedVersion),@UserId)", new { tenant.TenantId, id, FromStatus = current.Status, reason, expectedVersion, tenant.UserId }, t);
        }, ct);
    }
    public Task<NonConformityDetail> NonConformityAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) =>
    {
        var row = await c.QuerySingleOrDefaultAsync<NcDetailRow>("select n.id,n.number,n.title,n.classification,n.severity,n.origin,s.name entityname,n.status,n.responsible_id responsibleid,n.due_on dueon,n.version,n.root_cause rootcause,(select count(*) from agro360.compliance_nc_actions a where a.tenant_id=n.tenant_id and a.non_conformity_id=n.id and a.status in('OPEN','IN_PROGRESS')) openactions,(select count(*) from agro360.compliance_nc_actions a where a.tenant_id=n.tenant_id and a.non_conformity_id=n.id and a.status='COMPLETED') completedactions,(select count(*) from agro360.compliance_nc_verifications v where v.tenant_id=n.tenant_id and v.non_conformity_id=n.id and v.deleted_at is null) verificationcount,(select count(*) from agro360.compliance_lot_restrictions r where r.tenant_id=n.tenant_id and r.non_conformity_id=n.id and r.released_at is null) activerestrictions,(select v.result from agro360.compliance_nc_verifications v where v.tenant_id=n.tenant_id and v.non_conformity_id=n.id and v.deleted_at is null order by v.decided_at desc limit 1) latestverificationresult from agro360.compliance_non_conformities n join agro360.compliance_subjects s on s.id=n.entity_id where n.tenant_id=@TenantId and n.id=@Id and n.deleted_at is null", new { tenant.TenantId, id }, t);
        if (row is null) throw new NotFoundException("Não conformidade", id);
        return new NonConformityDetail(row.Id, row.Number, row.Title, row.Classification, row.Severity, row.Origin, row.EntityName, row.Status, row.ResponsibleId, row.DueOn, row.Version, row.RootCause, QualityComplianceRules.AvailableTransitions(row.Status), row.OpenActions, row.CompletedActions, row.VerificationCount, row.ActiveRestrictions, row.LatestVerificationResult);
    }, ct);
    public Task<IReadOnlyList<EffectivenessVerification>> VerificationsAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<EffectivenessVerification>)(await c.QueryAsync<EffectivenessVerification>("select id,non_conformity_id nonconformityid,criterion_type criteriontype,criterion,criterion_version criterionversion,method,responsible_id responsibleid,due_on dueon,observation_started_on observationstartedon,observation_ended_on observationendedon,evidence_requirements evidencerequirements,expected_value expectedvalue,observed_value observedvalue,unit,comparison_operator comparisonoperator,percentage_basis percentagebasis,result_observed resultobserved,conclusion,result,decided_at decidedat,decided_by decidedby from agro360.compliance_nc_verifications where tenant_id=@TenantId and non_conformity_id=@Id and deleted_at is null order by decided_at desc", new { tenant.TenantId, id }, t)).ToArray(), ct);
    public Task<Guid> AddVerificationAsync(Guid id, EffectivenessVerificationCommand command, CancellationToken ct)
    {
        QualityComplianceRules.EnsureEffectivenessCriterion(command.CriterionType, command.Unit, command.ComparisonOperator, command.ExpectedValue, command.ObservedValue, command.PercentageBasis);
        if (command.Result is not ("EFFECTIVE" or "INEFFECTIVE" or "INCONCLUSIVE")) throw new ArgumentException("Resultado de eficácia inválido.");
        if (command.ObservationEndedOn.HasValue && (!command.ObservationStartedOn.HasValue || command.ObservationEndedOn < command.ObservationStartedOn)) throw new ArgumentException("Período de observação inválido.");
        return db.InTenantTransactionAsync(async (c, t) =>
        {
            var existing = await c.ExecuteScalarAsync<Guid?>("select id from agro360.compliance_nc_verifications where tenant_id=@TenantId and idempotency_key=@IdempotencyKey", new { tenant.TenantId, command.IdempotencyKey }, t);
            if (existing.HasValue) return existing.Value;
            var current = await c.QuerySingleOrDefaultAsync<NcStateRow>("select status,version from agro360.compliance_non_conformities where tenant_id=@TenantId and id=@Id and deleted_at is null for update", new { tenant.TenantId, id }, t);
            if (current is null) throw new NotFoundException("Não conformidade", id);
            if (current.Version != command.ExpectedCaseVersion) throw new ConflictException("O registro mudou. Recarregue os dados e revise a decisão antes de confirmar.");
            if (!current.Status.Equals("AWAITING_VERIFICATION", StringComparison.OrdinalIgnoreCase)) throw new DomainException("A não conformidade não está aguardando verificação de eficácia.", "invalid_quality_transition");
            if (await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.compliance_nc_actions where tenant_id=@TenantId and non_conformity_id=@Id and mandatory and status<>'COMPLETED')", new { tenant.TenantId, id }, t)) throw new DomainException("Conclua todas as ações obrigatórias antes da verificação.", "mandatory_actions_pending");
            if (!await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.identity_users where tenant_id=@TenantId and id=@ResponsibleId and deleted_at is null and status='ACTIVE')", new { tenant.TenantId, command.ResponsibleId }, t)) throw new DomainException("O responsável selecionado não está ativo neste tenant.", "invalid_verification_responsible");
            var actionSnapshot = await c.ExecuteScalarAsync<string>("select coalesce(jsonb_agg(jsonb_build_object('id',id,'version',version,'status',status,'completedAt',completed_at)),'[]'::jsonb)::text from agro360.compliance_nc_actions where tenant_id=@TenantId and non_conformity_id=@Id and mandatory", new { tenant.TenantId, id }, t) ?? "[]";
            var segregation = await c.ExecuteScalarAsync<bool>("select coalesce((compliance_parameters->>'segregateEffectivenessVerifier')::boolean,false) from agro360.saas_organization_settings where tenant_id=@TenantId", new { tenant.TenantId }, t);
            if (segregation && await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.compliance_nc_actions where tenant_id=@TenantId and non_conformity_id=@Id and completed_by=@Verifier)", new { tenant.TenantId, id, Verifier = tenant.UserId }, t)) throw new ForbiddenException("A segregação configurada impede que o executor verifique a própria ação.");
            var verificationId = Guid.NewGuid();
            await c.ExecuteAsync("insert into agro360.compliance_nc_verifications(id,tenant_id,non_conformity_id,criterion_type,criterion,criterion_version,method,responsible_id,due_on,observation_started_on,observation_ended_on,evidence_requirements,expected_value,observed_value,unit,comparison_operator,percentage_basis,result_observed,conclusion,result,justification,verified_by,verified_at,action_snapshot,idempotency_key,decided_at,decided_by,created_by) values(@VerificationId,@TenantId,@Id,@CriterionType,@Criterion,1,@Method,@ResponsibleId,@DueOn,@ObservationStartedOn,@ObservationEndedOn,@EvidenceRequirements,@ExpectedValue,@ObservedValue,@Unit,@ComparisonOperator,@PercentageBasis,@ResultObserved,@Conclusion,@Result,@Conclusion,@UserId,now(),cast(@ActionSnapshot as jsonb),@IdempotencyKey,now(),@UserId,@UserId)", new { verificationId, tenant.TenantId, id, command.CriterionType, command.Criterion, command.Method, command.ResponsibleId, command.DueOn, command.ObservationStartedOn, command.ObservationEndedOn, command.EvidenceRequirements, command.ExpectedValue, command.ObservedValue, command.Unit, command.ComparisonOperator, command.PercentageBasis, command.ResultObserved, command.Conclusion, command.Result, command.IdempotencyKey, ActionSnapshot = actionSnapshot, tenant.UserId }, t);
            await c.ExecuteAsync("update agro360.compliance_non_conformities set version=version+1,updated_at=now() where tenant_id=@TenantId and id=@Id and version=@ExpectedCaseVersion", new { tenant.TenantId, id, command.ExpectedCaseVersion }, t);
            await c.ExecuteAsync("insert into agro360.compliance_nc_events(id,tenant_id,non_conformity_id,event_type,from_status,to_status,reason,snapshot,actor_id) values(gen_random_uuid(),@TenantId,@Id,'EFFECTIVENESS_DECIDED',@Status,@Status,@Conclusion,jsonb_build_object('verificationId',@VerificationId,'result',@Result,'caseVersion',@ExpectedCaseVersion),@UserId)", new { tenant.TenantId, id, current.Status, command.Conclusion, verificationId, command.Result, command.ExpectedCaseVersion, tenant.UserId }, t);
            return verificationId;
        }, ct);
    }
    public Task<IReadOnlyList<RelatedCase>> RelatedCasesAsync(Guid id, RelatedCaseQuery query, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<RelatedCase>)(await c.QueryAsync<RelatedCase>("select n.id,n.number,n.title,n.status,concat_ws(', ',case when @ProductId is not null and n.product_id=@ProductId then 'produto' end,case when @LotId is not null and n.lot_id=@LotId then 'lote' end,case when @UnitId is not null and n.unit_id=@UnitId then 'unidade' end,case when @Classification is not null and n.classification=@Classification then 'tipo' end,case when @Origin is not null and n.origin=@Origin then 'processo' end,case when @RootCause is not null and n.root_cause ilike '%'||@RootCause||'%' then 'causa informada' end) matchreason,n.identified_at identifiedat from agro360.compliance_non_conformities n where n.tenant_id=@TenantId and n.id<>@Id and n.deleted_at is null and (@From is null or n.identified_at>=@From) and (@To is null or n.identified_at<@To+1) and ((@ProductId is not null and n.product_id=@ProductId) or (@LotId is not null and n.lot_id=@LotId) or (@UnitId is not null and n.unit_id=@UnitId) or (@Classification is not null and n.classification=@Classification) or (@Origin is not null and n.origin=@Origin) or (@RootCause is not null and n.root_cause ilike '%'||@RootCause||'%')) order by n.identified_at desc limit 100", new { tenant.TenantId, id, query.ProductId, query.LotId, query.UnitId, query.Classification, query.Origin, query.RootCause, query.From, query.To }, t)).ToArray(), ct);
    public Task LinkRelatedCaseAsync(Guid id, RelatedCaseLinkCommand command, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) =>
    {
        if (id == command.RelatedNonConformityId) throw new ArgumentException("Um caso não pode ser relacionado a ele mesmo.");
        var changed = await c.ExecuteAsync("update agro360.compliance_non_conformities set version=version+1,updated_at=now() where tenant_id=@TenantId and id=@Id and version=@ExpectedCaseVersion and deleted_at is null", new { tenant.TenantId, id, command.ExpectedCaseVersion }, t);
        if (changed == 0) throw new ConflictException("O registro mudou ou não está mais disponível. Recarregue antes de vincular.");
        var relatedExists = await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.compliance_non_conformities where tenant_id=@TenantId and id=@RelatedId and deleted_at is null)", new { tenant.TenantId, RelatedId = command.RelatedNonConformityId }, t);
        if (!relatedExists) throw new NotFoundException("Caso relacionado", command.RelatedNonConformityId);
        await c.ExecuteAsync("insert into agro360.compliance_nc_related_cases(id,tenant_id,non_conformity_id,related_non_conformity_id,justification,created_by) values(gen_random_uuid(),@TenantId,@Id,@RelatedId,@Justification,@UserId) on conflict(tenant_id,non_conformity_id,related_non_conformity_id) do nothing", new { tenant.TenantId, id, RelatedId = command.RelatedNonConformityId, command.Justification, tenant.UserId }, t);
    }, ct);
    public Task AttachEvidenceAsync(string entityType, Guid entityId, EvidenceCommand command, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { await c.ExecuteAsync("insert into agro360.compliance_evidence(id,tenant_id,entity_type,entity_id,file_name,storage_url,sha256,uploaded_by) values(gen_random_uuid(),@TenantId,@EntityType,@EntityId,@FileName,@StorageUrl,@Sha256,@UserId)", new { tenant.TenantId, entityType, entityId, command.FileName, command.StorageUrl, command.Sha256, tenant.UserId }, t); }, ct);
    public Task<IReadOnlyList<ExportDossier>> DossiersAsync(CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<ExportDossier>)(await c.QueryAsync<ExportDossier>("select d.id,d.certificate_code certificatecode,l.code lotname,p.name productname,b.name buyername,d.market,d.status,d.generated_at generatedat from agro360.compliance_export_dossiers d join agro360.storage_lots l on l.id=d.lot_id join agro360.inventory_products p on p.id=l.product_id join agro360.compliance_buyers b on b.id=d.buyer_id where d.tenant_id=@TenantId order by d.generated_at desc", new { tenant.TenantId }, t)).ToArray(), ct);
    public Task<Guid> CreateDossierAsync(DossierCommand command, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { var missing = await c.ExecuteScalarAsync<int>("select count(*) from agro360.compliance_product_rules r join agro360.storage_lots l on l.product_id=r.product_id where r.tenant_id=@TenantId and l.id=@LotId and r.market=@Market and r.mandatory and not exists(select 1 from agro360.compliance_lot_requirements q where q.tenant_id=r.tenant_id and q.lot_id=l.id and q.rule_id=r.id and q.compliant)", new { tenant.TenantId, command.LotId, command.Market }, t); if (missing > 0) throw new InvalidOperationException("Lote não atende aos requisitos obrigatórios do mercado."); var id = Guid.NewGuid(); await c.ExecuteAsync("insert into agro360.compliance_export_dossiers(id,tenant_id,lot_id,buyer_id,market,certificate_code,public_token_hash,status,generated_by) values(@Id,@TenantId,@LotId,@BuyerId,@Market,upper(substr(encode(gen_random_bytes(10),'hex'),1,20)),encode(digest(gen_random_uuid()::text,'sha256'),'hex'),'ISSUED',@UserId)", new { id, tenant.TenantId, command.LotId, command.BuyerId, command.Market, tenant.UserId }, t); return id; }, ct);
    public async Task<byte[]> ExportDossierAsync(Guid id, CancellationToken ct) { var item = (await DossiersAsync(ct)).SingleOrDefault(x => x.Id == id) ?? throw new KeyNotFoundException("Dossiê não encontrado."); return Encoding.UTF8.GetBytes($"AGRO 360 - DOSSIÊ DE CONFORMIDADE\nCertificado: {item.CertificateCode}\nLote: {item.LotName}\nProduto: {item.ProductName}\nComprador: {item.BuyerName}\nMercado: {item.Market}\nStatus: {item.Status}\nEmitido: {item.GeneratedAt:O}\n"); }
    public Task<PublicDossier?> PublicDossierAsync(string certificate, CancellationToken ct) => db.InSystemTransactionAsync((c, t) => c.QuerySingleOrDefaultAsync<PublicDossier>("select certificate_code certificatecode,product,lot,origin,status,issued_at issuedat,verification_hash verificationhash from agro360.compliance_verify_public_dossier(@Certificate)", new { Certificate = certificate.ToUpperInvariant() }, t), ct);
    public Task<ComplianceDashboard> DashboardAsync(CancellationToken ct) => db.InTenantTransactionAsync((c, t) => c.QuerySingleAsync<ComplianceDashboard>("select (select count(*) from agro360.quality_inspections where tenant_id=@TenantId and deleted_at is null and status in('PLANNED','IN_PROGRESS','PENDING_REVIEW')) pendinginspections,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and deleted_at is null and status not in('CLOSED','CANCELLED')) opennonconformities,(select count(distinct lot_id) from agro360.compliance_lot_restrictions where tenant_id=@TenantId and released_at is null) blockedlots,(select count(*) from agro360.compliance_nc_actions where tenant_id=@TenantId and status in('OPEN','IN_PROGRESS') and due_on<current_date) overdueactions,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and deleted_at is null and status='AWAITING_VERIFICATION') awaitingverification,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and deleted_at is null and reopened_count>0 and status not in('CLOSED','CANCELLED')) reopenedcases,(select count(*) from agro360.compliance_documents where tenant_id=@TenantId and status='DRAFT') pendingdocuments,(select count(*) from agro360.compliance_documents where tenant_id=@TenantId and expires_on<current_date) expireddocuments,(select count(*) from agro360.compliance_documents where tenant_id=@TenantId and expires_on between current_date and current_date+30) expiringdocuments,(select count(*) from agro360.storage_lots where tenant_id=@TenantId and status='AVAILABLE') eligiblelots,(select count(*) from agro360.compliance_audits where tenant_id=@TenantId and status='PLANNED') pendingaudits,coalesce((select round(avg(value),2) from agro360.esg_indicators where tenant_id=@TenantId and period>=current_date-365),0) esgscore,(select count(*) from agro360.compliance_certifications where tenant_id=@TenantId and status='APPROVED' and valid_until>=current_date) validcertifications,(select count(*) from agro360.compliance_certifications where tenant_id=@TenantId and valid_until<current_date) expiredcertifications,(select count(distinct lot_id) from agro360.compliance_export_dossiers where tenant_id=@TenantId and status='ISSUED') exporteligibleproducts,(select count(*) from agro360.compliance_non_conformities where tenant_id=@TenantId and severity='CRITICAL' and status not in('CLOSED','CANCELLED')) criticalrisks", new { tenant.TenantId }, t), ct);
    private Task<Guid> Upsert(Guid? original, string table, object p, string columns, string values, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { var id = (Guid)p.GetType().GetProperty("id")!.GetValue(p)!; var sql = original is null ? $"insert into agro360.compliance_{table}(id,tenant_id,{columns}) values(@id,@TenantId,{values})" : $"update agro360.compliance_{table} set ({columns})=({values}),updated_at=now() where id=@id and tenant_id=@TenantId"; var n = await c.ExecuteAsync(sql, p, t); if (n == 0) throw new KeyNotFoundException("Registro não encontrado."); return id; }, ct);
    private Task Transition(string table, Guid id, string status, string reason, CancellationToken ct) { if (string.IsNullOrWhiteSpace(reason)) throw new ArgumentException("Motivo é obrigatório."); return db.InTenantTransactionAsync(async (c, t) => { var n = await c.ExecuteAsync($"update agro360.compliance_{table} set status=@Status,decision_reason=@Reason,decided_by=@UserId,decided_at=now() where id=@Id and tenant_id=@TenantId", new { tenant.TenantId, id, status, reason, tenant.UserId }, t); if (n == 0) throw new KeyNotFoundException("Registro não encontrado."); }, ct); }
    private sealed record NcDetailRow(Guid Id, long Number, string Title, string Classification, string Severity, string Origin, string EntityName, string Status, Guid ResponsibleId, DateOnly DueOn, long Version, string? RootCause, int OpenActions, int CompletedActions, int VerificationCount, int ActiveRestrictions, string? LatestVerificationResult);
    private sealed record NcStateRow(string Status, long Version);
    private sealed record NcCloseRow(string Status, long Version, string? RootCause, bool HasEvidence, bool ActionsCompleted, string? VerificationResult);
}

public sealed class EsgService(DatabaseExecutor db, ITenantContext tenant) : IEsgService
{
    public Task<IReadOnlyList<EsgIndicator>> IndicatorsAsync(CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<EsgIndicator>)(await c.QueryAsync<EsgIndicator>("select id,pillar,name,value,unit,period,methodology from agro360.esg_indicators where tenant_id=@TenantId order by period desc,pillar,name", new { tenant.TenantId }, t)).ToArray(), ct);
    public Task<Guid> AddIndicatorAsync(EsgIndicatorCommand command, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { var id = Guid.NewGuid(); await c.ExecuteAsync("insert into agro360.esg_indicators(id,tenant_id,pillar,name,value,unit,period,methodology,recorded_by) values(@Id,@TenantId,@Pillar,@Name,@Value,@Unit,@Period,@Methodology,@UserId)", new { id, tenant.TenantId, command.Pillar, command.Name, command.Value, command.Unit, command.Period, command.Methodology, tenant.UserId }, t); return id; }, ct);
    public Task<IReadOnlyList<CarbonEntry>> CarbonAsync(CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => (IReadOnlyList<CarbonEntry>)(await c.QueryAsync<CarbonEntry>("select id,source,practice,activity_amount activityamount,unit,factor_kg_co2e factorkgco2e,sequestration_kg_co2e sequestrationkgco2e,round((activity_amount*factor_kg_co2e-sequestration_kg_co2e)/1000,4) nettonnesco2e,period,methodology from agro360.esg_carbon_inventory where tenant_id=@TenantId order by period desc", new { tenant.TenantId }, t)).ToArray(), ct);
    public Task<Guid> AddCarbonAsync(CarbonCommand command, CancellationToken ct) => db.InTenantTransactionAsync(async (c, t) => { SustainabilityCalculations.CarbonTonnes(command.ActivityAmount, command.FactorKgCo2e, command.SequestrationKgCo2e); var id = Guid.NewGuid(); await c.ExecuteAsync("insert into agro360.esg_carbon_inventory(id,tenant_id,source,practice,activity_amount,unit,factor_kg_co2e,sequestration_kg_co2e,period,methodology,recorded_by) values(@Id,@TenantId,@Source,@Practice,@ActivityAmount,@Unit,@FactorKgCo2e,@SequestrationKgCo2e,@Period,@Methodology,@UserId)", new { id, tenant.TenantId, command.Source, command.Practice, command.ActivityAmount, command.Unit, command.FactorKgCo2e, command.SequestrationKgCo2e, command.Period, command.Methodology, tenant.UserId }, t); return id; }, ct);
}
