using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Cooperatives;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class CooperativeService(DatabaseExecutor db,ITenantContext tenant) : ICooperativeService
{
 public Task<IReadOnlyList<CooperativeRecord>> ListAsync(string kind,string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<CooperativeRecord>)(await c.QueryAsync<CooperativeRecord>("select id,kind,name,status,amount,updated_at updatedat from agro360.cooperative_records where tenant_id=@TenantId and kind=@Kind and (@Status is null or status=@Status) order by updated_at desc",new{tenant.TenantId,Kind=kind,Status=status},t)).ToArray(),ct);
 public Task<Guid> SaveAsync(Guid? id,CooperativeCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(command.Kind=="OFFER"&&command.TraceabilityLotId is null)throw new ArgumentException("Selecione um lote rastreável para a oferta.");var key=id??Guid.NewGuid();var affected=await c.ExecuteAsync(id is null?"insert into agro360.cooperative_records(id,tenant_id,kind,name,party_id,property_id,traceability_lot_id,amount,details,status,created_by,updated_by) values(@Id,@TenantId,@Kind,@Name,@PartyId,@PropertyId,@TraceabilityLotId,@Amount,@Details::jsonb,'DRAFT',@UserId,@UserId)":"update agro360.cooperative_records set name=@Name,party_id=@PartyId,property_id=@PropertyId,traceability_lot_id=@TraceabilityLotId,amount=@Amount,details=@Details::jsonb,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and kind=@Kind",new{Id=key,tenant.TenantId,command.Kind,command.Name,command.PartyId,command.PropertyId,command.TraceabilityLotId,command.Amount,Details=JsonSerializer.Serialize(new{notes=command.Details}),tenant.UserId},t);if(affected==0)throw new KeyNotFoundException("Registro não encontrado.");return key;},ct);
 public Task<Guid> AddMemberAsync(MemberCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.cooperative_members where tenant_id=@TenantId and document=@Document)",new{tenant.TenantId,command.Document},t))throw new ArgumentException("Documento já cadastrado neste tenant.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.cooperative_members(id,tenant_id,name,document,organization_id,classification_id,property_id,productive_profile,status,created_by) values(@Id,@TenantId,@Name,@Document,@OrganizationId,@ClassificationId,@PropertyId,@ProductiveProfile,'ACTIVE',@UserId)",new{id,tenant.TenantId,command.Name,command.Document,command.OrganizationId,command.ClassificationId,command.PropertyId,command.ProductiveProfile,tenant.UserId},t);return id;},ct);
 public Task<Guid> AddCollectivePurchaseAsync(CollectivePurchaseCommand command,CancellationToken ct){CooperativeRules.ValidateAllocation(command.Quantity,command.Allocations.Select(a=>a.Quantity));return db.InTenantTransactionAsync(async(c,t)=>{var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.cooperative_collective_purchases(id,tenant_id,name,product_id,total_quantity,status,created_by) values(@Id,@TenantId,@Name,@ProductId,@Quantity,'DRAFT',@UserId)",new{id,tenant.TenantId,command.Name,command.ProductId,command.Quantity,tenant.UserId},t);foreach(var a in command.Allocations)await c.ExecuteAsync("insert into agro360.cooperative_collective_allocations(id,tenant_id,purchase_id,member_id,quantity) values(gen_random_uuid(),@TenantId,@Id,@MemberId,@Quantity)",new{tenant.TenantId,id,a.MemberId,a.Quantity},t);return id;},ct);}
 public Task ChangeStatusAsync(Guid id,string status,CancellationToken ct){CooperativeRules.ValidateTransition(status);return db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.cooperative_records set status=@Status,updated_by=@UserId,updated_at=now() where tenant_id=@TenantId and id=@Id; update agro360.cooperative_collective_purchases set status=@Status,approved_by=case when @Status='APPROVED' then @UserId end,approved_at=case when @Status='APPROVED' then now() end where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,Status=status,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Registro não encontrado.");},ct);}
 public Task<CooperativeDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<CooperativeDashboard>("select (select count(*) from agro360.cooperative_members where tenant_id=@TenantId and status='ACTIVE') activemembers,count(*) filter(where kind='PROGRAM' and status='ACTIVE') activeprograms,coalesce(sum(amount) filter(where kind='CONTRACT' and status='ACTIVE'),0) contractedvolume,coalesce(sum(amount) filter(where kind='CONTRACT' and status='CLOSED'),0) deliveredvolume,count(*) filter(where kind='OFFER' and status='ACTIVE') openoffers,count(*) filter(where kind='DEMAND' and status='ACTIVE') opendemands,(select count(*) from agro360.cooperative_collective_purchases where tenant_id=@TenantId and status in('DRAFT','APPROVED')) collectivepurchases,count(*) filter(where kind='VISIT' and status='DRAFT') pendingvisits,count(*) filter(where kind='CONTRACT' and status='ACTIVE' and (details->>'expiresOn')::date<=current_date+30) expiringcontracts,coalesce(sum(amount) filter(where kind='BONUS_RULE' and status='APPROVED'),0) pendingsettlements,count(*) filter(where kind='CREDIT_PREANALYSIS' and status not in('CLOSED','CANCELLED')) creditpreanalyses from agro360.cooperative_records where tenant_id=@TenantId",new{tenant.TenantId},t),ct);
 public Task<object> ProducerDashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(object)(await c.QueryAsync("select kind,name,status,amount,updated_at from agro360.cooperative_records where tenant_id=@TenantId and party_id=@UserId order by updated_at desc",new{tenant.TenantId,tenant.UserId},t)).ToArray(),ct);
}
