using Agro360.Application.Contracts;
using Agro360.Domain.Commercial;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;
namespace Agro360.Infrastructure.Services;

public sealed class CrmSaasService(DatabaseExecutor db,ITenantContext tenant):ICrmSaasService
{
 public Task<IReadOnlyList<SupportLookup>> PlansAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SupportLookup>)(await c.QueryAsync<SupportLookup>("select id,name from agro360.saas_plans where active order by monthly_price,name",transaction:t)).AsList(),ct);
 public Task<IReadOnlyList<CrmLead>> LeadsAsync(string? q,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<CrmLead>)(await c.QueryAsync<CrmLead>("select id,name,company,document,email,segment,source,status,revenue_potential revenuepotential,owner_id ownerid,created_at createdat from agro360.commercial_crm_leads where tenant_id=@TenantId and deleted_at is null and (@Q is null or name ilike '%'||@Q||'%' or company ilike '%'||@Q||'%' or email ilike '%'||@Q||'%') order by created_at desc limit 200",new{tenant.TenantId,Q=string.IsNullOrWhiteSpace(q)?null:q.Trim()},t)).AsList(),ct);
 public Task<IReadOnlyList<DuplicateLead>> DuplicatesAsync(string? document,string? email,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<DuplicateLead>)(await c.QueryAsync<DuplicateLead>("select id,name,document,email from agro360.commercial_crm_leads where tenant_id=@TenantId and deleted_at is null and ((@Document is not null and document=@Document) or (@Email is not null and lower(email)=lower(@Email)))",new{tenant.TenantId,Document=Clean(document),Email=Clean(email)},t)).AsList(),ct);
 public Task<Guid> CreateLeadAsync(LeadCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var duplicates=await c.ExecuteScalarAsync<int>("select count(*) from agro360.commercial_crm_leads where tenant_id=@TenantId and deleted_at is null and ((@Document is not null and document=@Document) or (@Email is not null and lower(email)=lower(@Email)))",new{tenant.TenantId,Document=Clean(x.Document),Email=Clean(x.Email)},t);if(duplicates>0)throw new InvalidOperationException("Possível lead duplicado por CPF/CNPJ ou e-mail. Revise o cadastro existente.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.commercial_crm_leads(id,tenant_id,name,company,document,email,segment,source,status,revenue_potential,owner_id,created_by,updated_by) values(@Id,@TenantId,@Name,@Company,@Document,@Email,@Segment,@Source,'NEW',@RevenuePotential,@OwnerId,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,x.Name,x.Company,Document=Clean(x.Document),Email=Clean(x.Email),x.Segment,x.Source,x.RevenuePotential,x.OwnerId},t);return id;},ct);
 public Task<IReadOnlyList<CrmOpportunity>> OpportunitiesAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<CrmOpportunity>)(await c.QueryAsync<CrmOpportunity>("select id,lead_id leadid,title,status,revenue_potential revenuepotential,probability,loss_reason lossreason,owner_id ownerid,expected_close_on expectedcloseon from agro360.commercial_crm_opportunities where tenant_id=@TenantId and deleted_at is null order by created_at desc",new{tenant.TenantId},t)).AsList(),ct);
 public Task<Guid> CreateOpportunityAsync(CrmOpportunityCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var id=Guid.NewGuid();var n=await c.ExecuteAsync("insert into agro360.commercial_crm_opportunities(id,tenant_id,lead_id,title,status,revenue_potential,probability,owner_id,expected_close_on,created_by,updated_by) select @Id,@TenantId,id,@Title,'NEW',@RevenuePotential,@Probability,@OwnerId,@ExpectedCloseOn,@UserId,@UserId from agro360.commercial_crm_leads where tenant_id=@TenantId and id=@LeadId and deleted_at is null",new{id,tenant.TenantId,tenant.UserId,x.LeadId,x.Title,x.RevenuePotential,x.Probability,x.OwnerId,x.ExpectedCloseOn},t);if(n==0)throw new KeyNotFoundException("Lead não encontrado.");return id;},ct);
 public Task<Guid?> TransitionOpportunityAsync(Guid id,OpportunityTransition x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SaasCommercialRules.ValidateOpportunityTransition(x.Status,x.Reason);Guid? createdTenant=null;if(x.Status=="WON"&&x.CreateTenant){var lead=await c.QuerySingleOrDefaultAsync<(string Name,string? Document)>("select l.name,l.document from agro360.commercial_crm_opportunities o join agro360.commercial_crm_leads l on l.tenant_id=o.tenant_id and l.id=o.lead_id where o.tenant_id=@TenantId and o.id=@Id",new{tenant.TenantId,id},t);if(lead==default)throw new KeyNotFoundException("Oportunidade não encontrada.");createdTenant=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.tenancy_tenants(id,name,slug,status,created_at,updated_at) values(@Id,@Name,lower(regexp_replace(@Name,'[^a-zA-Z0-9]+','-','g'))||'-'||substr(@Id::text,1,8),1,now(),now())",new{Id=createdTenant,lead.Name,lead.Document},t);}var n=await c.ExecuteAsync("update agro360.commercial_crm_opportunities set status=@Status,loss_reason=case when @Status='LOST' then @Reason else loss_reason end,won_tenant_id=coalesce(@CreatedTenant,won_tenant_id),updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,id,x.Status,x.Reason,CreatedTenant=createdTenant},t);if(n==0)throw new KeyNotFoundException("Oportunidade não encontrada.");return createdTenant;},ct);
 public Task<IReadOnlyList<CommercialProposal>> ProposalsAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<CommercialProposal>)(await c.QueryAsync<CommercialProposal>(ProposalSelect+" where tenant_id=@TenantId and deleted_at is null order by created_at desc",new{tenant.TenantId},t)).AsList(),ct);
 public Task<Guid> CreateProposalAsync(ProposalCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SaasCommercialRules.ValidateProposalForSending(x.CustomerTenantId,x.LeadId,x.PlanId);var total=SaasCommercialRules.ProposalTotal(x.MonthlyValue,x.ImplementationValue,x.SupportValue,x.Discount);var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.commercial_proposals(id,tenant_id,lead_id,customer_tenant_id,plan_id,status,users,units,monthly_value,annual_value,discount,implementation_value,support_value,total,valid_until,notes,created_by,updated_by) values(@Id,@TenantId,@LeadId,@CustomerTenantId,@PlanId,'DRAFT',@Users,@Units,@MonthlyValue,@AnnualValue,@Discount,@ImplementationValue,@SupportValue,@Total,@ValidUntil,@Notes,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,x.LeadId,x.CustomerTenantId,x.PlanId,x.Users,x.Units,x.MonthlyValue,AnnualValue=x.MonthlyValue*12,x.Discount,x.ImplementationValue,x.SupportValue,total,x.ValidUntil,x.Notes},t);return id;},ct);
 public Task TransitionProposalAsync(Guid id,ProposalTransition x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(x.Status=="REJECTED"&&string.IsNullOrWhiteSpace(x.Reason))throw new ArgumentException("A recusa exige motivo.");var p=await c.QuerySingleOrDefaultAsync<(DateOnly ValidUntil,Guid? LeadId,Guid? CustomerTenantId,Guid? PlanId)>("select valid_until validuntil,lead_id leadid,customer_tenant_id customertenantid,plan_id planid from agro360.commercial_proposals where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,id},t);if(p==default)throw new KeyNotFoundException("Proposta não encontrada.");if(x.Status=="SENT")SaasCommercialRules.ValidateProposalForSending(p.CustomerTenantId,p.LeadId,p.PlanId);if(x.Status=="ACCEPTED")SaasCommercialRules.ValidateProposalAcceptance(p.ValidUntil,DateOnly.FromDateTime(DateTime.UtcNow));await c.ExecuteAsync("update agro360.commercial_proposals set status=@Status,rejection_reason=case when @Status='REJECTED' then @Reason else rejection_reason end,accepted_at=case when @Status='ACCEPTED' then now() else accepted_at end,accepted_by=case when @Status='ACCEPTED' then @UserId else accepted_by end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,id,x.Status,x.Reason},t);},ct);
 public Task<Guid> CreateContractAsync(Guid proposalId,DateOnly startsOn,DateOnly endsOn,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(endsOn<=startsOn)throw new ArgumentException("A vigência final deve ser posterior à inicial.");var id=Guid.NewGuid();var n=await c.ExecuteAsync("insert into agro360.commercial_contracts(id,tenant_id,proposal_id,customer_tenant_id,plan_id,status,monthly_value,annual_value,starts_on,ends_on,sla,created_by,updated_by) select @Id,@TenantId,id,customer_tenant_id,plan_id,'ACTIVE',monthly_value,annual_value,@StartsOn,@EndsOn,'STANDARD',@UserId,@UserId from agro360.commercial_proposals where tenant_id=@TenantId and id=@ProposalId and status='ACCEPTED' and customer_tenant_id is not null",new{id,tenant.TenantId,tenant.UserId,proposalId,startsOn,endsOn},t);if(n==0)throw new InvalidOperationException("Contrato exige proposta aceita vinculada a um cliente.");await c.ExecuteAsync("update agro360.saas_organizations x set plan_id=c.plan_id,status='ACTIVE',updated_at=now() from agro360.commercial_contracts c where c.id=@Id and x.tenant_id=c.customer_tenant_id",new{id},t);return id;},ct);
 public Task<IReadOnlyList<SaasContract>> ContractsAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SaasContract>)(await c.QueryAsync<SaasContract>("select id,public_code publiccode,customer_tenant_id tenantid,proposal_id proposalid,plan_id planid,status,monthly_value monthlyvalue,annual_value annualvalue,starts_on startson,ends_on endson,sla from agro360.commercial_contracts where tenant_id=@TenantId and deleted_at is null order by created_at desc",new{tenant.TenantId},t)).AsList(),ct);
 public Task SuspendContractAsync(Guid id,string reason,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("A suspensão exige motivo.");var n=await c.ExecuteAsync("update agro360.commercial_contracts set status='SUSPENDED',suspension_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id; update agro360.tenancy_tenants x set status=2,updated_at=now() from agro360.commercial_contracts c where c.tenant_id=@TenantId and c.id=@Id and x.id=c.customer_tenant_id",new{tenant.TenantId,tenant.UserId,id,reason},t);if(n==0)throw new KeyNotFoundException("Contrato não encontrado.");},ct);
 public Task<IReadOnlyList<CustomerHealth>> HealthAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var rows=(await c.QueryAsync<(Guid TenantId,string TenantName,decimal AdoptionPercent,int CriticalTickets,int OverdueInvoices,int? Nps)>("select x.id tenantid,x.name tenantname,coalesce(m.adoption,0) adoptionpercent,coalesce(s.critical,0)::int criticaltickets,coalesce(i.overdue,0)::int overdueinvoices,f.nps from agro360.tenancy_tenants x left join lateral(select avg(value) adoption from agro360.support_customer_success_metrics where tenant_id=x.id and metric='USER_ADOPTION')m on true left join lateral(select count(*) critical from agro360.support_tickets where tenant_id=x.id and priority='CRITICAL' and status not in('RESOLVED','CLOSED','CANCELLED'))s on true left join lateral(select count(*) overdue from agro360.finance_receivables where tenant_id=x.id and status='OVERDUE')i on true left join lateral(select round(avg(score))::int nps from agro360.support_customer_feedback where tenant_id=x.id and type='NPS')f on true where x.id=@TenantId",new{tenant.TenantId},t)).AsList();return (IReadOnlyList<CustomerHealth>)rows.Select(x=>{var score=SaasCommercialRules.HealthScore(x.AdoptionPercent,x.CriticalTickets,x.OverdueInvoices,x.Nps);var risk=score<40?"HIGH":score<70?"MEDIUM":"LOW";var rec=x.OverdueInvoices>0?"Regularizar cobranças vencidas":x.AdoptionPercent<40?"Executar plano de adoção dos módulos contratados":x.CriticalTickets>0?"Priorizar chamados críticos":"Manter acompanhamento periódico";return new CustomerHealth(x.TenantId,x.TenantName,x.AdoptionPercent,x.CriticalTickets,x.OverdueInvoices,x.Nps,score,risk,rec);}).ToList();},ct);
 private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
 private const string ProposalSelect="select id,public_code publiccode,lead_id leadid,customer_tenant_id customertenantid,plan_id planid,status,monthly_value monthlyvalue,annual_value annualvalue,discount,implementation_value implementationvalue,support_value supportvalue,total,valid_until validuntil,accepted_at acceptedat from agro360.commercial_proposals";
}
