using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Deployment;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;
using Microsoft.Extensions.Logging;

namespace Agro360.Infrastructure.Services;

public sealed class DeploymentService(DatabaseExecutor db,ITenantContext tenant,ILogger<DeploymentService> logger):IDeploymentService
{
 public Task<IReadOnlyList<DeploymentTemplate>> TemplatesAsync(CancellationToken ct)=>db.InSystemTransactionAsync(async(c,t)=>(IReadOnlyList<DeploymentTemplate>)(await c.QueryAsync<DeploymentTemplate>("select code,name,segment,description,configuration::text Configuration from deployment.templates where active order by name",transaction:t)).ToArray(),ct);
 public Task<OnboardingResult> OnboardAsync(OnboardingCommand x,Guid actor,CancellationToken ct)
 {
  DeploymentRules.ValidateOnboarding(x.OrganizationName,x.Slug,x.Segment,x.PropertyName,x.AdministratorName,x.AdministratorEmail,x.InitialCycle,x.Modules);
  if(string.IsNullOrWhiteSpace(x.TemplateCode))throw new ArgumentException("Selecione um template de implantação.");
  return db.InSystemTransactionAsync(async(c,t)=>{
   var tenantId=Guid.NewGuid();var onboardingId=Guid.NewGuid();
   var exists=await c.ExecuteScalarAsync<bool>("select exists(select 1 from deployment.templates where code=@TemplateCode and active)",x,t);if(!exists)throw new ArgumentException("Template não encontrado.");
   await c.ExecuteAsync("insert into tenancy.tenants(id,name,slug,status,created_at) values(@TenantId,@OrganizationName,lower(@Slug),2,now()); select set_config('app.tenant_id',cast(@TenantId as text),true); insert into deployment.onboardings(id,tenant_id,segment,template_code,status,payload,created_by) values(@Id,@TenantId,upper(@Segment),@TemplateCode,'COMPLETED',cast(@Payload as jsonb),@Actor); insert into deployment.organization_modules(tenant_id,module_code,enabled,configured_by) select @TenantId,unnest(@Modules),true,@Actor; insert into deployment.checklist(tenant_id,item_code,label,required,completed,completed_at,updated_by,sort_order) select @TenantId,code,label,required,case when code=any(@Done) then true else false end,case when code=any(@Done) then now() end,@Actor,sort_order from deployment.checklist_catalog",new{TenantId=tenantId,Id=onboardingId,x.OrganizationName,x.Slug,x.Segment,x.TemplateCode,Payload=JsonSerializer.Serialize(x),x.Modules,Actor=actor,Done=new[]{"ORGANIZATION","ADMIN_USER","PROPERTY","CYCLE","PRODUCTS","COST_CENTERS","MODULES"}},t);
   logger.LogInformation("Onboarding {OnboardingId} concluiu organização {TenantId} no segmento {Segment}",onboardingId,tenantId,x.Segment);
   return new OnboardingResult(tenantId,onboardingId,x.ConfigureInitialStock&&x.ConfigureInitialFinance?75:58,"COMPLETED");
  },ct);
 }
 public Task<DeploymentChecklist> ChecklistAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var items=(await c.QueryAsync<ChecklistItem>("select item_code Code,label,required,completed,notes from deployment.checklist where tenant_id=@TenantId order by sort_order,item_code",new{tenant.TenantId},t)).ToArray();return new DeploymentChecklist(tenant.TenantId,DeploymentRules.Progress(items.Where(x=>x.Required).Select(x=>x.Completed)),items);},ct);
 public Task SetChecklistAsync(string code,bool completed,string? notes,Guid actor,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update deployment.checklist set completed=@Completed,completed_at=case when @Completed then now() else null end,notes=@Notes,updated_by=@Actor,updated_at=now() where tenant_id=@TenantId and item_code=@Code",new{tenant.TenantId,Code=code,completed,Notes=notes,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Item de checklist não encontrado.");},ct);
 public async Task<ImportPreview> PreviewAsync(ImportPreviewCommand x,CancellationToken ct)
 {
  var allowed=new[]{"PRODUCERS","PROPERTIES","FIELDS","PRODUCTS","SUPPLIERS","INPUTS","STOCK","CUSTOMERS","LIVESTOCK","MEMBERS"};if(!allowed.Contains(x.Type))throw new ArgumentException("Tipo de importação inválido.");
  var csv=DeploymentRules.ParseCsv(x.Content,x.Delimiter);var headers=csv[0];var rows=csv.Skip(1).Select((cells,i)=>{var values=headers.Select((h,j)=>(h,j)).ToDictionary(p=>p.h,p=>p.j<cells.Length?cells[p.j]:"");var errors=new List<string>();foreach(var target in x.Mapping.Where(m=>m.Key.Equals("name",StringComparison.OrdinalIgnoreCase)||m.Key.Equals("code",StringComparison.OrdinalIgnoreCase))){if(!values.TryGetValue(target.Value,out var value)||string.IsNullOrWhiteSpace(value))errors.Add($"{target.Key} é obrigatório.");}if(cells.Length!=headers.Length)errors.Add("Quantidade de colunas diferente do cabeçalho.");return new ImportRow(i+2,errors.Count==0,values,errors.ToArray());}).ToArray();
  var token=Guid.NewGuid();await db.InTenantTransactionAsync(async(c,t)=>{
   await c.ExecuteAsync("insert into deployment.import_previews(token,tenant_id,type,file_name,mapping,rows,expires_at) values(@Token,@TenantId,@Type,@FileName,cast(@Mapping as jsonb),cast(@Rows as jsonb),now()+interval '2 hours')",new{Token=token,tenant.TenantId,x.Type,x.FileName,Mapping=JsonSerializer.Serialize(x.Mapping),Rows=JsonSerializer.Serialize(rows)},t);
   var errors=rows.SelectMany(r=>r.Errors.Select(message=>new{Line=r.Line,Message=message})).ToArray();
   if(errors.Length>0)await c.ExecuteAsync("insert into deployment.import_errors(tenant_id,preview_token,line_number,message) values(@TenantId,@Token,@Line,@Message)",errors.Select(e=>new{tenant.TenantId,Token=token,e.Line,e.Message}),t);
  },ct);
  return new ImportPreview(token,x.Type,x.FileName,rows.Count(r=>r.Valid),rows.Count(r=>!r.Valid),rows);
 }
 public Task<Guid> ConfirmImportAsync(Guid token,Guid actor,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var preview=await c.QuerySingleOrDefaultAsync<(string Type,string FileName,string Rows)>("select type Type,file_name FileName,rows::text Rows from deployment.import_previews where token=@Token and tenant_id=@TenantId and expires_at>now()",new{Token=token,tenant.TenantId},t);if(preview==default)throw new KeyNotFoundException("Pré-visualização expirada ou inexistente.");var rows=JsonSerializer.Deserialize<ImportRow[]>(preview.Rows)??[];if(rows.Any(r=>!r.Valid))throw new ArgumentException("Corrija todas as linhas inválidas antes de confirmar.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into deployment.imports(id,tenant_id,type,file_name,status,total_rows,valid_rows,invalid_rows,rows,created_by,confirmed_at) values(@Id,@TenantId,@Type,@FileName,'COMPLETED',@Total,@Total,0,cast(@Rows as jsonb),@Actor,now()); delete from deployment.import_previews where token=@Token and tenant_id=@TenantId",new{Id=id,tenant.TenantId,preview.Type,preview.FileName,Total=rows.Length,Rows=preview.Rows,Actor=actor,Token=token},t);return id;},ct);
 public Task<IReadOnlyList<ImportHistory>> ImportsAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<ImportHistory>)(await c.QueryAsync<ImportHistory>("select id,type,file_name FileName,status,total_rows TotalRows,valid_rows ValidRows,invalid_rows InvalidRows,created_at CreatedAt from deployment.imports where tenant_id=@TenantId order by created_at desc limit 100",new{tenant.TenantId},t)).ToArray(),ct);
 public Task RollbackImportAsync(Guid id,Guid actor,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update deployment.imports set status='ROLLED_BACK',rolled_back_at=now(),rolled_back_by=@Actor where id=@Id and tenant_id=@TenantId and status='COMPLETED'",new{id,tenant.TenantId,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Importação concluída não encontrada.");},ct);
 public Task<DeploymentDashboard> DashboardAsync(CancellationToken ct)=>db.InSystemTransactionAsync(async(c,t)=>{var totals=await c.QuerySingleAsync<(int Done,int Pending,decimal Average)>("select count(*) filter(where progress=100)::int Done,count(*) filter(where progress<100)::int Pending,coalesce(avg(progress),0) Average from deployment.organization_progress",transaction:t);var modules=(await c.QueryAsync<string>("select module_code from deployment.organization_modules where enabled group by module_code order by count(*) desc limit 5",transaction:t)).ToArray();var segments=(await c.QueryAsync<string>("select segment from deployment.onboardings group by segment order by count(*) desc",transaction:t)).ToArray();var imports=(await c.QueryAsync<ImportHistory>("select id,type,file_name FileName,status,total_rows TotalRows,valid_rows ValidRows,invalid_rows InvalidRows,created_at CreatedAt from deployment.imports order by created_at desc limit 10",transaction:t)).ToArray();return new DeploymentDashboard(totals.Done,totals.Pending,totals.Average,modules,segments,imports.Sum(x=>x.InvalidRows),imports);},ct);
}
