using System.Text;
using Agro360.Application.Contracts;
using Agro360.Domain.Documents;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Agro360.Infrastructure.Services;

public sealed class DocumentService(DatabaseExecutor db, ITenantContext tenant, IConfiguration configuration, ILogger<DocumentService> logger) : IDocumentService
{
    private readonly string root = Path.GetFullPath(configuration["Storage:RootPath"] ?? Path.Combine(AppContext.BaseDirectory, "App_Data", "documents"));
    private readonly long maximumBytes = configuration.GetValue("Storage:MaxFileSizeBytes", DocumentRules.DefaultMaximumBytes);

    public Task<IReadOnlyList<LookupOption>> DocumentTypesAsync(CancellationToken ct) => Tx(async (c,t) => (IReadOnlyList<LookupOption>)(await c.QueryAsync<LookupOption>(new CommandDefinition("select id,name label from agro360.documents_document_types where active order by name", transaction:t,cancellationToken:ct))).ToArray(), ct);
    public Task<IReadOnlyList<DocumentRow>> DocumentsAsync(string? search, Guid? typeId, string? status, CancellationToken ct) => Tx(async(c,t)=>(IReadOnlyList<DocumentRow>)(await c.QueryAsync<DocumentRow>(new CommandDefinition("select d.id,d.name,dt.name typename,d.status,v.original_name originalname,v.size_bytes sizebytes,v.sha256,d.current_version currentversion,v.created_at uploadedat from agro360.documents d join agro360.documents_document_types dt on dt.id=d.document_type_id join agro360.documents_document_versions v on v.document_id=d.id and v.version_number=d.current_version and v.tenant_id=d.tenant_id where d.tenant_id=@TenantId and d.deleted_at is null and (@Search is null or d.name ilike '%'||@Search||'%' or coalesce(d.description,'') ilike '%'||@Search||'%' or exists(select 1 from agro360.documents_document_tags tg where tg.document_id=d.id and tg.tag ilike '%'||@Search||'%')) and (@TypeId is null or d.document_type_id=@TypeId) and (@Status is null or d.status=@Status) order by d.updated_at desc limit 200",new{tenant.TenantId,Search=Clean(search),TypeId=typeId,Status=Clean(status)?.ToUpperInvariant()},t,cancellationToken:ct))).ToArray(),ct);

    public async Task<Guid> UploadAsync(UploadDocumentCommand x, Stream content, string originalName, string mimeType, long length, CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>180) throw new DomainException("Nome do documento é obrigatório e deve ter até 180 caracteres.", "agro360.documents_validation");
        var extension=DocumentRules.ValidateFile(originalName,mimeType,length,maximumBytes);
        await EnsureLinkAsync(x.EntityType,x.EntityId,ct).ConfigureAwait(false);
        var id=Guid.CreateVersion7(); var versionId=Guid.CreateVersion7(); var relative=Path.Combine(tenant.TenantId.ToString("N"),id.ToString("N"),$"{versionId:N}{extension}");
        var physical=SafePath(relative); Directory.CreateDirectory(Path.GetDirectoryName(physical)!);
        try
        {
            await using(var output=new FileStream(physical,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true)) await content.CopyToAsync(output,ct).ConfigureAwait(false);
            await using var input=File.OpenRead(physical); var hash=await DocumentRules.Sha256Async(input,ct).ConfigureAwait(false);
            await Tx(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents(id,tenant_id,document_type_id,name,description,status,current_version,created_by,updated_by) values(@Id,@TenantId,@DocumentTypeId,@Name,@Description,'ACTIVE',1,@UserId,@UserId); insert into agro360.documents_document_versions(id,tenant_id,document_id,version_number,original_name,storage_key,extension,mime_type,size_bytes,sha256,created_by) values(@VersionId,@TenantId,@Id,1,@OriginalName,@Relative,@Extension,@MimeType,@Length,@Hash,@UserId); insert into agro360.documents_document_tags(id,tenant_id,document_id,tag,created_by) select gen_random_uuid(),@TenantId,@Id,trim(value),@UserId from unnest(string_to_array(coalesce(@Tags,''),',')) value where trim(value)<>''; insert into agro360.documents_document_links(id,tenant_id,document_id,entity_type,entity_id,entity_label,created_by) select gen_random_uuid(),@TenantId,@Id,@EntityType,@EntityId,@EntityLabel,@UserId where @EntityId is not null",new{Id=id,VersionId=versionId,tenant.TenantId,x.DocumentTypeId,Name=x.Name.Trim(),Description=Clean(x.Description),OriginalName=Path.GetFileName(originalName),Relative=relative.Replace('\\','/'),Extension=extension,MimeType=mimeType,Length=length,Hash,tenant.UserId,x.Tags,x.EntityType,x.EntityId,EntityLabel=x.EntityType},t,cancellationToken:ct));},ct).ConfigureAwait(false);
            return id;
        }
        catch(Exception ex){logger.LogError(ex,"Falha ao armazenar documento {DocumentId} do tenant {TenantId}",id,tenant.TenantId); try{File.Delete(physical);}catch(IOException cleanup){logger.LogWarning(cleanup,"Falha ao limpar arquivo de upload incompleto {DocumentId}",id);} throw;}
    }

    public async Task AddVersionAsync(Guid id,Stream content,string originalName,string mimeType,long length,string reason,CancellationToken ct)
    {
        DocumentRules.RequireReason(reason,"criar uma nova versão"); var extension=DocumentRules.ValidateFile(originalName,mimeType,length,maximumBytes); var versionId=Guid.CreateVersion7(); var relative=Path.Combine(tenant.TenantId.ToString("N"),id.ToString("N"),$"{versionId:N}{extension}"); var physical=SafePath(relative); Directory.CreateDirectory(Path.GetDirectoryName(physical)!);
        try { await using(var output=new FileStream(physical,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true))await content.CopyToAsync(output,ct); await using var input=File.OpenRead(physical);var hash=await DocumentRules.Sha256Async(input,ct); await Tx(async(c,t)=>{var next=await c.ExecuteScalarAsync<int?>(new CommandDefinition("select current_version+1 from agro360.documents where id=@Id and tenant_id=@TenantId and deleted_at is null for update",new{Id=id,tenant.TenantId},t,cancellationToken:ct))??throw new NotFoundException("Documento",id);await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_document_versions(id,tenant_id,document_id,version_number,original_name,storage_key,extension,mime_type,size_bytes,sha256,change_reason,created_by) values(@VersionId,@TenantId,@Id,@Next,@OriginalName,@Relative,@Extension,@MimeType,@Length,@Hash,@Reason,@UserId);update agro360.documents set current_version=@Next,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId",new{VersionId=versionId,tenant.TenantId,Id=id,Next=next,OriginalName=Path.GetFileName(originalName),Relative=relative.Replace('\\','/'),Extension=extension,MimeType=mimeType,Length=length,Hash,Reason=reason.Trim(),tenant.UserId},t,cancellationToken:ct));},ct); }
        catch(Exception ex){logger.LogError(ex,"Falha ao criar versão de {DocumentId}",id);try{File.Delete(physical);}catch(IOException){}throw;}
    }

    public Task<DocumentDetails?> DocumentAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var d=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select d.id,d.name,d.description,d.document_type_id,dt.name type_name,d.status from agro360.documents d join agro360.documents_document_types dt on dt.id=d.document_type_id where d.id=@Id and d.tenant_id=@TenantId and d.deleted_at is null",new{Id=id,tenant.TenantId},t,cancellationToken:ct));if(d is null)return null;var versions=(await c.QueryAsync<DocumentVersionRow>(new CommandDefinition("select id,version_number versionnumber,original_name originalname,size_bytes sizebytes,mime_type mimetype,sha256,change_reason changereason,created_at createdat from agro360.documents_document_versions where tenant_id=@TenantId and document_id=@Id order by version_number desc",new{Id=id,tenant.TenantId},t,cancellationToken:ct))).ToArray();var links=(await c.QueryAsync<DocumentLinkRow>(new CommandDefinition("select id,entity_type entitytype,entity_label entitylabel from agro360.documents_document_links where tenant_id=@TenantId and document_id=@Id and deleted_at is null",new{Id=id,tenant.TenantId},t,cancellationToken:ct))).ToArray();var tags=(await c.QueryAsync<string>(new CommandDefinition("select tag from agro360.documents_document_tags where tenant_id=@TenantId and document_id=@Id order by tag",new{Id=id,tenant.TenantId},t,cancellationToken:ct))).ToArray();return new DocumentDetails(d.id,d.name,d.description,d.document_type_id,d.type_name,d.status,versions,links,tags);},ct);
    public Task<StoredDownload> DownloadAsync(Guid documentId,Guid? versionId,CancellationToken ct)=>Tx(async(c,t)=>{var row=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select v.storage_key,v.mime_type,v.original_name from agro360.documents d join agro360.documents_document_versions v on v.document_id=d.id and v.tenant_id=d.tenant_id where d.id=@Id and d.tenant_id=@TenantId and d.deleted_at is null and (@VersionId is null and v.version_number=d.current_version or v.id=@VersionId)",new{Id=documentId,VersionId=versionId,tenant.TenantId},t,cancellationToken:ct))??throw new NotFoundException("Documento",documentId);var path=SafePath((string)row.storage_key);if(!File.Exists(path))throw new NotFoundException("Arquivo",documentId);await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_document_access_logs(id,tenant_id,document_id,version_id,action,accessed_by) values(gen_random_uuid(),@TenantId,@Id,@VersionId,'DOWNLOAD',@UserId)",new{tenant.TenantId,Id=documentId,VersionId=versionId,tenant.UserId},t,cancellationToken:ct));return new StoredDownload(new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read),row.mime_type,row.original_name);},ct);
    public Task ArchiveAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.documents set status='ARCHIVED',updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId and deleted_at is null",new{Id=id,tenant.TenantId,tenant.UserId},t,cancellationToken:ct))==0)throw new NotFoundException("Documento",id);},ct);

    public Task<IReadOnlyList<EvidenceRow>> EvidencesAsync(string? status,CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<EvidenceRow>)(await c.QueryAsync<EvidenceRow>(new CommandDefinition("select e.id,e.document_id documentid,d.name documentname,e.origin,e.description,e.status,e.event_at eventat,e.latitude,e.longitude from agro360.documents_evidences e join agro360.documents d on d.id=e.document_id and d.tenant_id=e.tenant_id where e.tenant_id=@TenantId and e.deleted_at is null and (@Status is null or e.status=@Status) order by e.event_at desc",new{tenant.TenantId,Status=Clean(status)?.ToUpperInvariant()},t,cancellationToken:ct))).ToArray(),ct);
    public Task<Guid> CreateEvidenceAsync(CreateEvidenceCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var id=Guid.CreateVersion7();if(await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_evidences(id,tenant_id,document_id,origin,description,event_at,latitude,longitude,tags,status,created_by,updated_by) select @Id,@TenantId,@DocumentId,@Origin,@Description,@EventAt,@Latitude,@Longitude,string_to_array(coalesce(@Tags,''),','),'PENDING',@UserId,@UserId where exists(select 1 from agro360.documents where id=@DocumentId and tenant_id=@TenantId and deleted_at is null)",new{Id=id,tenant.TenantId,x.DocumentId,Origin=x.Origin.ToUpperInvariant(),Description=x.Description.Trim(),x.EventAt,x.Latitude,x.Longitude,x.Tags,tenant.UserId},t,cancellationToken:ct))==0)throw new DomainException("Documento não encontrado neste tenant.", "agro360.documents_validation");return id;},ct);
    public Task ValidateEvidenceAsync(Guid id,ValidateEvidenceCommand x,CancellationToken ct){var status=x.Status.ToUpperInvariant();DocumentRules.ValidateDecision(status,x.Reason);return Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.documents_evidences set status=@Status,validation_reason=@Reason,validated_at=now(),validated_by=@UserId,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId and status='PENDING';insert into agro360.documents_evidence_validations(id,tenant_id,evidence_id,status,reason,validated_by) select gen_random_uuid(),@TenantId,@Id,@Status,@Reason,@UserId where exists(select 1 from agro360.documents_evidences where id=@Id and tenant_id=@TenantId and status=@Status)",new{Id=id,tenant.TenantId,Status=status,Reason=Clean(x.Reason),tenant.UserId},t,cancellationToken:ct))<2)throw new ConflictException("Evidência inexistente ou já decidida.");},ct);}

    public Task<IReadOnlyList<DossierRow>> DossiersAsync(CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<DossierRow>)(await c.QueryAsync<DossierRow>(new CommandDefinition("select d.id,d.name,d.type,d.status,d.opened_at openedat,(select count(*) from agro360.documents_dossier_items i where i.dossier_id=d.id and i.tenant_id=d.tenant_id) itemcount,(select count(*) from agro360.documents_dossier_checklist_items q where q.dossier_id=d.id and q.tenant_id=d.tenant_id and not q.completed) pendingchecklist from agro360.documents_dossiers d where d.tenant_id=@TenantId and d.deleted_at is null order by d.updated_at desc",new{tenant.TenantId},t,cancellationToken:ct))).ToArray(),ct);
    public Task<Guid> CreateDossierAsync(CreateDossierCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_dossiers(id,tenant_id,name,type,status,entity_type,entity_id,notes,responsible_id,created_by,updated_by) values(@Id,@TenantId,@Name,@Type,'BUILDING',@EntityType,@EntityId,@Notes,@UserId,@UserId,@UserId);insert into agro360.documents_dossier_checklist_items(id,tenant_id,dossier_id,label,required,completed,created_by) select gen_random_uuid(),@TenantId,@Id,trim(value),true,false,@UserId from unnest(@Checklist) value where trim(value)<>''",new{Id=id,tenant.TenantId,Name=x.Name.Trim(),Type=x.Type.ToUpperInvariant(),x.EntityType,x.EntityId,x.Notes,Checklist=x.Checklist.ToArray(),tenant.UserId},t,cancellationToken:ct));return id;},ct);
    public Task DecideDossierAsync(Guid id,DossierDecisionCommand x,CancellationToken ct){var status=x.Status.ToUpperInvariant();if(status=="REJECTED")DocumentRules.RequireReason(x.Reason,"reprovar o dossiê");return Tx(async(c,t)=>{if(status=="APPROVED"&&await c.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.documents_dossier_checklist_items where dossier_id=@Id and tenant_id=@TenantId and required and not completed",new{Id=id,tenant.TenantId},t,cancellationToken:ct))>0)throw new DomainException("Conclua o checklist obrigatório antes da aprovação.", "agro360.documents_validation");if(await c.ExecuteAsync(new CommandDefinition("update agro360.documents_dossiers set status=@Status,rejection_reason=case when @Status='REJECTED' then @Reason end,closed_at=case when @Status='CLOSED' then now() end,closed_by=case when @Status='CLOSED' then @UserId end,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId",new{Id=id,tenant.TenantId,Status=status,Reason=Clean(x.Reason),tenant.UserId},t,cancellationToken:ct))==0)throw new NotFoundException("Dossiê",id);},ct);}

    public Task<IReadOnlyList<CertificateRow>> CertificatesAsync(CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<CertificateRow>)(await c.QueryAsync<CertificateRow>(new CommandDefinition(CertificateSql+" where c.tenant_id=@TenantId order by c.issued_at desc",new{tenant.TenantId},t,cancellationToken:ct))).ToArray(),ct);
    public Task<CertificateRow> IssueCertificateAsync(IssueCertificateCommand x,CancellationToken ct)=>Tx(async(c,t)=>{if(!await EntityExists(c,t,x.EntityType,x.EntityId,ct))throw new DomainException("Vínculo do certificado não existe neste tenant.", "agro360.documents_validation");var id=Guid.CreateVersion7();var code=Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(10));var payload=$"{code}|{x.Type}|{x.SubjectSummary}|{tenant.TenantId:N}|{DateTimeOffset.UtcNow:O}";var hash=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(payload))).ToLowerInvariant();await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_certificates(id,tenant_id,dossier_id,type,public_code,verification_hash,status,organization_name,entity_type,entity_id,subject_summary,traceability_summary,issued_at,valid_until,issued_by,created_by,updated_by) values(@Id,@TenantId,@DossierId,@Type,@Code,@Hash,'ISSUED',(select name from agro360.tenancy_tenants where id=@TenantId),@EntityType,@EntityId,@SubjectSummary,@TraceabilitySummary,now(),@ValidUntil,@UserId,@UserId,@UserId);insert into agro360.documents_certificate_events(id,tenant_id,certificate_id,event_type,created_by) values(gen_random_uuid(),@TenantId,@Id,'ISSUED',@UserId)",new{Id=id,tenant.TenantId,x.DossierId,Type=x.Type.ToUpperInvariant(),Code=code,Hash,x.EntityType,x.EntityId,x.SubjectSummary,x.TraceabilitySummary,x.ValidUntil,tenant.UserId},t,cancellationToken:ct));return await c.QuerySingleAsync<CertificateRow>(new CommandDefinition(CertificateSql+" where c.id=@Id and c.tenant_id=@TenantId",new{Id=id,tenant.TenantId},t,cancellationToken:ct));},ct);
    public Task RevokeCertificateAsync(Guid id,string reason,CancellationToken ct){DocumentRules.RequireReason(reason,"revogar o certificado");return Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.documents_certificates set status='REVOKED',revocation_reason=@Reason,revoked_at=now(),revoked_by=@UserId,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId and status='ISSUED';insert into agro360.documents_certificate_events(id,tenant_id,certificate_id,event_type,reason,created_by) select gen_random_uuid(),@TenantId,@Id,'REVOKED',@Reason,@UserId where exists(select 1 from agro360.documents_certificates where id=@Id and tenant_id=@TenantId and status='REVOKED')",new{Id=id,tenant.TenantId,Reason=reason.Trim(),tenant.UserId},t,cancellationToken:ct))<2)throw new ConflictException("Certificado inexistente ou não está emitido.");},ct);}
    public Task<PublicCertificate?> PublicCertificateAsync(string code,string? remote,CancellationToken ct){if(string.IsNullOrWhiteSpace(code)||code.Length is <10 or >40)return Task.FromResult<PublicCertificate?>(null);return db.InSystemTransactionAsync(async(c,t)=>{var item=await c.QuerySingleOrDefaultAsync<PublicCertificate>(new CommandDefinition("select public_code publiccode,type,case when valid_until<now() and status='ISSUED' then 'EXPIRED' else status end status,organization_name organizationname,subject_summary subjectsummary,traceability_summary traceabilitysummary,issued_at issuedat,valid_until validuntil,verification_hash verificationhash from agro360.documents_certificates where public_code=@Code",new{Code=code.Trim().ToUpperInvariant()},t,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("insert into agro360.documents_public_certificate_access_logs(id,certificate_id,code_searched,found,remote_address_hash) values(gen_random_uuid(),@Id,@Code,@Found,encode(digest(coalesce(@Remote,''),'sha256'),'hex'))",new{Id=item is null?(Guid?)null:await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.documents_certificates where public_code=@Code",new{Code=code.Trim().ToUpperInvariant()},t,cancellationToken:ct)),Code=code.Trim().ToUpperInvariant(),Found=item is not null,Remote=remote},t,cancellationToken:ct));return item;},ct);}

    public async Task<DocumentDashboard> DashboardAsync(CancellationToken ct)=>await Tx(async(c,t)=>{var p=new{tenant.TenantId};var counts=await c.QuerySingleAsync<dynamic>(new CommandDefinition("select (select count(*) from agro360.documents where tenant_id=@TenantId and deleted_at is null) total,(select count(*) from agro360.documents d where tenant_id=@TenantId and deleted_at is null and not exists(select 1 from agro360.documents_document_links l where l.document_id=d.id and l.deleted_at is null)) unlinked,(select count(*) from agro360.documents_evidences where tenant_id=@TenantId and status='PENDING') pending,(select count(*) from agro360.documents_evidences where tenant_id=@TenantId and status='VALIDATED') validated,(select count(*) from agro360.documents_evidences where tenant_id=@TenantId and status='REJECTED') rejected,(select count(*) from agro360.documents_dossiers where tenant_id=@TenantId and status='BUILDING') building,(select count(*) from agro360.documents_dossiers where tenant_id=@TenantId and status='REVIEWING') reviewing,(select count(*) from agro360.documents_dossiers where tenant_id=@TenantId and status='APPROVED') approved,(select count(*) from agro360.documents_certificates where tenant_id=@TenantId and status='ISSUED') issued,(select count(*) from agro360.documents_certificates where tenant_id=@TenantId and status='REVOKED') revoked",p,t,cancellationToken:ct));var docs=(await c.QueryAsync<DocumentRow>(new CommandDefinition("select d.id,d.name,dt.name typename,d.status,v.original_name originalname,v.size_bytes sizebytes,v.sha256,d.current_version currentversion,v.created_at uploadedat from agro360.documents d join agro360.documents_document_types dt on dt.id=d.document_type_id join agro360.documents_document_versions v on v.document_id=d.id and v.version_number=d.current_version where d.tenant_id=@TenantId and d.deleted_at is null order by d.created_at desc limit 5",p,t,cancellationToken:ct))).ToArray();var certs=(await c.QueryAsync<CertificateRow>(new CommandDefinition(CertificateSql+" where c.tenant_id=@TenantId order by c.issued_at desc limit 5",p,t,cancellationToken:ct))).ToArray();return new DocumentDashboard(counts.total,counts.unlinked,counts.pending,counts.validated,counts.rejected,counts.building,counts.reviewing,counts.approved,counts.issued,counts.revoked,docs,certs);},ct);
    public async Task<byte[]> ExportCsvAsync(string resource,CancellationToken ct){IEnumerable<object> rows=resource switch{"documents"=>await DocumentsAsync(null,null,null,ct),"evidences"=>await EvidencesAsync(null,ct),"dossiers"=>await DossiersAsync(ct),"certificates"=>await CertificatesAsync(ct),_=>throw new DomainException("Exportação inválida.", "agro360.documents_validation")};var props=rows.GetType().GetGenericArguments().FirstOrDefault()?.GetProperties()??rows.FirstOrDefault()?.GetType().GetProperties()??[];var sb=new StringBuilder().AppendLine(string.Join(';',props.Select(p=>p.Name)));foreach(var row in rows)sb.AppendLine(string.Join(';',props.Select(p=>$"\"{p.GetValue(row)?.ToString()?.Replace("\"","\"\"")}\"")));return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray();}

    public Task<IReadOnlyList<LookupOption>> EntityLookupAsync(string entityType,string? search,CancellationToken ct)=>Tx(async(c,t)=>{var (table,label)=EntitySource(entityType);var sql=$"select id,{label} label from {table} where tenant_id=@TenantId and (@Search is null or {label} ilike '%'||@Search||'%') order by {label} limit 50";return(IReadOnlyList<LookupOption>)(await c.QueryAsync<LookupOption>(new CommandDefinition(sql,new{tenant.TenantId,Search=Clean(search)},t,cancellationToken:ct))).ToArray();},ct);
    private async Task EnsureLinkAsync(string? type,Guid? id,CancellationToken ct){if(id is null&&string.IsNullOrWhiteSpace(type))return;if(id is null||string.IsNullOrWhiteSpace(type))throw new DomainException("Selecione um vínculo válido.", "agro360.documents_validation");await Tx(async(c,t)=>{if(!await EntityExists(c,t,type,id.Value,ct))throw new DomainException("Vínculo inexistente ou não autorizado.", "agro360.documents_validation");},ct);}
    private async Task<bool> EntityExists(System.Data.Common.DbConnection c,System.Data.Common.DbTransaction t,string type,Guid id,CancellationToken ct){var(table,_)=EntitySource(type);return await c.ExecuteScalarAsync<bool>(new CommandDefinition($"select exists(select 1 from {table} where tenant_id=@TenantId and id=@Id)",new{tenant.TenantId,Id=id},t,cancellationToken:ct));}
    private static (string,string) EntitySource(string type)=>type.ToUpperInvariant() switch{"PROPERTY"=>("agro360.geo_farms","name"),"PLOT"=>("agro360.geo_plots","name"),"SEASON"=>("agro360.agriculture_seasons","name"),"PRODUCT"=>("agro360.inventory_products","name"),"LOT"=>("agro360.traceability_lots","code"),"CUSTOMER"=>("agro360.crm_customers","name"),"CONTRACT"=>("agro360.sales_contracts","name"),"SUPPLIER"=>("agro360.purchasing_suppliers","name"),"DOSSIER"=>("agro360.documents_dossiers","name"),_=>throw new DomainException("Tipo de vínculo não suportado.", "agro360.documents_validation")};
    private string SafePath(string relative){if(Path.IsPathRooted(relative))throw new DomainException("Caminho de armazenamento inválido.", "agro360.documents_validation");var path=Path.GetFullPath(Path.Combine(root,relative));var prefix=root.TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;if(!path.StartsWith(prefix,StringComparison.Ordinal))throw new DomainException("Caminho de armazenamento inválido.", "agro360.documents_validation");return path;}
    private Task<T> Tx<T>(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task<T>> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);private Task Tx(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);
    private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private const string CertificateSql="select c.id,c.public_code publiccode,c.type,c.status,c.organization_name organizationname,c.subject_summary subjectsummary,c.issued_at issuedat,c.valid_until validuntil,c.verification_hash verificationhash from agro360.documents_certificates c";
}
