using System.Security.Cryptography;
using System.Text;
using Agro360.Application.Abstractions;
using Agro360.Application.Contracts;
using Agro360.Domain.Ecosystem;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;
using Microsoft.Extensions.Logging;
namespace Agro360.Infrastructure.Services;

public sealed class EcosystemService(DatabaseExecutor db,ITenantContext tenant,ILogger<EcosystemService> log):IEcosystemService
{
 public Task<EcosystemDashboard> DashboardAsync(CancellationToken ct)=>Tx((c,t)=>c.QuerySingleAsync<EcosystemDashboard>("select (select count(*) from agro360.platform_marketplace_modules where deleted_at is null) modules,(select count(*) from agro360.platform_marketplace_requests where tenant_id=@TenantId and status='PENDING') pendingrequests,(select count(*) from agro360.platform_partner_tenant_access where tenant_id=@TenantId and status='ACTIVE' and expires_at>now()) activepartners,(select count(*) from agro360.platform_external_apps where tenant_id=@TenantId and status='ACTIVE') activeapps,(select count(*) from agro360.platform_webhook_subscriptions where tenant_id=@TenantId and status='ACTIVE') activewebhooks,(select count(*) from agro360.platform_webhook_deliveries where tenant_id=@TenantId and status='FAILED') faileddeliveries",new{tenant.TenantId},t),ct);
 public Task<IReadOnlyList<MarketplaceModule>> ModulesAsync(CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<MarketplaceModule>)(await c.QueryAsync<MarketplaceModule>("select m.id,m.code,m.name,m.description,m.segments,m.plans,m.dependencies,m.official,m.featured,coalesce(tm.status,'AVAILABLE') status from agro360.platform_marketplace_modules m left join agro360.platform_tenant_modules tm on tm.module_id=m.id and tm.tenant_id=@TenantId where m.deleted_at is null and (m.plans='{}' or m.plans && (select p.modules from agro360.saas_organizations o join agro360.saas_plans p on p.id=o.plan_id where o.tenant_id=@TenantId)) order by m.featured desc,m.name",new{tenant.TenantId},t)).ToArray(),ct);
 public Task<Guid>CreateModuleAsync(MarketplaceModuleCommand x,Guid actor,CancellationToken ct){EcosystemRules.Module(x.Code,x.Name);return Tx(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.platform_marketplace_modules(id,code,name,description,segments,plans,dependencies,official,featured,status,created_by,updated_by) values(@Id,@Code,@Name,@Description,@Segments,@Plans,@Dependencies,@Official,@Featured,'ACTIVE',@Actor,@Actor)",new{Id=id,x.Code,x.Name,x.Description,x.Segments,x.Plans,x.Dependencies,x.Official,x.Featured,Actor=actor},t);return id;},ct);}
 public Task<Guid>RequestModuleAsync(ModuleActivationCommand x,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{var missing=await c.ExecuteScalarAsync<int>("select count(*) from agro360.platform_marketplace_modules m,unnest(m.dependencies) d where m.id=@ModuleId and not exists(select 1 from agro360.platform_tenant_modules tm join agro360.platform_marketplace_modules dm on dm.id=tm.module_id where tm.tenant_id=@TenantId and dm.code=d and tm.status='ACTIVE')",new{x.ModuleId,tenant.TenantId},t);if(missing>0)throw new InvalidOperationException("Ative primeiro as dependências obrigatórias do módulo.");var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.platform_marketplace_requests(id,tenant_id,module_id,status,justification,trial_ends_at,created_by,updated_by) values(@Id,@TenantId,@ModuleId,'PENDING',@Justification,@TrialEndsAt,@Actor,@Actor);insert into agro360.platform_integration_audit_events(id,tenant_id,category,action,entity_id,actor_id,details) values(gen_random_uuid(),@TenantId,'MARKETPLACE','MODULE_REQUESTED',@Id,@Actor,'{}')",new{Id=id,tenant.TenantId,x.ModuleId,x.Justification,x.TrialEndsAt,Actor=actor},t);return id;},ct);
 public Task DecideModuleAsync(Guid id,bool approve,string reason,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Informe a decisão.");var n=await c.ExecuteAsync("with r as(update agro360.platform_marketplace_requests set status=@Status,decision_reason=@Reason,decided_at=now(),decided_by=@Actor,updated_at=now(),updated_by=@Actor where id=@Id and status='PENDING' returning tenant_id,module_id,trial_ends_at) insert into agro360.platform_tenant_modules(id,tenant_id,module_id,status,trial_started_at,trial_ends_at,created_by,updated_by) select gen_random_uuid(),tenant_id,module_id,case when @Approve then 'ACTIVE' else 'REJECTED' end,case when trial_ends_at is not null then now() end,trial_ends_at,@Actor,@Actor from r on conflict(tenant_id,module_id) do update set status=excluded.status,trial_ends_at=excluded.trial_ends_at,updated_at=now(),updated_by=@Actor",new{Id=id,Approve=approve,Status=approve?"APPROVED":"REJECTED",Reason=reason.Trim(),Actor=actor},t);if(n==0)throw new KeyNotFoundException("Solicitação pendente não encontrada.");},ct);
 public Task<object>PartnersAsync(CancellationToken ct)=>Rows("select p.id,p.name,p.type,p.document,p.email,p.status,a.scopes,a.modules,a.expires_at from agro360.platform_partner_accounts p left join agro360.platform_partner_tenant_access a on a.partner_id=p.id and a.tenant_id=@TenantId and a.status='ACTIVE' where p.deleted_at is null order by p.name",ct);
 public Task<Guid>CreatePartnerAsync(PartnerCommand x,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{var id=Guid.CreateVersion7();var doc=EcosystemRules.Document(x.Document);await c.ExecuteAsync("insert into agro360.platform_partner_accounts(id,name,type,document,email,coverage,segments,status,created_by,updated_by) values(@Id,@Name,@Type,@Document,@Email,@Coverage,@Segments,'ACTIVE',@Actor,@Actor)",new{Id=id,x.Name,x.Type,Document=doc,x.Email,x.Coverage,x.Segments,Actor=actor},t);return id;},ct);
 public Task SetPartnerBlockedAsync(Guid id,bool blocked,string reason,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{if(blocked&&string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo obrigatório.");await c.ExecuteAsync("update agro360.platform_partner_accounts set status=@Status,blocked_reason=@Reason,updated_at=now(),updated_by=@Actor where id=@Id;update agro360.platform_partner_tenant_access set status=case when @Blocked then 'BLOCKED' else status end,updated_at=now(),updated_by=@Actor where partner_id=@Id",new{Id=id,Blocked=blocked,Status=blocked?"BLOCKED":"ACTIVE",Reason=reason,Actor=actor},t);},ct);
 public Task<Guid>GrantPartnerAsync(PartnerAccessCommand x,Guid actor,CancellationToken ct){EcosystemRules.Scopes(x.Scopes);return Tx(async(c,t)=>{if(x.TenantId!=tenant.TenantId)throw new UnauthorizedAccessException("Tenant fora do contexto.");if(x.ExpiresAt<=DateTimeOffset.UtcNow)throw new ArgumentException("Prazo deve ser futuro.");var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.platform_partner_tenant_access(id,tenant_id,partner_id,scopes,modules,status,expires_at,created_by,updated_by) select @Id,@TenantId,@PartnerId,@Scopes,@Modules,'ACTIVE',@ExpiresAt,@Actor,@Actor where exists(select 1 from agro360.platform_partner_accounts where id=@PartnerId and status='ACTIVE')",new{Id=id,tenant.TenantId,x.PartnerId,x.Scopes,x.Modules,x.ExpiresAt,Actor=actor},t);return id;},ct);}
 public Task RevokePartnerAsync(Guid id,string reason,Guid actor,CancellationToken ct)=>Update("update agro360.platform_partner_tenant_access set status='REVOKED',revoked_at=now(),revocation_reason=@Reason,updated_at=now(),updated_by=@Actor where id=@Id and tenant_id=@TenantId and status='ACTIVE'",id,reason,actor,ct);
 public Task<object>AppsAsync(CancellationToken ct)=>Rows("select id,name,description,status,requests_per_minute,created_at from agro360.platform_external_apps where tenant_id=@TenantId and deleted_at is null order by created_at desc",ct);
 public Task<Guid>CreateAppAsync(ExternalAppCommand x,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{if(string.IsNullOrWhiteSpace(x.Name)||x.RequestsPerMinute is <1 or >10000)throw new ArgumentException("Aplicação e limite válidos são obrigatórios.");var id=Guid.CreateVersion7();await c.ExecuteAsync("insert into agro360.platform_external_apps(id,tenant_id,name,description,status,requests_per_minute,created_by,updated_by) values(@Id,@TenantId,@Name,@Description,'ACTIVE',@RequestsPerMinute,@Actor,@Actor)",new{Id=id,tenant.TenantId,x.Name,x.Description,x.RequestsPerMinute,Actor=actor},t);return id;},ct);
 public Task<PlatformApiKeyCreated>CreateKeyAsync(PlatformApiKeyCommand x,Guid actor,CancellationToken ct){EcosystemRules.Scopes(x.Scopes);return Tx(async(c,t)=>{var id=Guid.CreateVersion7();var raw="ag360_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw))).ToLowerInvariant();var n=await c.ExecuteAsync("insert into agro360.platform_api_keys(id,tenant_id,app_id,name,key_prefix,key_hash,status,expires_at,created_by,updated_by) select @Id,@TenantId,@AppId,@Name,@Prefix,@Hash,'ACTIVE',@ExpiresAt,@Actor,@Actor where exists(select 1 from agro360.platform_external_apps where id=@AppId and tenant_id=@TenantId and status='ACTIVE');insert into agro360.platform_api_key_scopes(api_key_id,scope_id) select @Id,id from agro360.platform_api_scopes where code=any(@Scopes)",new{Id=id,tenant.TenantId,x.AppId,x.Name,Prefix=raw[..14],Hash=hash,x.ExpiresAt,x.Scopes,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Aplicação ativa não encontrada.");return new(id,raw,raw[..14]);},ct);}
 public Task RevokeKeyAsync(Guid id,Guid actor,CancellationToken ct)=>Update("update agro360.platform_api_keys set status='REVOKED',revoked_at=now(),updated_at=now(),updated_by=@Actor where id=@Id and tenant_id=@TenantId and status='ACTIVE'",id,"revoked",actor,ct);
 public Task<object>WebhooksAsync(CancellationToken ct)=>Rows("select id,url,events,status,maximum_attempts,created_at from agro360.platform_webhook_subscriptions where tenant_id=@TenantId and deleted_at is null order by created_at desc",ct);
 public Task<Guid>CreateWebhookAsync(WebhookSubscriptionCommand x,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{var url=EcosystemRules.Webhook(x.Url);if(x.Events.Length==0||x.Events.Any(e=>!EcosystemRules.WebhookEvents.Contains(e)))throw new ArgumentException("Evento inválido.");if(x.MaximumAttempts is <1 or >10)throw new ArgumentException("Tentativas entre 1 e 10.");var id=Guid.CreateVersion7();var secret=RandomNumberGenerator.GetBytes(32);var hash=Convert.ToHexString(SHA256.HashData(secret)).ToLowerInvariant();await c.ExecuteAsync("insert into agro360.platform_webhook_subscriptions(id,tenant_id,app_id,url,events,secret_hash,status,maximum_attempts,created_by,updated_by) values(@Id,@TenantId,@AppId,@Url,@Events,@Hash,'ACTIVE',@MaximumAttempts,@Actor,@Actor)",new{Id=id,tenant.TenantId,x.AppId,Url=url.ToString(),x.Events,Hash=hash,x.MaximumAttempts,Actor=actor},t);return id;},ct);
 public Task<object>LogsAsync(CancellationToken ct)=>Rows("select id,category,action,entity_id,created_at,details from agro360.platform_integration_audit_events where tenant_id=@TenantId order by created_at desc limit 200",ct);
 public Task<object>DeveloperDocsAsync(CancellationToken ct)=>Rows("select slug,title,culture,content,example_payload,updated_at from agro360.platform_developer_docs where active and culture=current_setting('app.culture',true) order by sort_order",ct);
 public Task<object>CommercialCatalogAsync(CancellationToken ct)=>Rows("select c.id,c.name,c.description,c.monthly_price,c.annual_price,c.user_limit,c.property_limit,c.integration_limit,c.webhook_limit,c.languages,c.status,array_agg(f.feature_code) features from agro360.platform_commercial_catalog c left join agro360.platform_commercial_plan_features f on f.catalog_id=c.id group by c.id order by c.monthly_price",ct);
 private Task<object>Rows(string sql,CancellationToken ct)=>Tx(async(c,t)=>(object)(await c.QueryAsync(sql,new{tenant.TenantId},t)).ToArray(),ct);
 private Task Update(string sql,Guid id,string reason,Guid actor,CancellationToken ct)=>Tx(async(c,t)=>{var n=await c.ExecuteAsync(sql,new{Id=id,tenant.TenantId,Reason=reason,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Registro ativo não encontrado.");},ct);
 private async Task<T>Tx<T>(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task<T>> work,CancellationToken ct){try{return await db.InTenantTransactionAsync(work,ct);}catch(Exception ex){log.LogError(ex,"Falha no ecossistema do tenant {TenantId}",tenant.TenantId);throw;}}
 private async Task Tx(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task> work,CancellationToken ct)=>await Tx(async(c,t)=>{await work(c,t);return true;},ct);
}
