using System.Text;
using Agro360.Application.Contracts;
using Agro360.Domain.Export;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class ExportTradingService(DatabaseExecutor db, ITenantContext tenant, ILogger<ExportTradingService> logger) : IExportTradingService
{
    public Task<dynamic> DashboardAsync(CancellationToken ct) => Tx(async (c,t) => await c.QuerySingleAsync(new CommandDefinition("select count(*) filter(where status not in ('CANCELLED','CLOSED','DELIVERED')) contracts_open,count(*) filter(where status='APPROVED') contracts_approved,count(*) filter(where status='AWAITING_DOCUMENTS') contracts_awaiting_documents,(select count(*) from agro360.export_trading_shipments where tenant_id=@TenantId and status='PLANNED') shipments_planned,(select count(*) from agro360.export_trading_shipments where tenant_id=@TenantId and expected_date<current_date and status not in('DELIVERED','CANCELLED')) shipments_late,(select coalesce(sum(total),0) from agro360.export_trading_contracts where tenant_id=@TenantId and status in('SHIPPED','DELIVERED','CLOSED') and updated_at>=date_trunc('month',now())) exported_month,(select coalesce(sum(amount_base),0) from agro360.export_trading_costs where tenant_id=@TenantId) costs,(select count(*) from agro360.export_trading_documents where tenant_id=@TenantId and required and status<>'APPROVED') documents_pending from agro360.export_trading_contracts where tenant_id=@TenantId and deleted_at is null",new{tenant.TenantId},t,cancellationToken:ct)));
    public Task<IReadOnlyList<dynamic>> CustomersAsync(ExportQuery q,CancellationToken ct)=>List("select * from agro360.export_trading_customers where tenant_id=@TenantId and deleted_at is null and (@Search is null or name ilike '%'||@Search||'%' or main_contact ilike '%'||@Search||'%') and (@Status is null or status=@Status) and (@Country is null or country=@Country) order by name limit @Take offset @Skip",q,ct);
    public Task<Guid> SaveCustomerAsync(Guid? id,ExportCustomerCommand x,CancellationToken ct)=>Tx(async(c,t)=>{if(x.Status=="REJECTED"&&string.IsNullOrWhiteSpace(x.RejectionReason))throw new DomainException("Cliente reprovado exige motivo.","export.rejection_reason_required");var key=id??Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var sql=id is null?"insert into agro360.export_trading_customers(id,tenant_id,name,country,city,tax_document,main_contact,email,phone,language,currency,commercial_terms,preferred_incoterm,status,risk,rejection_reason,notes,tags,approved_at,approved_by,created_by,updated_by) values(@Id,@TenantId,@Name,upper(@Country),@City,@TaxDocument,@MainContact,@Email,@Phone,@Language,upper(@Currency),@CommercialTerms,@PreferredIncoterm,@Status,@Risk,@RejectionReason,@Notes,@Tags,case when @Status='APPROVED' then now() end,case when @Status='APPROVED' then @UserId end,@UserId,@UserId)":"update agro360.export_trading_customers set name=@Name,country=upper(@Country),city=@City,tax_document=@TaxDocument,main_contact=@MainContact,email=@Email,phone=@Phone,language=@Language,currency=upper(@Currency),commercial_terms=@CommercialTerms,preferred_incoterm=@PreferredIncoterm,status=@Status,risk=@Risk,rejection_reason=@RejectionReason,notes=@Notes,tags=@Tags,approved_at=case when @Status='APPROVED' then coalesce(approved_at,now()) end,approved_by=case when @Status='APPROVED' then coalesce(approved_by,@UserId) end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and deleted_at is null";if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("Cliente internacional",key);await Audit(c,t,"CUSTOMER",key,id is null?"CREATED":"UPDATED",ct);return key;});
    public Task<IReadOnlyList<dynamic>> ContractsAsync(ExportQuery q,CancellationToken ct)=>List("select c.*,u.name customer_name from agro360.export_trading_contracts c join agro360.export_trading_customers u on u.tenant_id=c.tenant_id and u.id=c.customer_id where c.tenant_id=@TenantId and c.deleted_at is null and (@Search is null or c.number ilike '%'||@Search||'%' or u.name ilike '%'||@Search||'%') and (@Status is null or c.status=@Status) and (@Country is null or c.destination_country=@Country) order by c.contract_date desc limit @Take offset @Skip",q,ct);
    public Task<Guid> CreateContractAsync(ExportContractCommand x,CancellationToken ct){var total=ExportTradingRules.ContractTotal(x.Items.Select(i=>(i.Quantity,i.UnitPrice)));if(string.IsNullOrWhiteSpace(x.Incoterm)||string.IsNullOrWhiteSpace(x.Currency))throw new DomainException("Moeda e Incoterm são obrigatórios.","export.commercial_required");return Tx(async(c,t)=>{var status=await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select status from agro360.export_trading_customers where tenant_id=@TenantId and id=@Id and deleted_at is null",new{tenant.TenantId,Id=x.CustomerId},t,cancellationToken:ct));if(status is null)throw new NotFoundException("Cliente internacional",x.CustomerId);if(status is "BLOCKED" or "REJECTED" or "INACTIVE")throw new DomainException("Cliente indisponível para novo contrato.","export.customer_blocked");var id=Guid.CreateVersion7();var number=$"EXP-{DateTime.UtcNow:yyyyMMdd}-{id.ToString()[..8].ToUpperInvariant()}";await c.ExecuteAsync(new CommandDefinition("insert into agro360.export_trading_contracts(id,tenant_id,number,customer_id,trade_partner_id,currency,total,incoterm,origin_port,destination_port,destination_country,contract_date,expected_shipment_date,payment_terms,status,notes,created_by,updated_by) values(@Id,@TenantId,@Number,@CustomerId,@TradePartnerId,upper(@Currency),@Total,@Incoterm,@OriginPort,@DestinationPort,upper(@DestinationCountry),@ContractDate,@ExpectedShipmentDate,@PaymentTerms,'DRAFT',@Notes,@UserId,@UserId)",new{Id=id,tenant.TenantId,Number=number,x.CustomerId,x.TradePartnerId,x.Currency,Total=total,x.Incoterm,x.OriginPort,x.DestinationPort,x.DestinationCountry,x.ContractDate,x.ExpectedShipmentDate,x.PaymentTerms,x.Notes,tenant.UserId},t,cancellationToken:ct));foreach(var i in x.Items)await c.ExecuteAsync(new CommandDefinition("insert into agro360.export_trading_contract_items(id,tenant_id,contract_id,product_id,lot_id,quantity,unit,unit_price,total,created_by,updated_by) values(@Id,@TenantId,@ContractId,@ProductId,@LotId,@Quantity,@Unit,@UnitPrice,@Total,@UserId,@UserId)",new{Id=Guid.CreateVersion7(),tenant.TenantId,ContractId=id,i.ProductId,i.LotId,i.Quantity,i.Unit,i.UnitPrice,Total=decimal.Round(i.Quantity*i.UnitPrice,2),tenant.UserId},t,cancellationToken:ct));return id;});}
    public Task ApproveContractAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var changed=await c.ExecuteAsync(new CommandDefinition("update agro360.export_trading_contracts c set status='APPROVED',approved_at=now(),approved_by=@UserId,updated_at=now(),updated_by=@UserId from agro360.export_trading_customers u where c.tenant_id=@TenantId and c.id=@Id and u.tenant_id=c.tenant_id and u.id=c.customer_id and u.status in('ACTIVE','APPROVED') and c.status in('DRAFT','UNDER_REVIEW')",new{tenant.TenantId,tenant.UserId,Id=id},t,cancellationToken:ct));if(changed==0)throw new DomainException("Contrato inexistente, estado inválido ou cliente não ativo.","export.approval_blocked");});
    public Task CancelContractAsync(Guid id,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Cancelamento exige motivo.","export.cancel_reason_required");return Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.export_trading_contracts set status='CANCELLED',cancellation_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status not in('CANCELLED','DELIVERED','CLOSED')",new{tenant.TenantId,tenant.UserId,Id=id,Reason=reason},t,cancellationToken:ct))==0)throw new DomainException("Contrato não pode ser cancelado.","export.cancel_invalid");});}
    public Task<IReadOnlyList<dynamic>> ShipmentsAsync(ExportQuery q,CancellationToken ct)=>List("select s.*,c.number contract_number,u.name customer_name from agro360.export_trading_shipments s join agro360.export_trading_contracts c on c.tenant_id=s.tenant_id and c.id=s.contract_id join agro360.export_trading_customers u on u.tenant_id=c.tenant_id and u.id=c.customer_id where s.tenant_id=@TenantId and (@Search is null or s.number ilike '%'||@Search||'%') and (@Status is null or s.status=@Status) order by s.expected_date desc limit @Take offset @Skip",q,ct);
    public Task<Guid> CreateShipmentAsync(ExportShipmentCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var approved=await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.export_trading_contracts where tenant_id=@TenantId and id=@Id and status='APPROVED')",new{tenant.TenantId,Id=x.ContractId},t,cancellationToken:ct));if(!approved)throw new DomainException("Embarque exige contrato aprovado.","export.contract_not_approved");if(x.Items.Count==0||x.Items.Any(i=>i.Quantity<=0))throw new DomainException("Embarque deve possuir itens com quantidade positiva.","export.shipment_items_required");foreach(var i in x.Items){var available=await c.ExecuteScalarAsync<decimal?>(new CommandDefinition("select l.current_balance from agro360.storage_lots l join agro360.export_trading_contract_items ci on ci.tenant_id=l.tenant_id and ci.lot_id=l.id where l.tenant_id=@TenantId and l.id=@LotId and ci.id=@ItemId and ci.contract_id=@ContractId and l.status not in('BLOCKED','REJECTED')",new{tenant.TenantId,i.LotId,ItemId=i.ContractItemId,x.ContractId},t,cancellationToken:ct));if(available is null)throw new DomainException("Lote inexistente ou bloqueado pela qualidade.","export.lot_blocked");if(i.Quantity>available&&string.IsNullOrWhiteSpace(x.OverrideJustification))throw new DomainException("Quantidade excede o saldo disponível.","export.insufficient_stock");}var id=Guid.CreateVersion7();var number=$"SHP-{DateTime.UtcNow:yyyyMMdd}-{id.ToString()[..8].ToUpperInvariant()}";await c.ExecuteAsync(new CommandDefinition("insert into agro360.export_trading_shipments(id,tenant_id,number,contract_id,expected_date,origin_terminal,destination,carrier,freight_agent,status,notes,created_by,updated_by) values(@Id,@TenantId,@Number,@ContractId,@ExpectedDate,@OriginTerminal,@Destination,@Carrier,@FreightAgent,'AWAITING_DOCUMENTS',@Notes,@UserId,@UserId)",new{Id=id,tenant.TenantId,Number=number,x.ContractId,x.ExpectedDate,x.OriginTerminal,x.Destination,x.Carrier,x.FreightAgent,x.Notes,tenant.UserId},t,cancellationToken:ct));foreach(var i in x.Items)await c.ExecuteAsync(new CommandDefinition("insert into agro360.export_trading_shipment_items(id,tenant_id,shipment_id,contract_item_id,lot_id,quantity,created_by,updated_by) values(@Id,@TenantId,@ShipmentId,@ContractItemId,@LotId,@Quantity,@UserId,@UserId)",new{Id=Guid.CreateVersion7(),tenant.TenantId,ShipmentId=id,i.ContractItemId,i.LotId,i.Quantity,tenant.UserId},t,cancellationToken:ct));return id;});
    public async Task<byte[]> ExportCsvAsync(string report,ExportQuery q,CancellationToken ct){IReadOnlyList<dynamic> rows=report switch{"customers"=>await CustomersAsync(q,ct),"contracts" or "contracts-country" or "contracts-customer" or "contracts-product" or "margin"=>await ContractsAsync(q,ct),"shipments"=>await ShipmentsAsync(q,ct),_=>throw new DomainException("Relatório de exportação inválido.","export.report_invalid")};var sb=new StringBuilder("sep=;\n");if(report=="customers"){sb.AppendLine("Nome;País;Cidade;Moeda;Status;Risco");foreach(var r in rows)sb.AppendLine($"{Csv(r.name)};{r.country};{Csv(r.city)};{r.currency};{r.status};{r.risk}");}else if(report=="shipments"){sb.AppendLine("Número;Contrato;Cliente;Previsão;Status;Destino");foreach(var r in rows)sb.AppendLine($"{r.number};{r.contract_number};{Csv(r.customer_name)};{r.expected_date:yyyy-MM-dd};{r.status};{Csv(r.destination)}");}else{sb.AppendLine("Número;Cliente;País;Moeda;Total;Status");foreach(var r in rows)sb.AppendLine($"{r.number};{Csv(r.customer_name)};{r.destination_country};{r.currency};{r.total};{r.status}");}return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray();}
    private Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work)=>db.InTenantTransactionAsync(work,CancellationToken.None); private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>db.InTenantTransactionAsync(work,CancellationToken.None);
    private Task<IReadOnlyList<dynamic>> List(string sql,ExportQuery q,CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<dynamic>)(await c.QueryAsync(new CommandDefinition(sql,new{tenant.TenantId,q.Search,q.Status,q.Country,Take=Math.Clamp(q.PageSize,1,100),Skip=(Math.Max(q.Page,1)-1)*Math.Clamp(q.PageSize,1,100)},t,cancellationToken:ct))).ToArray());
    private Task Audit(System.Data.IDbConnection c,System.Data.IDbTransaction t,string entity,Guid id,string action,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("insert into agro360.export_trading_events(id,tenant_id,entity_type,entity_id,event_type,created_by) values(@EventId,@TenantId,@Entity,@Id,@Action,@UserId)",new{EventId=Guid.CreateVersion7(),tenant.TenantId,Entity=entity,Id=id,Action=action,tenant.UserId},t,cancellationToken:ct)); private static string Csv(object? value)=>$"\"{value?.ToString()?.Replace("\"","\"\"")}\"";
}
