using Agro360.Application.Contracts;
using Agro360.Domain.Finance;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class FinanceService(DatabaseExecutor db, ITenantContext tenant, ILogger<FinanceService> logger) : IFinanceService
{
    public Task<IReadOnlyList<dynamic>> ListAccountsAsync(CancellationToken ct) => Query("select * from finance.chart_of_accounts where tenant_id=@TenantId order by display_order,code", null, ct);
    public Task<IReadOnlyList<dynamic>> ListCostCentersAsync(CancellationToken ct) => Query("select * from finance.cost_centers where tenant_id=@TenantId order by code", null, ct);
    public Task<IReadOnlyList<dynamic>> ListTitlesAsync(bool payable, CancellationToken ct) => Query($"select *,case when status in ('OPEN','PARTIAL') and due_on<current_date then 'OVERDUE' else status end effective_status from finance.{Table(payable)} where tenant_id=@TenantId order by due_on", null, ct);
    public Task<dynamic?> GetTitleAsync(bool payable, Guid id, CancellationToken ct) => Tx(async (c,t) => await c.QuerySingleOrDefaultAsync(new CommandDefinition($"select * from finance.{Table(payable)} where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct)));
    public Task<Guid> SaveAccountAsync(Guid? id, AccountCommand x, CancellationToken ct)
    {
        FinanceRules.Account(x.Code,x.Name,x.Type,x.Nature);
        return Tx(async(c,t)=> { if(x.ParentId is not null && !await Exists(c,t,"finance.chart_of_accounts",x.ParentId.Value,ct)) throw new DomainException("Conta pai não pertence ao tenant.","finance.parent_invalid"); var key=id??Guid.CreateVersion7(); var sql=id is null?"insert into finance.chart_of_accounts(id,tenant_id,code,name,type,nature,category,parent_id,active,display_order,created_by) values(@Id,@TenantId,@Code,@Name,@Type,@Nature,@Category,@ParentId,@Active,@DisplayOrder,@UserId)":"update finance.chart_of_accounts set code=@Code,name=@Name,type=@Type,nature=@Nature,category=@Category,parent_id=@ParentId,active=@Active,display_order=@DisplayOrder,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id"; await ExecuteSaved(c,t,sql,key,x,ct); await Audit(c,t,id is null?"create":"update","ChartOfAccount",key,x,ct); return key; });
    }
    public Task<Guid> SaveCostCenterAsync(Guid? id, CostCenterCommand x, CancellationToken ct)
    {
        Guard.Required(x.Code,nameof(x.Code),40); Guard.Required(x.Name,nameof(x.Name),160);
        string[] kinds=["PROPERTY","FARM","PLOT","PADDOCK","SEASON","CROP","ACTIVITY","HERD","ANIMAL_LOT","MACHINE","EQUIPMENT","PROJECT","ADMINISTRATIVE"];
        if(!kinds.Contains(x.Kind.ToUpperInvariant())) throw new DomainException("Tipo de centro de custo inválido.","finance.cost_center_kind_invalid");
        return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var sql=id is null?"insert into finance.cost_centers(id,tenant_id,code,name,kind,reference_id,active,created_by) values(@Id,@TenantId,@Code,@Name,@Kind,@ReferenceId,@Active,@UserId)":"update finance.cost_centers set code=@Code,name=@Name,kind=@Kind,reference_id=@ReferenceId,active=@Active,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id";await ExecuteSaved(c,t,sql,key,x,ct);await Audit(c,t,id is null?"create":"update","CostCenter",key,x,ct);return key;});
    }
    public Task<Guid> SaveTitleAsync(bool payable, Guid? id, TitleCommand x, CancellationToken ct)
    {
        var total=FinanceRules.FinalAmount(x.OriginalAmount,x.Discount,x.Interest,x.Fine); if(x.DueOn<x.IssuedOn)throw new DomainException("Vencimento anterior à emissão.","finance.due_date_invalid");
        return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var table=Table(payable);var party=payable?"supplier_name":"customer_name";var sql=id is null?$"insert into finance.{table}(id,tenant_id,{party},document,original_amount,discount,interest,fine,final_amount,balance,issued_on,due_on,account_id,cost_center_id,notes,source_id,status,created_by) values(@Id,@TenantId,@Party,@Document,@OriginalAmount,@Discount,@Interest,@Fine,@Total,@Total,@IssuedOn,@DueOn,@AccountId,@CostCenterId,@Notes,@SourceId,'OPEN',@UserId)":$"update finance.{table} set {party}=@Party,document=@Document,original_amount=@OriginalAmount,discount=@Discount,interest=@Interest,fine=@Fine,final_amount=@Total,balance=@Total-coalesce((select sum(amount) from finance.settlements where tenant_id=@TenantId and title_id=@Id and direction=@Direction),0),issued_on=@IssuedOn,due_on=@DueOn,account_id=@AccountId,cost_center_id=@CostCenterId,notes=@Notes,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status in('OPEN','PARTIAL')";var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);p.Add("Party",x.PartyName);p.Add("Total",total);p.Add("Direction",payable?"OUT":"IN");if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException(payable?"Conta a pagar":"Conta a receber",key);await Audit(c,t,id is null?"create":"update",payable?"Payable":"Receivable",key,x,ct);return key;});
    }
    public Task SettleAsync(bool payable, Guid id, SettlementCommand x, CancellationToken ct)
    {
        if(x.Amount<=0)throw new DomainException("Valor da baixa deve ser positivo.","finance.settlement_invalid");
        return Tx(async(c,t)=>{var table=Table(payable);var row=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition($"select balance,status from finance.{table} where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Título",id);if((string)row.status is "CANCELLED" or "PAID" or "RECEIVED")throw new ConflictException("Título encerrado.");if(x.Amount>(decimal)row.balance)throw new DomainException("Baixa maior que o saldo.","finance.overpayment");var balance=(decimal)row.balance-x.Amount;var status=balance==0?(payable?"PAID":"RECEIVED"):"PARTIAL";await c.ExecuteAsync(new CommandDefinition($"insert into finance.settlements(id,tenant_id,title_id,direction,amount,settled_on,account_id,notes,created_by) values(@Settlement,@TenantId,@Id,@Direction,@Amount,@Date,@AccountId,@Notes,@UserId);update finance.{table} set balance=@Balance,status=@Status,settled_on=case when @Balance=0 then @Date else null end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{Settlement=Guid.CreateVersion7(),tenant.TenantId,Id=id,Direction=payable?"OUT":"IN",x.Amount,x.Date,x.AccountId,x.Notes,tenant.UserId,Balance=balance,Status=status},t,cancellationToken:ct));await Audit(c,t,payable?"pay":"receive",payable?"Payable":"Receivable",id,x,ct);});
    }
    public Task CancelAsync(bool payable, Guid id, CancelFinanceCommand x, CancellationToken ct)
    { Guard.Required(x.Reason,nameof(x.Reason),500); return Tx(async(c,t)=>{var n=await c.ExecuteAsync(new CommandDefinition($"update finance.{Table(payable)} set status='CANCELLED',cancel_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status in('OPEN','PARTIAL')",new{tenant.TenantId,tenant.UserId,Id=id,x.Reason},t,cancellationToken:ct));if(n==0)throw new ConflictException("Título inexistente ou encerrado.");await Audit(c,t,"cancel",payable?"Payable":"Receivable",id,x,ct);}); }
    public Task<Guid> AddManualEntryAsync(ManualEntryCommand x,CancellationToken ct){var type=x.Type.ToUpperInvariant();if(!new[]{"REVENUE","EXPENSE","COST","INVESTMENT"}.Contains(type)||x.Amount<=0)throw new DomainException("Lançamento inválido.","finance.entry_invalid");if(type=="COST"&&x.CostCenterId is null)throw new DomainException("Centro de custo é obrigatório.","finance.cost_center_required");return Tx(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into finance.manual_entries(id,tenant_id,type,amount,entry_date,account_id,cost_center_id,property_id,season_id,notes,origin,status,created_by) values(@Id,@TenantId,@Type,@Amount,@Date,@AccountId,@CostCenterId,@PropertyId,@SeasonId,@Notes,@Origin,'POSTED',@UserId)",new{Id=id,tenant.TenantId,Type=type,x.Amount,x.Date,x.AccountId,x.CostCenterId,x.PropertyId,x.SeasonId,x.Notes,x.Origin,tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"create","ManualEntry",id,x,ct);return id;});}
    public Task<IReadOnlyList<dynamic>> CashFlowAsync(FinanceQuery q,CancellationToken ct)=>Query("select * from finance.cash_flow(@TenantId,@From,@To) where (@GroupBy is null or period_kind=@GroupBy)",q,ct);
    public Task<IReadOnlyList<dynamic>> ResultsAsync(FinanceQuery q,CancellationToken ct)=>Query("select * from finance.economic_results(@TenantId,@From,@To,@PropertyId,@SeasonId,@PlotId,@HerdId,@MachineId)",q,ct);
    public Task<dynamic> DashboardAsync(CancellationToken ct)=>Tx<dynamic>(async(c,t)=>await c.QuerySingleAsync(new CommandDefinition("select * from finance.dashboard(@TenantId)",new{tenant.TenantId},t,cancellationToken:ct)));
    private Task<IReadOnlyList<dynamic>> Query(string sql,object? value,CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>{var p=new DynamicParameters(value);p.Add("TenantId",tenant.TenantId);return (await c.QueryAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))).AsList();});
    private async Task ExecuteSaved(NpgsqlConnection c,NpgsqlTransaction t,string sql,Guid id,object value,CancellationToken ct){var p=new DynamicParameters(value);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("Registro financeiro",id);}
    private Task<bool> Exists(NpgsqlConnection c,NpgsqlTransaction t,string table,Guid id,CancellationToken ct)=>c.ExecuteScalarAsync<bool>(new CommandDefinition($"select exists(select 1 from {table} where tenant_id=@TenantId and id=@Id)",new{tenant.TenantId,Id=id},t,cancellationToken:ct));
    private Task Audit(NpgsqlConnection c,NpgsqlTransaction t,string action,string entity,Guid id,object value,CancellationToken ct)=>c.WriteAuditAsync(t,tenant,action,entity,id,null,value,ct);
    private static string Table(bool payable)=>payable?"payables":"receivables";
    private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha na fronteira financeira do tenant {TenantId}",tenant.TenantId);throw;}}
    private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
