using Agro360.Application.Contracts;
using Agro360.Domain.Finance;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class FinanceService(DatabaseExecutor db, ITenantContext tenant, ILogger<FinanceService> logger) : IFinanceService
{
    public Task<IReadOnlyList<dynamic>> ListAccountsAsync(CancellationToken ct) => Query("select * from agro360.finance_chart_of_accounts where tenant_id=@TenantId order by display_order,code", null, ct);
    public Task<IReadOnlyList<dynamic>> ListCostCentersAsync(CancellationToken ct) => Query("select * from agro360.finance_cost_centers where tenant_id=@TenantId order by code", null, ct);
    public Task<IReadOnlyList<dynamic>> ListTitlesAsync(bool payable, CancellationToken ct) => Query($"select *,case when status in ('OPEN','PARTIAL') and due_on<current_date then 'OVERDUE' else status end effective_status from agro360.finance_{Table(payable)} where tenant_id=@TenantId order by due_on", null, ct);
    public Task<dynamic?> GetTitleAsync(bool payable, Guid id, CancellationToken ct) => Tx(async (c,t) => await c.QuerySingleOrDefaultAsync(new CommandDefinition($"select * from agro360.finance_{Table(payable)} where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct)));
    public Task<Guid> SaveAccountAsync(Guid? id, AccountCommand command, CancellationToken ct)
    {
        FinanceRules.Account(command.Code,command.Name,command.Type,command.Nature);
        return Tx(async(c,t)=> { if(command.ParentId is not null && !await Exists(c,t,"agro360.finance_chart_of_accounts",command.ParentId.Value,ct)) throw new DomainException("Conta pai não pertence ao tenant.","agro360.finance_parent_invalid"); var key=id??Guid.CreateVersion7(); var sql=id is null?"insert into agro360.finance_chart_of_accounts(id,tenant_id,code,name,type,nature,category,parent_id,active,display_order,created_by) values(@Id,@TenantId,@Code,@Name,@Type,@Nature,@Category,@ParentId,@Active,@DisplayOrder,@UserId)":"update agro360.finance_chart_of_accounts set code=@Code,name=@Name,type=@Type,nature=@Nature,category=@Category,parent_id=@ParentId,active=@Active,display_order=@DisplayOrder,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id"; await ExecuteSaved(c,t,sql,key,command,ct); await Audit(c,t,id is null?"create":"update","ChartOfAccount",key,command,ct); return key; });
    }
    public Task<Guid> SaveCostCenterAsync(Guid? id, CostCenterCommand command, CancellationToken ct)
    {
        Guard.Required(command.Code,nameof(command.Code),40); Guard.Required(command.Name,nameof(command.Name),160);
        string[] kinds=["PROPERTY","FARM","PLOT","PADDOCK","SEASON","CROP","ACTIVITY","HERD","ANIMAL_LOT","MACHINE","EQUIPMENT","PROJECT","ADMINISTRATIVE"];
        if(!kinds.Contains(command.Kind.ToUpperInvariant())) throw new DomainException("Tipo de centro de custo inválido.","agro360.finance_cost_center_kind_invalid");
        return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var sql=id is null?"insert into agro360.finance_cost_centers(id,tenant_id,code,name,kind,reference_id,active,created_by) values(@Id,@TenantId,@Code,@Name,@Kind,@ReferenceId,@Active,@UserId)":"update agro360.finance_cost_centers set code=@Code,name=@Name,kind=@Kind,reference_id=@ReferenceId,active=@Active,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id";await ExecuteSaved(c,t,sql,key,command,ct);await Audit(c,t,id is null?"create":"update","CostCenter",key,command,ct);return key;});
    }
    public Task<Guid> SaveTitleAsync(bool payable, Guid? id, TitleCommand command, CancellationToken ct)
    {
        var total=FinanceRules.FinalAmount(command.OriginalAmount,command.Discount,command.Interest,command.Fine); if(command.DueOn<command.IssuedOn)throw new DomainException("Vencimento anterior à emissão.","agro360.finance_due_date_invalid");
        return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var table=Table(payable);var party=payable?"supplier_name":"customer_name";var sql=id is null?$"insert into agro360.finance_{table}(id,tenant_id,{party},document,original_amount,discount,interest,fine,final_amount,balance,issued_on,due_on,account_id,cost_center_id,notes,source_id,status,created_by) values(@Id,@TenantId,@Party,@Document,@OriginalAmount,@Discount,@Interest,@Fine,@Total,@Total,@IssuedOn,@DueOn,@AccountId,@CostCenterId,@Notes,@SourceId,'OPEN',@UserId)":$"update agro360.finance_{table} set {party}=@Party,document=@Document,original_amount=@OriginalAmount,discount=@Discount,interest=@Interest,fine=@Fine,final_amount=@Total,balance=@Total-coalesce((select sum(amount) from agro360.finance_settlements where tenant_id=@TenantId and title_id=@Id and direction=@Direction),0),issued_on=@IssuedOn,due_on=@DueOn,account_id=@AccountId,cost_center_id=@CostCenterId,notes=@Notes,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status in('OPEN','PARTIAL')";var p=new DynamicParameters(command);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);p.Add("Party",command.PartyName);p.Add("Total",total);p.Add("Direction",payable?"OUT":"IN");if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException(payable?"Conta a pagar":"Conta a receber",key);await Audit(c,t,id is null?"create":"update",payable?"Payable":"Receivable",key,command,ct);return key;});
    }
    public Task SettleAsync(bool payable, Guid id, SettlementCommand command, CancellationToken ct)
    {
        if(command.Amount<=0)throw new DomainException("Valor da baixa deve ser positivo.","agro360.finance_settlement_invalid");
        return Tx(async(c,t)=>{var table=Table(payable);var row=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition($"select balance,status from agro360.finance_{table} where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Título",id);if((string)row.status is "CANCELLED" or "PAID" or "RECEIVED")throw new ConflictException("Título encerrado.");if(command.Amount>(decimal)row.balance)throw new DomainException("Baixa maior que o saldo.","agro360.finance_overpayment");var balance=(decimal)row.balance-command.Amount;var status=balance==0?(payable?"PAID":"RECEIVED"):"PARTIAL";await c.ExecuteAsync(new CommandDefinition($"insert into agro360.finance_settlements(id,tenant_id,title_id,direction,amount,settled_on,account_id,notes,created_by) values(@Settlement,@TenantId,@Id,@Direction,@Amount,@Date,@AccountId,@Notes,@UserId);update agro360.finance_{table} set balance=@Balance,status=@Status,settled_on=case when @Balance=0 then @Date else null end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{Settlement=Guid.CreateVersion7(),tenant.TenantId,Id=id,Direction=payable?"OUT":"IN",command.Amount,command.Date,command.AccountId,command.Notes,tenant.UserId,Balance=balance,Status=status},t,cancellationToken:ct));await Audit(c,t,payable?"pay":"receive",payable?"Payable":"Receivable",id,command,ct);});
    }
    public Task CancelAsync(bool payable, Guid id, CancelFinanceCommand command, CancellationToken ct)
    { Guard.Required(command.Reason,nameof(command.Reason),500); return Tx(async(c,t)=>{var n=await c.ExecuteAsync(new CommandDefinition($"update agro360.finance_{Table(payable)} set status='CANCELLED',cancel_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status in('OPEN','PARTIAL')",new{tenant.TenantId,tenant.UserId,Id=id,command.Reason},t,cancellationToken:ct));if(n==0)throw new ConflictException("Título inexistente ou encerrado.");await Audit(c,t,"cancel",payable?"Payable":"Receivable",id,command,ct);}); }
    public Task<Guid> AddManualEntryAsync(ManualEntryCommand command,CancellationToken ct){var type=command.Type.ToUpperInvariant();if(!new[]{"REVENUE","EXPENSE","COST","INVESTMENT"}.Contains(type)||command.Amount<=0)throw new DomainException("Lançamento inválido.","agro360.finance_entry_invalid");if(type=="COST"&&command.CostCenterId is null)throw new DomainException("Centro de custo é obrigatório.","agro360.finance_cost_center_required");return Tx(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.finance_manual_entries(id,tenant_id,type,amount,entry_date,account_id,cost_center_id,property_id,season_id,notes,origin,status,created_by) values(@Id,@TenantId,@Type,@Amount,@Date,@AccountId,@CostCenterId,@PropertyId,@SeasonId,@Notes,@Origin,'POSTED',@UserId)",new{Id=id,tenant.TenantId,Type=type,command.Amount,command.Date,command.AccountId,command.CostCenterId,command.PropertyId,command.SeasonId,command.Notes,command.Origin,tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"create","ManualEntry",id,command,ct);return id;});}
    public Task<IReadOnlyList<dynamic>> CashFlowAsync(FinanceQuery query,CancellationToken ct)=>Query("select * from agro360.finance_cash_flow(@TenantId,@From,@To) where (@GroupBy is null or period_kind=@GroupBy)",query,ct);
    public Task<IReadOnlyList<dynamic>> ResultsAsync(FinanceQuery query,CancellationToken ct)=>Query("select * from agro360.finance_economic_results(@TenantId,@From,@To,@PropertyId,@SeasonId,@PlotId,@HerdId,@MachineId)",query,ct);
    public Task<dynamic> DashboardAsync(CancellationToken ct)=>Tx<dynamic>(async(c,t)=>await c.QuerySingleAsync(new CommandDefinition("select * from agro360.finance_dashboard(@TenantId)",new{tenant.TenantId},t,cancellationToken:ct)));
    public Task<IReadOnlyList<dynamic>> ListBudgetsAsync(CancellationToken ct)=>Query("select p.id,p.name,p.budget_type,p.period_start,p.period_end,p.status,p.current_version,coalesce(sum(i.planned_amount),0) planned_amount from agro360.finance_budget_plans p left join agro360.finance_budget_items i on i.tenant_id=p.tenant_id and i.budget_plan_id=p.id and i.deleted_at is null where p.tenant_id=@TenantId and p.deleted_at is null group by p.id order by p.period_start desc",null,ct);
    public Task<Guid> CreateBudgetAsync(BudgetCommand command,CancellationToken ct)
    {
        FinanceRules.Budget(command.PlannedAmount,command.PeriodStart,command.PeriodEnd); Guard.Required(command.Name,nameof(command.Name),160);
        var type=command.Type.ToUpperInvariant(); if(!new[]{"ANNUAL","MONTHLY","SEASON","PROPERTY","PLOT","CROP","COST_CENTER","PROJECT"}.Contains(type))throw new DomainException("Tipo de orçamento inválido.","agro360.finance_budget_type_invalid");
        return Tx(async(c,t)=>{if(!await Exists(c,t,"agro360.finance_account_categories",command.CategoryId,ct))throw new DomainException("Categoria financeira não pertence ao tenant.","agro360.finance_category_invalid");var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.finance_budget_plans(id,tenant_id,name,budget_type,period_start,period_end,season_id,property_id,plot_id,cost_center_id,responsible_id,status,notes,created_by,updated_by) values(@Id,@TenantId,@Name,@Type,@PeriodStart,@PeriodEnd,@SeasonId,@PropertyId,@PlotId,@CostCenterId,@UserId,'DRAFT',@Notes,@UserId,@UserId);insert into agro360.finance_budget_items(id,tenant_id,budget_plan_id,category_id,cost_center_id,planned_amount,created_by,updated_by) values(@Item,@TenantId,@Id,@CategoryId,@CostCenterId,@PlannedAmount,@UserId,@UserId)",new{Id=id,Item=Guid.CreateVersion7(),tenant.TenantId,tenant.UserId,command.Name,Type=type,command.PeriodStart,command.PeriodEnd,command.SeasonId,command.PropertyId,command.PlotId,command.CostCenterId,command.CategoryId,command.PlannedAmount,command.Notes},t,cancellationToken:ct));await Audit(c,t,"create","BudgetPlan",id,command,ct);return id;});
    }
    public Task ApproveBudgetAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var n=await c.ExecuteAsync(new CommandDefinition("update agro360.finance_budget_plans set status='APPROVED',approved_at=now(),approved_by=@UserId,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status in('DRAFT','SUBMITTED')",new{tenant.TenantId,tenant.UserId,Id=id},t,cancellationToken:ct));if(n==0)throw new ConflictException("Orçamento inexistente ou já decidido.");await Audit(c,t,"approve","BudgetPlan",id,new{},ct);});
    public Task<Guid> ReconcileAsync(ReconciliationCommand command,CancellationToken ct)
    { Guard.Required(command.Reference,nameof(command.Reference),160); return Tx(async(c,t)=>{if(!await Exists(c,t,"agro360.finance_settlements",command.SettlementId,ct))throw new NotFoundException("Baixa",command.SettlementId);var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.finance_reconciliations(id,tenant_id,settlement_id,reference,status,reconciled_at,reconciled_by,created_by,updated_by) values(@Id,@TenantId,@SettlementId,@Reference,'RECONCILED',now(),@UserId,@UserId,@UserId)",new{Id=id,tenant.TenantId,tenant.UserId,command.SettlementId,command.Reference},t,cancellationToken:ct));await Audit(c,t,"reconcile","Settlement",command.SettlementId,new{command.Reference},ct);return id;}); }
    public Task ReverseReconciliationAsync(Guid id,string reason,CancellationToken ct)
    { Guard.Required(reason,nameof(reason),500);return Tx(async(c,t)=>{var n=await c.ExecuteAsync(new CommandDefinition("update agro360.finance_reconciliations set status='REVERSED',reversal_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status='RECONCILED'",new{tenant.TenantId,tenant.UserId,Id=id,Reason=reason},t,cancellationToken:ct));if(n==0)throw new ConflictException("Conciliação inexistente ou já desfeita.");await Audit(c,t,"unreconcile","Reconciliation",id,new{reason},ct);});}
    private Task<IReadOnlyList<dynamic>> Query(string sql,object? value,CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>{var p=new DynamicParameters(value);p.Add("TenantId",tenant.TenantId);return (await c.QueryAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))).AsList();});
    private async Task ExecuteSaved(NpgsqlConnection c,NpgsqlTransaction t,string sql,Guid id,object value,CancellationToken ct){var p=new DynamicParameters(value);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("Registro financeiro",id);}
    private Task<bool> Exists(NpgsqlConnection c,NpgsqlTransaction t,string table,Guid id,CancellationToken ct)=>c.ExecuteScalarAsync<bool>(new CommandDefinition($"select exists(select 1 from {table} where tenant_id=@TenantId and id=@Id)",new{tenant.TenantId,Id=id},t,cancellationToken:ct));
    private Task Audit(NpgsqlConnection c,NpgsqlTransaction t,string action,string entity,Guid id,object value,CancellationToken ct)=>c.WriteAuditAsync(t,tenant,action,entity,id,null,value,ct);
    private static string Table(bool payable)=>payable?"payables":"receivables";
    private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){InfrastructureLogMessages.FinanceBoundaryFailed(logger,tenant.TenantId,ex);throw;}}
    private Task<bool> Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
