using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Geospatial;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class GeospatialService(DatabaseExecutor db, ITenantContext tenant) : IGeospatialService
{
    public Task<IReadOnlyList<GeoFeature>> ListAsync(string? entityType,string? status,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<GeoFeature>)(await c.QueryAsync<GeoFeature>("select id,entity_type entitytype,name,geometry_type geometrytype,geojson::text geojson,centroid_latitude centroidlatitude,centroid_longitude centroidlongitude,status,informed_area_ha informedareaha,calculated_area_ha calculatedareaha,origin,updated_at updatedat from agro360.geospatial_features where tenant_id=@TenantId and (@EntityType is null or entity_type=@EntityType) and (@Status is null or status=@Status) order by updated_at desc",new{tenant.TenantId,EntityType=entityType,Status=status},t)).ToArray(),ct);
    public Task<GeoFeature> GetAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>await c.QuerySingleOrDefaultAsync<GeoFeature>("select id,entity_type entitytype,name,geometry_type geometrytype,geojson::text geojson,centroid_latitude centroidlatitude,centroid_longitude centroidlongitude,status,informed_area_ha informedareaha,calculated_area_ha calculatedareaha,origin,updated_at updatedat from agro360.geospatial_features where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id},t)??throw new KeyNotFoundException("Feature não encontrada."),ct);
    public Task<Guid> SaveAsync(Guid? id,GeoFeatureCommand x,CancellationToken ct)
    {
        using var geometry=GeoJsonRules.ParseGeometry(x.GeoJson); var type=geometry.RootElement.GetProperty("type").GetString()!; var center=Center(geometry.RootElement.GetProperty("coordinates")); var normalized=geometry.RootElement.GetRawText();
        if (x.EntityType is "FIELD" or "PASTURE" or "PADDOCK" or "MANAGEMENT_ZONE" && x.PropertyId is null) throw new ArgumentException("Selecione uma propriedade.");
        return db.InTenantTransactionAsync(async(c,t)=>{var key=id??Guid.NewGuid();var count=await c.ExecuteAsync(id is null?"insert into agro360.geospatial_features(id,tenant_id,entity_type,name,geometry_type,geojson,centroid_latitude,centroid_longitude,property_id,parent_id,informed_area_ha,status,origin,created_by,updated_by) values(@Id,@TenantId,@EntityType,@Name,@GeometryType,@GeoJson::jsonb,@Latitude,@Longitude,@PropertyId,@ParentId,@InformedAreaHa,@Status,@Origin,@UserId,@UserId)":"update agro360.geospatial_features set entity_type=@EntityType,name=@Name,geometry_type=@GeometryType,geojson=@GeoJson::jsonb,centroid_latitude=@Latitude,centroid_longitude=@Longitude,property_id=@PropertyId,parent_id=@ParentId,informed_area_ha=@InformedAreaHa,status=@Status,origin=@Origin,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId",new{Id=key,tenant.TenantId,x.EntityType,x.Name,GeometryType=type,GeoJson=normalized,Latitude=center.Lat,Longitude=center.Lon,x.PropertyId,x.ParentId,x.InformedAreaHa,x.Status,x.Origin,tenant.UserId},t);if(count==0)throw new KeyNotFoundException();return key;},ct);
    }
    public Task<Guid> AddOccurrenceAsync(OccurrenceCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{using var geometry=GeoJsonRules.ParseGeometry(x.GeoJson);if(geometry.RootElement.GetProperty("type").GetString()!="Point")throw new ArgumentException("Ocorrência exige geometria Point.");var center=Center(geometry.RootElement.GetProperty("coordinates"));var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.geospatial_features(id,tenant_id,entity_type,name,geometry_type,geojson,centroid_latitude,centroid_longitude,property_id,status,origin,created_by,updated_by) values(@Id,@TenantId,'OCCURRENCE',@Name,'Point',@GeoJson::jsonb,@Latitude,@Longitude,@PropertyId,'ACTIVE','MANUAL',@UserId,@UserId); insert into agro360.geospatial_occurrences(id,tenant_id,feature_id,type,severity,responsible_id,status,notes) values(gen_random_uuid(),@TenantId,@Id,@Type,@Severity,@ResponsibleId,'OPEN',@Notes)",new{id,tenant.TenantId,x.Name,GeoJson=geometry.RootElement.GetRawText(),Latitude=center.Lat,Longitude=center.Lon,x.PropertyId,x.Type,x.Severity,x.ResponsibleId,x.Notes,tenant.UserId},t);return id;},ct);
    public Task<Guid> AddRouteSegmentAsync(RouteSegmentCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{using var geometry=GeoJsonRules.ParseGeometry(x.GeoJson);if(geometry.RootElement.GetProperty("type").GetString()!="LineString")throw new ArgumentException("Trecho exige geometria LineString.");if(x.Status=="BLOCKED"&&!x.AuthorizedOverride)throw new InvalidOperationException("Trecho interditado exige autorização explícita e bloqueará viagens.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.geospatial_route_segments(id,tenant_id,route_feature_id,type,name,geojson,distance_km,estimated_minutes,status,restrictions,operational_window,authorized_override,created_by) values(@Id,@TenantId,@RouteId,@Type,@Name,@GeoJson::jsonb,@DistanceKm,@EstimatedMinutes,@Status,@Restrictions,@OperationalWindow,@AuthorizedOverride,@UserId)",new{id,tenant.TenantId,x.RouteId,x.Type,x.Name,GeoJson=geometry.RootElement.GetRawText(),x.DistanceKm,x.EstimatedMinutes,x.Status,x.Restrictions,x.OperationalWindow,x.AuthorizedOverride,tenant.UserId},t);return id;},ct);
    public Task<GeoImportResult> ImportAsync(GeoJsonImportCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var importId=Guid.NewGuid();var errors=new List<GeoImportError>();var valid=new List<(string Name,string Geometry)>();try{using var document=JsonDocument.Parse(x.GeoJson);var root=document.RootElement;if(root.GetProperty("type").GetString()!="FeatureCollection")throw new ArgumentException("O arquivo deve ser uma FeatureCollection.");var index=0;foreach(var feature in root.GetProperty("features").EnumerateArray()){index++;try{var geometry=feature.GetProperty("geometry").GetRawText();using var parsed=GeoJsonRules.ParseGeometry(geometry);var name=feature.TryGetProperty("properties",out var p)&&p.TryGetProperty("name",out var n)?n.GetString():null;if(string.IsNullOrWhiteSpace(name))throw new ArgumentException("Propriedade name é obrigatória.");valid.Add((name!,parsed.RootElement.GetRawText()));}catch(Exception e){errors.Add(new(index,e.Message));}}}catch(Exception e) when(e is JsonException or KeyNotFoundException or InvalidOperationException or ArgumentException){errors.Add(new(0,e.Message));}
        await c.ExecuteAsync("insert into agro360.geospatial_imports(id,tenant_id,entity_type,file_name,payload,status,total_features,valid_features,error_features,created_by) values(@Id,@TenantId,@EntityType,@FileName,@Payload::jsonb,@Status,@Total,@Valid,@Errors,@UserId)",new{Id=importId,tenant.TenantId,x.EntityType,x.FileName,Payload=SafeJson(x.GeoJson),Status=errors.Count==0?x.Confirm?"IMPORTED":"VALIDATED":"INVALID",Total=valid.Count+errors.Count(e=>e.Feature>0),Valid=valid.Count,Errors=errors.Count,tenant.UserId},t);foreach(var e in errors)await c.ExecuteAsync("insert into agro360.geospatial_import_errors(id,tenant_id,import_id,feature_number,message) values(gen_random_uuid(),@TenantId,@ImportId,@Feature,@Message)",new{tenant.TenantId,ImportId=importId,e.Feature,e.Message},t);if(x.Confirm&&errors.Count==0)foreach(var item in valid){using var g=GeoJsonRules.ParseGeometry(item.Geometry);var center=Center(g.RootElement.GetProperty("coordinates"));await c.ExecuteAsync("insert into agro360.geospatial_features(id,tenant_id,entity_type,name,geometry_type,geojson,centroid_latitude,centroid_longitude,status,origin,created_by,updated_by) values(gen_random_uuid(),@TenantId,@EntityType,@Name,@GeometryType,@GeoJson::jsonb,@Lat,@Lon,'ACTIVE','GEOJSON_IMPORT',@UserId,@UserId)",new{tenant.TenantId,x.EntityType,item.Name,GeometryType=g.RootElement.GetProperty("type").GetString(),GeoJson=item.Geometry,center.Lat,center.Lon,tenant.UserId},t);}return new(importId,errors.Count==0,valid.Count+errors.Count(e=>e.Feature>0),valid.Count,errors,x.Confirm&&errors.Count==0);},ct);
    public async Task<string> ExportAsync(string? entityType,CancellationToken ct){var rows=await ListAsync(entityType,null,ct);return JsonSerializer.Serialize(new{type="FeatureCollection",features=rows.Select(r=>new{type="Feature",id=r.Id,geometry=JsonSerializer.Deserialize<JsonElement>(r.GeoJson),properties=new{name=r.Name,entityType=r.EntityType,status=r.Status,areaHa=r.CalculatedAreaHa??r.InformedAreaHa,origin=r.Origin}})});}
    public Task<GeoDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<GeoDashboard>("select count(*) filter(where entity_type='PROPERTY') georeferencedproperties,count(*) filter(where entity_type='FIELD') mappedfields,count(*) filter(where entity_type='PASTURE') mappedpastures,(select count(*) from agro360.geo_farms p where p.tenant_id=@TenantId and not exists(select 1 from agro360.geospatial_features f where f.tenant_id=p.tenant_id and f.property_id=p.id)) areaswithoutgeometry,(select count(*) from agro360.geospatial_occurrences where tenant_id=@TenantId and status not in('RESOLVED','CLOSED')) openoccurrences,(select count(*) from agro360.geospatial_occurrences where tenant_id=@TenantId and severity='CRITICAL' and status not in('RESOLVED','CLOSED')) criticaloccurrences,count(*) filter(where entity_type='ROUTE' and status='ACTIVE') activeroutes,(select count(*) from agro360.geospatial_route_segments where tenant_id=@TenantId and status in('RESTRICTED','BLOCKED')) tripsatrisk,count(*) filter(where entity_type='ENVIRONMENTAL_AREA') environmentalareas,count(*) filter(where entity_type='MANAGEMENT_ZONE') managementzones,count(*) filter(where entity_type='ENVIRONMENTAL_AREA' and status='BLOCKED') territorialalerts from agro360.geospatial_features where tenant_id=@TenantId",new{tenant.TenantId},t),ct);
    public async Task<object> LayersAsync(CancellationToken ct){var rows=await ListAsync(null,null,ct);return rows.GroupBy(x=>x.EntityType).Select(x=>new{id=x.Key,name=x.Key.Replace('_',' '),count=x.Count(),visible=true}).ToArray();}
    private static string SafeJson(string json){try{using var d=JsonDocument.Parse(json);return d.RootElement.GetRawText();}catch(JsonException){return JsonSerializer.Serialize(new{invalidPayload=json});}}
    private static (decimal Lat,decimal Lon) Center(JsonElement coordinates){var points=new List<(decimal Lat,decimal Lon)>();Collect(coordinates,points);return(points.Average(x=>x.Lat),points.Average(x=>x.Lon));}
    private static void Collect(JsonElement e,List<(decimal Lat,decimal Lon)> p){if(e[0].ValueKind==JsonValueKind.Number){p.Add((e[1].GetDecimal(),e[0].GetDecimal()));return;}foreach(var child in e.EnumerateArray())Collect(child,p);}
}
