using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class IntegrationService(DatabaseExecutor db,ITenantContext tenant) : IIntegrationService
{
 public Task<IReadOnlyList<IntegrationItem>> ListAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<IntegrationItem>)(await c.QueryAsync<IntegrationItem>("select id,name,type,provider,status,last_sync lastsync,last_error lasterror,attempts from agro360.integrations where tenant_id=@TenantId order by name",new{tenant.TenantId},t)).ToArray(),ct);
 public Task<Guid> SaveAsync(Guid? id,IntegrationCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var key=id??Guid.NewGuid();var n=id is null?await c.ExecuteAsync("insert into agro360.integrations(id,tenant_id,name,type,provider,status,credential_reference_id) values(@Id,@TenantId,@Name,@Type,@Provider,'AWAITING_CONFIGURATION',@CredentialReferenceId)",new{Id=key,tenant.TenantId,x.Name,x.Type,x.Provider,x.CredentialReferenceId},t):await c.ExecuteAsync("update agro360.integrations set name=@Name,type=@Type,provider=@Provider,credential_reference_id=@CredentialReferenceId,updated_at=now() where id=@Id and tenant_id=@TenantId",new{Id=key,tenant.TenantId,x.Name,x.Type,x.Provider,x.CredentialReferenceId},t);if(n==0)throw new KeyNotFoundException();return key;},ct);
 public Task SetStatusAsync(Guid id,bool active,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var status=active?"ACTIVE":"PAUSED";var n=await c.ExecuteAsync("update agro360.integrations set status=@Status,updated_at=now() where id=@Id and tenant_id=@TenantId and (not @Active or credential_reference_id is not null)",new{tenant.TenantId,id,status,active},t);if(n==0)throw new InvalidOperationException("Integração sem credencial configurada ou inexistente.");await Audit(c,t,"INTEGRATION_STATUS",id,new{status});},ct);
 public Task<object> LogsAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync<object>(async(c,t)=>(await c.QueryAsync("select occurred_at,event,status,error,attempt from agro360.integrations_integration_logs where tenant_id=@TenantId and integration_id=@Id order by occurred_at desc limit 200",new{tenant.TenantId,id},t)).ToArray(),ct);
 public Task<ApiKeyCreated> CreateApiKeyAsync(ApiKeyCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var allowed=new[]{"producers.read","properties.read","fields.read","lots.read","orders.read","contracts.read","certificates.read","agro360.fiscal_authorized.read","requests.write","quotations.write","agro360.logistics_events.write","evidence.write","agro360.traceability_read","marketplace.read"};if(x.Scopes.Length==0||x.Scopes.Any(s=>!allowed.Contains(s,StringComparer.OrdinalIgnoreCase)))throw new ArgumentException("Informe ao menos um escopo válido.");var id=Guid.NewGuid();var raw="ag360_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw))).ToLowerInvariant();await c.ExecuteAsync("insert into agro360.integrations_api_keys(id,tenant_id,name,key_prefix,key_hash,scopes,expires_at,rate_limit_per_minute) values(@Id,@TenantId,@Name,@Prefix,@Hash,@Scopes,@ExpiresAt,@RateLimitPerMinute)",new{id,tenant.TenantId,x.Name,Prefix=raw[..14],hash,x.Scopes,x.ExpiresAt,x.RateLimitPerMinute},t);return new ApiKeyCreated(id,raw,raw[..14],x.ExpiresAt);},ct);
 public Task<object> ApiKeysAsync(CancellationToken ct)=>Rows("select id,name,key_prefix,scopes,status,expires_at,last_used_at,rate_limit_per_minute from agro360.integrations_api_keys where tenant_id=@TenantId order by created_at desc",ct);
 public Task RevokeApiKeyAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.integrations_api_keys set status='REVOKED',revoked_at=now(),revoked_by=@UserId where id=@Id and tenant_id=@TenantId and status='ACTIVE'",new{tenant.TenantId,tenant.UserId,id},t);if(n==0)throw new InvalidOperationException("Chave inexistente ou já revogada.");await Audit(c,t,"API_KEY_REVOKED",id,new { revoked=true });},ct);
 public Task<Guid> CreateWebhookAsync(WebhookCommand x,CancellationToken ct)=>Insert("insert into agro360.integrations_webhooks(id,tenant_id,url,events,signing_credential_reference_id,status) values(@Id,@TenantId,@Url,@Events,@SigningCredentialReferenceId,case when @SigningCredentialReferenceId is null then 'AWAITING_CONFIGURATION' else 'ACTIVE' end)",x,ct);
 public Task<object> WebhooksAsync(CancellationToken ct)=>Rows("select id,url,events,status,created_at from agro360.integrations_webhooks where tenant_id=@TenantId order by created_at desc",ct);
 public Task<object> WebhookEventsAsync(CancellationToken ct)=>Rows("select id,event_type,status,attempts,next_attempt_at,last_error,created_at from agro360.integrations_webhook_events where tenant_id=@TenantId order by created_at desc limit 200",ct);
 public Task RetryWebhookAsync(Guid eventId,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.integrations_webhook_events set status='PENDING',next_attempt_at=now(),attempts=attempts+1 where id=@Id and tenant_id=@TenantId and status='FAILED'",new{tenant.TenantId,Id=eventId},t);if(n==0)throw new InvalidOperationException("Evento não está elegível para reenvio.");},ct);
 public Task CancelWebhookAsync(Guid eventId,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.integrations_webhook_events set status='CANCELLED',next_attempt_at=null where id=@Id and tenant_id=@TenantId and status='PENDING'",new{tenant.TenantId,Id=eventId},t);if(n==0)throw new InvalidOperationException("Somente entrega pendente pode ser cancelada.");},ct);
 public Task<Guid> CreateImportAsync(ImportCommand x,CancellationToken ct)=>Insert("insert into agro360.integrations_imports(id,tenant_id,entity_type,file_name,csv_content,status) values(@Id,@TenantId,@EntityType,@FileName,@CsvContent,'UPLOADED')",x,ct);
 public Task<object> ImportsAsync(CancellationToken ct)=>Rows("select id,entity_type,file_name,status,total_rows,valid_rows,error_rows,created_at from agro360.integrations_imports where tenant_id=@TenantId order by created_at desc",ct);
 public Task<object> ValidateImportAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync<object>(async(c,t)=>{var csv=await c.QuerySingleOrDefaultAsync<string>("select csv_content from agro360.integrations_imports where id=@Id and tenant_id=@TenantId",new{tenant.TenantId,id},t)??throw new KeyNotFoundException();var lines=csv.Replace("\r","").Split('\n',StringSplitOptions.RemoveEmptyEntries);var errors=new List<(int Line,string Error)>();if(lines.Length<2)errors.Add((1,"Arquivo sem dados."));for(var i=1;i<lines.Length;i++)if(lines[i].Split(',').Any(string.IsNullOrWhiteSpace))errors.Add((i+1,"Campo obrigatório vazio."));await c.ExecuteAsync("delete from agro360.integrations_import_errors where import_id=@Id; update agro360.integrations_imports set status=@Status,total_rows=@Total,valid_rows=@Valid,error_rows=@Errors,validated_at=now() where id=@Id and tenant_id=@TenantId",new{tenant.TenantId,id,Status=errors.Count==0?"VALIDATED":"INVALID",Total=Math.Max(0,lines.Length-1),Valid=Math.Max(0,lines.Length-1-errors.Count),Errors=errors.Count},t);foreach(var e in errors)await c.ExecuteAsync("insert into agro360.integrations_import_errors(id,tenant_id,import_id,line_number,message) values(gen_random_uuid(),@TenantId,@Id,@Line,@Message)",new{tenant.TenantId,id,e.Line,Message=e.Error},t);return new{valid=errors.Count==0,errors=errors.Select(e=>new{line=e.Line,error=e.Error})};},ct);
 public Task ConfirmImportAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.integrations_imports set status='CONFIRMED',confirmed_at=now(),confirmed_by=@UserId where id=@Id and tenant_id=@TenantId and status='VALIDATED'",new{tenant.TenantId,id,tenant.UserId},t);if(n==0)throw new InvalidOperationException("Somente importação validada pode ser confirmada.");},ct);
 public Task<byte[]> ExportAsync(string entity,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var supported=new Dictionary<string,string>{{"producers","select id,name from agro360.compliance_subjects where tenant_id=@TenantId and type='PRODUCER'"},{"properties","select id,name from agro360.geo_farms where tenant_id=@TenantId"},{"customers","select id,name from agro360.commercial_customers where tenant_id=@TenantId"}};if(!supported.TryGetValue(entity,out var sql))throw new ArgumentException("Exportação não suportada.");var rows=await c.QueryAsync(sql,new{tenant.TenantId},t);var output="id,name\n"+string.Join('\n',rows.Select(r=>$"{r.id},\"{r.name?.ToString().Replace("\"","\"\"")}\""));return Encoding.UTF8.GetBytes(output);},ct);
 public Task<Guid> AddFiscalDocumentAsync(IntegrationFiscalDocumentCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{byte[] bytes;try{bytes=Convert.FromBase64String(x.ContentBase64);}catch(FormatException){throw new ArgumentException("Conteúdo fiscal deve ser Base64 válido.");}if(bytes.Length>10_000_000)throw new ArgumentException("Documento excede 10 MB.");if(x.FileName.EndsWith(".xml",StringComparison.OrdinalIgnoreCase)){try{var xml=XDocument.Parse(Encoding.UTF8.GetString(bytes),LoadOptions.None);var root=xml.Root?.Name.LocalName;if(root is not ("NFe" or "nfeProc" or "CTe" or "cteProc" or "MDFe" or "mdfeProc"))throw new ArgumentException("Estrutura XML fiscal não reconhecida.");}catch(System.Xml.XmlException){throw new ArgumentException("XML fiscal inválido.");}}var hash=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.integrations_fiscal_documents(id,tenant_id,type,file_name,sha256,purchase_id,sale_id,shipment_id,lot_id,producer_id,supplier_id,uploaded_by,status) values(@Id,@TenantId,@Type,@FileName,@Hash,@PurchaseId,@SaleId,@ShipmentId,@LotId,@ProducerId,@SupplierId,@UserId,'IMPORTED')",new{id,tenant.TenantId,x.Type,x.FileName,hash,x.PurchaseId,x.SaleId,x.ShipmentId,x.LotId,x.ProducerId,x.SupplierId,tenant.UserId},t);return id;},ct);
 public Task<object> FiscalDocumentsAsync(CancellationToken ct)=>Rows("select id,type,file_name,sha256,status,uploaded_at from agro360.integrations_fiscal_documents where tenant_id=@TenantId order by uploaded_at desc",ct);
 public Task<(Guid Id,string Token)> AddDeviceAsync(DeviceCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(x.Minimum>x.Maximum)throw new ArgumentException("Limites inválidos.");var id=Guid.NewGuid();var raw="iot_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant();var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw))).ToLowerInvariant();await c.ExecuteAsync("insert into agro360.integrations_iot_devices(id,tenant_id,name,type,sensor_type,token_hash,minimum,maximum) values(@Id,@TenantId,@Name,@Type,@SensorType,@Hash,@Minimum,@Maximum)",new{id,tenant.TenantId,x.Name,x.Type,x.SensorType,hash,x.Minimum,x.Maximum},t);return(id,raw);},ct);
 public Task<object> DevicesAsync(CancellationToken ct)=>Rows("select id,name,type,sensor_type,status,minimum,maximum,last_seen_at from agro360.integrations_iot_devices where tenant_id=@TenantId order by name",ct);
 public Task<Guid> AddReadingAsync(ReadingCommand x,CancellationToken ct)=>db.InSystemTransactionAsync(async(c,t)=>{var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x.DeviceToken))).ToLowerInvariant();var device=await c.QuerySingleOrDefaultAsync<(Guid Id,Guid TenantId,decimal? Minimum,decimal? Maximum)>("select id,tenant_id,minimum,maximum from agro360.integrations_iot_devices where token_hash=@Hash and status='ACTIVE'",new{hash},t);if(device.Id==Guid.Empty)throw new UnauthorizedAccessException();var critical=device.Minimum.HasValue&&x.Value<device.Minimum||device.Maximum.HasValue&&x.Value>device.Maximum;var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.integrations_iot_readings(id,tenant_id,device_id,sensor_type,value,unit,recorded_at,latitude,longitude,critical) values(@Id,@TenantId,@DeviceId,@SensorType,@Value,@Unit,coalesce(@RecordedAt,now()),@Latitude,@Longitude,@Critical); update agro360.integrations_iot_devices set last_seen_at=now() where id=@DeviceId",new{id,TenantId=device.TenantId,DeviceId=device.Id,x.SensorType,x.Value,x.Unit,x.RecordedAt,x.Latitude,x.Longitude,critical},t);if(critical)await c.ExecuteAsync("insert into agro360.integrations_iot_alerts(id,tenant_id,device_id,reading_id,severity,message) values(gen_random_uuid(),@TenantId,@DeviceId,@Id,'CRITICAL','Leitura fora do limite configurado')",new{TenantId=device.TenantId,DeviceId=device.Id,id},t);return id;},ct);
 public Task<Guid> CalculateSplitAsync(SplitCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(Math.Abs(x.Participants.Sum(p=>p.Percentage)-100)>0.01m)throw new ArgumentException("Percentuais devem totalizar 100%.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.integrations_payment_splits(id,tenant_id,sale_id,gross_amount,status,provider,created_by) values(@Id,@TenantId,@SaleId,@GrossAmount,'CALCULATED','INTERNAL_MANUAL',@UserId)",new{id,tenant.TenantId,x.SaleId,x.GrossAmount,tenant.UserId},t);foreach(var p in x.Participants)await c.ExecuteAsync("insert into agro360.integrations_split_participants(id,tenant_id,split_id,party_id,percentage,amount) values(gen_random_uuid(),@TenantId,@Id,@PartyId,@Percentage,round(@GrossAmount*@Percentage/100,2))",new{tenant.TenantId,id,p.PartyId,p.Percentage,x.GrossAmount},t);return id;},ct);
 public Task ApproveSplitAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.integrations_payment_splits set status='APPROVED',approved_at=now(),approved_by=@UserId where id=@Id and tenant_id=@TenantId and status='CALCULATED'",new{tenant.TenantId,id,tenant.UserId},t);if(n==0)throw new InvalidOperationException("Split não calculado ou inexistente.");},ct);
 public Task<object> SplitsAsync(CancellationToken ct)=>Rows("select id,sale_id,gross_amount,status,provider,created_at,approved_at from agro360.integrations_payment_splits where tenant_id=@TenantId order by created_at desc",ct);
 public Task<Guid> EnqueueMessageAsync(MessageCommand x,CancellationToken ct){if(x.Body.Contains("password",StringComparison.OrdinalIgnoreCase)||x.Body.Contains("senha",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Mensagem não pode conter segredo.");return Insert("insert into agro360.integrations_message_outbox(id,tenant_id,channel,recipient_id,subject,body,status,provider) values(@Id,@TenantId,@Channel,@RecipientId,@Subject,@Body,'PENDING',case when @Channel='IN_APP' then 'INTERNAL' else 'AWAITING_CONFIGURATION' end)",x,ct);}
 public Task<object> OutboxAsync(CancellationToken ct)=>Rows("select id,channel,subject,status,provider,attempts,created_at,sent_at from agro360.integrations_message_outbox where tenant_id=@TenantId order by created_at desc",ct);
 public Task<IntegrationDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<IntegrationDashboard>("select count(*) filter(where status='ACTIVE') activeintegrations,count(*) filter(where status='ERROR') failedintegrations,(select count(*) from agro360.integrations_webhook_events where tenant_id=@TenantId and status='PENDING') pendingwebhooks,(select count(*) from agro360.integrations_imports where tenant_id=@TenantId and status='INVALID') failedimports,(select count(*) from agro360.integrations_iot_devices where tenant_id=@TenantId and coalesce(last_seen_at,created_at)<now()-interval '15 minutes') offlinesensors,(select count(*) from agro360.integrations_api_keys where tenant_id=@TenantId and expires_at between now() and now()+interval '30 days') expiringapikeys,(select count(*) from agro360.integrations_webhook_events where tenant_id=@TenantId and status='SENT') sentevents,coalesce((select avg(processing_ms) from agro360.integrations_webhook_events where tenant_id=@TenantId and processing_ms is not null),0) averageprocessingmilliseconds,(select count(*) from agro360.integrations_iot_alerts where tenant_id=@TenantId and severity='CRITICAL' and resolved_at is null) criticalalerts from agro360.integrations where tenant_id=@TenantId",new{tenant.TenantId},t),ct);
 private Task<object> Rows(string sql,CancellationToken ct)=>db.InTenantTransactionAsync<object>(async(c,t)=>(await c.QueryAsync(sql,new{tenant.TenantId},t)).ToArray(),ct);
 private Task<Guid> Insert(string sql,object x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var id=Guid.NewGuid();var p=new DynamicParameters(x);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);await c.ExecuteAsync(sql,p,t);return id;},ct);
 private async Task Audit(System.Data.IDbConnection c,System.Data.IDbTransaction t,string type,Guid entity,object details)=>await c.ExecuteAsync("insert into agro360.integrations_audit_events(id,tenant_id,actor_id,event_type,entity_id,details) values(gen_random_uuid(),@TenantId,@UserId,@Type,@Entity,@Details::jsonb)",new{tenant.TenantId,tenant.UserId,type,entity,Details=JsonSerializer.Serialize(details)},t);
}
