using Agro360.Application.Contracts; using Agro360.Domain.Storage; using Agro360.Infrastructure.Persistence; using Agro360.Multitenancy; using Agro360.SharedKernel; using Dapper; using Microsoft.Extensions.Logging; using Npgsql;
namespace Agro360.Infrastructure.Services;
public sealed class LogisticsService(DatabaseExecutor db,ITenantContext tenant,ILogger<LogisticsService> logger):ILogisticsService
{
 public Task<IReadOnlyList<dynamic>> ListAsync(CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition("select * from agro360.logistics_trips where tenant_id=@TenantId order by created_at desc",new{tenant.TenantId},t,cancellationToken:ct))).AsList());
 public Task<Guid> SaveAsync(Guid? id,TripCommand x,CancellationToken ct){StorageRules.Freight(x.FreightValue,x.EstimatedDistance,x.Tonnes);return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var sql=id is null?"insert into agro360.logistics_trips(id,tenant_id,number,shipment_id,origin,destination,estimated_distance,carrier,driver,vehicle,freight_type,freight_value,cost_per_tonne,cost_per_km,status,created_by) values(@Id,@TenantId,@Number,@ShipmentId,@Origin,@Destination,@EstimatedDistance,@Carrier,@Driver,@Vehicle,@FreightType,@FreightValue,case when @Tonnes=0 then 0 else @FreightValue/@Tonnes end,case when @EstimatedDistance=0 then 0 else @FreightValue/@EstimatedDistance end,@Status,@UserId)":"update agro360.logistics_trips set number=@Number,shipment_id=@ShipmentId,origin=@Origin,destination=@Destination,estimated_distance=@EstimatedDistance,carrier=@Carrier,driver=@Driver,vehicle=@Vehicle,freight_type=@FreightType,freight_value=@FreightValue,cost_per_tonne=case when @Tonnes=0 then 0 else @FreightValue/@Tonnes end,cost_per_km=case when @EstimatedDistance=0 then 0 else @FreightValue/@EstimatedDistance end,status=@Status,updated_at=now() where tenant_id=@TenantId and id=@Id";if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("Viagem",key);await Audit(c,t,id is null?"create":"update",key,x,ct);return key;});}
 public Task AddOccurrenceAsync(Guid id,TripOccurrenceCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Description))throw new DomainException("Descrição da ocorrência é obrigatória.");return Tx(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("insert into agro360.logistics_trip_occurrences(id,tenant_id,trip_id,description,created_by) select @Occurrence,@TenantId,@Id,@Description,@UserId where exists(select 1 from agro360.logistics_trips where tenant_id=@TenantId and id=@Id); update agro360.logistics_trips set status='WITH_OCCURRENCE',updated_at=now() where tenant_id=@TenantId and id=@Id",new{Occurrence=Guid.CreateVersion7(),tenant.TenantId,Id=id,x.Description,tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"occurrence",id,x,ct);});}
 public Task CompleteAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.logistics_trips set status='DELIVERED',delivered_at=now(),updated_at=now() where tenant_id=@TenantId and id=@Id and status not in('DELIVERED','CANCELLED')",new{tenant.TenantId,Id=id},t,cancellationToken:ct))==0)throw new ConflictException("Viagem não pode ser concluída.");await Audit(c,t,"complete",id,new{},ct);});
 private Task Audit(NpgsqlConnection c,NpgsqlTransaction t,string action,Guid id,object x,CancellationToken ct)=>c.WriteAuditAsync(t,tenant,action,"Trip",id,null,x,ct);
 private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> f){try{return await db.InTenantTransactionAsync(f,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha logística do tenant {TenantId}",tenant.TenantId);throw;}} private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> f)=>Tx(async(c,t)=>{await f(c,t);return true;});
}
public sealed class DeliveryContractService(DatabaseExecutor db,ITenantContext tenant,ILogger<DeliveryContractService> logger):IDeliveryContractService
{
 public Task<IReadOnlyList<dynamic>> ListAsync(CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition("select *,contracted_quantity-delivered_quantity balance_to_deliver from agro360.commercial_delivery_contracts where tenant_id=@TenantId order by delivery_deadline",new{tenant.TenantId},t,cancellationToken:ct))).AsList());
 public Task<Guid> SaveAsync(Guid? id,DeliveryContractCommand x,CancellationToken ct){if(x.ContractedQuantity<=0||x.ContractedPrice<0)throw new DomainException("Quantidade e preço contratados são inválidos.");if(x.Status=="CANCELLED"&&string.IsNullOrWhiteSpace(x.CancellationReason))throw new DomainException("Cancelamento exige motivo.");return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var sql=id is null?"insert into agro360.commercial_delivery_contracts(id,tenant_id,number,customer,product_id,contracted_quantity,contracted_price,unit,delivery_deadline,payment_terms,status,cancellation_reason,allow_overdelivery,created_by) values(@Id,@TenantId,@Number,@Customer,@ProductId,@ContractedQuantity,@ContractedPrice,@Unit,@DeliveryDeadline,@PaymentTerms,@Status,@CancellationReason,@AllowOverdelivery,@UserId)":"update agro360.commercial_delivery_contracts set number=@Number,customer=@Customer,product_id=@ProductId,contracted_quantity=@ContractedQuantity,contracted_price=@ContractedPrice,unit=@Unit,delivery_deadline=@DeliveryDeadline,payment_terms=@PaymentTerms,status=@Status,cancellation_reason=@CancellationReason,allow_overdelivery=@AllowOverdelivery,updated_at=now() where tenant_id=@TenantId and id=@Id";if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("Contrato",key);await c.WriteAuditAsync(t,tenant,id is null?"create":"update","DeliveryContract",key,null,x,ct);return key;});}
 private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> f){try{return await db.InTenantTransactionAsync(f,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha em contrato operacional do tenant {TenantId}",tenant.TenantId);throw;}}
}
