using System.Security.Cryptography;
using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Mobile;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class MobileService(DatabaseExecutor db, ITenantContext tenant, ILogger<MobileService> logger) : IMobileService
{
    public Task<dynamic> BootstrapAsync(Guid deviceId, CancellationToken ct) => Tx<dynamic>(async (c,t) => {
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_devices(id,tenant_id,user_id,last_seen_at) values(@DeviceId,@TenantId,@UserId,now()) on conflict(id) do update set last_seen_at=now() where agro360.mobile_devices.tenant_id=@TenantId and agro360.mobile_devices.user_id=@UserId", new { DeviceId=deviceId, tenant.TenantId, tenant.UserId },t,cancellationToken:ct));
        var lookups=await c.QueryAsync(new CommandDefinition("select 'properties' kind,id,name label from agro360.geo_farms where tenant_id=@TenantId and deleted_at is null union all select 'plots',id,name from agro360.geo_fields where tenant_id=@TenantId and deleted_at is null union all select 'seasons',id,name from agro360.agriculture_seasons where tenant_id=@TenantId and deleted_at is null union all select 'crops',id,name from agro360.agriculture_crops where tenant_id=@TenantId and active union all select 'animals',id,tag from agro360.livestock_animals where tenant_id=@TenantId and status=1 and deleted_at is null union all select 'animal-lots',id,name from agro360.livestock_herds where tenant_id=@TenantId and active union all select 'machines',id,name from agro360.fleet_assets where tenant_id=@TenantId and status<>'INACTIVE' union all select 'stock',id,name from agro360.inventory_products where tenant_id=@TenantId union all select 'responsibles',id,name from agro360.identity_users where tenant_id=@TenantId and status='ACTIVE' and deleted_at is null order by kind,label",new{tenant.TenantId},t,cancellationToken:ct));
        return new { serverTime=DateTimeOffset.UtcNow, deviceId, catalogVersion=DateTimeOffset.UtcNow.ToUnixTimeSeconds(), lookups=lookups.AsList() };
    });

    public Task<dynamic> SyncAsync(SyncCommand command, CancellationToken ct) => Tx<dynamic>(async(c,t) => {
        var batch=Guid.CreateVersion7(); var results=new List<object>();
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_sync_batches(id,tenant_id,user_id,device_id,session_id,status,started_at) values(@Batch,@TenantId,@UserId,@DeviceId,@SessionId,'PROCESSING',now())",new{Batch=batch,tenant.TenantId,tenant.UserId,command.DeviceId,command.SessionId},t,cancellationToken:ct));
        foreach(var offlineCommand in command.Commands) {
            if(string.IsNullOrWhiteSpace(offlineCommand.IdempotencyKey)){results.Add(new{offlineCommand.TemporaryId,status="ERROR",error="Chave idempotente obrigatória."});continue;}
            var existing=await c.QuerySingleOrDefaultAsync<Guid?>(new CommandDefinition("select definitive_id from agro360.mobile_offline_commands where tenant_id=@TenantId and user_id=@UserId and idempotency_key=@IdempotencyKey",new{tenant.TenantId,tenant.UserId,offlineCommand.IdempotencyKey},t,cancellationToken:ct));
            if(existing is not null){results.Add(new{offlineCommand.TemporaryId,status="ALREADY_PROCESSED",id=existing});continue;}
            try { var id=await MaterializeOfflineAsync(c,t,offlineCommand,ct); await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_offline_commands(id,tenant_id,user_id,device_id,session_id,batch_id,idempotency_key,temporary_id,command_type,payload,status,attempts,created_offline_at,received_at,processed_at,definitive_id) values(@CommandId,@TenantId,@UserId,@DeviceId,@SessionId,@Batch,@IdempotencyKey,@TemporaryId,@Type,cast(@Payload as jsonb),'SYNCED',1,@CreatedAt,now(),now(),@Id)",new{CommandId=Guid.CreateVersion7(),Id=id,tenant.TenantId,tenant.UserId,command.DeviceId,command.SessionId,Batch=batch,offlineCommand.IdempotencyKey,offlineCommand.TemporaryId,offlineCommand.Type,offlineCommand.Payload,offlineCommand.CreatedAt},t,cancellationToken:ct)); await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_id_mappings(id,tenant_id,temporary_id,definitive_id,entity_type) values(@Map,@TenantId,@TemporaryId,@Id,@Type)",new{Map=Guid.CreateVersion7(),tenant.TenantId,offlineCommand.TemporaryId,Id=id,offlineCommand.Type},t,cancellationToken:ct)); results.Add(new{offlineCommand.TemporaryId,status="SYNCED",id}); }
            catch(DomainException ex){await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_sync_errors(id,tenant_id,batch_id,temporary_id,error_code,message,retryable) values(@Id,@TenantId,@Batch,@TemporaryId,@Code,@Message,false)",new{Id=Guid.CreateVersion7(),tenant.TenantId,Batch=batch,offlineCommand.TemporaryId,Code=ex.Code??"VALIDATION",Message=ex.Message},t,cancellationToken:ct));results.Add(new{offlineCommand.TemporaryId,status="ERROR",error=ex.Message});}
            catch(PostgresException ex){await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_sync_errors(id,tenant_id,batch_id,temporary_id,error_code,message,retryable) values(@Id,@TenantId,@Batch,@TemporaryId,@Code,@Message,true)",new{Id=Guid.CreateVersion7(),tenant.TenantId,Batch=batch,offlineCommand.TemporaryId,Code=ex.SqlState,Message=ex.MessageText},t,cancellationToken:ct));results.Add(new{offlineCommand.TemporaryId,status="PENDING",error=ex.MessageText});}
        }
        await c.ExecuteAsync(new CommandDefinition("update agro360.mobile_sync_batches set status=@Status,finished_at=now() where id=@Batch and tenant_id=@TenantId",new{Status=results.Any(r=>JsonSerializer.Serialize(r).Contains("PENDING",StringComparison.Ordinal))?"PARTIAL":"COMPLETED",Batch=batch,tenant.TenantId},t,cancellationToken:ct));
        return new { batchId=batch, items=results };
    });
    public Task<dynamic> SyncStatusAsync(Guid deviceId,CancellationToken ct)=>One("select count(*) filter(where status='PENDING') pending,count(*) filter(where status='FAILED') errors,count(*) filter(where status='CONFLICT') conflicts,max(processed_at) last_sync from agro360.mobile_offline_commands where tenant_id=@TenantId and user_id=@UserId and device_id=@DeviceId",ct,new{DeviceId=deviceId});
    public Task<dynamic> DashboardAsync(CancellationToken ct)=>One("select (select count(*) from agro360.mobile_offline_commands where tenant_id=@TenantId and user_id=@UserId and status='PENDING') pending,(select count(*) from agro360.mobile_offline_commands where tenant_id=@TenantId and user_id=@UserId and status='FAILED') errors,(select count(*) from agro360.mobile_sync_conflicts where tenant_id=@TenantId and status='OPEN') conflicts,(select max(finished_at) from agro360.mobile_sync_batches where tenant_id=@TenantId and user_id=@UserId) last_sync,(select count(*) from agro360.mobile_checklist_runs where tenant_id=@TenantId and responsible_id=@UserId and status='PENDING') pending_checklists,(select count(*) from agro360.mobile_checklist_runs where tenant_id=@TenantId and responsible_id=@UserId and status='COMPLETED') completed_checklists,(select count(*) from agro360.mobile_evidences where tenant_id=@TenantId and sync_status='PENDING') pending_evidences,(select count(*) from agro360.field_operations_occurrences where tenant_id=@TenantId and severity='CRITICAL' and status in('OPEN','IN_PROGRESS') and deleted_at is null) critical_occurrences,(select count(*) from agro360.agriculture_records where tenant_id=@TenantId and created_at::date=current_date) today_activities",ct);
    public Task<Guid> QuickRecordAsync(string area,QuickRecordCommand command,CancellationToken ct){MobileRules.ValidateEntity(command.EntityType,command.EntityId);MobileRules.ValidateQuickRecord(command.Kind,command.Quantity,command.OccurredAt);MobileRules.ValidateLocation(command.Latitude,command.Longitude,null);return Insert("agro360.mobile_quick_records","area,kind,entity_type,entity_id,quantity,occurred_at,notes,latitude,longitude","@Area,@Kind,@EntityType,@EntityId,@Quantity,@OccurredAt,@Notes,@Latitude,@Longitude",new{Area=area,command.Kind,command.EntityType,command.EntityId,command.Quantity,command.OccurredAt,command.Notes,command.Latitude,command.Longitude},ct);}
    public Task<IReadOnlyList<dynamic>> EvidencesAsync(CancellationToken ct)=>List("select id,type,entity_type,entity_id,file_name,content_type,file_hash,notes,latitude,longitude,captured_at,sync_status from agro360.mobile_evidences where tenant_id=@TenantId order by captured_at desc",ct);
    public Task<Guid> AddEvidenceAsync(MobileEvidenceCommand command,CancellationToken ct){MobileRules.ValidateEntity(command.EntityType,command.EntityId);MobileRules.ValidateLocation(command.Latitude,command.Longitude,null);if(string.IsNullOrWhiteSpace(command.Type)||string.IsNullOrWhiteSpace(command.ContentBase64))throw new DomainException("Tipo e arquivo são obrigatórios.");byte[] bytes;try{bytes=Convert.FromBase64String(command.ContentBase64);}catch(FormatException){throw new DomainException("Arquivo inválido.");}if(bytes.Length>10_000_000)throw new DomainException("Arquivo excede 10 MB.");var hash=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();return Insert("agro360.mobile_evidences","type,entity_type,entity_id,file_name,content_type,file_data,file_hash,notes,latitude,longitude,captured_at,sync_status","@Type,@EntityType,@EntityId,@FileName,@ContentType,@Bytes,@Hash,@Notes,@Latitude,@Longitude,@CapturedAt,'SYNCED'",new{command.Type,command.EntityType,command.EntityId,command.FileName,command.ContentType,Bytes=bytes,Hash=hash,command.Notes,command.Latitude,command.Longitude,command.CapturedAt},ct);}
    public Task<IReadOnlyList<dynamic>> LocationsAsync(CancellationToken ct)=>List("select * from agro360.mobile_geolocation_events where tenant_id=@TenantId order by occurred_at desc",ct);
    public Task<Guid> AddLocationAsync(GeolocationCommand command,CancellationToken ct){MobileRules.ValidateEntity(command.EntityType,command.EntityId);MobileRules.ValidateLocation(command.Latitude,command.Longitude,command.Accuracy);return Insert("agro360.mobile_geolocation_events","entity_type,entity_id,event_type,origin,latitude,longitude,accuracy,occurred_at,location_available","@EntityType,@EntityId,@EventType,@Origin,@Latitude,@Longitude,@Accuracy,@OccurredAt,@Available",new{command.EntityType,command.EntityId,command.EventType,command.Origin,command.Latitude,command.Longitude,command.Accuracy,command.OccurredAt,Available=command.Latitude is not null},ct);}
    public Task<dynamic> GenerateQrAsync(QrGenerateCommand command,CancellationToken ct){MobileRules.ValidateEntity(command.EntityType,command.EntityId);return Tx<dynamic>(async(c,t)=>{var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(18)).ToLowerInvariant();await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_qr_codes(id,tenant_id,entity_type,entity_id,code,is_public,created_by) values(@Id,@TenantId,@EntityType,@EntityId,@Token,@Public,@UserId)",new{Id=Guid.CreateVersion7(),tenant.TenantId,command.EntityType,command.EntityId,Token=token,command.Public,tenant.UserId},t,cancellationToken:ct));return new{code=token,url=$"/field/qr/{token}",isPublic=command.Public};});}
    public Task<dynamic?> ResolveQrAsync(string code,bool authenticated,CancellationToken ct)=>Tx<dynamic?>(async(c,t)=>{var row=await c.QuerySingleOrDefaultAsync(new CommandDefinition("select entity_type,entity_id,is_public,active from agro360.mobile_qr_codes where code=@Code and tenant_id=@TenantId",new{Code=code,tenant.TenantId},t,cancellationToken:ct));if(row is null)return null;if(!(bool)row.is_public&&!authenticated)throw new UnauthorizedAccessException("QR interno exige autenticação.");return new{entityType=row.entity_type,entityId=row.entity_id,active=row.active,operationUrl=$"/field?entity={row.entity_type}&selected={row.entity_id}"};});
    public Task<IReadOnlyList<dynamic>> TemplatesAsync(CancellationToken ct)=>List("select t.*,coalesce(jsonb_agg(q order by q.position) filter(where q.id is not null),'[]') questions from agro360.mobile_checklist_templates t left join agro360.mobile_checklist_questions q on q.template_id=t.id where t.tenant_id=@TenantId and t.active group by t.id order by t.name",ct);
    public Task<Guid> AddTemplateAsync(ChecklistTemplateCommand command,CancellationToken ct)=>Tx(async(c,t)=>{if(string.IsNullOrWhiteSpace(command.Name)||command.Questions.Count==0)throw new DomainException("Nome e perguntas são obrigatórios.");var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_checklist_templates(id,tenant_id,name,usage,required,active,created_by) values(@Id,@TenantId,@Name,@Usage,@Required,true,@UserId)",new{Id=id,tenant.TenantId,command.Name,command.Usage,command.Required,tenant.UserId},t,cancellationToken:ct));for(var i=0;i<command.Questions.Count;i++){var q=command.Questions[i];await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_checklist_questions(id,tenant_id,template_id,text,response_type,required,options,position) values(@Id,@TenantId,@TemplateId,@Text,@ResponseType,@Required,cast(@Options as jsonb),@Position)",new{Id=Guid.CreateVersion7(),tenant.TenantId,TemplateId=id,q.Text,q.ResponseType,q.Required,Options=JsonSerializer.Serialize(q.Options??[]),Position=i},t,cancellationToken:ct));}return id;});
    public Task<Guid> ApplyChecklistAsync(ChecklistApplyCommand command,CancellationToken ct){MobileRules.ValidateEntity(command.EntityType,command.EntityId);return Insert("agro360.mobile_checklist_runs","template_id,entity_type,entity_id,responsible_id,status,applied_at","@TemplateId,@EntityType,@EntityId,@ResponsibleId,'PENDING',now()",command,ct);}
    public Task CompleteChecklistAsync(Guid id,ChecklistCompleteCommand command,CancellationToken ct)=>Tx(async(c,t)=>{var required=(await c.QueryAsync<(Guid Id,string ResponseType)>(new CommandDefinition("select q.id,q.response_type from agro360.mobile_checklist_runs r join agro360.mobile_checklist_questions q on q.template_id=r.template_id where r.id=@Id and r.tenant_id=@TenantId and q.required",new{Id=id,tenant.TenantId},t,cancellationToken:ct))).ToList();foreach(var q in required){var answer=command.Answers.FirstOrDefault(a=>a.QuestionId==q.Id);if(answer is null||string.IsNullOrWhiteSpace(answer.Value)&&answer.EvidenceId is null||q.ResponseType=="PHOTO"&&answer.EvidenceId is null)throw new DomainException("Responda todas as perguntas obrigatórias, incluindo fotos.","checklist.required");}foreach(var a in command.Answers)await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_checklist_answers(id,tenant_id,run_id,question_id,value,evidence_id,answered_by) values(@AnswerId,@TenantId,@RunId,@QuestionId,@Value,@EvidenceId,@UserId)",new{AnswerId=Guid.CreateVersion7(),tenant.TenantId,RunId=id,a.QuestionId,a.Value,a.EvidenceId,tenant.UserId},t,cancellationToken:ct));if(await c.ExecuteAsync(new CommandDefinition("update agro360.mobile_checklist_runs set status='COMPLETED',completed_at=now() where id=@Id and tenant_id=@TenantId and status='PENDING'",new{Id=id,tenant.TenantId},t,cancellationToken:ct))==0)throw new NotFoundException("Checklist",id);});
    public Task<Guid> AddOccurrenceAsync(FieldOccurrenceCommand command,CancellationToken ct)
    {
        MobileRules.ValidateLocation(command.Latitude,command.Longitude,null);
        FieldMobileRules.ValidateOccurrence(Enum.Parse<FieldPriority>(command.Severity, true),command.ResponsibleId,null,null);
        if(command.OccurredAt==default||command.OccurredAt>DateTimeOffset.UtcNow.AddMinutes(10)) throw new DomainException("Data da ocorrência inválida.");
        return Insert("agro360.field_operations_occurrences","user_id,occurrence_type,severity,title,description,entity_type,entity_id,responsible_id,latitude,longitude,occurred_at,status,updated_by","@UserId,@OccurrenceType,@Severity,@Title,@Description,@EntityType,@EntityId,@ResponsibleId,@Latitude,@Longitude,@OccurredAt,'OPEN',@UserId",command,ct);
    }
    public Task<Guid> AddCheckinAsync(FieldCheckinCommand command,CancellationToken ct)
    {
        MobileRules.ValidateManualLocation(command.LocationSource,command.ManualReason,command.Latitude,command.Longitude,command.Accuracy);
        if(command.OccurredAt==default||command.OccurredAt>DateTimeOffset.UtcNow.AddMinutes(10)) throw new DomainException("Data do check-in inválida.");
        return Insert("agro360.field_operations_checkins","user_id,operation_type,entity_type,entity_id,latitude,longitude,accuracy,location_source,manual_reason,observation,occurred_at,status,updated_by","@UserId,@OperationType,@EntityType,@EntityId,@Latitude,@Longitude,@Accuracy,@LocationSource,@ManualReason,@Observation,@OccurredAt,'REGISTERED',@UserId",command,ct);
    }
    private async Task<Guid> MaterializeOfflineAsync(NpgsqlConnection c,NpgsqlTransaction t,OfflineCommand offlineCommand,CancellationToken ct)
    {
        var json=new JsonSerializerOptions { PropertyNameCaseInsensitive=true };
        var id=Guid.CreateVersion7();
        if(offlineCommand.Type.StartsWith("quick-",StringComparison.Ordinal))
        {
            var quickRecord=JsonSerializer.Deserialize<QuickRecordCommand>(offlineCommand.Payload,json) ?? throw new DomainException("Payload de manejo inválido.");
            var area=offlineCommand.Type[6..]; MobileRules.ValidateEntity(quickRecord.EntityType,quickRecord.EntityId); MobileRules.ValidateQuickRecord(quickRecord.Kind,quickRecord.Quantity,quickRecord.OccurredAt); MobileRules.ValidateLocation(quickRecord.Latitude,quickRecord.Longitude,null);
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_quick_records(id,tenant_id,area,kind,entity_type,entity_id,quantity,occurred_at,notes,latitude,longitude,created_by) values(@Id,@TenantId,@Area,@Kind,@EntityType,@EntityId,@Quantity,@OccurredAt,@Notes,@Latitude,@Longitude,@UserId)",new{Id=id,tenant.TenantId,Area=area,quickRecord.Kind,quickRecord.EntityType,quickRecord.EntityId,quickRecord.Quantity,quickRecord.OccurredAt,quickRecord.Notes,quickRecord.Latitude,quickRecord.Longitude,tenant.UserId},t,cancellationToken:ct));
        }
        else if(offlineCommand.Type=="field-occurrence")
        {
            var occurrence=JsonSerializer.Deserialize<FieldOccurrenceCommand>(offlineCommand.Payload,json) ?? throw new DomainException("Payload de ocorrência inválido."); MobileRules.ValidateLocation(occurrence.Latitude,occurrence.Longitude,null);
            FieldMobileRules.ValidateOccurrence(Enum.Parse<FieldPriority>(occurrence.Severity, true),occurrence.ResponsibleId,null,null);
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.field_operations_occurrences(id,tenant_id,user_id,occurrence_type,severity,title,description,entity_type,entity_id,responsible_id,latitude,longitude,occurred_at,status,created_by,updated_by) values(@Id,@TenantId,@UserId,@OccurrenceType,@Severity,@Title,@Description,@EntityType,@EntityId,@ResponsibleId,@Latitude,@Longitude,@OccurredAt,'OPEN',@UserId,@UserId)",new{Id=id,tenant.TenantId,tenant.UserId,occurrence.OccurrenceType,occurrence.Severity,occurrence.Title,occurrence.Description,occurrence.EntityType,occurrence.EntityId,occurrence.ResponsibleId,occurrence.Latitude,occurrence.Longitude,occurrence.OccurredAt},t,cancellationToken:ct));
        }
        else if(offlineCommand.Type=="field-checkin")
        {
            var checkin=JsonSerializer.Deserialize<FieldCheckinCommand>(offlineCommand.Payload,json) ?? throw new DomainException("Payload de check-in inválido."); MobileRules.ValidateManualLocation(checkin.LocationSource,checkin.ManualReason,checkin.Latitude,checkin.Longitude,checkin.Accuracy);
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.field_operations_checkins(id,tenant_id,user_id,operation_type,entity_type,entity_id,latitude,longitude,accuracy,location_source,manual_reason,observation,occurred_at,status,created_by,updated_by) values(@Id,@TenantId,@UserId,@OperationType,@EntityType,@EntityId,@Latitude,@Longitude,@Accuracy,@LocationSource,@ManualReason,@Observation,@OccurredAt,'REGISTERED',@UserId,@UserId)",new{Id=id,tenant.TenantId,tenant.UserId,checkin.OperationType,checkin.EntityType,checkin.EntityId,checkin.Latitude,checkin.Longitude,checkin.Accuracy,checkin.LocationSource,checkin.ManualReason,checkin.Observation,checkin.OccurredAt},t,cancellationToken:ct));
        }
        else if(offlineCommand.Type=="evidence")
        {
            var evidence=JsonSerializer.Deserialize<MobileEvidenceCommand>(offlineCommand.Payload,json) ?? throw new DomainException("Payload de evidência inválido."); MobileRules.ValidateEntity(evidence.EntityType,evidence.EntityId); MobileRules.ValidateLocation(evidence.Latitude,evidence.Longitude,null);
            byte[] bytes; try{bytes=Convert.FromBase64String(evidence.ContentBase64);}catch(FormatException){throw new DomainException("Arquivo inválido.");} if(bytes.Length is 0 or >10_000_000)throw new DomainException("Arquivo deve ter entre 1 byte e 10 MB.");
            if(evidence.ContentType is not ("image/jpeg" or "image/png" or "image/webp" or "application/pdf"))throw new DomainException("Tipo de arquivo não permitido."); var hash=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.mobile_evidences(id,tenant_id,type,entity_type,entity_id,file_name,content_type,file_data,file_hash,notes,latitude,longitude,captured_at,sync_status,created_by) values(@Id,@TenantId,@Type,@EntityType,@EntityId,@FileName,@ContentType,@Bytes,@Hash,@Notes,@Latitude,@Longitude,@CapturedAt,'SYNCED',@UserId)",new{Id=id,tenant.TenantId,tenant.UserId,evidence.Type,evidence.EntityType,evidence.EntityId,FileName=Path.GetFileName(evidence.FileName),evidence.ContentType,Bytes=bytes,Hash=hash,evidence.Notes,evidence.Latitude,evidence.Longitude,evidence.CapturedAt},t,cancellationToken:ct));
        }
        else throw new DomainException("Tipo de operação offline não permitido.","agro360.mobile_operation_not_allowed");
        return id;
    }
    private Task<Guid> Insert(string table,string columns,string values,object data,CancellationToken ct)=>Tx(async(c,t)=>{var id=Guid.CreateVersion7();var p=new DynamicParameters(data);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);await c.ExecuteAsync(new CommandDefinition($"insert into {table}(id,tenant_id,{columns},created_by) values(@Id,@TenantId,{values},@UserId)",p,t,cancellationToken:ct));return id;});
    private Task<IReadOnlyList<dynamic>> List(string sql,CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition(sql,new{tenant.TenantId,tenant.UserId},t,cancellationToken:ct))).AsList());
    private Task<dynamic> One(string sql,CancellationToken ct,object? extra=null)=>Tx<dynamic>(async(c,t)=>{var p=new DynamicParameters(extra);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);return await c.QuerySingleAsync(new CommandDefinition(sql,p,t,cancellationToken:ct));});
    private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){InfrastructureLogMessages.MobileBoundaryFailed(logger,tenant.TenantId,ex);throw;}}
    private Task<bool> Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
