using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;
using Microsoft.Extensions.Logging;

namespace Agro360.Infrastructure.Services;

public sealed class OperationalIntelligenceService(DatabaseExecutor database, ITenantContext tenant, ILogger<OperationalIntelligenceService> logger) : IOperationalIntelligenceService
{
    public Task<IntelligenceDashboardSummary> DashboardAsync(CancellationToken ct) => Guard("dashboard", () => database.InTenantTransactionAsync(async (c, t) =>
    {
        var counts = await c.QuerySingleAsync("""select count(*) filter(where status='OPEN') open_recommendations,count(*) filter(where status='OPEN' and severity='CRITICAL') critical_recommendations,count(*) filter(where status='ACCEPTED') accepted_recommendations,count(*) filter(where status='REJECTED') rejected_recommendations from agro360.intelligence_recommendations where tenant_id=@TenantId and deleted_at is null""", new { tenant.TenantId }, t);
        var anomaly = await c.QuerySingleAsync("""select count(*) filter(where status='OPEN') open_anomalies,count(*) filter(where status='OPEN' and severity='CRITICAL') critical_anomalies from agro360.intelligence_anomalies where tenant_id=@TenantId and deleted_at is null""", new { tenant.TenantId }, t);
        var priority = await c.QuerySingleAsync("""select count(*) filter(where due_at<now()) overdue,count(*) filter(where assigned_to is null) unassigned,coalesce(sum(impact_amount),0) impact from agro360.intelligence_priority_items where tenant_id=@TenantId and status='OPEN'""", new { tenant.TenantId }, t);
        var criticalScores = await c.ExecuteScalarAsync<int>("select count(*) from agro360.intelligence_scores where tenant_id=@TenantId and risk_band='CRITICAL' and deleted_at is null", new { tenant.TenantId }, t);
        var risks = (await c.QueryAsync<RiskScoreSummary>("select id,entity_type EntityType,entity_id EntityId,module,overall_score OverallScore,risk_band RiskBand,formula_version FormulaVersion,calculated_at CalculatedAt from agro360.intelligence_scores where tenant_id=@TenantId and deleted_at is null order by overall_score desc limit 10", new { tenant.TenantId }, t)).ToArray();
        var priorities = await LoadPriorities(c, t, 10);
        return new IntelligenceDashboardSummary((int)counts.open_recommendations,(int)counts.critical_recommendations,(int)counts.accepted_recommendations,(int)counts.rejected_recommendations,(int)anomaly.open_anomalies,(int)anomaly.critical_anomalies,criticalScores,(int)priority.overdue,(int)priority.unassigned,(decimal)priority.impact,risks,priorities);
    }, ct));

    public Task<IntelligencePage<RecommendationSummary>> RecommendationsAsync(IntelligencePageFilter filter, CancellationToken ct) => Guard("recommendations", () => database.InTenantTransactionAsync(async (c,t) =>
    {
        Validate(filter); var p = Parameters(filter); const string where="tenant_id=@TenantId and deleted_at is null and (@Search is null or title ilike '%'||@Search||'%' or reason ilike '%'||@Search||'%') and (@Status is null or status=@Status) and (@Severity is null or severity=@Severity) and (@Module is null or module=@Module)";
        var total=await c.ExecuteScalarAsync<int>($"select count(*) from agro360.intelligence_recommendations where {where}",p,t);
        var rows=(await c.QueryAsync<RecommendationSummary>($"select id,module,type,title,reason,suggested_action SuggestedAction,severity,status,entity_type EntityType,created_at CreatedAt,due_at DueAt from agro360.intelligence_recommendations where {where} order by case severity when 'CRITICAL' then 0 when 'HIGH' then 1 else 2 end,created_at desc limit @PageSize offset @Offset",p,t)).ToArray();
        return new IntelligencePage<RecommendationSummary>(rows,total,filter.Page,filter.PageSize);
    },ct));

    public Task<RecommendationDetail> RecommendationAsync(Guid id,CancellationToken ct)=>Guard("recommendation-detail",()=>database.InTenantTransactionAsync(async(c,t)=>
    {
        var item=await c.QuerySingleOrDefaultAsync<RecommendationSummary>("select id,module,type,title,reason,suggested_action SuggestedAction,severity,status,entity_type EntityType,created_at CreatedAt,due_at DueAt from agro360.intelligence_recommendations where tenant_id=@TenantId and id=@Id and deleted_at is null",new{tenant.TenantId,Id=id},t)??throw new KeyNotFoundException("Recomendação não encontrada.");
        var sources=(await c.QueryAsync<RecommendationSource>("select source_module SourceModule,source_entity_type SourceEntityType,coalesce(observed_value,'') DisplayValue,reference_value ReferenceValue,observed_at ObservedAt from agro360.intelligence_recommendation_sources where tenant_id=@TenantId and recommendation_id=@Id order by observed_at desc",new{tenant.TenantId,Id=id},t)).ToArray();
        return new RecommendationDetail(item,sources);
    },ct));

    public Task DecideRecommendationAsync(Guid id,RecommendationDecision decision,Guid userId,CancellationToken ct)=>Guard("recommendation-decision",()=>database.InTenantTransactionAsync(async(c,t)=>
    {
        var status=decision.Status.ToUpperInvariant(); if(status=="REJECTED"&&string.IsNullOrWhiteSpace(decision.Reason))throw new ArgumentException("Informe o motivo da recusa."); if(userId==Guid.Empty)throw new UnauthorizedAccessException("Usuário inválido.");
        var changed=await c.ExecuteAsync("update agro360.intelligence_recommendations set status=@Status,decision_reason=@Reason,decided_by=@UserId,decided_at=now(),updated_by=@UserId,updated_at=now() where tenant_id=@TenantId and id=@Id and status='OPEN' and deleted_at is null",new{tenant.TenantId,Id=id,Status=status,Reason=decision.Reason,UserId=userId},t);
        if(changed==0)throw new KeyNotFoundException("Recomendação não encontrada ou já decidida.");
        await c.ExecuteAsync("insert into agro360.intelligence_recommendation_events(tenant_id,recommendation_id,event_type,reason,created_by,updated_by) values(@TenantId,@Id,@Status,@Reason,@UserId,@UserId)",new{tenant.TenantId,Id=id,Status=status,Reason=decision.Reason,UserId=userId},t);
    },ct));

    public Task<IntelligencePage<RiskScoreSummary>> ScoresAsync(IntelligencePageFilter filter,CancellationToken ct)=>Guard("scores",()=>database.InTenantTransactionAsync(async(c,t)=>
    {
        Validate(filter);var p=Parameters(filter);const string where="tenant_id=@TenantId and deleted_at is null and (@Search is null or entity_type ilike '%'||@Search||'%') and (@Severity is null or risk_band=@Severity) and (@Module is null or module=@Module)";var total=await c.ExecuteScalarAsync<int>($"select count(*) from agro360.intelligence_scores where {where}",p,t);var rows=(await c.QueryAsync<RiskScoreSummary>($"select id,entity_type EntityType,entity_id EntityId,module,overall_score OverallScore,risk_band RiskBand,formula_version FormulaVersion,calculated_at CalculatedAt from agro360.intelligence_scores where {where} order by overall_score desc limit @PageSize offset @Offset",p,t)).ToArray();return new IntelligencePage<RiskScoreSummary>(rows,total,filter.Page,filter.PageSize);
    },ct));
    public Task<RiskScoreDetail> ScoreAsync(Guid id,CancellationToken ct)=>Guard("score-detail",()=>database.InTenantTransactionAsync(async(c,t)=>{var score=await c.QuerySingleOrDefaultAsync<RiskScoreSummary>("select id,entity_type EntityType,entity_id EntityId,module,overall_score OverallScore,risk_band RiskBand,formula_version FormulaVersion,calculated_at CalculatedAt from agro360.intelligence_scores where tenant_id=@TenantId and id=@Id and deleted_at is null",new{tenant.TenantId,Id=id},t)??throw new KeyNotFoundException("Score não encontrado.");var factors=(await c.QueryAsync<RiskFactor>("select code,description,observed_value ObservedValue,reference_value ReferenceValue,weight,contribution,source_module SourceModule from agro360.intelligence_score_factors where tenant_id=@TenantId and score_id=@Id order by abs(contribution) desc",new{tenant.TenantId,Id=id},t)).ToArray();return new RiskScoreDetail(score,factors);},ct));
    public Task<IntelligencePage<AnomalySummary>> AnomaliesAsync(IntelligencePageFilter filter,CancellationToken ct)=>Guard("anomalies",()=>database.InTenantTransactionAsync(async(c,t)=>{Validate(filter);var p=Parameters(filter);const string where="tenant_id=@TenantId and deleted_at is null and (@Search is null or title ilike '%'||@Search||'%' or criterion ilike '%'||@Search||'%') and (@Status is null or status=@Status) and (@Severity is null or severity=@Severity) and (@Module is null or module=@Module)";var total=await c.ExecuteScalarAsync<int>($"select count(*) from agro360.intelligence_anomalies where {where}",p,t);var rows=(await c.QueryAsync<AnomalySummary>($"select id,module,type,title,criterion,observed_value ObservedValue,reference_value ReferenceValue,severity,status,entity_type EntityType,detected_at DetectedAt from agro360.intelligence_anomalies where {where} order by case severity when 'CRITICAL' then 0 when 'HIGH' then 1 else 2 end,detected_at desc limit @PageSize offset @Offset",p,t)).ToArray();return new IntelligencePage<AnomalySummary>(rows,total,filter.Page,filter.PageSize);},ct));
    public Task ArchiveAnomalyAsync(Guid id,string? reason,Guid userId,CancellationToken ct)=>Guard("archive-anomaly",()=>database.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("update agro360.intelligence_anomalies set status='ARCHIVED',archived_at=now(),updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status<>'ARCHIVED'",new{tenant.TenantId,Id=id,UserId=userId},t);if(n==0)throw new KeyNotFoundException("Anomalia não encontrada ou arquivada.");await c.ExecuteAsync("insert into agro360.intelligence_anomaly_events(tenant_id,anomaly_id,event_type,reason,created_by,updated_by) values(@TenantId,@Id,'ARCHIVED',@Reason,@UserId,@UserId)",new{tenant.TenantId,Id=id,Reason=reason,UserId=userId},t);},ct));
    public Task<IReadOnlyList<PrioritySummary>> PrioritiesAsync(CancellationToken ct)=>Guard("priorities",()=>database.InTenantTransactionAsync((c,t)=>LoadPriorities(c,t,100),ct));
    public Task<IReadOnlyList<IntelligenceRuleSummary>> RulesAsync(CancellationToken ct)=>Guard("rules",()=>database.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<IntelligenceRuleSummary>)(await c.QueryAsync<IntelligenceRuleSummary>("select id,name,description,module,type,severity,weight,active,periodicity_minutes PeriodicityMinutes,last_executed_at LastExecutedAt from agro360.intelligence_rules where tenant_id=@TenantId and deleted_at is null order by active desc,name",new{tenant.TenantId},t)).ToArray(),ct));
    public Task<Guid> SaveRuleAsync(Guid? id,IntelligenceRuleCommand command,Guid userId,CancellationToken ct)=>Guard("save-rule",()=>database.InTenantTransactionAsync(async(c,t)=>{if(string.IsNullOrWhiteSpace(command.ConditionDefinition))throw new ArgumentException("Informe a condição JSON.",nameof(command));try{using var json=JsonDocument.Parse(command.ConditionDefinition);if(json.RootElement.ValueKind!=JsonValueKind.Object)throw new ArgumentException("A condição deve ser um objeto JSON rastreável.");}catch(JsonException exception){throw new ArgumentException("A condição JSON é inválida.",nameof(command),exception);}var key=id??Guid.NewGuid();var n=await c.ExecuteAsync("insert into agro360.intelligence_rules(id,tenant_id,name,description,module,type,condition_definition,severity,weight,suggested_action,active,periodicity_minutes,required_permission,created_by,updated_by) values(@Id,@TenantId,@Name,@Description,@Module,@Type,cast(@Condition as jsonb),@Severity,@Weight,@SuggestedAction,@Active,@PeriodicityMinutes,@RequiredPermission,@UserId,@UserId) on conflict(tenant_id,id) do update set name=excluded.name,description=excluded.description,module=excluded.module,type=excluded.type,condition_definition=excluded.condition_definition,severity=excluded.severity,weight=excluded.weight,suggested_action=excluded.suggested_action,active=excluded.active,periodicity_minutes=excluded.periodicity_minutes,required_permission=excluded.required_permission,updated_by=@UserId,updated_at=now() where agro360.intelligence_rules.tenant_id=@TenantId",new{Id=key,tenant.TenantId,Name=command.Name.Trim(),command.Description,command.Module,command.Type,Condition=command.ConditionDefinition,command.Severity,command.Weight,command.SuggestedAction,command.Active,command.PeriodicityMinutes,command.RequiredPermission,UserId=userId},t);if(n==0)throw new InvalidOperationException("Regra não foi salva.");return key;},ct));

    private async Task<IReadOnlyList<PrioritySummary>> LoadPriorities(System.Data.IDbConnection c,System.Data.IDbTransaction t,int limit)=>(await c.QueryAsync<PrioritySummary>("select id,source_type SourceType,module,title,severity,priority_score PriorityScore,impact_amount ImpactAmount,due_at DueAt,action_url ActionUrl from agro360.intelligence_priority_items where tenant_id=@TenantId and status='OPEN' order by priority_score desc,due_at nulls last limit @Limit",new{tenant.TenantId,Limit=limit},t)).ToArray();
    private object Parameters(IntelligencePageFilter f)=>new{tenant.TenantId,Search=string.IsNullOrWhiteSpace(f.Search)?null:f.Search.Trim(),Status=Normalize(f.Status),Severity=Normalize(f.Severity),Module=string.IsNullOrWhiteSpace(f.Module)?null:f.Module.Trim(),f.PageSize,Offset=(f.Page-1)*f.PageSize};
    private static string? Normalize(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim().ToUpperInvariant();
    private static void Validate(IntelligencePageFilter f){if(f.Page<1||f.PageSize is <1 or >100)throw new ArgumentException("Paginação inválida.");}
    private async Task<T> Guard<T>(string operation,Func<Task<T>> work){try{return await work();}catch(Exception ex){InfrastructureLogMessages.OperationalIntelligenceFailed(logger,operation,tenant.TenantId,ex);throw;}}
    private async Task Guard(string operation,Func<Task> work){try{await work();}catch(Exception ex){InfrastructureLogMessages.OperationalIntelligenceFailed(logger,operation,tenant.TenantId,ex);throw;}}
}
