using Agro360.Application.Contracts;
using Agro360.Domain.Operations;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class OperationsService(DatabaseExecutor database, ITenantContext tenant) : IOperationsService
{
    public Task<PagedResult<SupplierDto>> ListSuppliersAsync(string? search, string? status, int page, int pageSize, CancellationToken ct) => database.InTenantTransactionAsync(async (c,t) => {
        page=Math.Max(1,page); pageSize=Math.Clamp(pageSize,1,100); var p=new {tenant.TenantId, Search=string.IsNullOrWhiteSpace(search)?null:search.Trim(), Status=string.IsNullOrWhiteSpace(status)?null:status.ToUpperInvariant(), Limit=pageSize, Offset=(page-1)*pageSize};
        using var grid=await c.QueryMultipleAsync(new CommandDefinition("select count(*) from agro360.purchasing_suppliers where tenant_id=@TenantId and deleted_at is null and (@Search is null or name ilike '%'||@Search||'%' or document_number ilike '%'||@Search||'%') and (@Status is null or status=@Status); select id, name, type, document_number Document, email, phone, categories, status, coalesce(updated_at,created_at) UpdatedAt from agro360.purchasing_suppliers where tenant_id=@TenantId and deleted_at is null and (@Search is null or name ilike '%'||@Search||'%' or document_number ilike '%'||@Search||'%') and (@Status is null or status=@Status) order by name limit @Limit offset @Offset",p,t,cancellationToken:ct));
        var total=await grid.ReadSingleAsync<long>(); return new PagedResult<SupplierDto>((await grid.ReadAsync<SupplierDto>()).ToArray(),page,pageSize,total);
    },ct);
    public Task<SupplierDto?> GetSupplierAsync(Guid id,CancellationToken ct)=>database.InTenantTransactionAsync((c,t)=>c.QuerySingleOrDefaultAsync<SupplierDto>(new CommandDefinition("select id,name,type,document_number Document,email,phone,categories,status,coalesce(updated_at,created_at) UpdatedAt from agro360.purchasing_suppliers where tenant_id=@TenantId and id=@Id and deleted_at is null",new{tenant.TenantId,Id=id},t,cancellationToken:ct)),ct);
    public Task<SupplierDto> CreateSupplierAsync(SupplierCommand command,CancellationToken ct)=>SaveSupplier(Guid.CreateVersion7(),command,false,ct);
    public Task<SupplierDto> UpdateSupplierAsync(Guid id,SupplierCommand command,CancellationToken ct)=>SaveSupplier(id,command,true,ct);
    private Task<SupplierDto> SaveSupplier(Guid id,SupplierCommand command,bool update,CancellationToken ct){
        var name=Guard.Required(command.Name,nameof(command.Name),160); var doc=Guard.Required(command.Document,nameof(command.Document),30); var status=Guard.Required(command.Status,nameof(command.Status),20).ToUpperInvariant();
        if(status is not ("ACTIVE" or "INACTIVE" or "BLOCKED")) throw new DomainException("Situação de fornecedor inválida.","supplier.status_invalid");
        return database.InTenantTransactionAsync(async(c,t)=>{ var p=new{Id=id,tenant.TenantId,Name=name,Type=command.Type.ToUpperInvariant(),Document=doc, command.StateRegistration,command.Email,command.Phone,command.Address,Categories=command.Categories.Select(v=>v.ToUpperInvariant()).ToArray(),Status=status,command.Notes,UserId=tenant.UserId};
            var affected=await c.ExecuteAsync(new CommandDefinition(update?"update agro360.purchasing_suppliers set name=@Name,type=@Type,document_number=@Document,state_registration=@StateRegistration,email=@Email,phone=@Phone,address=@Address,categories=@Categories,status=@Status,notes=@Notes,updated_at=now(),updated_by=@UserId,version=version+1 where id=@Id and tenant_id=@TenantId and deleted_at is null":"insert into agro360.purchasing_suppliers(id,tenant_id,name,type,document_number,state_registration,email,phone,address,categories,status,notes,created_by) values(@Id,@TenantId,@Name,@Type,@Document,@StateRegistration,@Email,@Phone,@Address,@Categories,@Status,@Notes,@UserId)",p,t,cancellationToken:ct));
            if(affected==0) throw new NotFoundException("Fornecedor",id); await Audit(c,t,update?"update":"create","Supplier",id,ct); return (await GetSupplierRow(c,t,id,ct))!;},ct); }
    private Task<SupplierDto?> GetSupplierRow(System.Data.Common.DbConnection c,System.Data.Common.DbTransaction t,Guid id,CancellationToken ct)=>c.QuerySingleOrDefaultAsync<SupplierDto>(new CommandDefinition("select id,name,type,document_number Document,email,phone,categories,status,coalesce(updated_at,created_at) UpdatedAt from agro360.purchasing_suppliers where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct));
    public Task DeleteSupplierAsync(Guid id,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.purchasing_suppliers set deleted_at=now(),deleted_by=@UserId where id=@Id and tenant_id=@TenantId and deleted_at is null",new{tenant.TenantId,tenant.UserId,Id=id},t,cancellationToken:ct))==0)throw new NotFoundException("Fornecedor",id);await Audit(c,t,"delete","Supplier",id,ct);},ct);

    public Task<IReadOnlyList<PurchaseDto>> ListPurchasesAsync(string? status,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<PurchaseDto>)(await c.QueryAsync<PurchaseDto>(new CommandDefinition("select id,supplier_id SupplierId,status,total,created_at CreatedAt from agro360.purchasing_purchase_orders where tenant_id=@TenantId and (@Status is null or status=@Status) order by created_at desc limit 200",new{tenant.TenantId,Status=status?.ToUpperInvariant()},t,cancellationToken:ct))).ToArray(),ct);
    public Task<PurchaseDto> CreatePurchaseAsync(PurchaseCommand command,CancellationToken ct){var total=OperationalRules.PurchaseTotal(command.Items.Select(i=>(i.Quantity,i.UnitPrice)),command.Discount,command.Freight,command.Taxes);return database.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.purchasing_purchase_orders(id,tenant_id,supplier_id,farm_id,cost_center,season_id,status,discount,freight,taxes,total,created_by) values(@Id,@TenantId,@SupplierId,@FarmId,@CostCenter,@SeasonId,'DRAFT',@Discount,@Freight,@Taxes,@Total,@UserId)",new{Id=id,tenant.TenantId,command.SupplierId,command.FarmId,command.CostCenter,command.SeasonId,command.Discount,command.Freight,command.Taxes,Total=total,tenant.UserId},t,cancellationToken:ct));foreach(var i in command.Items)await c.ExecuteAsync(new CommandDefinition("insert into agro360.purchasing_purchase_items(id,tenant_id,purchase_id,product_id,description,quantity,unit_price) values(@Id,@TenantId,@PurchaseId,@ProductId,@Description,@Quantity,@UnitPrice)",new{Id=Guid.CreateVersion7(),tenant.TenantId,PurchaseId=id,i.ProductId,i.Description,i.Quantity,i.UnitPrice},t,cancellationToken:ct));await Audit(c,t,"create","Purchase",id,ct);return new PurchaseDto(id,command.SupplierId,"DRAFT",total,DateTimeOffset.UtcNow);},ct);}
    public Task ChangePurchaseStatusAsync(Guid id,string action,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{var current=await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select status from agro360.purchasing_purchase_orders where id=@Id and tenant_id=@TenantId for update",new{Id=id,tenant.TenantId},t,cancellationToken:ct))??throw new NotFoundException("Compra",id);var next=action.ToLowerInvariant() switch{"submit" when current=="DRAFT"=>"REQUESTED","approve" when current is "REQUESTED" or "AWAITING_APPROVAL"=>"APPROVED","cancel" when current is not "RECEIVED"=>"CANCELLED",_=>throw new ConflictException("Transição de compra inválida.","purchase.transition_invalid")};await c.ExecuteAsync(new CommandDefinition("update agro360.purchasing_purchase_orders set status=@Next,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId; insert into agro360.purchasing_purchase_status_history(id,tenant_id,purchase_id,from_status,to_status,changed_by) values(@HistoryId,@TenantId,@Id,@Current,@Next,@UserId)",new{Id=id,tenant.TenantId,Next=next,Current=current,tenant.UserId,HistoryId=Guid.CreateVersion7()},t,cancellationToken:ct));await Audit(c,t,action,"Purchase",id,ct);},ct);
    public Task ReceivePurchaseAsync(Guid id,ReceiptCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{var status=await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select status from agro360.purchasing_purchase_orders where id=@Id and tenant_id=@TenantId for update",new{Id=id,tenant.TenantId},t,cancellationToken:ct))??throw new NotFoundException("Compra",id);if(status=="CANCELLED")throw new ConflictException("Pedido cancelado não pode ser recebido.","purchase.cancelled");foreach(var r in command.Items){var item=await c.QuerySingleAsync<(Guid ProductId,decimal Quantity,decimal ReceivedQuantity,decimal UnitPrice)>(new CommandDefinition("select product_id ProductId,quantity,received_quantity ReceivedQuantity,unit_price UnitPrice from agro360.purchasing_purchase_items where id=@ItemId and purchase_id=@Id and tenant_id=@TenantId for update",new{ItemId=r.PurchaseItemId,Id=id,tenant.TenantId},t,cancellationToken:ct));if(r.Quantity<=0||item.ReceivedQuantity+r.Quantity>item.Quantity) throw new DomainException("Quantidade de recebimento inválida.","purchase.receipt_invalid");await c.ExecuteAsync(new CommandDefinition("update agro360.purchasing_purchase_items set received_quantity=received_quantity+@Quantity where id=@ItemId; select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@ProductId,@Quantity,@UnitPrice,'PURCHASE_RECEIPT',@ReferenceId,@LotNumber,@ExpiresOn,@UserId)",new{r.Quantity,ItemId=r.PurchaseItemId,tenant.TenantId,r.WarehouseId,item.ProductId,item.UnitPrice,ReferenceId=id,r.LotNumber,r.ExpiresOn,tenant.UserId},t,cancellationToken:ct));}var pending=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from agro360.purchasing_purchase_items where purchase_id=@Id and tenant_id=@TenantId and received_quantity<quantity",new{Id=id,tenant.TenantId},t,cancellationToken:ct));var next=pending==0?"RECEIVED":"PARTIALLY_RECEIVED";await c.ExecuteAsync(new CommandDefinition("update agro360.purchasing_purchase_orders set status=@Next,received_at=case when @Next='RECEIVED' then now() else received_at end where id=@Id and tenant_id=@TenantId; insert into agro360.purchasing_purchase_status_history(id,tenant_id,purchase_id,from_status,to_status,changed_by) values(@HistoryId,@TenantId,@Id,@Status,@Next,@UserId)",new{Id=id,tenant.TenantId,Next=next,Status=status,HistoryId=Guid.CreateVersion7(),tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"receive","Purchase",id,ct);},ct);
    public Task<Guid> CreateInventoryItemAsync(InventoryItemCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_products(id,tenant_id,sku,name,category,base_unit,requires_lot,is_perishable,minimum_stock,created_by) values(@Id,@TenantId,@Sku,@Name,@Type,@Unit,@RequiresLot,@IsPerishable,@Minimum,@UserId)",new{Id=id,tenant.TenantId,Sku=Guard.Required(command.Sku,nameof(command.Sku),60),Name=Guard.Required(command.Name,nameof(command.Name),160),Type=command.Type.ToUpperInvariant(),Unit=command.Unit.ToLowerInvariant(),command.RequiresLot,command.IsPerishable,command.Minimum,tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"create","InventoryItem",id,ct);return id;},ct);
    public Task<Guid> MoveInventoryAsync(string type,InventoryMovementCommand command,CancellationToken ct){type=type.ToUpperInvariant();if(type is not("ENTRY" or "EXIT" or "ADJUST"))throw new DomainException("Tipo de movimento inválido.","agro360.inventory_type_invalid");if(type=="ADJUST"&&string.IsNullOrWhiteSpace(command.Reason))throw new DomainException("Ajuste exige motivo.","agro360.inventory_reason_required");if(command.Quantity<=0||command.UnitCost<0)throw new DomainException("Quantidade/custo inválido.","agro360.inventory_value_invalid");return database.InTenantTransactionAsync(async(c,t)=>{var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@ProductId,@SignedQuantity,@UnitCost,@Type,null,@LotNumber,@ExpiresOn,@UserId,@Reason)",new{tenant.TenantId,command.WarehouseId,command.ProductId,SignedQuantity=type=="ENTRY"?command.Quantity:-command.Quantity,command.UnitCost,Type=type,command.LotNumber,command.ExpiresOn,tenant.UserId,command.Reason},t,cancellationToken:ct));return id;},ct);}
    public Task TransferInventoryAsync(TransferCommand command,CancellationToken ct){if(command.SourceWarehouseId==command.DestinationWarehouseId)throw new DomainException("Origem e destino devem ser diferentes.","agro360.inventory_transfer_same_location");return database.InTenantTransactionAsync(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("select agro360.inventory_apply_stock_movement(@TenantId,@SourceWarehouseId,@ProductId,-@Quantity,0,'TRANSFER_OUT',@ReferenceId,null,null,@UserId,@Reason); select agro360.inventory_apply_stock_movement(@TenantId,@DestinationWarehouseId,@ProductId,@Quantity,0,'TRANSFER_IN',@ReferenceId,null,null,@UserId,@Reason)",new{tenant.TenantId,command.SourceWarehouseId,command.DestinationWarehouseId,command.ProductId,Quantity=Guard.Positive(command.Quantity,nameof(command.Quantity)),ReferenceId=Guid.CreateVersion7(),tenant.UserId,command.Reason},t,cancellationToken:ct));},ct);}
    public Task<IReadOnlyList<dynamic>> ListMovementsAsync(CancellationToken ct)=>ListDynamic("select id,product_id,warehouse_id,movement_type,quantity,balance_after,unit_cost,occurred_at created_at from agro360.inventory_stock_movements where tenant_id=@TenantId order by created_at desc limit 200",ct);
    public Task<Guid> CreateAssetAsync(OperationalFleetAssetCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into agro360.fleet_assets(id,tenant_id,type,brand,model,year,identification,hour_meter,odometer,farm_id,responsible_id,status,created_by) values(@Id,@TenantId,@Type,@Brand,@Model,@Year,@Identification,@HourMeter,@Odometer,@FarmId,@ResponsibleId,@Status,@UserId)",new{Id=id,tenant.TenantId,Type=command.Type.ToUpperInvariant(),command.Brand,command.Model,command.Year,Identification=Guard.Required(command.Identification,nameof(command.Identification),80),command.HourMeter,command.Odometer,command.FarmId,command.ResponsibleId,Status=command.Status.ToUpperInvariant(),tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"create","FleetAsset",id,ct);return id;},ct);
    public Task UpdateAssetAsync(Guid id,OperationalFleetAssetCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update agro360.fleet_assets set type=@Type,brand=@Brand,model=@Model,year=@Year,identification=@Identification,hour_meter=@HourMeter,odometer=@Odometer,farm_id=@FarmId,responsible_id=@ResponsibleId,status=@Status,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId",new{Id=id,tenant.TenantId,Type=command.Type.ToUpperInvariant(),command.Brand,command.Model,command.Year,command.Identification,command.HourMeter,command.Odometer,command.FarmId,command.ResponsibleId,Status=command.Status.ToUpperInvariant(),tenant.UserId},t,cancellationToken:ct))==0)throw new NotFoundException("Máquina",id);await Audit(c,t,"update","FleetAsset",id,ct);},ct);
    public Task<IReadOnlyList<dynamic>> ListAssetsAsync(CancellationToken ct)=>ListDynamic("select id,type,brand,model,year,identification,hour_meter,odometer,status,farm_id from agro360.fleet_assets where tenant_id=@TenantId and deleted_at is null order by identification",ct);
    public Task<Guid> CreateMaintenanceAsync(MaintenanceOrderCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();var parts=command.Parts.Sum(p=>p.Quantity*p.UnitCost);var total=OperationalRules.MaintenanceTotal(parts,command.LaborCost);await c.ExecuteAsync(new CommandDefinition("insert into agro360.fleet_maintenance_orders(id,tenant_id,asset_id,type,description,supplier_id,responsible_id,status,scheduled_for,next_review_date,next_hour_meter,next_odometer,parts_cost,labor_cost,total_cost,created_by) values(@Id,@TenantId,@AssetId,@Type,@Description,@SupplierId,@ResponsibleId,'OPEN',@ScheduledFor,@NextReviewDate,@NextHourMeter,@NextOdometer,@PartsCost,@LaborCost,@TotalCost,@UserId); update agro360.fleet_assets set status='IN_MAINTENANCE' where id=@AssetId and tenant_id=@TenantId",new{Id=id,tenant.TenantId,command.AssetId,Type=command.Type.ToUpperInvariant(),Description=Guard.Required(command.Description,nameof(command.Description),500),command.SupplierId,command.ResponsibleId,command.ScheduledFor,command.NextReviewDate,command.NextHourMeter,command.NextOdometer,PartsCost=parts,command.LaborCost,TotalCost=total,tenant.UserId},t,cancellationToken:ct));foreach(var p in command.Parts){await c.ExecuteAsync(new CommandDefinition("insert into agro360.fleet_maintenance_parts(id,tenant_id,maintenance_id,product_id,warehouse_id,quantity,unit_cost) values(@PartId,@TenantId,@Id,@ProductId,@WarehouseId,@Quantity,@UnitCost); select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@ProductId,-@Quantity,@UnitCost,'MAINTENANCE',@Id,null,null,@UserId,'Peça utilizada em manutenção')",new{PartId=Guid.CreateVersion7(),tenant.TenantId,Id=id,p.ProductId,p.WarehouseId,Quantity=Guard.Positive(p.Quantity,nameof(p.Quantity)),p.UnitCost,tenant.UserId},t,cancellationToken:ct));}await Audit(c,t,"create","Maintenance",id,ct);return id;},ct);
    public Task CompleteMaintenanceAsync(Guid id,CompleteMaintenanceCommand command,CancellationToken ct){if(string.IsNullOrWhiteSpace(command.CompletionNotes))throw new DomainException("A conclusão deve ser informada.","maintenance.completion_required");return database.InTenantTransactionAsync(async(c,t)=>{var asset=await c.QuerySingleOrDefaultAsync<Guid?>(new CommandDefinition("update agro360.fleet_maintenance_orders set status='COMPLETED',completed_at=@CompletedAt,completion_notes=@CompletionNotes,updated_by=@UserId,updated_at=now() where id=@Id and tenant_id=@TenantId and status<>'COMPLETED' returning asset_id",new{Id=id,tenant.TenantId,command.CompletedAt,command.CompletionNotes,tenant.UserId},t,cancellationToken:ct))??throw new NotFoundException("Manutenção",id);await c.ExecuteAsync(new CommandDefinition("update agro360.fleet_assets set status=@Status,updated_at=now() where id=@AssetId and tenant_id=@TenantId",new{AssetId=asset,tenant.TenantId,Status=command.AssetFinalStatus.ToUpperInvariant()},t,cancellationToken:ct));await Audit(c,t,"complete","Maintenance",id,ct);},ct);}
    public Task<IReadOnlyList<dynamic>> ListMaintenanceAsync(CancellationToken ct)=>ListDynamic("select m.id,m.asset_id,m.type,m.description,m.status,m.scheduled_for,m.completed_at,m.total_cost,a.identification from agro360.fleet_maintenance_orders m join agro360.fleet_assets a on a.id=m.asset_id and a.tenant_id=m.tenant_id where m.tenant_id=@TenantId order by m.created_at desc limit 200",ct);
    public Task<Guid> CreateFillUpAsync(FuelFillUpCommand command,CancellationToken ct){var total=OperationalRules.FuelTotal(command.Quantity,command.UnitPrice);return database.InTenantTransactionAsync(async(c,t)=>{var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@FuelProductId,-@Quantity,@UnitPrice,'FUEL',@Id,null,null,@UserId,'Abastecimento'); insert into agro360.fleet_fuel_fillups(id,tenant_id,asset_id,fuel_product_id,warehouse_id,quantity,unit_price,total,hour_meter,odometer,responsible_id,location,created_by) values(@Id,@TenantId,@AssetId,@FuelProductId,@WarehouseId,@Quantity,@UnitPrice,@Total,@HourMeter,@Odometer,@ResponsibleId,@Location,@UserId); update agro360.fleet_assets set hour_meter=coalesce(@HourMeter,hour_meter),odometer=coalesce(@Odometer,odometer) where id=@AssetId and tenant_id=@TenantId",new{Id=id,tenant.TenantId,command.AssetId,command.FuelProductId,command.WarehouseId,command.Quantity,command.UnitPrice,Total=total,command.HourMeter,command.Odometer,command.ResponsibleId,command.Location,tenant.UserId},t,cancellationToken:ct));await Audit(c,t,"create","FuelFillUp",id,ct);return id;},ct);}
    public Task<IReadOnlyList<dynamic>> ListFillUpsAsync(CancellationToken ct)=>ListDynamic("select f.id,f.asset_id,a.identification,f.quantity,f.unit_price,f.total,f.hour_meter,f.odometer,f.location,f.created_at from agro360.fleet_fuel_fillups f join agro360.fleet_assets a on a.id=f.asset_id and a.tenant_id=f.tenant_id where f.tenant_id=@TenantId order by f.created_at desc limit 200",ct);
    public Task<OperationalDashboardDto> DashboardAsync(CancellationToken ct)=>database.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<OperationalDashboardDto>(new CommandDefinition("""
select
 (select count(*) from agro360.purchasing_suppliers where tenant_id=@TenantId and status='ACTIVE' and deleted_at is null) ActiveSuppliers,
 (select count(*) from agro360.purchasing_purchase_orders where tenant_id=@TenantId and status not in ('RECEIVED','CANCELLED')) OpenPurchases,
 (select count(*) from agro360.purchasing_purchase_orders where tenant_id=@TenantId and status='AWAITING_APPROVAL') AwaitingApproval,
 (select count(*) from agro360.purchasing_purchase_orders where tenant_id=@TenantId and status='RECEIVED' and received_at>=date_trunc('month',now())) ReceivedThisMonth,
 (select coalesce(sum(total),0) from agro360.purchasing_purchase_orders where tenant_id=@TenantId and status='RECEIVED' and received_at>=date_trunc('month',now())) PurchasedThisMonth,
 (select count(*) from agro360.inventory_stock_balances where tenant_id=@TenantId and available<minimum) LowStockItems,
 (select count(*) from agro360.inventory_stock_lots where tenant_id=@TenantId and expires_on<=current_date+30 and quantity>0) ExpiringItems,
 (select count(*) from agro360.fleet_assets where tenant_id=@TenantId and status='AVAILABLE' and deleted_at is null) AvailableAssets,
 (select count(*) from agro360.fleet_assets where tenant_id=@TenantId and status='IN_MAINTENANCE' and deleted_at is null) AssetsInMaintenance,
 (select count(*) from agro360.fleet_maintenance_orders where tenant_id=@TenantId and status<>'COMPLETED' and scheduled_for<current_date) OverdueMaintenance,
 (select coalesce(sum(total_cost),0) from agro360.fleet_maintenance_orders where tenant_id=@TenantId and completed_at>=date_trunc('month',now())) MaintenanceCostThisMonth,
 (select coalesce(sum(quantity),0) from agro360.fleet_fuel_fillups where tenant_id=@TenantId and created_at>=date_trunc('month',now())) FuelThisMonth
""",new{tenant.TenantId},t,cancellationToken:ct)),ct);
    private Task<IReadOnlyList<dynamic>> ListDynamic(string sql,CancellationToken ct)=>database.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<dynamic>)(await c.QueryAsync(new CommandDefinition(sql,new{tenant.TenantId},t,cancellationToken:ct))).ToArray(),ct);
    private Task<int> Audit(System.Data.Common.DbConnection c,System.Data.Common.DbTransaction t,string action,string entity,Guid id,CancellationToken ct)=>c.ExecuteAsync(new CommandDefinition("insert into agro360.audit_logs(id,tenant_id,user_id,action,entity_type,entity_id,occurred_at) values(@AuditId,@TenantId,@UserId,@Action,@Entity,@Id,now())",new{AuditId=Guid.CreateVersion7(),tenant.TenantId,tenant.UserId,Action=action,Entity=entity,Id=id},t,cancellationToken:ct));
}
