using System.Security.Cryptography;
using System.Text;
using Agro360.Application;
using Agro360.Application.Abstractions;
using Agro360.Application.Contracts;
using Agro360.Domain.Portal;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;

namespace Agro360.Infrastructure.Services;

public sealed class PortalService(DatabaseExecutor db,ITenantContext tenant,IClock clock,IPasswordHasher passwords,ITokenService tokens,ILogger<PortalService> logger):IPortalService
{
 public Task<IReadOnlyList<PortalInvitationRow>> InvitationsAsync(string? status,CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<PortalInvitationRow>)(await c.QueryAsync<PortalInvitationRow>(new CommandDefinition("select i.id,i.name,i.email,p.code profile,i.entity_type entitytype,i.entity_label entitylabel,case when i.revoked_at is not null then 'REVOKED' when i.accepted_at is not null then 'ACCEPTED' when i.expires_at<=now() then 'EXPIRED' else 'PENDING' end status,i.expires_at expiresat,i.created_at createdat from portal.portal_invitations i join portal.portal_profiles p on p.id=i.profile_id and p.tenant_id=i.tenant_id where i.tenant_id=@TenantId and (@Status is null or case when i.revoked_at is not null then 'REVOKED' when i.accepted_at is not null then 'ACCEPTED' when i.expires_at<=now() then 'EXPIRED' else 'PENDING' end=@Status) order by i.created_at desc",new{tenant.TenantId,Status=status?.Trim().ToUpperInvariant()},t,cancellationToken:ct))).ToArray(),ct);
 public Task<PortalInvitationCreated> InviteAsync(PortalInvitationCommand x,CancellationToken ct)
 {
  var email=PortalRules.Email(x.Email);var profile=PortalRules.Profile(x.Profile);if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Trim().Length>160)throw new DomainException("Informe o nome do convidado.","portal.name");if(x.EntityId==Guid.Empty||string.IsNullOrWhiteSpace(x.EntityType))throw new DomainException("Selecione a entidade vinculada.","portal.entity");if(x.ExpiresAt<=clock.UtcNow||x.ExpiresAt>clock.UtcNow.AddDays(30))throw new DomainException("A validade deve estar entre agora e 30 dias.","portal.expiry");
  return Tx(async(c,t)=>{var raw=Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(RandomNumberGenerator.GetBytes(48));var hash=Hash(raw);var id=Guid.CreateVersion7();var profileId=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from portal.portal_profiles where tenant_id=@TenantId and code=@Profile and active",new{tenant.TenantId,Profile=profile},t,cancellationToken:ct))??throw new DomainException("Perfil externo ainda não foi homologado para esta organização.","portal.profile");await c.ExecuteAsync(new CommandDefinition("insert into portal.portal_invitations(id,tenant_id,profile_id,name,email,entity_type,entity_id,entity_label,token_hash,expires_at,created_by,updated_by) values(@Id,@TenantId,@ProfileId,@Name,@Email,@EntityType,@EntityId,@EntityLabel,@Hash,@ExpiresAt,@UserId,@UserId);insert into platform.outbox_messages(id,tenant_id,event_type,aggregate_id,payload,occurred_at) values(gen_random_uuid(),@TenantId,'PortalInvitationRequested',@Id,jsonb_build_object('invitationId',@Id,'email',@Email),now())",new{Id=id,tenant.TenantId,ProfileId,Name=x.Name.Trim(),Email=email,EntityType=x.EntityType.Trim().ToUpperInvariant(),x.EntityId,EntityLabel=x.EntityType.Trim(),Hash,x.ExpiresAt,tenant.UserId},t,cancellationToken:ct));logger.LogInformation("Convite externo {InvitationId} registrado para o tenant {TenantId}; entrega delegada à outbox",id,tenant.TenantId);return new PortalInvitationCreated(id,raw,x.ExpiresAt);},ct);
 }
 public Task RevokeInvitationAsync(Guid id,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo da revogação.","portal.revoke.reason");return Tx(async(c,t)=>{if(await c.ExecuteAsync(new CommandDefinition("update portal.portal_invitations set revoked_at=now(),revoked_by=@UserId,revoke_reason=@Reason,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId and accepted_at is null and revoked_at is null",new{Id=id,tenant.TenantId,tenant.UserId,Reason=reason.Trim()},t,cancellationToken:ct))==0)throw new ConflictException("Convite inexistente ou não pode mais ser revogado.");},ct);}
 public Task<PortalAuthentication> AcceptInvitationAsync(AcceptPortalInvitationCommand x,CancellationToken ct)
 {
  if(!x.AcceptTerms)throw new DomainException("Você precisa aceitar os termos para continuar.","portal.terms");if(string.IsNullOrWhiteSpace(x.Token))throw new DomainException("O link de convite é inválido.","portal.invitation.token");var hash=Hash(x.Token);
  return db.InSystemTransactionAsync(async(c,t)=>{var row=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select i.id,i.tenant_id,i.name,i.email,i.entity_type,i.entity_id,i.expires_at,i.revoked_at,i.accepted_at,p.id profile_id,p.code profile from portal.portal_invitations i join portal.portal_profiles p on p.id=i.profile_id and p.tenant_id=i.tenant_id where i.token_hash=@Hash for update",new{Hash=hash},t,cancellationToken:ct))??throw new NotFoundException("Convite",Guid.Empty);PortalRules.Invitation(row.expires_at,clock.UtcNow,row.revoked_at,row.accepted_at);var userId=Guid.CreateVersion7();var passwordHash=passwords.Hash(x.Password);await c.ExecuteAsync(new CommandDefinition("insert into portal.portal_external_users(id,tenant_id,profile_id,name,email,password_hash,status,terms_accepted_at,last_login_at,created_by,updated_by) values(@UserId,@TenantId,@ProfileId,@Name,@Email,@PasswordHash,'ACTIVE',now(),now(),@UserId,@UserId);insert into portal.portal_external_user_links(id,tenant_id,external_user_id,entity_type,entity_id,created_by,updated_by) values(gen_random_uuid(),@TenantId,@UserId,@EntityType,@EntityId,@UserId,@UserId);insert into portal.portal_terms_acceptances(id,tenant_id,external_user_id,term_id,accepted_at,created_by,updated_by) select gen_random_uuid(),@TenantId,@UserId,id,now(),@UserId,@UserId from portal.portal_terms where tenant_id=@TenantId and active order by version desc limit 1;update portal.portal_invitations set accepted_at=now(),accepted_user_id=@UserId,updated_at=now(),updated_by=@UserId where id=@Id",new{Id=(Guid)row.id,UserId=userId,TenantId=(Guid)row.tenant_id,ProfileId=(Guid)row.profile_id,Name=(string)row.name,Email=(string)row.email,PasswordHash,EntityType=(string)row.entity_type,EntityId=(Guid)row.entity_id},t,cancellationToken:ct));return Auth((Guid)row.tenant_id,userId,(string)row.name,(string)row.email,(string)row.profile);},ct);
 }
 public Task<PortalAuthentication> LoginAsync(PortalLoginCommand x,CancellationToken ct)=>db.InSystemTransactionAsync(async(c,t)=>{var email=PortalRules.Email(x.Email);var row=await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select u.id,u.tenant_id,u.name,u.email,u.password_hash,p.code profile from portal.portal_external_users u join portal.portal_profiles p on p.id=u.profile_id and p.tenant_id=u.tenant_id join tenancy.tenants tn on tn.id=u.tenant_id where tn.slug=@Slug and u.email=@Email and u.status='ACTIVE' and u.deleted_at is null",new{Slug=x.TenantSlug.Trim().ToLowerInvariant(),Email=email},t,cancellationToken:ct));if(row is null||!passwords.Verify(x.Password,(string)row.password_hash))throw new ForbiddenException("E-mail, organização ou senha inválidos.");await c.ExecuteAsync(new CommandDefinition("update portal.portal_external_users set last_login_at=now(),updated_at=now() where id=@Id and tenant_id=@TenantId",new{Id=(Guid)row.id,TenantId=(Guid)row.tenant_id},t,cancellationToken:ct));return Auth((Guid)row.tenant_id,(Guid)row.id,(string)row.name,(string)row.email,(string)row.profile);},ct);
 public Task<PortalDashboard> DashboardAsync(CancellationToken ct)=>Tx(async(c,t)=>{var user=await User(c,t,ct);var announcements=(await c.QueryAsync<PortalAnnouncement>(new CommandDefinition("select a.id,a.title,a.summary,a.severity,a.published_at publishedat,(r.id is not null) read from portal.portal_announcements a left join portal.portal_announcement_reads r on r.announcement_id=a.id and r.external_user_id=@UserId and r.tenant_id=a.tenant_id where a.tenant_id=@TenantId and a.status='PUBLISHED' and a.published_at<=now() and (a.expires_at is null or a.expires_at>now()) and (a.audience='ALL' or a.audience=@Profile) order by a.published_at desc limit 8",new{tenant.TenantId,tenant.UserId,Profile=(string)user.profile},t,cancellationToken:ct))).ToArray();var metrics=new[]{new PortalMetric("requests","Solicitações abertas",await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from portal.portal_requests where tenant_id=@TenantId and external_user_id=@UserId and status in ('OPEN','IN_REVIEW','WAITING_RESPONSE')",new{tenant.TenantId,tenant.UserId},t,cancellationToken:ct)),"/Portal/Requests"),new PortalMetric("quotes","Cotações em andamento",await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*) from portal.marketplace_quote_requests where tenant_id=@TenantId and external_user_id=@UserId and status not in ('CANCELLED','CONVERTED','REJECTED')",new{tenant.TenantId,tenant.UserId},t,cancellationToken:ct)),"/Portal/Marketplace")};return new PortalDashboard((string)user.name,(string)user.profile,metrics,announcements,Array.Empty<PortalActivity>());},ct);
 public Task<IReadOnlyList<MarketplaceListing>> MarketplaceAsync(MarketplaceFilter f,CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<MarketplaceListing>)(await c.QueryAsync<MarketplaceListing>(new CommandDefinition("select l.id,l.product_name product,l.crop,l.harvest,l.region,l.unit,l.available_quantity availablequantity,l.unit_price unitprice,l.commercial_terms commercialterms,coalesce(array_agg(c.name) filter(where c.name is not null),'{}') certifications from portal.marketplace_listings l left join portal.marketplace_listing_certificates lc on lc.listing_id=l.id and lc.tenant_id=l.tenant_id left join documents.certificates c on c.id=lc.certificate_id and c.tenant_id=l.tenant_id and c.status='ISSUED' where l.tenant_id=@TenantId and l.status='AVAILABLE' and l.available_quantity>0 and (@Search is null or l.product_name ilike '%'||@Search||'%') and (@Crop is null or l.crop=@Crop) and (@Region is null or l.region=@Region) and (@Unit is null or l.unit=@Unit) and (@MaximumPrice is null or l.unit_price<=@MaximumPrice) group by l.id order by l.product_name",new{tenant.TenantId,Search=Clean(f.Search),Crop=Clean(f.Crop),Region=Clean(f.Region),Unit=Clean(f.Unit),f.MaximumPrice},t,cancellationToken:ct))).ToArray(),ct);
 public Task<Guid> RequestQuoteAsync(CreateQuoteCommand x,CancellationToken ct){PortalRules.Quote(x.Items.Select(i=>(i.ListingId,i.Quantity)).ToArray());var email=PortalRules.Email(x.ContactEmail);return Tx(async(c,t)=>{await User(c,t,ct);var id=Guid.CreateVersion7();var args=new{Id=id,tenant.TenantId,tenant.UserId,x.ContactName,Email=email,x.Notes,ListingIds=x.Items.Select(i=>i.ListingId).ToArray(),Quantities=x.Items.Select(i=>i.Quantity).ToArray()};await c.ExecuteAsync(new CommandDefinition("insert into portal.marketplace_quote_requests(id,tenant_id,external_user_id,protocol,contact_name,contact_email,notes,status,created_by,updated_by) values(@Id,@TenantId,@UserId,'COT-'||to_char(now(),'YYYYMMDD')||'-'||upper(substr(replace(@Id::text,'-',''),1,6)),@ContactName,@Email,@Notes,'REQUESTED',@UserId,@UserId)",args,t,cancellationToken:ct));var inserted=await c.ExecuteAsync(new CommandDefinition("insert into portal.marketplace_quote_request_items(id,tenant_id,quote_request_id,listing_id,quantity,unit,created_by,updated_by) select gen_random_uuid(),@TenantId,@Id,x.listing_id,x.quantity,l.unit,@UserId,@UserId from unnest(@ListingIds::uuid[],@Quantities::numeric[]) x(listing_id,quantity) join portal.marketplace_listings l on l.id=x.listing_id and l.tenant_id=@TenantId and l.status='AVAILABLE' and l.available_quantity>=x.quantity",args,t,cancellationToken:ct));if(inserted!=x.Items.Count)throw new DomainException("Um item não está mais disponível na quantidade solicitada.","portal.quote.availability");return id;},ct);}
 public Task<IReadOnlyList<PortalRequestRow>> RequestsAsync(CancellationToken ct)=>Tx(async(c,t)=>(IReadOnlyList<PortalRequestRow>)(await c.QueryAsync<PortalRequestRow>(new CommandDefinition("select id,protocol,type,subject,status,priority,created_at createdat,updated_at updatedat from portal.portal_requests where tenant_id=@TenantId and external_user_id=@UserId and deleted_at is null order by updated_at desc",new{tenant.TenantId,tenant.UserId},t,cancellationToken:ct))).ToArray(),ct);
 public Task<Guid> CreateRequestAsync(PortalRequestCommand x,CancellationToken ct){PortalRules.Request(x.Subject,x.Description);return Tx(async(c,t)=>{await User(c,t,ct);var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into portal.portal_requests(id,tenant_id,external_user_id,protocol,type,subject,description,status,priority,created_by,updated_by) values(@Id,@TenantId,@UserId,'SOL-'||to_char(now(),'YYYYMMDD')||'-'||upper(substr(replace(@Id::text,'-',''),1,6)),@Type,@Subject,@Description,'OPEN',@Priority,@UserId,@UserId);insert into portal.portal_request_events(id,tenant_id,request_id,event_type,message,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,'CREATED','Solicitação aberta pelo portal',@UserId,@UserId);insert into platform.outbox_messages(id,tenant_id,event_type,aggregate_id,payload,occurred_at) values(gen_random_uuid(),@TenantId,'PortalRequestCreated',@Id,jsonb_build_object('requestId',@Id,'priority',@Priority),now())",new{Id=id,tenant.TenantId,tenant.UserId,Type=x.Type.Trim().ToUpperInvariant(),Subject=x.Subject.Trim(),Description=x.Description.Trim(),Priority=x.Priority.Trim().ToUpperInvariant()},t,cancellationToken:ct));return id;},ct);}
 public Task MarkAnnouncementReadAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("insert into portal.portal_announcement_reads(id,tenant_id,announcement_id,external_user_id,read_at,created_by,updated_by) select gen_random_uuid(),@TenantId,@Id,@UserId,now(),@UserId,@UserId where exists(select 1 from portal.portal_announcements where id=@Id and tenant_id=@TenantId and status='PUBLISHED') on conflict(tenant_id,announcement_id,external_user_id) do nothing",new{Id=id,tenant.TenantId,tenant.UserId},t,cancellationToken:ct));},ct);
 private PortalAuthentication Auth(Guid tenantId,Guid userId,string name,string email,string profile){var pair=tokens.Create(tenantId,userId,email,[Permissions.PortalAccess,$"portal.profile.{profile.ToLowerInvariant()}"]);return new(tenantId,userId,name,profile,pair.AccessToken,pair.RefreshToken,pair.ExpiresAt);}
 private async Task<dynamic> User(Npgsql.NpgsqlConnection c,Npgsql.NpgsqlTransaction t,CancellationToken ct)=>await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select u.name,p.code profile from portal.portal_external_users u join portal.portal_profiles p on p.id=u.profile_id and p.tenant_id=u.tenant_id where u.id=@UserId and u.tenant_id=@TenantId and u.status='ACTIVE' and u.deleted_at is null",new{tenant.TenantId,tenant.UserId},t,cancellationToken:ct))??throw new ForbiddenException("Acesso externo não autorizado.");
 private Task<T> Tx<T>(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task<T>> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);private Task Tx(Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);
 private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();private static string? Clean(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
}
