using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Agro360.Application.Contracts;
using Agro360.Domain.Procurement;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class ProcurementService(
    DatabaseExecutor db,
    ITenantContext tenant,
    ILogger<ProcurementService> logger,
    IOperationalInspectionTrigger inspectionTrigger) : IProcurementService
{
    public Task<dynamic> DashboardAsync(CancellationToken ct) => Tx(async (c, t) => await c.QuerySingleAsync(new CommandDefinition("select count(*) filter(where status='OPEN') requisitions_open,count(*) filter(where status='OPEN' and priority='URGENT') requisitions_urgent,(select count(*) from agro360.procurement_quotations where tenant_id=@TenantId and status in('SENT','PARTIAL','RESPONDED','ANALYSIS')) quotations_running,(select count(*) from agro360.procurement_purchase_orders where tenant_id=@TenantId and status='AWAITING_APPROVAL') orders_awaiting_approval,(select count(*) from agro360.procurement_purchase_orders where tenant_id=@TenantId and status='PARTIALLY_RECEIVED') orders_partially_received,(select count(*) from agro360.procurement_receipts where tenant_id=@TenantId and status='DIVERGENT') divergent_receipts,(select count(*) from agro360.procurement_suppliers where tenant_id=@TenantId and status in('ACTIVE','APPROVED')) active_suppliers,(select count(*) from agro360.procurement_suppliers where tenant_id=@TenantId and status='BLOCKED') blocked_suppliers,(select coalesce(sum(total),0) from agro360.procurement_purchase_orders where tenant_id=@TenantId and status not in('DRAFT','CANCELLED') and approved_at>=date_trunc('month',now())) purchased_month from agro360.procurement_requisitions where tenant_id=@TenantId", new { tenant.TenantId }, t, cancellationToken: ct)));
    public Task<IReadOnlyList<dynamic>> SuppliersAsync(ProcurementQuery q, CancellationToken ct) => List("select * from agro360.procurement_suppliers where tenant_id=@TenantId and deleted_at is null and (@Search is null or legal_name ilike '%'||@Search||'%' or trade_name ilike '%'||@Search||'%') and (@Status is null or status=@Status) and (@Category is null or main_category=@Category) order by legal_name limit @Take offset @Skip", q, ct);
    public Task<Guid> SaveSupplierAsync(Guid? id, ProcurementSupplierCommand x, CancellationToken ct)
    {
        ProcurementRules.Supplier(x.LegalName, x.Email, x.Status, x.RejectionReason); if (x.AverageDeliveryDays < 0) throw new DomainException("Prazo médio inválido.", "agro360.procurement_delivery_invalid");
        return Tx(async (c, t) => { var key = id ?? Guid.CreateVersion7(); var p = new DynamicParameters(x); p.Add("Id", key); p.Add("TenantId", tenant.TenantId); p.Add("UserId", tenant.UserId); var sql = id is null ? "insert into agro360.procurement_suppliers(id,tenant_id,legal_name,trade_name,tax_document,state_registration,supplier_type,main_category,email,phone,address,city,state,country,main_contact,payment_terms,average_delivery_days,status,rejection_reason,notes,tags,created_by,updated_by) values(@Id,@TenantId,@LegalName,@TradeName,nullif(regexp_replace(coalesce(@TaxDocument,''),'[^0-9]','','g'),''),@StateRegistration,@Type,@Category,@Email,@Phone,@Address,@City,@State,@Country,@MainContact,@PaymentTerms,@AverageDeliveryDays,@Status,@RejectionReason,@Notes,@Tags,@UserId,@UserId)" : "update agro360.procurement_suppliers set legal_name=@LegalName,trade_name=@TradeName,tax_document=nullif(regexp_replace(coalesce(@TaxDocument,''),'[^0-9]','','g'),''),state_registration=@StateRegistration,supplier_type=@Type,main_category=@Category,email=@Email,phone=@Phone,address=@Address,city=@City,state=@State,country=@Country,main_contact=@MainContact,payment_terms=@PaymentTerms,average_delivery_days=@AverageDeliveryDays,status=@Status,rejection_reason=@RejectionReason,notes=@Notes,tags=@Tags,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and deleted_at is null"; if (await c.ExecuteAsync(new CommandDefinition(sql, p, t, cancellationToken: ct)) == 0) throw new NotFoundException("Fornecedor", key); await Audit(c, t, "SUPPLIER", key, id is null ? "CREATED" : "UPDATED", x, ct); return key; });
    }
    public Task HomologateAsync(Guid supplierId, bool approve, HomologationCommand x, CancellationToken ct)
    {
        if (!approve && string.IsNullOrWhiteSpace(x.Reason)) throw new DomainException("Reprovação exige motivo.", "agro360.procurement_rejection_reason_required"); if (approve && x.ValidUntil <= DateOnly.FromDateTime(DateTime.UtcNow)) throw new DomainException("Validade deve ser futura.", "agro360.procurement_homologation_validity_invalid");
        return Tx(async (c, t) => { if (!await Exists(c, t, "suppliers", supplierId, ct)) throw new NotFoundException("Fornecedor", supplierId); var status = approve ? "APPROVED" : "REJECTED"; await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_supplier_homologations(id,tenant_id,supplier_id,status,valid_until,criteria,reason,decided_at,decided_by,created_by,updated_by) values(@Id,@TenantId,@SupplierId,@Status,@ValidUntil,jsonb_build_object('fiscal',@Fiscal,'sanitary',@Sanitary,'environmental',@Environmental,'certifications',@Certifications,'deliveryCapacity',@DeliveryCapacity,'qualityHistory',@QualityHistory,'commercial',@Commercial,'compliance',@Compliance,'operationalRisk',@OperationalRisk),@Reason,now(),@UserId,@UserId,@UserId);update agro360.procurement_suppliers set status=@Status,homologated_at=case when @Status='APPROVED' then now() end,homologated_by=case when @Status='APPROVED' then @UserId end,rejection_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@SupplierId", new { Id = Guid.CreateVersion7(), tenant.TenantId, SupplierId = supplierId, Status = status, x.ValidUntil, x.Fiscal, x.Sanitary, x.Environmental, x.Certifications, x.DeliveryCapacity, x.QualityHistory, x.Commercial, x.Compliance, x.OperationalRisk, x.Reason, tenant.UserId }, t, cancellationToken: ct)); await Audit(c, t, "SUPPLIER", supplierId, status, x, ct); });
    }
    public Task<IReadOnlyList<dynamic>> CatalogAsync(ProcurementQuery q, CancellationToken ct) => List("select * from agro360.procurement_item_catalog where tenant_id=@TenantId and deleted_at is null and (@Search is null or name ilike '%'||@Search||'%' or internal_code ilike '%'||@Search||'%') and (@Category is null or category=@Category) and (@Status is null or (@Status='ACTIVE' and active) or (@Status='INACTIVE' and not active)) order by name limit @Take offset @Skip", q, ct);
    public Task<Guid> SaveCatalogItemAsync(Guid? id, CatalogItemCommand x, CancellationToken ct) => Tx(async (c, t) =>
    {
        if (string.IsNullOrWhiteSpace(x.Name) || string.IsNullOrWhiteSpace(x.Code) || string.IsNullOrWhiteSpace(x.Category) || string.IsNullOrWhiteSpace(x.Unit)) throw new DomainException("Nome, código, categoria e unidade são obrigatórios.", "agro360.procurement_catalog_required");
        if (x.MinimumStock < 0) throw new DomainException("Estoque mínimo inválido.", "agro360.procurement_minimum_stock_invalid");
        if (x.Type is not "SERVICE" && x.RelatedProductId is null) throw new DomainException("Materiais e ativos devem estar vinculados a um produto de estoque.", "agro360.procurement_stock_product_required");
        if (x.RelatedProductId is not null && !await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.inventory_products where tenant_id=@TenantId and id=@ProductId and deleted_at is null)", new { tenant.TenantId, ProductId = x.RelatedProductId }, t, cancellationToken: ct))) throw new DomainException("Produto de estoque inexistente ou inativo.", "agro360.procurement_stock_product_invalid");
        var key = id ?? Guid.CreateVersion7();
        var p = new DynamicParameters(x);
        p.Add("Id", key); p.Add("TenantId", tenant.TenantId); p.Add("UserId", tenant.UserId);
        var sql = id is null
            ? "insert into agro360.procurement_item_catalog(id,tenant_id,name,internal_code,category,unit,item_type,description,active,minimum_stock,cost_center_id,related_product_id,requires_lot,requires_expiry,requires_document,requires_inspection,requires_approved_supplier,notes,created_by,updated_by) values(@Id,@TenantId,@Name,@Code,@Category,@Unit,@Type,@Description,@Active,@MinimumStock,@CostCenterId,@RelatedProductId,@RequiresLot,@RequiresExpiry,@RequiresDocument,@RequiresInspection,@RequiresApprovedSupplier,@Notes,@UserId,@UserId)"
            : "update agro360.procurement_item_catalog set name=@Name,internal_code=@Code,category=@Category,unit=@Unit,item_type=@Type,description=@Description,active=@Active,minimum_stock=@MinimumStock,cost_center_id=@CostCenterId,related_product_id=@RelatedProductId,requires_lot=@RequiresLot,requires_expiry=@RequiresExpiry,requires_document=@RequiresDocument,requires_inspection=@RequiresInspection,requires_approved_supplier=@RequiresApprovedSupplier,notes=@Notes,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id";
        if (await c.ExecuteAsync(new CommandDefinition(sql, p, t, cancellationToken: ct)) == 0) throw new NotFoundException("Item", key);
        return key;
    });
    public Task<Guid> CreateRequisitionAsync(RequisitionCommand x, CancellationToken ct)
    {
        ProcurementRules.Requisition(x.Priority, x.NeededOn, x.Items.Count, x.Justification); if (x.Items.Any(i => i.Quantity <= 0)) throw new DomainException("Quantidades devem ser positivas.", "agro360.procurement_quantity_invalid");
        return Tx(async (c, t) => {
            if (x.CostCenterId is not null && !await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.finance_cost_centers where tenant_id=@TenantId and id=@Id and active and deleted_at is null)", new { tenant.TenantId, Id = x.CostCenterId }, t, cancellationToken: ct))) throw new DomainException("Centro de custo inexistente ou inativo.", "agro360.procurement_cost_center_invalid");
            if (x.PropertyId is not null && !await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.geo_farms where tenant_id=@TenantId and id=@Id and deleted_at is null)", new { tenant.TenantId, Id = x.PropertyId }, t, cancellationToken: ct))) throw new DomainException("Unidade operacional inexistente.", "agro360.procurement_property_invalid");
            foreach (var line in x.Items) { var unit = await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select unit from agro360.procurement_item_catalog where tenant_id=@TenantId and id=@Id and active and deleted_at is null", new { tenant.TenantId, Id = line.CatalogItemId }, t, cancellationToken: ct)); if (unit is null) throw new DomainException("Item inexistente ou inativo.", "agro360.procurement_item_inactive"); if (!unit.Equals(line.Unit.Trim(), StringComparison.OrdinalIgnoreCase)) throw new DomainException("A unidade deve ser igual à unidade cadastrada; conversões precisam ser explícitas.", "agro360.procurement_unit_mismatch"); }
            var id = Guid.CreateVersion7(); var number = await Number(c, t, "REQ", ct); var status = x.Submit ? "AWAITING_APPROVAL" : "DRAFT";
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_requisitions(id,tenant_id,number,requester_id,origin,cost_center_id,property_id,justification,priority,needed_on,status,version,created_by,updated_by) values(@Id,@TenantId,@Number,@UserId,@Origin,@CostCenterId,@PropertyId,@Justification,@Priority,@NeededOn,@Status,1,@UserId,@UserId)", new { Id = id, tenant.TenantId, Number = number, tenant.UserId, x.Origin, x.CostCenterId, x.PropertyId, x.Justification, Priority = x.Priority.ToUpperInvariant(), x.NeededOn, Status = status }, t, cancellationToken: ct));
            foreach (var i in x.Items) await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_requisition_items(id,tenant_id,requisition_id,catalog_item_id,quantity,unit,notes,created_by,updated_by) values(@Id,@TenantId,@RequisitionId,@CatalogItemId,@Quantity,@Unit,@Notes,@UserId,@UserId)", new { Id = Guid.CreateVersion7(), tenant.TenantId, RequisitionId = id, i.CatalogItemId, i.Quantity, Unit = i.Unit.Trim(), i.Notes, tenant.UserId }, t, cancellationToken: ct));
            await RequisitionEvent(c, t, id, x.Submit ? "SUBMITTED" : "DRAFT_CREATED", null, 1, ct); return id;
        });
    }
    public Task<IReadOnlyList<dynamic>> RequisitionsAsync(ProcurementQuery q, CancellationToken ct) => List("select r.*,count(i.id) item_count from agro360.procurement_requisitions r left join agro360.procurement_requisition_items i on i.tenant_id=r.tenant_id and i.requisition_id=r.id where r.tenant_id=@TenantId and r.deleted_at is null and (@Search is null or r.number ilike '%'||@Search||'%') and (@Status is null or r.status=@Status) group by r.id order by r.created_at desc limit @Take offset @Skip", q, ct);
    public Task<dynamic> RequisitionAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c,t) => { var requisition = await c.QuerySingleOrDefaultAsync(new CommandDefinition("select r.*,coalesce(f.name,'Não informada') operational_unit,coalesce(cc.name,'Não informado') cost_center from agro360.procurement_requisitions r left join agro360.geo_farms f on f.tenant_id=r.tenant_id and f.id=r.property_id left join agro360.finance_cost_centers cc on cc.tenant_id=r.tenant_id and cc.id=r.cost_center_id where r.tenant_id=@TenantId and r.id=@Id and r.deleted_at is null",new { tenant.TenantId,Id=id},t,cancellationToken:ct)) ?? throw new NotFoundException("Requisição",id); var items=(await c.QueryAsync(new CommandDefinition("select i.*,c.name catalog_name,c.active,i.quantity-coalesce((select sum(oi.quantity) from agro360.procurement_purchase_order_items oi join agro360.procurement_purchase_orders o on o.tenant_id=oi.tenant_id and o.id=oi.purchase_order_id where oi.tenant_id=i.tenant_id and oi.requisition_item_id=i.id and o.status<>'CANCELLED'),0) pending_quantity from agro360.procurement_requisition_items i join agro360.procurement_item_catalog c on c.tenant_id=i.tenant_id and c.id=i.catalog_item_id where i.tenant_id=@TenantId and i.requisition_id=@Id and i.deleted_at is null",new {tenant.TenantId,Id=id},t,cancellationToken:ct))).AsList(); var history=(await c.QueryAsync(new CommandDefinition("select event_type,reason,version,created_at,created_by from agro360.procurement_requisition_events where tenant_id=@TenantId and requisition_id=@Id order by created_at,id",new {tenant.TenantId,Id=id},t,cancellationToken:ct))).AsList(); return new {requisition,items,history}; },ct);
    public Task SubmitRequisitionAsync(Guid id, RequisitionTransitionCommand x, CancellationToken ct) => ChangeRequisition(id,x.Version,"DRAFT","AWAITING_APPROVAL","SUBMITTED",null,ct);
    public Task CancelRequisitionAsync(Guid id, RequisitionTransitionCommand x, CancellationToken ct) { if(string.IsNullOrWhiteSpace(x.Reason)) throw new DomainException("Cancelamento após submissão exige justificativa.","agro360.procurement_reason_required"); return Tx(async(c,t)=>{var row=await c.QuerySingleOrDefaultAsync<RequisitionRow>(new CommandDefinition("select status,version from agro360.procurement_requisitions where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Requisição",id); if(row.Version!=x.Version||row.Status is "CONVERTED" or "FULFILLED" or "CANCELLED")throw new ConflictException("A requisição mudou ou não pode ser cancelada."); await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_requisitions set status='CANCELLED',cancel_reason=@Reason,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=id,x.Reason},t,cancellationToken:ct));await RequisitionEvent(c,t,id,"CANCELLED",x.Reason,row.Version+1,ct);}); }
    public Task DecideRequisitionAsync(Guid id, RequisitionDecisionCommand x, CancellationToken ct) => Tx(async(c,t)=>{var decision=x.Decision.Trim().ToUpperInvariant();if(decision is not ("APPROVE" or "REJECT"))throw new DomainException("Decisão inválida.","agro360.procurement_decision_invalid");if(decision=="REJECT"&&string.IsNullOrWhiteSpace(x.Reason))throw new DomainException("Rejeição exige justificativa.","agro360.procurement_reason_required");var row=await c.QuerySingleOrDefaultAsync<RequisitionRow>(new CommandDefinition("select status,version,requester_id RequesterId from agro360.procurement_requisitions where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Requisição",id);if(row.Status!="AWAITING_APPROVAL"||row.Version!=x.Version)throw new ConflictException("A requisição já foi decidida ou alterada.");if(row.RequesterId==tenant.UserId)throw new DomainException("O solicitante não pode aprovar a própria requisição.","agro360.procurement_separation_of_duties");var status=decision=="APPROVE"?"APPROVED":"REJECTED";await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_requisitions set status=@Status,rejection_reason=case when @Status='REJECTED' then @Reason end,approved_at=case when @Status='APPROVED' then now() end,approved_by=case when @Status='APPROVED' then @UserId end,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=id,Status=status,x.Reason},t,cancellationToken:ct));await RequisitionEvent(c,t,id,status,x.Reason,row.Version+1,ct);});
    public Task<IReadOnlyList<dynamic>> ApprovalQueueAsync(ProcurementQuery q,CancellationToken ct)=>List("select r.id,r.number,r.priority,r.needed_on,r.version,r.created_at,coalesce(f.name,'Não informada') operational_unit,coalesce(cc.name,'Não informado') cost_center,coalesce(u.name,u.email) requester from agro360.procurement_requisitions r left join agro360.geo_farms f on f.tenant_id=r.tenant_id and f.id=r.property_id left join agro360.finance_cost_centers cc on cc.tenant_id=r.tenant_id and cc.id=r.cost_center_id left join agro360.identity_users u on u.tenant_id=r.tenant_id and u.id=r.requester_id where r.tenant_id=@TenantId and r.status='AWAITING_APPROVAL' and r.deleted_at is null and (@Search is null or r.number ilike '%'||@Search||'%' or u.name ilike '%'||@Search||'%') order by case r.priority when 'URGENT' then 1 when 'HIGH' then 2 else 3 end,r.needed_on,r.created_at limit @Take offset @Skip",q,ct);
    public Task<Guid> CreateOrderAsync(PurchaseOrderCommand x, CancellationToken ct)
    {
        var total = ProcurementRules.OrderTotal(x.Items.Select(i => (i.Quantity, i.UnitPrice, i.Discount)), x.Freight, x.Taxes); return Tx(async (c, t) => { var supplier = await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select status from agro360.procurement_suppliers where tenant_id=@TenantId and id=@Id and deleted_at is null", new { tenant.TenantId, Id = x.SupplierId }, t, cancellationToken: ct)); if (supplier is null) throw new NotFoundException("Fornecedor", x.SupplierId); if (supplier is "BLOCKED" or "INACTIVE" or "REJECTED") throw new DomainException("Fornecedor indisponível para compras.", "agro360.procurement_supplier_unavailable");
            if(x.RequisitionId is not null){var status=await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select status from agro360.procurement_requisitions where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=x.RequisitionId},t,cancellationToken:ct));if(status!="APPROVED"&&status!="PARTIALLY_FULFILLED")throw new DomainException("Somente requisição aprovada pode originar pedido.","agro360.procurement_requisition_not_approved");}
            foreach(var i in x.Items){var catalogUnit=await c.QuerySingleOrDefaultAsync<string>(new CommandDefinition("select unit from agro360.procurement_item_catalog where tenant_id=@TenantId and id=@Id and active and deleted_at is null",new{tenant.TenantId,Id=i.CatalogItemId},t,cancellationToken:ct));if(catalogUnit is null||!catalogUnit.Equals(i.Unit.Trim(),StringComparison.OrdinalIgnoreCase))throw new DomainException("Item ou unidade inválidos; conversões precisam ser explícitas.","agro360.procurement_unit_mismatch");if(x.RequisitionId is not null){if(i.RequisitionItemId is null)throw new DomainException("Vincule cada linha ao item aprovado da requisição.","agro360.procurement_requisition_item_required");var available=await c.ExecuteScalarAsync<decimal?>(new CommandDefinition("select ri.quantity-coalesce((select sum(oi.quantity) from agro360.procurement_purchase_order_items oi join agro360.procurement_purchase_orders o on o.tenant_id=oi.tenant_id and o.id=oi.purchase_order_id where oi.tenant_id=ri.tenant_id and oi.requisition_item_id=ri.id and o.status<>'CANCELLED'),0) from agro360.procurement_requisition_items ri where ri.tenant_id=@TenantId and ri.id=@ItemId and ri.requisition_id=@RequisitionId and ri.catalog_item_id=@CatalogItemId and upper(ri.unit)=upper(@Unit) for update",new{tenant.TenantId,ItemId=i.RequisitionItemId,x.RequisitionId,i.CatalogItemId,Unit=i.Unit.Trim()},t,cancellationToken:ct));if(available is null||i.Quantity>available)throw new ConflictException("Quantidade excede o saldo autorizado da requisição.","agro360.procurement_authorized_balance_exceeded");}}
            var id = Guid.CreateVersion7(); var number = await Number(c, t, "PO", ct); await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_purchase_orders(id,tenant_id,number,supplier_id,requisition_id,quotation_id,cost_center_id,property_id,payment_terms,delivery_on,delivery_address,freight,taxes,total,status,created_by,updated_by) values(@Id,@TenantId,@Number,@SupplierId,@RequisitionId,@QuotationId,@CostCenterId,@PropertyId,@PaymentTerms,@DeliveryOn,@DeliveryAddress,@Freight,@Taxes,@Total,'AWAITING_APPROVAL',@UserId,@UserId)", new { Id = id, tenant.TenantId, Number = number, x.SupplierId, x.RequisitionId, x.QuotationId, x.CostCenterId, x.PropertyId, x.PaymentTerms, x.DeliveryOn, x.DeliveryAddress, x.Freight, x.Taxes, Total = total, tenant.UserId }, t, cancellationToken: ct)); foreach (var i in x.Items) await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_purchase_order_items(id,tenant_id,purchase_order_id,catalog_item_id,requisition_item_id,quantity,unit,unit_price,discount,total,created_by,updated_by) values(@Id,@TenantId,@OrderId,@CatalogItemId,@RequisitionItemId,@Quantity,@Unit,@UnitPrice,@Discount,@Total,@UserId,@UserId)", new { Id = Guid.CreateVersion7(), tenant.TenantId, OrderId = id, i.CatalogItemId,i.RequisitionItemId, i.Quantity, Unit=i.Unit.Trim(), i.UnitPrice, i.Discount, Total = i.Quantity * i.UnitPrice - i.Discount, tenant.UserId }, t, cancellationToken: ct)); if(x.RequisitionId is not null)await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_requisitions r set status=case when exists(select 1 from agro360.procurement_requisition_items ri where ri.tenant_id=r.tenant_id and ri.requisition_id=r.id and ri.quantity>coalesce((select sum(oi.quantity) from agro360.procurement_purchase_order_items oi join agro360.procurement_purchase_orders o on o.tenant_id=oi.tenant_id and o.id=oi.purchase_order_id where oi.tenant_id=ri.tenant_id and oi.requisition_item_id=ri.id and o.status<>'CANCELLED'),0)) then 'PARTIALLY_FULFILLED' else 'CONVERTED' end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@RequisitionId",new{tenant.TenantId,tenant.UserId,x.RequisitionId},t,cancellationToken:ct));return id; });
    }
    public Task<IReadOnlyList<dynamic>> OrdersAsync(ProcurementQuery q, CancellationToken ct) => List("select o.*,s.legal_name supplier_name,(select oi.id from agro360.procurement_purchase_order_items oi where oi.tenant_id=o.tenant_id and oi.purchase_order_id=o.id and oi.received_quantity<oi.quantity order by oi.created_at limit 1) pending_item_id from agro360.procurement_purchase_orders o join agro360.procurement_suppliers s on s.tenant_id=o.tenant_id and s.id=o.supplier_id where o.tenant_id=@TenantId and o.deleted_at is null and (@Search is null or o.number ilike '%'||@Search||'%' or s.legal_name ilike '%'||@Search||'%') and (@Status is null or o.status=@Status) order by o.created_at desc limit @Take offset @Skip", q, ct);
    public Task ApproveOrderAsync(Guid id, string? comment, CancellationToken ct) => Tx(async (c, t) => { var row = await c.QuerySingleOrDefaultAsync<dynamic>(new CommandDefinition("select o.requester_id,s.status supplier_status from agro360.procurement_purchase_orders o join agro360.procurement_suppliers s on s.tenant_id=o.tenant_id and s.id=o.supplier_id where o.tenant_id=@TenantId and o.id=@Id for update", new { tenant.TenantId, Id = id }, t, cancellationToken: ct)) ?? throw new NotFoundException("Pedido", id); if ((string)row.supplier_status == "BLOCKED") throw new DomainException("Fornecedor bloqueado.", "agro360.procurement_supplier_blocked"); var n = await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_purchase_orders set status='APPROVED',approved_at=now(),approved_by=@UserId,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status='AWAITING_APPROVAL';insert into agro360.procurement_purchase_order_events(id,tenant_id,purchase_order_id,event_type,comment,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,'APPROVED',@Comment,@UserId,@UserId)", new { tenant.TenantId, tenant.UserId, Id = id, Comment = comment }, t, cancellationToken: ct)); if (n < 2) throw new ConflictException("Pedido não está aguardando aprovação."); InfrastructureLogMessages.PurchaseOrderApproved(logger, id); });
    public Task CancelOrderAsync(Guid id,RequisitionTransitionCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Reason))throw new DomainException("Cancelamento exige justificativa.","agro360.procurement_reason_required");return Tx(async(c,t)=>{var row=await c.QuerySingleOrDefaultAsync<OrderCancelRow>(new CommandDefinition("select status,version,requisition_id RequisitionId from agro360.procurement_purchase_orders where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Pedido",id);if(row.Version!=x.Version||row.Status is "CANCELLED" or "RECEIVED" or "CLOSED")throw new ConflictException("Pedido alterado ou não cancelável.");await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_purchase_orders set status='CANCELLED',cancel_reason=@Reason,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id;insert into agro360.procurement_purchase_order_events(id,tenant_id,purchase_order_id,event_type,comment,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,'CANCELLED',@Reason,@UserId,@UserId)",new{tenant.TenantId,tenant.UserId,Id=id,x.Reason},t,cancellationToken:ct));if(row.RequisitionId is not null)await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_requisitions set status='APPROVED',updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@RequisitionId and status in('PARTIALLY_FULFILLED','CONVERTED')",new{tenant.TenantId,tenant.UserId,row.RequisitionId},t,cancellationToken:ct));});}
    public async Task<Guid> ReceiveAsync(ProcurementReceiptCommand x, CancellationToken ct)
    {
        Guid? createdReceiptId = null;
        Guid? firstProductId = null;
        var resultId = await db.InTenantTransactionAsync(async (c, t) =>
        {
            if (x.Items.Count == 0) throw new DomainException("Informe os itens recebidos.", "agro360.procurement_items_required");
            if (string.IsNullOrWhiteSpace(x.IdempotencyKey) || x.IdempotencyKey.Trim().Length is < 16 or > 100) throw new DomainException("A chave de idempotência do recebimento é obrigatória.", "agro360.procurement_idempotency_required");
            if (x.Installments is < 1 or > 60 || x.FinanceAccountId is null || x.FirstDueOn is null || x.FirstDueOn < DateOnly.FromDateTime(x.ReceivedAt.UtcDateTime)) throw new DomainException("Conta financeira, primeiro vencimento e parcelas válidas são obrigatórios.", "agro360.procurement_financial_forecast_invalid");

            var idempotencyKey = x.IdempotencyKey.Trim();
            var requestFingerprint = ReceiptFingerprint(x);
            await c.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@LockKey,0))", new { LockKey = $"{tenant.TenantId:N}:{idempotencyKey}" }, t, cancellationToken: ct));
            var existing = await c.QuerySingleOrDefaultAsync<ExistingReceipt>(new CommandDefinition("select id,request_fingerprint RequestFingerprint from agro360.procurement_receipts where tenant_id=@TenantId and idempotency_key=@IdempotencyKey", new { tenant.TenantId, IdempotencyKey = idempotencyKey }, t, cancellationToken: ct));
            if (existing is not null)
            {
                if (!string.Equals(existing.RequestFingerprint, requestFingerprint, StringComparison.Ordinal))
                    throw new ConflictException("A chave de idempotência já foi utilizada com outro conteúdo.");
                return existing.Id;
            }

            var order = await c.QuerySingleOrDefaultAsync<ReceiptOrderRow>(new CommandDefinition("select o.id,o.total,o.cost_center_id CostCenterId,s.legal_name SupplierName from agro360.procurement_purchase_orders o join agro360.procurement_suppliers s on s.tenant_id=o.tenant_id and s.id=o.supplier_id where o.tenant_id=@TenantId and o.id=@OrderId and o.status in('APPROVED','SENT','PARTIALLY_RECEIVED') and o.deleted_at is null for update of o", new { tenant.TenantId, OrderId = x.PurchaseOrderId }, t, cancellationToken: ct)) ?? throw new DomainException("Pedido não está apto ao recebimento.", "agro360.procurement_order_not_receivable");
            var financeAccountValid = await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.finance_chart_of_accounts where tenant_id=@TenantId and id=@AccountId and active and type in('EXPENSE','COST','LIABILITY'))", new { tenant.TenantId, AccountId = x.FinanceAccountId }, t, cancellationToken: ct));
            if (!financeAccountValid) throw new DomainException("Conta financeira inexistente ou incompatível.", "agro360.procurement_finance_account_invalid");

            var itemIds = x.Items.Select(item => item.PurchaseOrderItemId).Distinct().ToArray();
            var rows = (await c.QueryAsync<ReceiptItemRow>(new CommandDefinition("select oi.id,oi.quantity,oi.received_quantity ReceivedQuantity,oi.unit_price UnitPrice,oi.unit,c.name,c.requires_lot RequiresLot,c.requires_expiry RequiresExpiry,c.requires_inspection RequiresInspection,c.item_type ItemType,c.related_product_id RelatedProductId,p.base_unit ProductBaseUnit from agro360.procurement_purchase_order_items oi join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id left join agro360.inventory_products p on p.tenant_id=c.tenant_id and p.id=c.related_product_id and p.deleted_at is null where oi.tenant_id=@TenantId and oi.purchase_order_id=@OrderId and oi.id=any(@ItemIds) order by oi.id for update of oi", new { tenant.TenantId, OrderId = x.PurchaseOrderId, ItemIds = itemIds }, t, cancellationToken: ct))).ToDictionary(item => item.Id);
            if (rows.Count != itemIds.Length) throw new DomainException("Um ou mais itens não pertencem ao pedido.", "agro360.procurement_receipt_item_invalid");

            var runningQuantity = rows.ToDictionary(pair => pair.Key, pair => pair.Value.ReceivedQuantity);
            var requiresStock = false;
            foreach (var item in x.Items)
            {
                var row = rows[item.PurchaseOrderItemId];
                ProcurementRules.Receipt(row.Quantity, runningQuantity[row.Id], item.Quantity, x.OverrideExcess, x.ExcessJustification, row.RequiresLot, item.SupplierLot, row.RequiresExpiry, item.ExpiresOn);
                runningQuantity[row.Id] += item.Quantity;
                if (row.ItemType != "SERVICE")
                {
                    requiresStock = true;
                    if (row.RelatedProductId is null) throw new DomainException($"O item '{row.Name}' não está vinculado a produto de estoque.", "agro360.procurement_stock_product_required");
                    if (!string.Equals(row.Unit, row.ProductBaseUnit, StringComparison.OrdinalIgnoreCase)) throw new DomainException($"A unidade de compra de '{row.Name}' ({row.Unit}) difere da unidade-base ({row.ProductBaseUnit}); cadastre uma conversão explícita antes de receber.", "agro360.procurement_unit_conversion_required");
                }
            }

            if (requiresStock)
            {
                if (x.WarehouseId is null) throw new DomainException("Selecione o depósito para a entrada física.", "agro360.procurement_warehouse_required");
                var warehouseValid = await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.inventory_warehouses where tenant_id=@TenantId and id=@WarehouseId and deleted_at is null)", new { tenant.TenantId, x.WarehouseId }, t, cancellationToken: ct));
                if (!warehouseValid) throw new DomainException("Depósito inexistente para esta organização.", "agro360.procurement_warehouse_invalid");
            }

            var id = Guid.CreateVersion7();
            var number = await Number(c, t, "RCV", ct);
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipts(id,tenant_id,number,purchase_order_id,received_at,responsible_id,invoice_document,status,excess_justification,stock_integration_status,finance_integration_status,idempotency_key,request_fingerprint,warehouse_id,created_by,updated_by) values(@Id,@TenantId,@Number,@OrderId,@ReceivedAt,@UserId,@Invoice,'PENDING',@Reason,'PENDING','PENDING',@IdempotencyKey,@RequestFingerprint,@WarehouseId,@UserId,@UserId)", new { Id = id, tenant.TenantId, Number = number, OrderId = x.PurchaseOrderId, x.ReceivedAt, tenant.UserId, Invoice = x.InvoiceDocument, Reason = x.ExcessJustification, IdempotencyKey = idempotencyKey, RequestFingerprint = requestFingerprint, x.WarehouseId }, t, cancellationToken: ct));

            foreach (var item in x.Items)
            {
                var row = rows[item.PurchaseOrderItemId];
                var receiptItemId = Guid.CreateVersion7();
                var expired = item.ExpiresOn is not null && item.ExpiresOn < DateOnly.FromDateTime(DateTime.UtcNow);
                var requiresQuality = row.RequiresInspection || expired;
                var qualityStatus = requiresQuality ? "PENDING" : "NOT_REQUIRED";
                await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipt_items(id,tenant_id,receipt_id,purchase_order_item_id,quantity,supplier_lot,expires_on,quality_status,notes,created_by,updated_by) values(@Id,@TenantId,@ReceiptId,@PurchaseOrderItemId,@Quantity,@SupplierLot,@ExpiresOn,@QualityStatus,@Notes,@UserId,@UserId); update agro360.procurement_purchase_order_items set received_quantity=received_quantity+@Quantity,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@PurchaseOrderItemId", new { Id = receiptItemId, tenant.TenantId, ReceiptId = id, item.PurchaseOrderItemId, item.Quantity, item.SupplierLot, item.ExpiresOn, QualityStatus = qualityStatus, item.Notes, tenant.UserId }, t, cancellationToken: ct));
                if (row.ItemType != "SERVICE" && !requiresQuality)
                {
                    var movementId = await c.ExecuteScalarAsync<Guid>(new CommandDefinition("select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@ProductId,@Quantity,@UnitCost,'PURCHASE_RECEIPT',@ReferenceId,@Lot,@ExpiresOn,@UserId,@Reason)", new { tenant.TenantId, x.WarehouseId, ProductId = row.RelatedProductId, item.Quantity, UnitCost = row.UnitPrice, ReferenceId = receiptItemId, Lot = item.SupplierLot, item.ExpiresOn, tenant.UserId, Reason = $"Recebimento {number}" }, t, cancellationToken: ct));
                    await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipt_stock_links(tenant_id,receipt_item_id,stock_movement_id,created_by) values(@TenantId,@ReceiptItemId,@MovementId,@UserId)", new { tenant.TenantId, ReceiptItemId = receiptItemId, MovementId = movementId, tenant.UserId }, t, cancellationToken: ct));
                }
                else if (row.ItemType != "SERVICE")
                {
                    await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipt_quarantine(tenant_id,receipt_item_id,warehouse_id,product_id,quantity,unit,lot_number,expires_on,status,reason,created_by,updated_by) values(@TenantId,@ReceiptItemId,@WarehouseId,@ProductId,@Quantity,@Unit,@Lot,@ExpiresOn,'PENDING',@Reason,@UserId,@UserId)", new { tenant.TenantId, ReceiptItemId = receiptItemId, x.WarehouseId, ProductId = row.RelatedProductId, item.Quantity, row.Unit, Lot = item.SupplierLot, item.ExpiresOn, Reason = expired ? "Validade vencida: liberação depende de decisão autorizada." : "Inspeção obrigatória pendente.", tenant.UserId }, t, cancellationToken: ct));
                }
            }

            var forecastExists = await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.procurement_order_financial_links where tenant_id=@TenantId and purchase_order_id=@OrderId)", new { tenant.TenantId, OrderId = x.PurchaseOrderId }, t, cancellationToken: ct));
            if (!forecastExists)
            {
                var remaining = decimal.Round(order.Total, 2, MidpointRounding.AwayFromZero);
                if (remaining <= 0 || remaining * 100 < x.Installments) throw new DomainException("O total do pedido não permite gerar parcelas positivas na quantidade informada.", "agro360.procurement_installments_amount_invalid");
                var regularAmount = decimal.Floor(remaining * 100 / x.Installments) / 100;
                for (var installment = 1; installment <= x.Installments; installment++)
                {
                    var amount = installment == x.Installments ? remaining : regularAmount;
                    remaining -= amount;
                    var payableId = Guid.CreateVersion7();
                    var dueOn = x.FirstDueOn.Value.AddMonths(installment - 1);
                    await c.ExecuteAsync(new CommandDefinition("insert into agro360.finance_payables(id,tenant_id,supplier_name,document,original_amount,discount,interest,fine,final_amount,balance,issued_on,due_on,account_id,cost_center_id,notes,source_id,status,created_by) values(@Id,@TenantId,@Supplier,@Document,@Amount,0,0,0,@Amount,@Amount,@IssuedOn,@DueOn,@AccountId,@CostCenterId,@Notes,@OrderId,'OPEN',@UserId); insert into agro360.procurement_order_financial_links(tenant_id,purchase_order_id,installment,payable_id,amount,created_by) values(@TenantId,@OrderId,@Installment,@Id,@Amount,@UserId)", new { Id = payableId, tenant.TenantId, Supplier = order.SupplierName, Document = x.InvoiceDocument, Amount = amount, IssuedOn = DateOnly.FromDateTime(x.ReceivedAt.UtcDateTime), DueOn = dueOn, AccountId = x.FinanceAccountId, order.CostCenterId, Notes = $"Previsão do pedido {x.PurchaseOrderId:N} · parcela {installment}/{x.Installments}", OrderId = x.PurchaseOrderId, Installment = installment, tenant.UserId }, t, cancellationToken: ct));
                }
            }

            var hasPendingQuantity = await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.procurement_purchase_order_items where tenant_id=@TenantId and purchase_order_id=@OrderId and received_quantity<quantity)", new { tenant.TenantId, OrderId = x.PurchaseOrderId }, t, cancellationToken: ct));
            var hasPendingQuality = x.Items.Any(item => rows[item.PurchaseOrderItemId].RequiresInspection || (item.ExpiresOn is not null && item.ExpiresOn < DateOnly.FromDateTime(DateTime.UtcNow)));
            var receiptStatus = hasPendingQuality ? "DIVERGENT" : hasPendingQuantity ? "PARTIAL" : "RECEIVED";
            var orderStatus = hasPendingQuantity ? "PARTIALLY_RECEIVED" : hasPendingQuality ? "DIVERGENT" : "RECEIVED";
            await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_receipts set status=@ReceiptStatus,stock_integration_status=@StockStatus,finance_integration_status='COMPLETED',updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id; update agro360.procurement_purchase_orders set status=@OrderStatus,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@OrderId; insert into agro360.procurement_purchase_order_events(id,tenant_id,purchase_order_id,event_type,comment,metadata,created_by,updated_by) values(gen_random_uuid(),@TenantId,@OrderId,'RECEIPT_INTEGRATED',@Comment,jsonb_build_object('receiptId',@Id,'stockStatus',@StockStatus,'financeStatus','COMPLETED'),@UserId,@UserId)", new { tenant.TenantId, tenant.UserId, Id = id, OrderId = x.PurchaseOrderId, ReceiptStatus = receiptStatus, OrderStatus = orderStatus, StockStatus = !requiresStock ? "NOT_APPLICABLE" : hasPendingQuality ? "PENDING" : "COMPLETED", Comment = hasPendingQuality ? "Entrada física concluída; inspeção de qualidade pendente." : "Entrada física e previsão financeira concluídas." }, t, cancellationToken: ct));
            await Audit(c, t, "RECEIPT", id, "INTEGRATED", new { x.PurchaseOrderId, ReceiptStatus = receiptStatus, OrderStatus = orderStatus }, ct);
            createdReceiptId = id;
            firstProductId = rows.Values.FirstOrDefault(r => r.RelatedProductId.HasValue)?.RelatedProductId;
            return id;
        }, ct);

        if (createdReceiptId.HasValue)
        {
            await inspectionTrigger.TryStartFromOriginAsync(new OperationalInspectionEventRequest(
                ProcessCode: "PURCHASE_RECEIPT",
                OriginType: "procurement_receipts",
                OriginId: createdReceiptId.Value,
                ProductId: firstProductId,
                UnitId: x.WarehouseId,
                Notes: $"Recebimento de compra doc {x.InvoiceDocument}"), ct);
        }

        return resultId;
    }
    public Task<IReadOnlyList<dynamic>> ReceiptsAsync(ProcurementQuery q, CancellationToken ct) => List("select r.id,r.number,o.number order_number,s.legal_name supplier_name,r.received_at,r.status,r.stock_integration_status,r.finance_integration_status,r.invoice_document,(select count(*) from agro360.procurement_receipt_items i where i.tenant_id=r.tenant_id and i.receipt_id=r.id) item_count from agro360.procurement_receipts r join agro360.procurement_purchase_orders o on o.tenant_id=r.tenant_id and o.id=r.purchase_order_id join agro360.procurement_suppliers s on s.tenant_id=o.tenant_id and s.id=o.supplier_id where r.tenant_id=@TenantId and r.deleted_at is null and (@Search is null or r.number ilike '%'||@Search||'%' or o.number ilike '%'||@Search||'%' or s.legal_name ilike '%'||@Search||'%') and (@Status is null or r.status=@Status) order by r.received_at desc limit @Take offset @Skip", q, ct);
    public Task<dynamic> ReceiptAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c, t) =>
    {
        var receipt = await c.QuerySingleOrDefaultAsync(new CommandDefinition("select r.id,r.number,r.received_at,r.status,r.invoice_document,r.stock_integration_status,r.finance_integration_status,r.warehouse_id,o.number order_number,s.legal_name supplier_name from agro360.procurement_receipts r join agro360.procurement_purchase_orders o on o.tenant_id=r.tenant_id and o.id=r.purchase_order_id join agro360.procurement_suppliers s on s.tenant_id=o.tenant_id and s.id=o.supplier_id where r.tenant_id=@TenantId and r.id=@Id and r.deleted_at is null", new { tenant.TenantId, Id = id }, t, cancellationToken: ct)) ?? throw new NotFoundException("Recebimento", id);
        var items = (await c.QueryAsync(new CommandDefinition("select ri.id,c.name,oi.quantity ordered_quantity,oi.received_quantity,ri.quantity,oi.unit,ri.supplier_lot,ri.expires_on,ri.quality_status,coalesce(q.quantity,0) quarantine_quantity,coalesce(q.released_quantity,0) released_quantity,coalesce(q.rejected_quantity,0) rejected_quantity from agro360.procurement_receipt_items ri join agro360.procurement_purchase_order_items oi on oi.tenant_id=ri.tenant_id and oi.id=ri.purchase_order_item_id join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id left join agro360.procurement_receipt_quarantine q on q.tenant_id=ri.tenant_id and q.receipt_item_id=ri.id where ri.tenant_id=@TenantId and ri.receipt_id=@Id order by c.name,ri.supplier_lot", new { tenant.TenantId, Id = id }, t, cancellationToken: ct))).AsList();
        var history = (await c.QueryAsync(new CommandDefinition("select d.id,d.result,d.accepted_quantity,d.rejected_quantity,d.reason,d.evidence_reference,d.decided_at,d.decided_by from agro360.procurement_receipt_quality_decisions d join agro360.procurement_receipt_items i on i.tenant_id=d.tenant_id and i.id=d.receipt_item_id where d.tenant_id=@TenantId and i.receipt_id=@Id order by d.decided_at desc", new { tenant.TenantId, Id = id }, t, cancellationToken: ct))).AsList();
        return new { receipt, items, history };
    }, ct);
    public Task<Guid> DecideQualityAsync(Guid receiptItemId, ReceiptQualityDecisionCommand x, CancellationToken ct) => Tx(async (c, t) =>
    {
        if (string.IsNullOrWhiteSpace(x.IdempotencyKey)) throw new DomainException("Chave de idempotência é obrigatória.", "procurement.idempotency_required");
        var replay = await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.procurement_receipt_quality_decisions where tenant_id=@TenantId and idempotency_key=@Key", new { tenant.TenantId, Key = x.IdempotencyKey }, t, cancellationToken: ct));
        if (replay is not null) return replay.Value;
        var row = await c.QuerySingleOrDefaultAsync<QualityRow>(new CommandDefinition("select q.quantity,q.released_quantity Released,q.rejected_quantity Rejected,q.warehouse_id WarehouseId,q.product_id ProductId,q.unit,q.lot_number Lot,q.expires_on ExpiresOn,oi.unit_price UnitCost,i.receipt_id ReceiptId from agro360.procurement_receipt_quarantine q join agro360.procurement_receipt_items i on i.tenant_id=q.tenant_id and i.id=q.receipt_item_id join agro360.procurement_purchase_order_items oi on oi.tenant_id=i.tenant_id and oi.id=i.purchase_order_item_id where q.tenant_id=@TenantId and q.receipt_item_id=@ItemId and q.status='PENDING' for update", new { tenant.TenantId, ItemId = receiptItemId }, t, cancellationToken: ct)) ?? throw new ConflictException("Item não está pendente de inspeção ou já foi totalmente decidido.");
        var result = (x.Result ?? string.Empty).Trim().ToUpperInvariant();
        ProcurementRules.QualityDecision(row.Quantity, row.Released + row.Rejected, x.AcceptedQuantity, x.RejectedQuantity, result, x.Reason);
        var decisionId = Guid.CreateVersion7();
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipt_quality_decisions(id,tenant_id,receipt_item_id,result,accepted_quantity,rejected_quantity,reason,evidence_reference,idempotency_key,decided_at,decided_by,created_by) values(@Id,@TenantId,@ItemId,@Result,@Accepted,@Rejected,@Reason,@Evidence,@Key,now(),@UserId,@UserId)", new { Id = decisionId, tenant.TenantId, ItemId = receiptItemId, Result = result, Accepted = x.AcceptedQuantity, Rejected = x.RejectedQuantity, x.Reason, Evidence = x.EvidenceReference, Key = x.IdempotencyKey, tenant.UserId }, t, cancellationToken: ct));
        if (x.AcceptedQuantity > 0)
        {
            var movementId = await c.ExecuteScalarAsync<Guid>(new CommandDefinition("select agro360.inventory_apply_stock_movement(@TenantId,@WarehouseId,@ProductId,@Quantity,@UnitCost,'PURCHASE_RECEIPT',@ReferenceId,@Lot,@ExpiresOn,@UserId,@Reason)", new { tenant.TenantId, row.WarehouseId, row.ProductId, Quantity = x.AcceptedQuantity, row.UnitCost, ReferenceId = decisionId, row.Lot, row.ExpiresOn, tenant.UserId, Reason = "Liberação autorizada após inspeção" }, t, cancellationToken: ct));
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_receipt_release_links(tenant_id,decision_id,stock_movement_id,created_by) values(@TenantId,@DecisionId,@MovementId,@UserId)", new { tenant.TenantId, DecisionId = decisionId, MovementId = movementId, tenant.UserId }, t, cancellationToken: ct));
        }
        var decided = row.Released + row.Rejected + x.AcceptedQuantity + x.RejectedQuantity;
        var status = decided == row.Quantity ? (row.Rejected + x.RejectedQuantity > 0 ? "DECIDED_WITH_REJECTION" : "RELEASED") : "PENDING";
        await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_receipt_quarantine set released_quantity=released_quantity+@Accepted,rejected_quantity=rejected_quantity+@Rejected,status=@Status,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and receipt_item_id=@ItemId; update agro360.procurement_receipt_items set quality_status=@QualityStatus,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@ItemId", new { tenant.TenantId, ItemId = receiptItemId, Accepted = x.AcceptedQuantity, Rejected = x.RejectedQuantity, Status = status, QualityStatus = status == "PENDING" ? "PENDING" : result, tenant.UserId }, t, cancellationToken: ct));
        await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_receipts r set status=case when exists(select 1 from agro360.procurement_receipt_quarantine q join agro360.procurement_receipt_items i on i.tenant_id=q.tenant_id and i.id=q.receipt_item_id where i.receipt_id=r.id and q.status='PENDING') then 'DIVERGENT' when exists(select 1 from agro360.procurement_receipt_quarantine q join agro360.procurement_receipt_items i on i.tenant_id=q.tenant_id and i.id=q.receipt_item_id where i.receipt_id=r.id and q.rejected_quantity>0) then 'DIVERGENT' else 'RECEIVED' end,stock_integration_status=case when exists(select 1 from agro360.procurement_receipt_quarantine q join agro360.procurement_receipt_items i on i.tenant_id=q.tenant_id and i.id=q.receipt_item_id where i.receipt_id=r.id and q.status='PENDING') then 'PENDING' else 'COMPLETED' end,updated_at=now(),updated_by=@UserId where r.tenant_id=@TenantId and r.id=@ReceiptId", new { tenant.TenantId, row.ReceiptId, tenant.UserId }, t, cancellationToken: ct));
        await Audit(c, t, "RECEIPT_ITEM", receiptItemId, "QUALITY_DECIDED", new { decisionId, x.AcceptedQuantity, x.RejectedQuantity, Result = result }, ct);
        return decisionId;
    });
    public Task<IReadOnlyList<dynamic>> PendingOrderItemsAsync(Guid orderId, CancellationToken ct) => db.InTenantTransactionAsync<IReadOnlyList<dynamic>>(async (c, t) => (await c.QueryAsync(new CommandDefinition("select oi.id,c.name,oi.unit,oi.quantity,oi.received_quantity,oi.quantity-oi.received_quantity pending_quantity,c.requires_lot,c.requires_expiry,c.requires_inspection,c.item_type,c.related_product_id from agro360.procurement_purchase_order_items oi join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id where oi.tenant_id=@TenantId and oi.purchase_order_id=@OrderId and oi.received_quantity<oi.quantity order by c.name", new { tenant.TenantId, OrderId = orderId }, t, cancellationToken: ct))).AsList(), ct);
    public Task<dynamic> ReceiptOptionsAsync(CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c, t) =>
    {
        using var grid = await c.QueryMultipleAsync(new CommandDefinition("select id,code,name from agro360.inventory_warehouses where tenant_id=@TenantId and deleted_at is null order by name; select id,code,name,type from agro360.finance_chart_of_accounts where tenant_id=@TenantId and active and type in('EXPENSE','COST','LIABILITY') order by code,name; select id,sku,name,base_unit from agro360.inventory_products where tenant_id=@TenantId and deleted_at is null order by name", new { tenant.TenantId }, t, cancellationToken: ct));
        var warehouses = (await grid.ReadAsync()).AsList();
        var financeAccounts = (await grid.ReadAsync()).AsList();
        var products = (await grid.ReadAsync()).AsList();
        return new { warehouses, financeAccounts, products };
    }, ct);
    public Task<Guid> MatchInvoiceAsync(PurchaseInvoiceMatchCommand command, CancellationToken ct) => db.InTenantTransactionAsync<Guid>(async (c, t) =>
    {
        if (command.Items.Count == 0) throw new DomainException("Informe ao menos uma linha da cobrança.", "procurement.match.items_required");
        if (string.IsNullOrWhiteSpace(command.DocumentNumber) || string.IsNullOrWhiteSpace(command.IdempotencyKey) || command.IdempotencyKey.Trim().Length is < 16 or > 100) throw new DomainException("Número do documento e chave de idempotência válida são obrigatórios.", "procurement.match.identity_required");
        if (!string.Equals(command.Currency?.Trim(), "BRL", StringComparison.OrdinalIgnoreCase)) throw new DomainException("A conferência está disponível somente em BRL enquanto não houver política de câmbio configurada.", "procurement.match.currency_policy_missing");
        if (command.Items.Any(i => i.Quantity <= 0 || i.UnitPrice < 0 || i.Discount < 0 || string.IsNullOrWhiteSpace(i.Unit) || string.IsNullOrWhiteSpace(i.Description))) throw new DomainException("As linhas da cobrança possuem quantidade, unidade ou valor inválido.", "procurement.match.line_invalid");
        var calculatedGoods = decimal.Round(command.Items.Sum(i => i.Quantity * i.UnitPrice - i.Discount), 2, MidpointRounding.AwayFromZero);
        var calculatedTotal = decimal.Round(calculatedGoods - command.Discount + command.Freight + command.AdditionalAmount, 2, MidpointRounding.AwayFromZero);
        if (command.Discount < 0 || command.Freight < 0 || command.AdditionalAmount < 0 || command.GoodsTotal != calculatedGoods || command.Total != calculatedTotal) throw new DomainException($"Totais inconsistentes. Itens: {calculatedGoods:N2}; documento: {calculatedTotal:N2}.", "procurement.match.total_invalid");

        var key = command.IdempotencyKey.Trim();
        await c.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@Key,0))", new { Key = $"invoice-match:{tenant.TenantId:N}:{key}" }, t, cancellationToken: ct));
        var replay = await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.procurement_invoice_matches where tenant_id=@TenantId and idempotency_key=@Key", new { tenant.TenantId, Key = key }, t, cancellationToken: ct));
        if (replay is not null) return replay.Value;
        var order = await c.QuerySingleOrDefaultAsync<MatchOrderRow>(new CommandDefinition("select id,supplier_id SupplierId,total,delivery_on DeliveryOn,status from agro360.procurement_purchase_orders where tenant_id=@TenantId and id=@Id and deleted_at is null for update", new { tenant.TenantId, Id = command.PurchaseOrderId }, t, cancellationToken: ct)) ?? throw new NotFoundException("Pedido", command.PurchaseOrderId);
        if (order.Status is "DRAFT" or "AWAITING_APPROVAL" or "CANCELLED") throw new ConflictException("Somente pedido aprovado e não cancelado pode ser conferido.", "procurement.match.order_unavailable");
        var tolerance = await c.QuerySingleOrDefaultAsync<MatchToleranceRow>(new CommandDefinition("select quantity_percent QuantityPercent,quantity_absolute QuantityAbsolute,price_percent PricePercent,price_absolute PriceAbsolute,total_percent TotalPercent,total_absolute TotalAbsolute,excess_percent ExcessPercent,excess_absolute ExcessAbsolute,delivery_days DeliveryDays,separation_of_duties SeparationOfDuties,version from agro360.procurement_match_tolerances where tenant_id=@TenantId and active and deleted_at is null", new { tenant.TenantId }, t, cancellationToken: ct)) ?? new MatchToleranceRow();
        var snapshot = System.Text.Json.JsonSerializer.Serialize(tolerance);
        var documentId = Guid.CreateVersion7(); var matchId = Guid.CreateVersion7(); var divergences = new List<MatchDivergence>();
        try
        {
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_billing_documents(id,tenant_id,purchase_order_id,supplier_id,document_number,document_series,issued_on,currency,goods_total,discount,freight,additional_amount,total,created_by,updated_by) values(@Id,@TenantId,@OrderId,@SupplierId,@Number,@Series,@IssuedOn,'BRL',@Goods,@Discount,@Freight,@Additional,@Total,@UserId,@UserId)", new { Id = documentId, tenant.TenantId, OrderId = command.PurchaseOrderId, order.SupplierId, Number = command.DocumentNumber.Trim(), Series = command.DocumentSeries?.Trim() ?? "", command.IssuedOn, Goods = calculatedGoods, command.Discount, command.Freight, Additional = command.AdditionalAmount, Total = calculatedTotal, tenant.UserId }, t, cancellationToken: ct));
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.UniqueViolation) { throw new ConflictException("Esta cobrança já foi registrada para o fornecedor.", "procurement.match.duplicate_document"); }

        decimal matchedContractTotal = 0; DateTimeOffset? latestReceiptAt = null;
        foreach (var line in command.Items)
        {
            var row = await c.QuerySingleOrDefaultAsync<MatchLineRow>(new CommandDefinition("select oi.id,oi.quantity OrderedQuantity,oi.unit,oi.unit_price UnitPrice,oi.discount,c.item_type ItemType,ri.quantity ReceivedQuantity,ri.quality_status QualityStatus,r.received_at ReceivedAt,coalesce(q.released_quantity,case when ri.quality_status='NOT_REQUIRED' then ri.quantity else 0 end) AcceptedQuantity,coalesce((select sum(bl.quantity) from agro360.procurement_billing_lines bl join agro360.procurement_billing_documents bd on bd.tenant_id=bl.tenant_id and bd.id=bl.billing_document_id where bl.tenant_id=@TenantId and bl.receipt_item_id=ri.id and bl.deleted_at is null and bd.status not in('CANCELLED','REPLACED')),0) AlreadyBilled from agro360.procurement_purchase_order_items oi join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id join agro360.procurement_receipt_items ri on ri.tenant_id=oi.tenant_id and ri.purchase_order_item_id=oi.id join agro360.procurement_receipts r on r.tenant_id=ri.tenant_id and r.id=ri.receipt_id left join agro360.procurement_receipt_quarantine q on q.tenant_id=ri.tenant_id and q.receipt_item_id=ri.id where oi.tenant_id=@TenantId and oi.purchase_order_id=@OrderId and oi.id=@OrderItemId and ri.id=@ReceiptItemId for update of oi,ri,r", new { tenant.TenantId, OrderId = command.PurchaseOrderId, OrderItemId = line.PurchaseOrderItemId, line.ReceiptItemId }, t, cancellationToken: ct)) ?? throw new DomainException("A linha deve apontar explicitamente para item e recebimento do pedido.", "procurement.match.link_invalid");
            if (!string.Equals(row.Unit, line.Unit.Trim(), StringComparison.OrdinalIgnoreCase)) throw new DomainException($"Unidade incompatível: pedido em {row.Unit} e cobrança em {line.Unit}.", "procurement.match.unit_incompatible");
            if (line.Quantity > row.AcceptedQuantity - row.AlreadyBilled) throw new ConflictException("A cobrança excede o saldo recebido e aceito disponível desta linha.", "procurement.match.accepted_balance_exceeded");
            var billingLineId = Guid.CreateVersion7(); var lineTotal = decimal.Round(line.Quantity * line.UnitPrice - line.Discount, 2, MidpointRounding.AwayFromZero);
            await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_billing_lines(id,tenant_id,billing_document_id,purchase_order_item_id,receipt_item_id,description,quantity,unit,unit_price,discount,total,created_by,updated_by) values(@Id,@TenantId,@DocumentId,@OrderItemId,@ReceiptItemId,@Description,@Quantity,@Unit,@Price,@Discount,@Total,@UserId,@UserId)", new { Id = billingLineId, tenant.TenantId, DocumentId = documentId, OrderItemId = line.PurchaseOrderItemId, line.ReceiptItemId, Description = line.Description.Trim(), line.Quantity, Unit = row.Unit, Price = line.UnitPrice, line.Discount, Total = lineTotal, tenant.UserId }, t, cancellationToken: ct));
            matchedContractTotal += decimal.Round(line.Quantity * row.UnitPrice - row.Discount * (line.Quantity / row.OrderedQuantity), 2, MidpointRounding.AwayFromZero);
            if (latestReceiptAt is null || row.ReceivedAt > latestReceiptAt) latestReceiptAt = row.ReceivedAt;
            AddDifference(divergences, "PRICE", billingLineId, line, row.UnitPrice, line.UnitPrice, tolerance.PriceAbsolute, tolerance.PricePercent, "Solicitar correção da cobrança", snapshot);
        }
        AddDifference(divergences, "TOTAL", null, null, matchedContractTotal, calculatedTotal, tolerance.TotalAbsolute, tolerance.TotalPercent, "Solicitar correção ou aprovar exceção", snapshot);
        var actualDeliveryOn = DateOnly.FromDateTime(latestReceiptAt!.Value.UtcDateTime); var deliveryDifference = actualDeliveryOn.DayNumber - order.DeliveryOn.DayNumber;
        if (deliveryDifference > tolerance.DeliveryDays) divergences.Add(new MatchDivergence("DELIVERY", null, null, order.DeliveryOn.DayNumber, actualDeliveryOn.DayNumber, deliveryDifference, null, "Revisar atraso do recebimento", snapshot));
        var status = divergences.Count == 0 ? "MATCHED" : "PENDING_EXCEPTION";
        var diff = calculatedTotal - matchedContractTotal; var percent = matchedContractTotal == 0 ? (decimal?)null : decimal.Round(diff / matchedContractTotal * 100, 4, MidpointRounding.AwayFromZero);
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_invoice_matches(id,tenant_id,billing_document_id,purchase_order_id,status,idempotency_key,tolerance_snapshot,contracted_total,accepted_total,billed_total,difference_total,difference_percent,decided_at,decided_by,created_by,updated_by) values(@Id,@TenantId,@DocumentId,@OrderId,@Status,@Key,@Snapshot::jsonb,@Contracted,@Accepted,@Billed,@Difference,@Percent,case when @Status='MATCHED' then now() end,case when @Status='MATCHED' then @UserId end,@UserId,@UserId); update agro360.procurement_billing_documents set status=@Status,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@DocumentId", new { Id = matchId, tenant.TenantId, DocumentId = documentId, OrderId = command.PurchaseOrderId, Status = status, Key = key, Snapshot = snapshot, Contracted = matchedContractTotal, Accepted = matchedContractTotal, Billed = calculatedTotal, Difference = diff, Percent = percent, tenant.UserId }, t, cancellationToken: ct));
        foreach (var d in divergences) await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_match_divergences(id,tenant_id,invoice_match_id,billing_line_id,purchase_order_item_id,receipt_item_id,type,origin,description,expected_value,actual_value,difference_value,difference_percent,operational_impact,required_action,status,tolerance_snapshot,created_by,updated_by) values(@Id,@TenantId,@MatchId,@LineId,@OrderItemId,@ReceiptItemId,@Type,'BILLING',@Description,@Expected,@Actual,@Difference,@Percent,'Cobrança permanece pendente; nenhum pagamento é registrado.',@Action,'OPEN',@Snapshot::jsonb,@UserId,@UserId)", new { Id = Guid.CreateVersion7(), tenant.TenantId, MatchId = matchId, LineId = d.BillingLineId, OrderItemId = d.Line?.PurchaseOrderItemId, ReceiptItemId = d.Line?.ReceiptItemId, d.Type, Description = $"{d.Type}: esperado {d.Expected:N4}, informado {d.Actual:N4}, diferença {d.Difference:N4}{(d.Percent is null ? "" : $" ({d.Percent:N4}%)")}.", d.Expected, d.Actual, d.Difference, d.Percent, Action = d.Action, Snapshot = d.Snapshot, tenant.UserId }, t, cancellationToken: ct));
        await Audit(c, t, "INVOICE_MATCH", matchId, status, new { documentId, command.PurchaseOrderId, divergenceCount = divergences.Count }, ct);
        return matchId;
    }, ct);
    public Task<IReadOnlyList<dynamic>> InvoiceMatchesAsync(ProcurementQuery query, CancellationToken ct) => List("select m.id,d.document_number,d.document_series,d.issued_on,d.total,o.number order_number,s.legal_name supplier_name,m.status,m.difference_total,(select count(*) from agro360.procurement_match_divergences x where x.tenant_id=m.tenant_id and x.invoice_match_id=m.id and x.status='OPEN') open_divergences from agro360.procurement_invoice_matches m join agro360.procurement_billing_documents d on d.tenant_id=m.tenant_id and d.id=m.billing_document_id join agro360.procurement_purchase_orders o on o.tenant_id=m.tenant_id and o.id=m.purchase_order_id join agro360.procurement_suppliers s on s.tenant_id=d.tenant_id and s.id=d.supplier_id where m.tenant_id=@TenantId and m.deleted_at is null and (@Search is null or d.document_number ilike '%'||@Search||'%' or o.number ilike '%'||@Search||'%' or s.legal_name ilike '%'||@Search||'%') and (@Status is null or m.status=@Status) order by m.created_at desc limit @Take offset @Skip", query, ct);
    public Task<IReadOnlyList<dynamic>> MatchOptionsAsync(Guid orderId, CancellationToken ct) => db.InTenantTransactionAsync<IReadOnlyList<dynamic>>(async (c, t) => (await c.QueryAsync(new CommandDefinition("select oi.id purchase_order_item_id,ri.id receipt_item_id,c.name,r.number receipt_number,oi.unit,oi.unit_price,case when c.item_type='SERVICE' then ri.quantity when ri.quality_status='NOT_REQUIRED' then ri.quantity else coalesce(q.released_quantity,0) end-coalesce((select sum(bl.quantity) from agro360.procurement_billing_lines bl join agro360.procurement_billing_documents bd on bd.tenant_id=bl.tenant_id and bd.id=bl.billing_document_id where bl.tenant_id=ri.tenant_id and bl.receipt_item_id=ri.id and bl.deleted_at is null and bd.status not in('CANCELLED','REPLACED')),0) available_quantity from agro360.procurement_purchase_order_items oi join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id join agro360.procurement_receipt_items ri on ri.tenant_id=oi.tenant_id and ri.purchase_order_item_id=oi.id join agro360.procurement_receipts r on r.tenant_id=ri.tenant_id and r.id=ri.receipt_id and r.deleted_at is null left join agro360.procurement_receipt_quarantine q on q.tenant_id=ri.tenant_id and q.receipt_item_id=ri.id where oi.tenant_id=@TenantId and oi.purchase_order_id=@OrderId and (case when c.item_type='SERVICE' then ri.quantity when ri.quality_status='NOT_REQUIRED' then ri.quantity else coalesce(q.released_quantity,0) end)>coalesce((select sum(bl.quantity) from agro360.procurement_billing_lines bl join agro360.procurement_billing_documents bd on bd.tenant_id=bl.tenant_id and bd.id=bl.billing_document_id where bl.tenant_id=ri.tenant_id and bl.receipt_item_id=ri.id and bl.deleted_at is null and bd.status not in('CANCELLED','REPLACED')),0) order by r.received_at,c.name", new { tenant.TenantId, OrderId = orderId }, t, cancellationToken: ct))).AsList(), ct);
    public Task<dynamic> InvoiceMatchAsync(Guid id, CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c, t) =>
    {
        var match = await c.QuerySingleOrDefaultAsync(new CommandDefinition("select m.*,d.document_number,d.document_series,d.issued_on,d.currency,d.goods_total,d.discount,d.freight,d.additional_amount,d.total,d.fiscal_validation_status,o.number order_number,s.legal_name supplier_name from agro360.procurement_invoice_matches m join agro360.procurement_billing_documents d on d.tenant_id=m.tenant_id and d.id=m.billing_document_id join agro360.procurement_purchase_orders o on o.tenant_id=m.tenant_id and o.id=m.purchase_order_id join agro360.procurement_suppliers s on s.tenant_id=d.tenant_id and s.id=d.supplier_id where m.tenant_id=@TenantId and m.id=@Id and m.deleted_at is null", new { tenant.TenantId, Id = id }, t, cancellationToken: ct)) ?? throw new NotFoundException("Conferência", id);
        var lines = (await c.QueryAsync(new CommandDefinition("select l.*,c.name item_name,r.number receipt_number from agro360.procurement_billing_lines l join agro360.procurement_purchase_order_items oi on oi.tenant_id=l.tenant_id and oi.id=l.purchase_order_item_id join agro360.procurement_item_catalog c on c.tenant_id=oi.tenant_id and c.id=oi.catalog_item_id join agro360.procurement_receipt_items ri on ri.tenant_id=l.tenant_id and ri.id=l.receipt_item_id join agro360.procurement_receipts r on r.tenant_id=ri.tenant_id and r.id=ri.receipt_id where l.tenant_id=@TenantId and l.billing_document_id=@DocumentId and l.deleted_at is null", new { tenant.TenantId, DocumentId = (Guid)match.billing_document_id }, t, cancellationToken: ct))).AsList();
        var divergences = (await c.QueryAsync(new CommandDefinition("select * from agro360.procurement_match_divergences where tenant_id=@TenantId and invoice_match_id=@Id and deleted_at is null order by created_at,id", new { tenant.TenantId, Id = id }, t, cancellationToken: ct))).AsList();
        return new { match, lines, divergences };
    }, ct);
    public Task ResolveMatchDivergenceAsync(Guid id, MatchDivergenceDecisionCommand command, CancellationToken ct) => Tx(async (c, t) =>
    {
        var decision = (command.Decision ?? "").Trim().ToUpperInvariant(); if (decision is not ("APPROVED_EXCEPTION" or "REJECTED" or "CORRECTION_REQUESTED") || string.IsNullOrWhiteSpace(command.Justification)) throw new DomainException("Decisão válida e justificativa são obrigatórias.", "procurement.match.decision_invalid");
        var row = await c.QuerySingleOrDefaultAsync<DivergenceRow>(new CommandDefinition("select d.invoice_match_id MatchId,m.created_by CreatedBy,(m.tolerance_snapshot->>'SeparationOfDuties')::boolean SeparationOfDuties from agro360.procurement_match_divergences d join agro360.procurement_invoice_matches m on m.tenant_id=d.tenant_id and m.id=d.invoice_match_id where d.tenant_id=@TenantId and d.id=@Id and d.status='OPEN' for update of d,m", new { tenant.TenantId, Id = id }, t, cancellationToken: ct)) ?? throw new ConflictException("Divergência inexistente ou já decidida.", "procurement.match.divergence_closed");
        if (row.SeparationOfDuties && row.CreatedBy == tenant.UserId) throw new DomainException("A segregação de funções impede o autor da conferência de aprovar a própria exceção.", "procurement.match.separation_of_duties");
        var status = decision == "REJECTED" ? "REJECTED" : "RESOLVED";
        await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_match_divergences set status=@Status,resolution=@Decision,resolution_reason=@Reason,evidence_reference=coalesce(@Evidence,evidence_reference),resolved_at=now(),resolved_by=@UserId,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id; update agro360.procurement_invoice_matches m set status=case when @Decision='REJECTED' then 'REJECTED' when exists(select 1 from agro360.procurement_match_divergences d where d.tenant_id=m.tenant_id and d.invoice_match_id=m.id and d.id<>@Id and d.status='OPEN') then 'PENDING_EXCEPTION' else 'MATCHED' end,decided_at=case when not exists(select 1 from agro360.procurement_match_divergences d where d.tenant_id=m.tenant_id and d.invoice_match_id=m.id and d.id<>@Id and d.status='OPEN') then now() else decided_at end,decided_by=case when not exists(select 1 from agro360.procurement_match_divergences d where d.tenant_id=m.tenant_id and d.invoice_match_id=m.id and d.id<>@Id and d.status='OPEN') then @UserId else decided_by end,decision=@Decision,decision_reason=@Reason,updated_at=now(),updated_by=@UserId where m.tenant_id=@TenantId and m.id=@MatchId; update agro360.procurement_billing_documents b set status=(select m.status from agro360.procurement_invoice_matches m where m.tenant_id=b.tenant_id and m.billing_document_id=b.id),updated_at=now(),updated_by=@UserId where b.tenant_id=@TenantId and b.id=(select m.billing_document_id from agro360.procurement_invoice_matches m where m.tenant_id=@TenantId and m.id=@MatchId)", new { tenant.TenantId, Id = id, row.MatchId, Status = status, Decision = decision, Reason = command.Justification.Trim(), Evidence = command.EvidenceReference?.Trim(), tenant.UserId }, t, cancellationToken: ct));
        await Audit(c, t, "MATCH_DIVERGENCE", id, decision, new { command.Justification, command.EvidenceReference }, ct);
    });
    public Task<dynamic> MatchToleranceAsync(CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c, t) => await c.QuerySingleOrDefaultAsync(new CommandDefinition("select id,quantity_percent,quantity_absolute,price_percent,price_absolute,total_percent,total_absolute,excess_percent,excess_absolute,delivery_days,separation_of_duties,version from agro360.procurement_match_tolerances where tenant_id=@TenantId and active and deleted_at is null", new { tenant.TenantId }, t, cancellationToken: ct)) ?? new { quantity_percent = 0, quantity_absolute = 0, price_percent = 0, price_absolute = 0, total_percent = 0, total_absolute = 0, excess_percent = 0, excess_absolute = 0, delivery_days = 0, separation_of_duties = true, version = 0 }, ct);
    public Task<Guid> SaveMatchToleranceAsync(MatchToleranceCommand command, CancellationToken ct) => Tx(async (c, t) =>
    {
        if (new[] { command.QuantityPercent, command.PricePercent, command.TotalPercent, command.ExcessPercent }.Any(v => v < 0 || v > 100) || new[] { command.QuantityAbsolute, command.PriceAbsolute, command.TotalAbsolute, command.ExcessAbsolute }.Any(v => v < 0) || command.DeliveryDays < 0) throw new DomainException("Tolerâncias devem ser não negativas e percentuais devem estar entre 0 e 100.", "procurement.match.tolerance_invalid");
        var current = await c.QuerySingleOrDefaultAsync<(Guid Id, long Version)>(new CommandDefinition("select id,version from agro360.procurement_match_tolerances where tenant_id=@TenantId and active and deleted_at is null for update", new { tenant.TenantId }, t, cancellationToken: ct));
        if (current.Id != Guid.Empty && command.Version != current.Version) throw new ConflictException("As tolerâncias foram alteradas. Atualize a página antes de salvar.", "procurement.match.tolerance_conflict");
        var id = current.Id == Guid.Empty ? Guid.CreateVersion7() : current.Id; var p = new { Id = id, tenant.TenantId, command.QuantityPercent, command.QuantityAbsolute, command.PricePercent, command.PriceAbsolute, command.TotalPercent, command.TotalAbsolute, command.ExcessPercent, command.ExcessAbsolute, command.DeliveryDays, command.SeparationOfDuties, tenant.UserId };
        await c.ExecuteAsync(new CommandDefinition(current.Id == Guid.Empty ? "insert into agro360.procurement_match_tolerances(id,tenant_id,quantity_percent,quantity_absolute,price_percent,price_absolute,total_percent,total_absolute,excess_percent,excess_absolute,delivery_days,separation_of_duties,created_by,updated_by) values(@Id,@TenantId,@QuantityPercent,@QuantityAbsolute,@PricePercent,@PriceAbsolute,@TotalPercent,@TotalAbsolute,@ExcessPercent,@ExcessAbsolute,@DeliveryDays,@SeparationOfDuties,@UserId,@UserId)" : "update agro360.procurement_match_tolerances set quantity_percent=@QuantityPercent,quantity_absolute=@QuantityAbsolute,price_percent=@PricePercent,price_absolute=@PriceAbsolute,total_percent=@TotalPercent,total_absolute=@TotalAbsolute,excess_percent=@ExcessPercent,excess_absolute=@ExcessAbsolute,delivery_days=@DeliveryDays,separation_of_duties=@SeparationOfDuties,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id", p, t, cancellationToken: ct));
        await Audit(c, t, "MATCH_TOLERANCE", id, current.Id == Guid.Empty ? "CREATED" : "UPDATED", command, ct); return id;
    });
    public async Task<byte[]> ExportAsync(string report, ProcurementQuery q, CancellationToken ct) { IReadOnlyList<dynamic> rows = report switch { "suppliers" => await SuppliersAsync(q, ct), "requisitions" => await RequisitionsAsync(q, ct), "orders" => await OrdersAsync(q, ct), _ => throw new DomainException("Relatório inválido.", "agro360.procurement_report_invalid") }; var sb = new StringBuilder("sep=;\n"); if (report == "suppliers") { sb.AppendLine("Razão social;Fantasia;Categoria;Status;E-mail"); foreach (var r in rows) sb.AppendLine(CultureInfo.InvariantCulture, $"{Csv(r.legal_name)};{Csv(r.trade_name)};{Csv(r.main_category)};{Csv(r.status)};{Csv(r.email)}"); } else if (report == "requisitions") { sb.AppendLine("Número;Prioridade;Necessidade;Status;Itens"); foreach (var r in rows) sb.AppendLine(CultureInfo.InvariantCulture, $"{r.number};{r.priority};{r.needed_on:yyyy-MM-dd};{r.status};{r.item_count}"); } else { sb.AppendLine("Número;Fornecedor;Entrega;Total;Status"); foreach (var r in rows) sb.AppendLine(CultureInfo.InvariantCulture, $"{r.number};{Csv(r.supplier_name)};{r.delivery_on:yyyy-MM-dd};{r.total};{r.status}"); } return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray(); }
    private Task<T> Tx<T>(Func<Npgsql.NpgsqlConnection, Npgsql.NpgsqlTransaction, Task<T>> action) => db.InTenantTransactionAsync(action, CancellationToken.None);
    private Task Tx(Func<Npgsql.NpgsqlConnection, Npgsql.NpgsqlTransaction, Task> action) => db.InTenantTransactionAsync(action, CancellationToken.None);
    private Task<IReadOnlyList<dynamic>> List(string sql, ProcurementQuery q, CancellationToken ct) => db.InTenantTransactionAsync<IReadOnlyList<dynamic>>(async (c, t) => (await c.QueryAsync(new CommandDefinition(sql, new { tenant.TenantId, Search = string.IsNullOrWhiteSpace(q.Search) ? null : q.Search, Status = string.IsNullOrWhiteSpace(q.Status) ? null : q.Status, Category = string.IsNullOrWhiteSpace(q.Category) ? null : q.Category, Take = Math.Clamp(q.PageSize, 1, 100), Skip = (Math.Max(q.Page, 1) - 1) * Math.Clamp(q.PageSize, 1, 100) }, t, cancellationToken: ct))).AsList(), ct);
    private async Task<bool> Exists(Npgsql.NpgsqlConnection c, Npgsql.NpgsqlTransaction t, string table, Guid id, CancellationToken ct) => await c.ExecuteScalarAsync<bool>(new CommandDefinition($"select exists(select 1 from agro360.procurement_{table} where tenant_id=@TenantId and id=@Id and deleted_at is null)", new { tenant.TenantId, Id = id }, t, cancellationToken: ct));
    private static async Task<string> Number(Npgsql.NpgsqlConnection c, Npgsql.NpgsqlTransaction t, string prefix, CancellationToken ct) { var n = await c.ExecuteScalarAsync<long>(new CommandDefinition("select nextval('agro360.procurement_document_number_seq')", transaction: t, cancellationToken: ct)); return $"{prefix}-{DateTime.UtcNow:yyyy}-{n:000000}"; }
    private async Task Audit(Npgsql.NpgsqlConnection c, Npgsql.NpgsqlTransaction t, string entity, Guid id, string action, object data, CancellationToken ct) => await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_audit_events(id,tenant_id,entity_type,entity_id,action,changed_fields,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Entity,@Id,@Action,@Data::jsonb,@UserId,@UserId)", new { tenant.TenantId, tenant.UserId, Entity = entity, Id = id, Action = action, Data = System.Text.Json.JsonSerializer.Serialize(data) }, t, cancellationToken: ct));
    private Task ChangeRequisition(Guid id,long version,string from,string to,string eventType,string? reason,CancellationToken ct)=>Tx(async(c,t)=>{var changed=await c.ExecuteAsync(new CommandDefinition("update agro360.procurement_requisitions set status=@To,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status=@From and version=@Version",new{tenant.TenantId,tenant.UserId,Id=id,Version=version,From=from,To=to},t,cancellationToken:ct));if(changed!=1)throw new ConflictException("A requisição foi alterada por outro usuário ou a transição não é permitida.");await RequisitionEvent(c,t,id,eventType,reason,version+1,ct);});
    private async Task RequisitionEvent(Npgsql.NpgsqlConnection c,Npgsql.NpgsqlTransaction t,Guid id,string eventType,string? reason,long version,CancellationToken ct)=>await c.ExecuteAsync(new CommandDefinition("insert into agro360.procurement_requisition_events(id,tenant_id,requisition_id,event_type,reason,version,created_by) values(gen_random_uuid(),@TenantId,@Id,@EventType,@Reason,@Version,@UserId)",new{tenant.TenantId,tenant.UserId,Id=id,EventType=eventType,Reason=reason,Version=version},t,cancellationToken:ct));
    private static string Csv(object? value) => $"\"{value?.ToString()?.Replace("\"", "\"\"")}\"";
    private static void AddDifference(List<MatchDivergence> target, string type, Guid? billingLineId, BillingLineCommand? line, decimal expected, decimal actual, decimal absoluteLimit, decimal percentLimit, string action, string snapshot)
    {
        var difference = actual - expected; var absoluteDifference = Math.Abs(difference);
        var percent = expected == 0 ? (absoluteDifference == 0 ? 0 : (decimal?)null) : decimal.Round(difference / expected * 100, 4, MidpointRounding.AwayFromZero);
        var outsideAbsolute = absoluteDifference > absoluteLimit;
        var outsidePercent = percent is null ? absoluteDifference > 0 : Math.Abs(percent.Value) > percentLimit;
        if (outsideAbsolute || outsidePercent) target.Add(new MatchDivergence(type, billingLineId, line, expected, actual, difference, percent, action, snapshot));
    }
    private static string ReceiptFingerprint(ProcurementReceiptCommand command)
    {
        var canonical = string.Join("|", command.PurchaseOrderId.ToString("N"), command.ReceivedAt.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture), command.InvoiceDocument?.Trim() ?? "", command.OverrideExcess, command.ExcessJustification?.Trim() ?? "", command.WarehouseId, command.FinanceAccountId, command.FirstDueOn, command.Installments,
            string.Join(";", command.Items.OrderBy(item => item.PurchaseOrderItemId).Select(item => string.Join(",", item.PurchaseOrderItemId.ToString("N"), item.Quantity.ToString(CultureInfo.InvariantCulture), item.SupplierLot?.Trim() ?? "", item.ExpiresOn, item.Notes?.Trim() ?? ""))));
        return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical))).ToLowerInvariant();
    }
    private sealed class ExistingReceipt { public Guid Id { get; init; } public string? RequestFingerprint { get; init; } }
    private sealed class RequisitionRow { public string Status { get; init; } = string.Empty; public long Version { get; init; } public Guid RequesterId { get; init; } }
    private sealed class OrderCancelRow { public string Status { get; init; } = string.Empty; public long Version { get; init; } public Guid? RequisitionId { get; init; } }
    private sealed class ReceiptOrderRow { public decimal Total { get; init; } public Guid? CostCenterId { get; init; } public string SupplierName { get; init; } = string.Empty; }
    private sealed class ReceiptItemRow { public Guid Id { get; init; } public decimal Quantity { get; init; } public decimal ReceivedQuantity { get; init; } public decimal UnitPrice { get; init; } public string Unit { get; init; } = string.Empty; public string? ProductBaseUnit { get; init; } public string Name { get; init; } = string.Empty; public bool RequiresLot { get; init; } public bool RequiresExpiry { get; init; } public bool RequiresInspection { get; init; } public string ItemType { get; init; } = string.Empty; public Guid? RelatedProductId { get; init; } }
    private sealed class QualityRow { public decimal Quantity { get; init; } public decimal Released { get; init; } public decimal Rejected { get; init; } public Guid WarehouseId { get; init; } public Guid ProductId { get; init; } public string Unit { get; init; } = string.Empty; public string? Lot { get; init; } public DateOnly? ExpiresOn { get; init; } public decimal UnitCost { get; init; } public Guid ReceiptId { get; init; } }
    private sealed class MatchOrderRow { public Guid SupplierId { get; init; } public decimal Total { get; init; } public DateOnly DeliveryOn { get; init; } public string Status { get; init; } = string.Empty; }
    private sealed class MatchLineRow { public decimal OrderedQuantity { get; init; } public string Unit { get; init; } = string.Empty; public decimal UnitPrice { get; init; } public decimal Discount { get; init; } public string ItemType { get; init; } = string.Empty; public decimal ReceivedQuantity { get; init; } public string QualityStatus { get; init; } = string.Empty; public DateTimeOffset ReceivedAt { get; init; } public decimal AcceptedQuantity { get; init; } public decimal AlreadyBilled { get; init; } }
    private sealed class MatchToleranceRow { public decimal QuantityPercent { get; init; } public decimal QuantityAbsolute { get; init; } public decimal PricePercent { get; init; } public decimal PriceAbsolute { get; init; } public decimal TotalPercent { get; init; } public decimal TotalAbsolute { get; init; } public decimal ExcessPercent { get; init; } public decimal ExcessAbsolute { get; init; } public int DeliveryDays { get; init; } public bool SeparationOfDuties { get; init; } = true; public long Version { get; init; } }
    private sealed record MatchDivergence(string Type, Guid? BillingLineId, BillingLineCommand? Line, decimal Expected, decimal Actual, decimal Difference, decimal? Percent, string Action, string Snapshot);
    private sealed class DivergenceRow { public Guid MatchId { get; init; } public Guid CreatedBy { get; init; } public bool SeparationOfDuties { get; init; } }
}
