using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class ReplenishmentService(DatabaseExecutor db, ITenantContext tenant) : IReplenishmentService
{
    public Task<dynamic> OptionsAsync(CancellationToken ct) => db.InTenantTransactionAsync<dynamic>(async (c,t) =>
    {
        using var grid=await c.QueryMultipleAsync(new CommandDefinition("select id,sku,name,base_unit from agro360.inventory_products where tenant_id=@TenantId and deleted_at is null order by name;select id,code,name from agro360.inventory_warehouses where tenant_id=@TenantId and deleted_at is null order by name;select id,name from agro360.identity_users where tenant_id=@TenantId and deleted_at is null order by name",new{tenant.TenantId},t,cancellationToken:ct));
        return new { products=(await grid.ReadAsync()).AsList(), warehouses=(await grid.ReadAsync()).AsList(), responsibles=(await grid.ReadAsync()).AsList() };
    },ct);

    public Task<IReadOnlyList<dynamic>> PoliciesAsync(MaterialNeedQuery query,CancellationToken ct)=>db.InTenantTransactionAsync<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition("select p.*,i.name product,i.base_unit,w.name warehouse,u.name responsible from agro360.inventory_replenishment_policies p join agro360.inventory_products i on i.tenant_id=p.tenant_id and i.id=p.product_id join agro360.inventory_warehouses w on w.tenant_id=p.tenant_id and w.id=p.warehouse_id join agro360.identity_users u on u.tenant_id=p.tenant_id and u.id=p.responsible_id where p.tenant_id=@TenantId and (@ProductId is null or p.product_id=@ProductId) and (@WarehouseId is null or p.warehouse_id=@WarehouseId) and (@ResponsibleId is null or p.responsible_id=@ResponsibleId) and (@Status is null or p.status=@Status) order by i.name,w.name,p.id limit @Take offset @Skip",Args(query),t,cancellationToken:ct))).AsList(),ct);

    public Task<Guid> SavePolicyAsync(Guid? id,ReplenishmentPolicyCommand command,CancellationToken ct)=>db.InTenantTransactionAsync<Guid>(async(c,t)=>
    {
        if(command.MinimumStock<0||command.TargetStock<command.MinimumStock||command.ReplenishmentDays<0||command.MinimumPurchase<0||command.PurchaseMultiple<=0||command.StockPerPurchaseUnit<=0) throw new DomainException("Revise mínimos, objetivo, prazo, lote, múltiplo e conversão.","agro360.replenishment_policy_invalid");
        if(string.IsNullOrWhiteSpace(command.PurchaseUnit)||command.Status is not ("ACTIVE" or "INACTIVE")) throw new DomainException("Unidade de compra e situação válidas são obrigatórias.","agro360.replenishment_policy_invalid");
        var valid=await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.inventory_products where tenant_id=@TenantId and id=@ProductId and deleted_at is null) and exists(select 1 from agro360.inventory_warehouses where tenant_id=@TenantId and id=@WarehouseId and deleted_at is null) and exists(select 1 from agro360.identity_users where tenant_id=@TenantId and id=@ResponsibleId and deleted_at is null)",new{tenant.TenantId,command.ProductId,command.WarehouseId,command.ResponsibleId},t,cancellationToken:ct));
        if(!valid) throw new DomainException("Produto, depósito ou responsável não pertence ao contexto autorizado.","agro360.replenishment_scope_invalid");
        var key=id??Guid.CreateVersion7(); var p=new DynamicParameters(command);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);
        try { var sql=id is null?"insert into agro360.inventory_replenishment_policies(id,tenant_id,product_id,warehouse_id,minimum_stock,target_stock,replenishment_days,minimum_purchase,purchase_multiple,purchase_unit,stock_per_purchase_unit,responsible_id,status,created_by,updated_by) values(@Id,@TenantId,@ProductId,@WarehouseId,@MinimumStock,@TargetStock,@ReplenishmentDays,@MinimumPurchase,@PurchaseMultiple,upper(@PurchaseUnit),@StockPerPurchaseUnit,@ResponsibleId,@Status,@UserId,@UserId)":"update agro360.inventory_replenishment_policies set minimum_stock=@MinimumStock,target_stock=@TargetStock,replenishment_days=@ReplenishmentDays,minimum_purchase=@MinimumPurchase,purchase_multiple=@PurchaseMultiple,purchase_unit=upper(@PurchaseUnit),stock_per_purchase_unit=@StockPerPurchaseUnit,responsible_id=@ResponsibleId,status=@Status,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and (@Version is null or version=@Version)"; if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0) throw new ConflictException("A política foi alterada por outra pessoa. Recarregue antes de salvar."); }
        catch(Npgsql.PostgresException e) when(e.SqlState=="23505"){throw new ConflictException("Já existe política ativa para este produto e depósito.");} return key;
    },ct);

    public Task<dynamic> NeedsAsync(MaterialNeedQuery query,CancellationToken ct)=>db.InTenantTransactionAsync<dynamic>(async(c,t)=>
    { var a=Args(query); const string where="n.tenant_id=@TenantId and (@ProductId is null or n.product_id=@ProductId) and (@WarehouseId is null or n.warehouse_id=@WarehouseId) and (@ResponsibleId is null or p.responsible_id=@ResponsibleId) and (@Status is null or n.status=@Status) and (@NeededUntil is null or n.needed_on<=@NeededUntil) and (@UncoveredOnly is null or not @UncoveredOnly or n.operational_need>0)"; var items=(await c.QueryAsync(new CommandDefinition($"select n.*,i.name product,i.base_unit,w.name warehouse,p.responsible_id from agro360.inventory_material_needs n join agro360.inventory_replenishment_policies p on p.tenant_id=n.tenant_id and p.id=n.policy_id join agro360.inventory_products i on i.tenant_id=n.tenant_id and i.id=n.product_id join agro360.inventory_warehouses w on w.tenant_id=n.tenant_id and w.id=n.warehouse_id where {where} order by n.needed_on,n.product_id,n.id limit @Take offset @Skip",a,t,cancellationToken:ct))).AsList();var total=await c.ExecuteScalarAsync<int>(new CommandDefinition($"select count(*) from agro360.inventory_material_needs n join agro360.inventory_replenishment_policies p on p.tenant_id=n.tenant_id and p.id=n.policy_id where {where}",a,t,cancellationToken:ct));return new{items,total,page=Math.Max(query.Page,1),pageSize=Math.Clamp(query.PageSize,1,100)};},ct);

    public Task<Guid> AnalyzeAsync(AnalyzeMaterialNeedCommand command,CancellationToken ct)=>db.InTenantTransactionAsync<Guid>(async(c,t)=>
    {
        if(command.HorizonOn<command.NeededOn) throw new DomainException("O horizonte não pode terminar antes da data necessária.","agro360.replenishment_horizon_invalid");
        var p=await c.QuerySingleOrDefaultAsync<Policy>(new CommandDefinition("select * from agro360.inventory_replenishment_policies where tenant_id=@TenantId and id=@Id and status='ACTIVE' for share",new{tenant.TenantId,Id=command.PolicyId},t,cancellationToken:ct))??throw new NotFoundException("Política de reposição",command.PolicyId);
        var s=await c.QuerySingleAsync<Scenario>(new CommandDefinition(@"select coalesce(b.available,0) available,coalesce(b.reserved,0) reserved,
coalesce((select sum(greatest(0,i.requested-i.reserved-i.delivered)) from agro360.inventory_material_request_items i join agro360.inventory_material_requests r on r.tenant_id=i.tenant_id and r.id=i.request_id where i.tenant_id=@TenantId and i.product_id=@ProductId and r.needed_on<=@NeededOn and r.status in('APPROVED','RESERVED','PARTIALLY_DELIVERED')),0) uncovered,
coalesce((select sum(oi.quantity-oi.received_quantity) from agro360.procurement_purchase_order_items oi join agro360.procurement_purchase_orders o on o.tenant_id=oi.tenant_id and o.id=oi.purchase_order_id join agro360.procurement_item_catalog ci on ci.tenant_id=oi.tenant_id and ci.id=oi.catalog_item_id where oi.tenant_id=@TenantId and ci.related_product_id=@ProductId and o.status in('APPROVED','PARTIALLY_RECEIVED') and o.delivery_on between current_date and @HorizonOn),0) purchase_inbound,
coalesce((select sum(ti.quantity-ti.received) from agro360.inventory_transfer_items ti join agro360.inventory_transfers tr on tr.tenant_id=ti.tenant_id and tr.id=ti.transfer_id where ti.tenant_id=@TenantId and ti.product_id=@ProductId and tr.destination_warehouse_id=@WarehouseId and tr.status in('AWAITING_SHIPMENT','IN_TRANSIT','PARTIALLY_RECEIVED') and tr.expected_on<=@HorizonOn),0) transfer_inbound,
coalesce((select sum(ri.quantity) from agro360.procurement_requisition_items ri join agro360.procurement_requisitions r on r.tenant_id=ri.tenant_id and r.id=ri.requisition_id join agro360.procurement_item_catalog ci on ci.tenant_id=ri.tenant_id and ci.id=ri.catalog_item_id where ri.tenant_id=@TenantId and ci.related_product_id=@ProductId and r.status in('OPEN','AWAITING_APPROVAL','APPROVED') and not exists(select 1 from agro360.procurement_purchase_orders o where o.tenant_id=r.tenant_id and o.requisition_id=r.id and o.status<>'CANCELLED')),0) open_requisitions
from (values(1))v(n) left join agro360.inventory_stock_balances b on b.tenant_id=@TenantId and b.product_id=@ProductId and b.warehouse_id=@WarehouseId",new{tenant.TenantId,p.ProductId,p.WarehouseId,command.NeededOn,command.HorizonOn},t,cancellationToken:ct));
        var usable=Math.Max(0,s.Available-s.Reserved); var projected=usable-s.Uncovered+s.PurchaseInbound+s.TransferInbound; var operational=Math.Max(0,p.TargetStock-(usable-s.Uncovered)); var suggestedStock=Math.Max(0,p.TargetStock-projected-s.OpenRequisitions); var purchase=suggestedStock==0?0:Math.Max(p.MinimumPurchase??0,decimal.Ceiling(suggestedStock/p.StockPerPurchaseUnit)); if(p.PurchaseMultiple is >0&&purchase>0) purchase=decimal.Ceiling(purchase/p.PurchaseMultiple.Value)*p.PurchaseMultiple.Value;
        var id=Guid.CreateVersion7(); var calculation=System.Text.Json.JsonSerializer.Serialize(new{formula="usable=available-reserved; operational=max(0,target-(usable-uncovered)); projected=usable-uncovered+confirmedInbound+transferInbound; suggested=max(0,target-projected-existingCoverage)",s.Available,s.Reserved,usable,s.Uncovered,s.PurchaseInbound,s.TransferInbound,s.OpenRequisitions,p.TargetStock,p.StockPerPurchaseUnit,roundingExcess=purchase*p.StockPerPurchaseUnit-suggestedStock,missingLeadTime=p.ReplenishmentDays is null});
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_material_needs(id,tenant_id,policy_id,product_id,warehouse_id,needed_on,horizon_on,usable_stock,reserved_stock,uncovered_demand,confirmed_inbound,transfer_inbound,existing_coverage,projected_stock,operational_need,suggested_stock_quantity,suggested_purchase_quantity,purchase_unit,calculation,created_by,updated_by) values(@Id,@TenantId,@PolicyId,@ProductId,@WarehouseId,@NeededOn,@HorizonOn,@Usable,@Reserved,@Uncovered,@PurchaseInbound,@TransferInbound,@OpenRequisitions,@Projected,@Operational,@SuggestedStock,@Purchase,@PurchaseUnit,@Calculation::jsonb,@UserId,@UserId)",new{Id=id,tenant.TenantId,PolicyId=p.Id,p.ProductId,p.WarehouseId,command.NeededOn,command.HorizonOn,Usable=usable,Reserved=s.Reserved,s.Uncovered,s.PurchaseInbound,s.TransferInbound,s.OpenRequisitions,Projected=projected,Operational=operational,SuggestedStock=suggestedStock,Purchase=purchase,p.PurchaseUnit,Calculation=calculation,tenant.UserId},t,cancellationToken:ct)); return id;
    },ct);

    public Task<dynamic> DetailAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync<dynamic>(async(c,t)=> await c.QuerySingleOrDefaultAsync(new CommandDefinition("select n.*,i.name product,i.base_unit,w.name warehouse,p.minimum_stock,p.target_stock,p.replenishment_days,p.minimum_purchase,p.purchase_multiple,p.stock_per_purchase_unit,(select coalesce(jsonb_agg(jsonb_build_object('warehouseId',b.warehouse_id,'warehouse',ow.name,'available',greatest(0,b.available-b.reserved-coalesce(op.minimum_stock,0)),'limitation','Preserva reservas e mínimo ativo da origem') order by ow.name),'[]'::jsonb) from agro360.inventory_stock_balances b join agro360.inventory_warehouses ow on ow.tenant_id=b.tenant_id and ow.id=b.warehouse_id left join agro360.inventory_replenishment_policies op on op.tenant_id=b.tenant_id and op.product_id=b.product_id and op.warehouse_id=b.warehouse_id and op.status='ACTIVE' where b.tenant_id=n.tenant_id and b.product_id=n.product_id and b.warehouse_id<>n.warehouse_id and b.available-b.reserved-coalesce(op.minimum_stock,0)>0) transfer_alternatives from agro360.inventory_material_needs n join agro360.inventory_replenishment_policies p on p.tenant_id=n.tenant_id and p.id=n.policy_id join agro360.inventory_products i on i.tenant_id=n.tenant_id and i.id=n.product_id join agro360.inventory_warehouses w on w.tenant_id=n.tenant_id and w.id=n.warehouse_id where n.tenant_id=@TenantId and n.id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Necessidade",id),ct);

    public Task<Guid> ConfirmPurchaseAsync(Guid id,ConfirmMaterialNeedCommand command,CancellationToken ct)=>db.InTenantTransactionAsync<Guid>(async(c,t)=>
    {
        if(string.IsNullOrWhiteSpace(command.IdempotencyKey))throw new DomainException("Chave de confirmação obrigatória.","agro360.idempotency_required"); await c.ExecuteAsync(new CommandDefinition("select pg_advisory_xact_lock(hashtextextended(@Key,0))",new{Key=$"{tenant.TenantId:N}:{id:N}"},t,cancellationToken:ct));
        var n=await c.QuerySingleOrDefaultAsync<Need>(new CommandDefinition("select n.*,p.stock_per_purchase_unit,c.id catalog_item_id from agro360.inventory_material_needs n join agro360.inventory_replenishment_policies p on p.tenant_id=n.tenant_id and p.id=n.policy_id join agro360.procurement_item_catalog c on c.tenant_id=n.tenant_id and c.related_product_id=n.product_id and c.active and c.deleted_at is null where n.tenant_id=@TenantId and n.id=@Id for update of n",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new DomainException("Necessidade ou item comprável ativo não encontrado.","agro360.replenishment_not_purchasable");
        if(n.RequisitionId is not null){if(n.IdempotencyKey==command.IdempotencyKey)return n.RequisitionId.Value;throw new ConflictException("Esta necessidade já foi encaminhada.");} if(n.Version!=command.Version)throw new ConflictException("O cenário mudou. Reanalise antes de confirmar."); var quantity=command.ConfirmedPurchaseQuantity??n.SuggestedPurchaseQuantity;if(quantity<=0)throw new DomainException("A quantidade confirmada deve ser positiva.","agro360.procurement_quantity_invalid");if(quantity!=n.SuggestedPurchaseQuantity&&string.IsNullOrWhiteSpace(command.Justification))throw new DomainException("Justifique o ajuste da quantidade sugerida.","agro360.replenishment_adjustment_reason_required");
        var req=Guid.CreateVersion7();var number=await c.ExecuteScalarAsync<long>(new CommandDefinition("select nextval('agro360.procurement_document_number_seq')",transaction:t,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition(@"insert into agro360.procurement_requisitions(id,tenant_id,number,requester_id,origin,justification,priority,needed_on,status,created_by,updated_by) values(@Req,@TenantId,@Number,@UserId,'REPLENISHMENT',@Reason,'MEDIUM',@NeededOn,'OPEN',@UserId,@UserId);insert into agro360.procurement_requisition_items(id,tenant_id,requisition_id,catalog_item_id,quantity,unit,notes,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Req,@CatalogItemId,@Quantity,@Unit,@Notes,@UserId,@UserId);update agro360.inventory_material_needs set status='FORWARDED',requisition_id=@Req,idempotency_key=@Key,decision_reason=@Reason,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{Req=req,tenant.TenantId,Number=$"REQ-{DateTime.UtcNow:yyyy}-{number:000000}",tenant.UserId,n.NeededOn,n.CatalogItemId,Quantity=quantity,Unit=n.PurchaseUnit,Notes=$"Necessidade {id}; {quantity*n.StockPerPurchaseUnit} em unidade de estoque",Key=command.IdempotencyKey,Reason=command.Justification??"Quantidade sugerida confirmada",Id=id},t,cancellationToken:ct));return req;
    },ct);
    public Task DismissAsync(Guid id,long version,string reason,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(string.IsNullOrWhiteSpace(reason))throw new DomainException("Informe o motivo da dispensa.","agro360.replenishment_reason_required");if(await c.ExecuteAsync(new CommandDefinition("update agro360.inventory_material_needs set status='DISMISSED',decision_reason=@Reason,version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and version=@Version and status in('IDENTIFIED','ANALYSIS')",new{tenant.TenantId,Id=id,Version=version,Reason=reason,tenant.UserId},t,cancellationToken:ct))==0)throw new ConflictException("A necessidade foi alterada ou não pode mais ser dispensada.");},ct);
    private object Args(MaterialNeedQuery query)=>new{tenant.TenantId,query.ProductId,query.WarehouseId,query.ResponsibleId,Status=string.IsNullOrWhiteSpace(query.Status)?null:query.Status,query.NeededUntil,query.UncoveredOnly,Take=Math.Clamp(query.PageSize,1,100),Skip=(Math.Max(query.Page,1)-1)*Math.Clamp(query.PageSize,1,100)};
    private sealed class Policy { public Guid Id{get;init;} public Guid ProductId{get;init;} public Guid WarehouseId{get;init;} public decimal TargetStock{get;init;} public decimal? MinimumPurchase{get;init;} public decimal? PurchaseMultiple{get;init;} public decimal StockPerPurchaseUnit{get;init;} public string PurchaseUnit{get;init;}=""; public int? ReplenishmentDays{get;init;} }
    private sealed class Scenario { public decimal Available{get;init;} public decimal Reserved{get;init;} public decimal Uncovered{get;init;} public decimal PurchaseInbound{get;init;} public decimal TransferInbound{get;init;} public decimal OpenRequisitions{get;init;} }
    private sealed class Need { public long Version{get;init;} public Guid? RequisitionId{get;init;} public string? IdempotencyKey{get;init;} public decimal SuggestedPurchaseQuantity{get;init;} public string PurchaseUnit{get;init;}="";public DateOnly NeededOn{get;init;}public Guid CatalogItemId{get;init;}public decimal StockPerPurchaseUnit{get;init;} }
}
