using System.Text.RegularExpressions;
using Agro360.Application.Abstractions;
using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.Domain.Tenancy;
using Dapper;
using Microsoft.Extensions.Logging;

namespace Agro360.Infrastructure.Services;

public sealed partial class SaasService(DatabaseExecutor db, ITenantContext tenant, ILogger<SaasService> logger) : ISaasService
{
    public Task<IReadOnlyList<TenantSummary>> GetTenantsAsync(CancellationToken ct) => System("list-tenants", async (c,t) => (IReadOnlyList<TenantSummary>)(await c.QueryAsync<TenantSummary>("select x.id,x.slug,x.name,s.organization_type type,s.document,s.responsible_name ResponsibleName,s.responsible_email ResponsibleEmail,s.plan_id PlanId,p.name PlanName,s.status,s.activated_at ActivatedAt,s.blocked_at BlockedAt,s.block_reason BlockReason from tenancy.tenants x join saas.organizations s on s.tenant_id=x.id join saas.plans p on p.id=s.plan_id where x.deleted_at is null order by x.name",transaction:t)).ToArray(),ct);
    public Task<Guid> CreateTenantAsync(TenantCommand x,Guid actor,CancellationToken ct)=>System("create-tenant",async(c,t)=>{ValidateTenant(x);if(!await c.ExecuteScalarAsync<bool>("select exists(select 1 from saas.plans where id=@PlanId and active)",new{x.PlanId},t))throw new InvalidOperationException("Plano inativo ou inexistente não pode ser atribuído.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into tenancy.tenants(id,slug,name,status,created_at) values(@Id,@Slug,@Name,2,now()); insert into saas.organizations(tenant_id,organization_type,document,responsible_name,responsible_email,plan_id,status) values(@Id,@Type,@Document,@ResponsibleName,@ResponsibleEmail,@PlanId,'IMPLEMENTING'); insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@Id,@Actor,'TENANT_CREATED',jsonb_build_object('planId',@PlanId))",new{Id=id,Slug=x.Slug.Trim().ToLowerInvariant(),Name=x.Name.Trim(),x.Type,Document=SaasGovernanceRules.NormalizeAndValidateDocument(x.Document),x.ResponsibleName,x.ResponsibleEmail,x.PlanId,Actor=actor},t);return id;},ct);
    public Task UpdateTenantAsync(Guid id,TenantUpdateCommand x,Guid actor,CancellationToken ct)=>System("update-tenant",async(c,t)=>{ValidateUpdate(x);var n=await c.ExecuteAsync("with old as (select plan_id from saas.organizations where tenant_id=@Id), u as (update tenancy.tenants set name=@Name where id=@Id returning id) update saas.organizations set organization_type=@Type,responsible_name=@ResponsibleName,responsible_email=@ResponsibleEmail,plan_id=@PlanId,updated_at=now() where tenant_id=@Id; insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) select gen_random_uuid(),@Id,@Actor,'TENANT_UPDATED',jsonb_build_object('planId',@PlanId,'previousPlanId',plan_id) from old",new{id,Name=x.Name.Trim(),x.Type,x.ResponsibleName,x.ResponsibleEmail,x.PlanId,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Organização não encontrada.");},ct);
    public Task SetTenantStatusAsync(Guid id,string status,string? reason,Guid actor,CancellationToken ct)=>System("tenant-status",async(c,t)=>{var current=await c.QuerySingleOrDefaultAsync<string>("select status from saas.organizations where tenant_id=@Id",new{id},t)??throw new KeyNotFoundException("Organização não encontrada.");SaasGovernanceRules.EnsureStatusTransition(current,status,reason);var n=await c.ExecuteAsync("update saas.organizations set status=@Status,activated_at=case when @Status='ACTIVE' then coalesce(activated_at,now()) else activated_at end,blocked_at=case when @Status='SUSPENDED' then now() else null end,block_reason=@Reason,updated_at=now() where tenant_id=@Id; update tenancy.tenants set status=case when @Status='ACTIVE' then 1 when @Status in ('IMPLEMENTING','TRIAL') then 2 else 3 end where id=@Id; insert into saas.tenant_status_events(id,tenant_id,previous_status,new_status,reason,created_by) values(gen_random_uuid(),@Id,@Current,@Status,@Reason,@Actor); insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@Id,@Actor,'TENANT_STATUS_CHANGED',jsonb_build_object('previousStatus',@Current,'status',@Status,'reason',@Reason))",new{id,status,Current=current,Reason=reason?.Trim(),Actor=actor},t);if(n==0)throw new KeyNotFoundException("Organização não encontrada.");},ct);
    public Task<IReadOnlyList<PlanSummary>> GetPlansAsync(CancellationToken ct)=>System("plans",async(c,t)=>(IReadOnlyList<PlanSummary>)(await c.QueryAsync<PlanSummary>("select id,name,description,monthly_price MonthlyPrice,annual_price AnnualPrice,user_limit UserLimit,property_limit PropertyLimit,storage_limit_mb StorageLimitMb,device_limit DeviceLimit,modules,premium_features PremiumFeatures,active from saas.plans order by monthly_price",transaction:t)).ToArray(),ct);
    public Task<Guid> CreatePlanAsync(PlanCommand x,Guid actor,CancellationToken ct)=>System("create-plan",async(c,t)=>{ValidatePlan(x);var id=Guid.NewGuid();await c.ExecuteAsync("insert into saas.plans(id,name,description,monthly_price,annual_price,user_limit,property_limit,storage_limit_mb,device_limit,modules,premium_features,active) values(@Id,@Name,@Description,@MonthlyPrice,@AnnualPrice,@UserLimit,@PropertyLimit,@StorageLimitMb,@DeviceLimit,@Modules,@PremiumFeatures,@Active); insert into audit.saas_events(id,actor_id,event_type,details) values(gen_random_uuid(),@Actor,'PLAN_CREATED',jsonb_build_object('planId',@Id))",new{Id=id,x.Name,x.Description,x.MonthlyPrice,x.AnnualPrice,x.UserLimit,x.PropertyLimit,x.StorageLimitMb,x.DeviceLimit,x.Modules,x.PremiumFeatures,x.Active,Actor=actor},t);return id;},ct);
    public Task UpdatePlanAsync(Guid id,PlanCommand x,Guid actor,CancellationToken ct)=>System("update-plan",async(c,t)=>{ValidatePlan(x);var n=await c.ExecuteAsync("update saas.plans p set name=@Name,description=@Description,monthly_price=@MonthlyPrice,annual_price=@AnnualPrice,user_limit=greatest(@UserLimit,(select count(*) from identity.users u join saas.organizations o on o.tenant_id=u.tenant_id where o.plan_id=p.id and u.status=1)),property_limit=greatest(@PropertyLimit,(select count(*) from geo.farms f join saas.organizations o on o.tenant_id=f.tenant_id where o.plan_id=p.id and f.deleted_at is null)),storage_limit_mb=@StorageLimitMb,device_limit=@DeviceLimit,modules=@Modules,premium_features=@PremiumFeatures,active=@Active,updated_at=now() where id=@Id; insert into audit.saas_events(id,actor_id,event_type,details) values(gen_random_uuid(),@Actor,'PLAN_UPDATED',jsonb_build_object('planId',@Id))",new{Id=id,x.Name,x.Description,x.MonthlyPrice,x.AnnualPrice,x.UserLimit,x.PropertyLimit,x.StorageLimitMb,x.DeviceLimit,x.Modules,x.PremiumFeatures,x.Active,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Plano não encontrado.");},ct);
    public Task<IReadOnlyList<UsageSummary>> GetPlatformUsageAsync(CancellationToken ct)=>System("usage",async(c,t)=>(IReadOnlyList<UsageSummary>)(await c.QueryAsync<UsageSummary>(UsageSql,transaction:t)).ToArray(),ct);
    public async Task<UsageSummary> GetUsageAsync(CancellationToken ct)=>(await Tenant("usage",async(c,t)=>(await c.QueryAsync<UsageSummary>(UsageSql+" where o.tenant_id=@TenantId",new{tenant.TenantId},t)).Single(),ct));
    public Task<PlatformDashboard> GetDashboardAsync(CancellationToken ct)=>System("dashboard",async(c,t)=>await c.QuerySingleAsync<PlatformDashboard>("select count(*) TotalOrganizations,count(*) filter(where status='ACTIVE') ActiveOrganizations,count(*) filter(where status in ('SUSPENDED','BLOCKED')) SuspendedOrganizations,count(*) filter(where created_at>=date_trunc('month',now())) NewThisMonth,(select count(*) from identity.users where status='ACTIVE') ActiveUsers,0 NearLimit,0 AboveLimit,(select count(*) from saas.invitations where status='PENDING' and expires_at>now()) PendingInvitations,(select count(*) from saas.login_history where occurred_at>=now()-interval '24 hours' and success) RecentLogins,(select count(*) from saas.login_history where occurred_at>=now()-interval '24 hours' and not success) SecurityAlerts,(select count(*) from saas.requests where type='UPGRADE' and status='OPEN') UpgradeRequests,(select count(*) from saas.requests where type='SUPPORT' and status='OPEN') SupportRequests from saas.organizations",transaction:t),ct);
    public Task<TenantSummary> GetOrganizationAsync(CancellationToken ct)=>Tenant("organization",async(c,t)=>await c.QuerySingleAsync<TenantSummary>("select x.id,x.slug,x.name,s.organization_type type,s.document,s.responsible_name ResponsibleName,s.responsible_email ResponsibleEmail,s.plan_id PlanId,p.name PlanName,s.status,s.activated_at ActivatedAt,s.blocked_at BlockedAt,s.block_reason BlockReason from tenancy.tenants x join saas.organizations s on s.tenant_id=x.id join saas.plans p on p.id=s.plan_id where x.id=@TenantId",new{tenant.TenantId},t),ct);
    public Task UpdateOrganizationAsync(TenantUpdateCommand x,Guid actor,CancellationToken ct)=>Tenant("organization-update",async(c,t)=>{ValidateUpdate(x);await c.ExecuteAsync("update tenancy.tenants set name=@Name where id=@TenantId; update saas.organizations set organization_type=@Type,responsible_name=@ResponsibleName,responsible_email=@ResponsibleEmail,updated_at=now() where tenant_id=@TenantId; insert into audit.saas_events(id,tenant_id,actor_id,event_type) values(gen_random_uuid(),@TenantId,@Actor,'ORGANIZATION_UPDATED')",new{tenant.TenantId,x.Name,x.Type,x.ResponsibleName,x.ResponsibleEmail,Actor=actor},t);},ct);
    public Task<PlanSummary> GetCurrentPlanAsync(CancellationToken ct)=>Tenant("current-plan",async(c,t)=>await c.QuerySingleAsync<PlanSummary>("select p.id,p.name,p.description,p.monthly_price MonthlyPrice,p.annual_price AnnualPrice,p.user_limit UserLimit,p.property_limit PropertyLimit,p.storage_limit_mb StorageLimitMb,p.device_limit DeviceLimit,p.modules,p.premium_features PremiumFeatures,p.active from saas.plans p join saas.organizations o on o.plan_id=p.id where o.tenant_id=@TenantId",new{tenant.TenantId},t),ct);
    public Task<Guid> RequestUpgradeAsync(UpgradeRequestCommand x,Guid actor,CancellationToken ct)=>Tenant("upgrade",async(c,t)=>{if(x.RequestedPlanId==Guid.Empty||string.IsNullOrWhiteSpace(x.Reason))throw new ArgumentException("Plano e justificativa são obrigatórios.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into saas.requests(id,tenant_id,type,requested_plan_id,reason,requested_by) values(@Id,@TenantId,'UPGRADE',@RequestedPlanId,@Reason,@Actor); insert into saas.notifications(id,tenant_id,user_id,type,priority,title,message,route,requires_action) select gen_random_uuid(),@TenantId,u.id,'SUBSCRIPTION','HIGH','Solicitação de upgrade',@Reason,'/saas/solicitacoes',true from identity.users u where u.is_platform_admin limit 1",new{Id=id,tenant.TenantId,x.RequestedPlanId,Reason=x.Reason.Trim(),Actor=actor},t);return id;},ct);
    public Task<IReadOnlyList<UserSummary>> GetUsersAsync(CancellationToken ct)=>Tenant("users",async(c,t)=>(IReadOnlyList<UserSummary>)(await c.QueryAsync<UserSummary>("select u.id,u.name,u.email,u.status,u.last_login_at LastAccess,coalesce(array_agg(r.name) filter(where r.id is not null),array[]::varchar[]) roles from identity.users u left join identity.user_roles ur on ur.tenant_id=u.tenant_id and ur.user_id=u.id left join identity.roles r on r.id=ur.role_id where u.tenant_id=@TenantId and u.deleted_at is null group by u.id order by u.name",new{tenant.TenantId},t)).ToArray(),ct);
    public Task<Guid> SaveUserAsync(Guid? id,UserCommand x,Guid actor,CancellationToken ct)=>Tenant("save-user",async(c,t)=>{if(string.IsNullOrWhiteSpace(x.Name)||!EmailRegex().IsMatch(x.Email)||x.RoleIds.Length==0)throw new ArgumentException("Nome, e-mail válido e perfil são obrigatórios.");var limit=await c.QuerySingleAsync<(long Used,int Limit)>("select count(*) Used,p.user_limit Limit from identity.users u cross join saas.organizations o join saas.plans p on p.id=o.plan_id where o.tenant_id=@TenantId and u.tenant_id=@TenantId and u.status='ACTIVE' group by p.user_limit",new{tenant.TenantId},t);if(id is null&&limit.Used>=limit.Limit){logger.LogWarning("Limite de usuários violado no tenant {TenantId}",tenant.TenantId);throw new InvalidOperationException($"Limite do plano atingido: {limit.Used} de {limit.Limit} usuários.");}var key=id??Guid.NewGuid();await c.ExecuteAsync("insert into identity.users(id,tenant_id,name,email,password_hash,status,created_by) values(@Id,@TenantId,@Name,@Email,encode(digest(gen_random_uuid()::text,'sha256'),'hex'),'INVITED',@Actor) on conflict(id) do update set name=excluded.name,email=excluded.email,updated_at=now(),updated_by=@Actor where identity.users.tenant_id=@TenantId; delete from identity.user_roles where tenant_id=@TenantId and user_id=@Id; insert into identity.user_roles(tenant_id,user_id,role_id) select @TenantId,@Id,id from identity.roles where tenant_id=@TenantId and id=any(@RoleIds); insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@TenantId,@Actor,'USER_ROLE_CHANGED',jsonb_build_object('userId',@Id))",new{Id=key,tenant.TenantId,Name=x.Name.Trim(),Email=x.Email.Trim().ToLowerInvariant(),x.RoleIds,Actor=actor},t);return key;},ct);
    public Task SetUserActiveAsync(Guid id,bool active,Guid actor,CancellationToken ct)=>Tenant("user-status",async(c,t)=>{var n=await c.ExecuteAsync("update identity.users set status=@Status,updated_at=now(),updated_by=@Actor where id=@Id and tenant_id=@TenantId",new{id,tenant.TenantId,Status=active?"ACTIVE":"DISABLED",Actor=actor},t);if(n==0)throw new KeyNotFoundException("Usuário não encontrado.");},ct);
    public Task<IReadOnlyList<RoleSummary>> GetRolesAsync(CancellationToken ct)=>Tenant("roles",async(c,t)=>(IReadOnlyList<RoleSummary>)(await c.QueryAsync<RoleSummary>("select r.id,r.name,coalesce(m.level,10) level,coalesce(array_agg(p.code) filter(where p.id is not null),array[]::varchar[]) permissions,r.is_system SystemRole from identity.roles r left join saas.role_metadata m on m.tenant_id=r.tenant_id and m.role_id=r.id left join identity.role_permissions rp on rp.tenant_id=r.tenant_id and rp.role_id=r.id left join identity.permissions p on p.id=rp.permission_id where r.tenant_id=@TenantId and r.code<>'PLATFORM_SUPER_ADMIN' group by r.id,m.level order by m.level desc,r.name",new{tenant.TenantId},t)).ToArray(),ct);
    public Task<Guid> SaveRoleAsync(Guid? id,RoleCommand x,Guid actor,CancellationToken ct)=>Tenant("save-role",async(c,t)=>{if(string.IsNullOrWhiteSpace(x.Name)||x.Level is <1 or >90)throw new ArgumentException("Nome e nível entre 1 e 90 são obrigatórios.");var key=id??Guid.NewGuid();await c.ExecuteAsync("insert into identity.roles(id,tenant_id,code,name,is_system) values(@Id,@TenantId,@Code,@Name,false) on conflict(id) do update set name=excluded.name where identity.roles.tenant_id=@TenantId and not identity.roles.is_system; insert into saas.role_metadata(tenant_id,role_id,level) values(@TenantId,@Id,@Level) on conflict(tenant_id,role_id) do update set level=excluded.level; delete from identity.role_permissions where tenant_id=@TenantId and role_id=@Id; insert into identity.role_permissions(tenant_id,role_id,permission_id) select @TenantId,@Id,id from identity.permissions where code=any(@Permissions); insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@TenantId,@Actor,'ROLE_CHANGED',jsonb_build_object('roleId',@Id))",new{Id=key,tenant.TenantId,Code="CUSTOM_"+key.ToString("N"),Name=x.Name.Trim(),x.Level,x.Permissions,Actor=actor},t);return key;},ct);
    public Task<IReadOnlyList<InvitationSummary>> GetInvitationsAsync(CancellationToken ct)=>Tenant("invitations",async(c,t)=>(IReadOnlyList<InvitationSummary>)(await c.QueryAsync<InvitationSummary>("select i.id,i.email,r.name RoleName,case when i.status='PENDING' and i.expires_at<=now() then 'EXPIRED' else i.status end status,i.expires_at ExpiresAt from saas.invitations i join identity.roles r on r.id=i.role_id where i.tenant_id=@TenantId order by i.created_at desc",new{tenant.TenantId},t)).ToArray(),ct);
    public Task<Guid> InviteAsync(InvitationCommand x,Guid actor,CancellationToken ct)=>Tenant("invite",async(c,t)=>{if(!EmailRegex().IsMatch(x.Email)||x.RoleId==Guid.Empty||x.ValidForHours is <1 or >168)throw new ArgumentException("E-mail, perfil e validade de até 168 horas são obrigatórios.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into saas.invitations(id,tenant_id,email,role_id,token_hash,expires_at,invited_by) select @Id,@TenantId,@Email,id,encode(digest(gen_random_uuid()::text,'sha256'),'hex'),now()+make_interval(hours=>@Hours),@Actor from identity.roles where id=@RoleId and tenant_id=@TenantId",new{Id=id,tenant.TenantId,Email=x.Email.Trim().ToLowerInvariant(),x.RoleId,Hours=x.ValidForHours,Actor=actor},t);return id;},ct);
    public Task ChangeInvitationAsync(Guid id,string action,Guid actor,CancellationToken ct)=>Tenant("invitation-action",async(c,t)=>{if(action is not("resend" or "cancel"))throw new ArgumentException("Ação inválida.");var n=await c.ExecuteAsync("update saas.invitations set status=case when @Action='cancel' then 'CANCELLED' else 'PENDING' end,expires_at=case when @Action='resend' then now()+interval '72 hours' else expires_at end,token_hash=case when @Action='resend' then encode(digest(gen_random_uuid()::text,'sha256'),'hex') else token_hash end where id=@Id and tenant_id=@TenantId and status='PENDING'; insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@TenantId,@Actor,'INVITATION_'||upper(@Action),jsonb_build_object('invitationId',@Id))",new{id,tenant.TenantId,action,Actor=actor},t);if(n==0)throw new KeyNotFoundException("Convite pendente não encontrado.");},ct);
    public Task<IReadOnlyList<SessionSummary>> GetSessionsAsync(CancellationToken ct)=>Tenant("sessions",async(c,t)=>(IReadOnlyList<SessionSummary>)(await c.QueryAsync<SessionSummary>("select id,device,ip_address IpAddress,created_at CreatedAt,last_seen_at LastSeenAt,revoked_at RevokedAt from saas.sessions where tenant_id=@TenantId order by last_seen_at desc",new{tenant.TenantId},t)).ToArray(),ct);
    public Task RevokeSessionAsync(Guid id,Guid actor,CancellationToken ct)=>Revoke("sessions",id,actor,ct);
    public Task<IReadOnlyList<DeviceSummary>> GetDevicesAsync(CancellationToken ct)=>Tenant("devices",async(c,t)=>(IReadOnlyList<DeviceSummary>)(await c.QueryAsync<DeviceSummary>("select id,name,platform,last_seen_at LastSeenAt,revoked_at RevokedAt from saas.devices where tenant_id=@TenantId order by last_seen_at desc",new{tenant.TenantId},t)).ToArray(),ct);
    public Task RevokeDeviceAsync(Guid id,Guid actor,CancellationToken ct)=>Revoke("devices",id,actor,ct);
    private Task Revoke(string table,Guid id,Guid actor,CancellationToken ct)=>Tenant("revoke-"+table,async(c,t)=>{var sql=$"update saas.{table} set revoked_at=coalesce(revoked_at,now()),revoked_by=@Actor where id=@Id and tenant_id=@TenantId and revoked_at is null; insert into audit.saas_events(id,tenant_id,actor_id,event_type,details) values(gen_random_uuid(),@TenantId,@Actor,@Event,jsonb_build_object('id',@Id))";var n=await c.ExecuteAsync(sql,new{id,tenant.TenantId,Actor=actor,Event=table=="sessions"?"SESSION_REVOKED":"DEVICE_REVOKED"},t);if(n==0)throw new KeyNotFoundException("Registro ativo não encontrado.");},ct);
    public Task<IReadOnlyList<NotificationSummary>> GetNotificationsAsync(string? type,string? priority,CancellationToken ct)=>Tenant("notifications",async(c,t)=>(IReadOnlyList<NotificationSummary>)(await c.QueryAsync<NotificationSummary>("select id,type,priority,title,message,route,created_at CreatedAt,read_at ReadAt,archived_at ArchivedAt,requires_action RequiresAction from saas.notifications where tenant_id=@TenantId and (user_id is null or user_id=current_setting('app.user_id',true)::uuid) and (@Type is null or type=@Type) and (@Priority is null or priority=@Priority) order by created_at desc limit 200",new{tenant.TenantId,Type=type,Priority=priority},t)).ToArray(),ct);
    public Task ChangeNotificationAsync(Guid id,string action,CancellationToken ct)=>Tenant("notification-action",async(c,t)=>{if(action is not("read" or "archive"))throw new ArgumentException("Ação inválida.");var n=await c.ExecuteAsync("update saas.notifications set read_at=case when @Action='read' then coalesce(read_at,now()) else read_at end,archived_at=case when @Action='archive' and not requires_action then now() else archived_at end where id=@Id and tenant_id=@TenantId",new{id,tenant.TenantId,action},t);if(n==0)throw new KeyNotFoundException("Notificação não encontrada.");},ct);
    public Task<OrganizationSettings> GetSettingsAsync(CancellationToken ct)=>Tenant("settings",async(c,t)=>await c.QuerySingleAsync<OrganizationSettings>("select x.name OrganizationName,s.unit_system UnitSystem,s.currency,s.time_zone TimeZone,s.main_culture MainCulture,s.main_activities MainActivities,s.stock_parameters::text StockParameters,s.finance_parameters::text FinanceParameters,s.traceability_parameters::text TraceabilityParameters,s.compliance_parameters::text ComplianceParameters,s.notification_preferences NotificationPreferences from saas.organization_settings s join tenancy.tenants x on x.id=s.tenant_id where s.tenant_id=@TenantId",new{tenant.TenantId},t),ct);
    public Task UpdateSettingsAsync(OrganizationSettings x,Guid actor,CancellationToken ct)=>Tenant("settings-update",async(c,t)=>{if(string.IsNullOrWhiteSpace(x.OrganizationName)||x.Currency.Length!=3||string.IsNullOrWhiteSpace(x.TimeZone)||x.MainActivities.Length==0)throw new ArgumentException("Organização, moeda, fuso e atividades são obrigatórios.");await c.ExecuteAsync("update tenancy.tenants set name=@OrganizationName where id=@TenantId; update saas.organization_settings set unit_system=@UnitSystem,currency=upper(@Currency),time_zone=@TimeZone,main_culture=@MainCulture,main_activities=@MainActivities,stock_parameters=@StockParameters::jsonb,finance_parameters=@FinanceParameters::jsonb,traceability_parameters=@TraceabilityParameters::jsonb,compliance_parameters=@ComplianceParameters::jsonb,notification_preferences=@NotificationPreferences,updated_at=now(),updated_by=@Actor where tenant_id=@TenantId; insert into audit.saas_events(id,tenant_id,actor_id,event_type) values(gen_random_uuid(),@TenantId,@Actor,'SETTINGS_CHANGED')",new{tenant.TenantId,x.OrganizationName,x.UnitSystem,x.Currency,x.TimeZone,x.MainCulture,x.MainActivities,x.StockParameters,x.FinanceParameters,x.TraceabilityParameters,x.ComplianceParameters,x.NotificationPreferences,Actor=actor},t);},ct);
    private const string UsageSql="select o.tenant_id TenantId,t.name TenantName,(select count(*) from identity.users u where u.tenant_id=o.tenant_id and u.status='ACTIVE') ActiveUsers,p.user_limit UserLimit,(select count(*) from geo.farms f where f.tenant_id=o.tenant_id and f.deleted_at is null) Properties,p.property_limit PropertyLimit,(select count(*) from saas.devices d where d.tenant_id=o.tenant_id and d.revoked_at is null) Devices,p.device_limit DeviceLimit,coalesce(m.storage_used_mb,0) StorageUsedMb,p.storage_limit_mb StorageLimitMb,coalesce(m.tracked_lots,0) TrackedLots,coalesce(m.certificates,0) Certificates,coalesce(m.offline_records,0) OfflineRecords,coalesce(m.ledger_events,0) LedgerEvents,coalesce(m.exported_reports,0) ExportedReports from saas.organizations o join tenancy.tenants t on t.id=o.tenant_id join saas.plans p on p.id=o.plan_id left join saas.usage_metrics m on m.tenant_id=o.tenant_id";
    private static void ValidateTenant(TenantCommand x){if(string.IsNullOrWhiteSpace(x.Name)||!SlugRegex().IsMatch(x.Slug)||!EmailRegex().IsMatch(x.ResponsibleEmail)||x.PlanId==Guid.Empty)throw new ArgumentException("Organização, slug, CPF/CNPJ, responsável e plano válidos são obrigatórios.");SaasGovernanceRules.NormalizeAndValidateDocument(x.Document);}
    private static void ValidateUpdate(TenantUpdateCommand x){if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.ResponsibleName)||!EmailRegex().IsMatch(x.ResponsibleEmail)||x.PlanId==Guid.Empty)throw new ArgumentException("Dados da organização e plano são obrigatórios.");}
    private static void ValidatePlan(PlanCommand x){if(string.IsNullOrWhiteSpace(x.Name)||x.MonthlyPrice<0||x.AnnualPrice<0||x.UserLimit<1||x.PropertyLimit<1||x.StorageLimitMb<1||x.DeviceLimit<1||x.Modules.Length==0)throw new ArgumentException("Plano e limites positivos são obrigatórios.");}
    private Task<T> System<T>(string op,Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task<T>> work,CancellationToken ct)=>Guard(op,()=>db.InSystemTransactionAsync(work,ct));
    private Task System(string op,Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task> work,CancellationToken ct)=>Guard(op,()=>db.InSystemTransactionAsync(async(c,t)=>{await work(c,t);return true;},ct));
    private Task<T> Tenant<T>(string op,Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task<T>> work,CancellationToken ct)=>Guard(op,()=>db.InTenantTransactionAsync(work,ct));
    private Task Tenant(string op,Func<Npgsql.NpgsqlConnection,Npgsql.NpgsqlTransaction,Task> work,CancellationToken ct)=>Guard(op,()=>db.InTenantTransactionAsync(work,ct));
    private async Task<T> Guard<T>(string op,Func<Task<T>> work){try{return await work();}catch(Exception ex){logger.LogError(ex,"Falha SaaS {Operation} no tenant {TenantId}",op,tenant.TenantId);throw;}}
    private async Task Guard(string op,Func<Task> work){try{await work();}catch(Exception ex){logger.LogError(ex,"Falha SaaS {Operation} no tenant {TenantId}",op,tenant.TenantId);throw;}}
    private static string Digits(string value)=>new(value.Where(char.IsDigit).ToArray());
    [GeneratedRegex("^[a-z0-9]+(?:-[a-z0-9]+)*$")] private static partial Regex SlugRegex();
    [GeneratedRegex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")] private static partial Regex EmailRegex();
}
