using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class SalesService(DatabaseExecutor db, ITenantContext tenant, ILogger<SalesService> logger) : ISalesService
{
    public Task<IReadOnlyList<dynamic>> ListAsync(CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition("select * from commercial.agro_sales where tenant_id=@TenantId order by sold_on desc",new{tenant.TenantId},t,cancellationToken:ct))).AsList());
    public Task<dynamic?> GetAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>await c.QuerySingleOrDefaultAsync(new CommandDefinition("select * from commercial.agro_sales where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct)));
    public Task<Guid> SaveAsync(Guid? id,SaleCommand x,CancellationToken ct){if(x.Quantity<=0||x.UnitPrice<0||x.Installments<=0)throw new DomainException("Quantidade, preço ou parcelas inválidos.","commercial.sale_invalid");return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var sql=id is null?"insert into commercial.agro_sales(id,tenant_id,buyer,product_id,origin_type,origin_id,quantity,unit,unit_price,total_amount,sold_on,delivery_on,payment_terms,installments,warehouse_id,cost_center_id,status,created_by) values(@Id,@TenantId,@Buyer,@ProductId,@OriginType,@OriginId,@Quantity,@Unit,@UnitPrice,@Total,@SoldOn,@DeliveryOn,@PaymentTerms,@Installments,@WarehouseId,@CostCenterId,'DRAFT',@UserId)":"update commercial.agro_sales set buyer=@Buyer,product_id=@ProductId,origin_type=@OriginType,origin_id=@OriginId,quantity=@Quantity,unit=@Unit,unit_price=@UnitPrice,total_amount=@Total,sold_on=@SoldOn,delivery_on=@DeliveryOn,payment_terms=@PaymentTerms,installments=@Installments,warehouse_id=@WarehouseId,cost_center_id=@CostCenterId,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id and status='DRAFT'";var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);p.Add("Total",x.Quantity*x.UnitPrice);if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new ConflictException("Venda inexistente ou não editável.");await Audit(c,t,id is null?"create":"update",key,x,ct);return key;});}
    public Task ConfirmAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var s=await Lock(c,t,id,ct);if((string)s.status!="DRAFT")throw new ConflictException("Somente rascunho pode ser confirmado.");if(s.warehouse_id is not null){var n=await c.ExecuteAsync(new CommandDefinition("update inventory.stock_balances set reserved=reserved+@Quantity,version=version+1,updated_at=now() where tenant_id=@TenantId and warehouse_id=@Warehouse and product_id=@Product and available-reserved>=@Quantity",new{tenant.TenantId,Warehouse=(Guid)s.warehouse_id,Product=(Guid)s.product_id,Quantity=(decimal)s.quantity},t,cancellationToken:ct));if(n==0)throw new ConflictException("Estoque insuficiente.","inventory.insufficient_stock");}await c.ExecuteAsync(new CommandDefinition("update commercial.agro_sales set status='CONFIRMED',updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=id},t,cancellationToken:ct));await Audit(c,t,"confirm",id,new{},ct);});
    public Task InvoiceAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var s=await Lock(c,t,id,ct);if((string)s.status!="CONFIRMED")throw new ConflictException("Venda deve estar confirmada.");if(s.warehouse_id is not null)await c.ExecuteAsync(new CommandDefinition("update inventory.stock_balances set available=available-@Quantity,reserved=greatest(reserved-@Quantity,0),version=version+1,updated_at=now() where tenant_id=@TenantId and warehouse_id=@Warehouse and product_id=@Product",new{tenant.TenantId,Warehouse=(Guid)s.warehouse_id,Product=(Guid)s.product_id,Quantity=(decimal)s.quantity},t,cancellationToken:ct));if((string)s.origin_type=="ANIMAL")await c.ExecuteAsync(new CommandDefinition("update livestock.animals set status=3,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Origin",new{tenant.TenantId,tenant.UserId,Origin=(Guid?)s.origin_id},t,cancellationToken:ct));var installments=Convert.ToInt32(s.installments);var total=(decimal)s.total_amount;for(var i=1;i<=installments;i++){var amount=i==installments?total-Math.Round(total/installments,2)*(installments-1):Math.Round(total/installments,2);await c.ExecuteAsync(new CommandDefinition("insert into finance.receivables(id,tenant_id,customer_name,document,original_amount,discount,interest,fine,final_amount,balance,issued_on,due_on,account_id,cost_center_id,source_id,status,created_by) values(@Rid,@TenantId,@Buyer,@Document,@Amount,0,0,0,@Amount,@Amount,current_date,current_date+(@Days*interval '1 day'),(select id from finance.chart_of_accounts where tenant_id=@TenantId and type='REVENUE' and active order by display_order limit 1),@CostCenter,@Id,'OPEN',@UserId)",new{Rid=Guid.CreateVersion7(),tenant.TenantId,Buyer=(string)s.buyer,Document=$"SALE-{id:N}-{i}",Amount=amount,Days=i*30,CostCenter=(Guid?)s.cost_center_id,Id=id,tenant.UserId},t,cancellationToken:ct));}await c.ExecuteAsync(new CommandDefinition("update commercial.agro_sales set status='INVOICED',updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=id},t,cancellationToken:ct));await Audit(c,t,"invoice",id,new{installments},ct);});
    public Task CancelAsync(Guid id,string reason,CancellationToken ct){Guard.Required(reason,nameof(reason),500);return Tx(async(c,t)=>{var s=await Lock(c,t,id,ct);if((string)s.status=="INVOICED")throw new ConflictException("Venda faturada deve ter seus títulos tratados antes do cancelamento.");if((string)s.status=="CONFIRMED"&&s.warehouse_id is not null)await c.ExecuteAsync(new CommandDefinition("update inventory.stock_balances set reserved=greatest(reserved-@Quantity,0),version=version+1 where tenant_id=@TenantId and warehouse_id=@Warehouse and product_id=@Product",new{tenant.TenantId,Warehouse=(Guid)s.warehouse_id,Product=(Guid)s.product_id,Quantity=(decimal)s.quantity},t,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("update commercial.agro_sales set status='CANCELLED',cancel_reason=@Reason,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=id,Reason=reason},t,cancellationToken:ct));await Audit(c,t,"cancel",id,new{reason},ct);});}
    private async Task<dynamic> Lock(NpgsqlConnection c,NpgsqlTransaction t,Guid id,CancellationToken ct)=>await c.QuerySingleOrDefaultAsync(new CommandDefinition("select * from commercial.agro_sales where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},t,cancellationToken:ct))??throw new NotFoundException("Venda",id);
    private Task Audit(NpgsqlConnection c,NpgsqlTransaction t,string action,Guid id,object value,CancellationToken ct)=>c.WriteAuditAsync(t,tenant,action,"AgroSale",id,null,value,ct);
    private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha na comercialização do tenant {TenantId}",tenant.TenantId);throw;}}
    private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
