using System.Globalization;
using System.Text;
using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Finance;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class SeasonCostService(DatabaseExecutor db, ITenantContext tenant, ILogger<SeasonCostService> logger) : ISeasonCostService
{
    public Task<dynamic> OverviewAsync(SeasonCostQuery q, CancellationToken ct) => Tx<dynamic>(async (c,t) =>
    {
        var p = Params(q); var where = Where(q);
        var summary = await c.QuerySingleAsync(new CommandDefinition($"""select coalesce(sum(planned_amount),0) planned,coalesce(sum(committed_amount),0) committed,coalesce(sum(recognized_amount),0) recognized,coalesce(sum(paid_amount),0) paid,coalesce(sum(allocated_amount),0) allocated,coalesce(sum(recognized_amount-allocated_amount),0) pending,count(*) entries from agro360.cost_management_entries e where {where}""",p,t,cancellationToken:ct));
        var categories = (await c.QueryAsync(new CommandDefinition($"""select category,coalesce(sum(allocated_amount),0) amount from agro360.cost_management_entries e where {where} group by category order by amount desc""",p,t,cancellationToken:ct))).AsList();
        var evolution = (await c.QueryAsync(new CommandDefinition($"""select date_trunc('month',competence_date)::date period,coalesce(sum(allocated_amount),0) amount from agro360.cost_management_entries e where {where} group by 1 order by 1""",p,t,cancellationToken:ct))).AsList();
        return new { summary, categories, evolution, definition = "Resultado gerencial: realizado reconhecido pelas origens operacionais; pagamento, compromisso e previsão são momentos distintos e não são somados.", currency = "BRL" };
    }, ct);

    public Task<dynamic> ListAsync(SeasonCostQuery q, CancellationToken ct) => Tx<dynamic>(async (c,t) =>
    {
        var page=Math.Max(1,q.Page); var size=Math.Clamp(q.PageSize,1,200); var p=Params(q); p.Add("Offset",(page-1)*size);p.Add("Limit",size); var where=Where(q);
        var total=await c.ExecuteScalarAsync<int>(new CommandDefinition($"select count(*) from agro360.cost_management_entries e where {where}",p,t,cancellationToken:ct));
        var items=(await c.QueryAsync(new CommandDefinition($"""select e.id,e.farm_id,e.category,e.competence_date,e.recognized_amount,e.allocated_amount,(e.recognized_amount-e.allocated_amount) available_amount,e.currency,e.source_type,e.source_key,e.source_document,e.description,e.status,e.row_version,e.created_at,f.name farm_name from agro360.cost_management_entries e join agro360.geo_farms f on f.tenant_id=e.tenant_id and f.id=e.farm_id where {where} order by e.competence_date desc,e.created_at desc limit @Limit offset @Offset""",p,t,cancellationToken:ct))).AsList();
        return new {items,total,page,pageSize=size};
    },ct);

    public Task<dynamic?> GetAsync(Guid id,CancellationToken ct)=>Tx<dynamic?>(async(c,t)=>await c.QuerySingleOrDefaultAsync(new CommandDefinition("""select e.*,f.name farm_name,u.name created_by_name from agro360.cost_management_entries e join agro360.geo_farms f on f.tenant_id=e.tenant_id and f.id=e.farm_id left join agro360.identity_users u on u.tenant_id=e.tenant_id and u.id=e.created_by where e.tenant_id=@TenantId and e.id=@Id and e.deleted_at is null and (@FarmScope is null or e.farm_id=@FarmScope)""",new{tenant.TenantId,Id=id,FarmScope=tenant.FarmId},t,cancellationToken:ct)),ct);

    public Task<Guid> AddManualAsync(ManualSeasonCostCommand x,CancellationToken ct)
    {
        Guard.Required(x.Category,nameof(x.Category),60);Guard.Required(x.Description,nameof(x.Description),240);Guard.Required(x.Justification,nameof(x.Justification),1000);Guard.Required(x.IdempotencyKey,nameof(x.IdempotencyKey),160);
        if(x.RecognizedAmount<=0||x.PlannedAmount<0||x.CommittedAmount<0||x.PaidAmount<0)throw new DomainException("Os valores devem ser positivos.","cost.amount_invalid");
        if(x.Currency.Trim().ToUpperInvariant()!="BRL")throw new DomainException("Não há política cambial implementada; use BRL.","cost.currency_unsupported");
        return Tx(async(c,t)=>{await RequireFarm(c,t,x.FarmId,ct);var existing=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.cost_management_entries where tenant_id=@TenantId and source_type='MANUAL' and source_key=@Key",new{tenant.TenantId,Key=x.IdempotencyKey},t,cancellationToken:ct));if(existing.HasValue)return existing.Value;var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("""insert into agro360.cost_management_entries(id,tenant_id,farm_id,category,competence_date,planned_amount,committed_amount,recognized_amount,paid_amount,currency,source_type,source_key,source_document,description,status,created_by) values(@Id,@TenantId,@FarmId,@Category,@CompetenceDate,@PlannedAmount,@CommittedAmount,@RecognizedAmount,@PaidAmount,'BRL','MANUAL',@IdempotencyKey,@Justification,@Description,'OPEN',@UserId)""",new{Id=id,tenant.TenantId,tenant.UserId,x.FarmId,x.Category,x.CompetenceDate,x.PlannedAmount,x.CommittedAmount,x.RecognizedAmount,x.PaidAmount,x.IdempotencyKey,x.Justification,x.Description},t,cancellationToken:ct));await c.WriteAuditAsync(t,tenant,"create","SeasonCost",id,null,x,ct);return id;},ct);
    }

    public Task<CostAllocationPreviewDto> PreviewAsync(CostAllocationPreviewCommand x,CancellationToken ct)=>Tx((c,t)=>BuildPreview(c,t,x,false,ct),ct);

    public Task<Guid> ConfirmAsync(ConfirmCostAllocationCommand x,CancellationToken ct)
    {
        Guard.Required(x.IdempotencyKey,nameof(x.IdempotencyKey),160);
        return Tx(async(c,t)=>{var old=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.cost_allocation_batches where tenant_id=@TenantId and idempotency_key=@Key",new{tenant.TenantId,Key=x.IdempotencyKey},t,cancellationToken:ct));if(old.HasValue)return old.Value;var preview=await BuildPreview(c,t,x.Preview,true,ct);if(preview.Method=="DIRECT"&&preview.Lines.Count!=1)throw new DomainException("A apropriação direta exige um destino.","cost.direct_destination_invalid");var batch=Guid.CreateVersion7();var snapshot=JsonSerializer.Serialize(preview);await c.ExecuteAsync(new CommandDefinition("""insert into agro360.cost_allocation_batches(id,tenant_id,entry_id,method,amount,currency,base_snapshot,idempotency_key,status,justification,confirmed_at,confirmed_by,created_by) values(@Id,@TenantId,@EntryId,@Method,@Amount,@Currency,cast(@Snapshot as jsonb),@Key,'CONFIRMED',@Justification,now(),@UserId,@UserId);""",new{Id=batch,tenant.TenantId,tenant.UserId,EntryId=preview.EntryId,preview.Method,Amount=preview.SelectedAmount,preview.Currency,Snapshot=snapshot,Key=x.IdempotencyKey,x.Justification},t,cancellationToken:ct));foreach(var line in preview.Lines)await c.ExecuteAsync(new CommandDefinition("""insert into agro360.cost_allocations(id,tenant_id,batch_id,entry_id,season_id,farm_id,field_id,cost_center_id,base_value,base_unit,percentage,amount,rounding_adjustment,status,confirmed_at,confirmed_by,created_by) values(@Id,@TenantId,@Batch,@EntryId,@SeasonId,@FarmId,@FieldId,@CostCenterId,@BaseValue,@Unit,@Percentage,@Amount,@Adjustment,'CONFIRMED',now(),@UserId,@UserId)""",new{Id=Guid.CreateVersion7(),tenant.TenantId,tenant.UserId,Batch=batch,EntryId=preview.EntryId,line.SeasonId,line.FarmId,line.FieldId,line.CostCenterId,line.BaseValue,line.Unit,line.Percentage,line.Amount,Adjustment=line.RoundingAdjustment},t,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("update agro360.cost_management_entries set allocated_amount=allocated_amount+@Amount,row_version=row_version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,tenant.UserId,Id=preview.EntryId,Amount=preview.SelectedAmount},t,cancellationToken:ct));await c.WriteAuditAsync(t,tenant,"confirm","CostAllocation",batch,null,preview,ct);InfrastructureLogMessages.CostAllocationChanged(logger,"confirm",tenant.TenantId,batch,tenant.UserId);return batch;},ct);
    }

    public Task ReverseAsync(Guid batchId,ReverseCostAllocationCommand x,CancellationToken ct)
    {Guard.Required(x.Reason,nameof(x.Reason),1000);Guard.Required(x.IdempotencyKey,nameof(x.IdempotencyKey),160);return Tx(async(c,t)=>{var b=await c.QuerySingleOrDefaultAsync(new CommandDefinition("select entry_id,amount,status from agro360.cost_allocation_batches where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=batchId},t,cancellationToken:ct))??throw new NotFoundException("Apropriação",batchId);if((string)b.status=="REVERSED")return;var entry=(Guid)b.entry_id;var amount=(decimal)b.amount;var changed=await c.ExecuteAsync(new CommandDefinition("""update agro360.cost_allocation_batches set status='REVERSED',reversal_reason=@Reason,reversed_at=now(),reversed_by=@UserId,reversal_key=@Key where tenant_id=@TenantId and id=@Id and status='CONFIRMED';update agro360.cost_allocations set status='REVERSED',reversal_reason=@Reason,reversed_at=now(),reversed_by=@UserId where tenant_id=@TenantId and batch_id=@Id and status='CONFIRMED';update agro360.cost_management_entries set allocated_amount=allocated_amount-@Amount,row_version=row_version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Entry and allocated_amount>=@Amount""",new{tenant.TenantId,tenant.UserId,Id=batchId,Entry=entry,Amount=amount,x.Reason,Key=x.IdempotencyKey},t,cancellationToken:ct));if(changed<3)throw new ConflictException("A apropriação já foi estornada ou o saldo mudou.");await c.WriteAuditAsync(t,tenant,"reverse","CostAllocation",batchId,null,x,ct);InfrastructureLogMessages.CostAllocationChanged(logger,"reverse",tenant.TenantId,batchId,tenant.UserId);},ct);}

    public Task<IReadOnlyList<dynamic>> HistoryAsync(Guid? seasonId,CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition("""select b.id,b.entry_id,b.method,b.amount,b.currency,b.status,b.confirmed_at,b.reversed_at,b.reversal_reason,u.name confirmed_by_name,count(a.id) destinations from agro360.cost_allocation_batches b join agro360.cost_allocations a on a.tenant_id=b.tenant_id and a.batch_id=b.id left join agro360.identity_users u on u.tenant_id=b.tenant_id and u.id=b.confirmed_by where b.tenant_id=@TenantId and (@SeasonId is null or a.season_id=@SeasonId) group by b.id,u.name order by b.created_at desc""",new{tenant.TenantId,SeasonId=seasonId},t,cancellationToken:ct))).AsList(),ct);
    public Task<dynamic> DestinationsAsync(Guid? farmId,CancellationToken ct)=>Tx<dynamic>(async(c,t)=>{var p=new{tenant.TenantId,FarmId=farmId,FarmScope=tenant.FarmId};var farms=(await c.QueryAsync(new CommandDefinition("select id,name,total_area_ha from agro360.geo_farms where tenant_id=@TenantId and deleted_at is null and (@FarmId is null or id=@FarmId) and (@FarmScope is null or id=@FarmScope) order by name",p,t,cancellationToken:ct))).AsList();var seasons=(await c.QueryAsync(new CommandDefinition("select id,farm_id,name,crop,planned_area_ha,start_date,end_date from agro360.agriculture_seasons where tenant_id=@TenantId and deleted_at is null and status not in(4,5) and (@FarmId is null or farm_id=@FarmId) and (@FarmScope is null or farm_id=@FarmScope) order by start_date desc",p,t,cancellationToken:ct))).AsList();var fields=(await c.QueryAsync(new CommandDefinition("select id,farm_id,name,area_ha from agro360.geo_fields where tenant_id=@TenantId and deleted_at is null and (@FarmId is null or farm_id=@FarmId) and (@FarmScope is null or farm_id=@FarmScope) order by name",p,t,cancellationToken:ct))).AsList();var centers=(await c.QueryAsync(new CommandDefinition("select id,code,name from agro360.finance_cost_centers where tenant_id=@TenantId and active and deleted_at is null order by name",p,t,cancellationToken:ct))).AsList();return new{farms,seasons,fields,costCenters=centers};},ct);

    public Task<dynamic> ClosingReviewAsync(Guid seasonId,DateOnly cutoff,CancellationToken ct)=>Tx<dynamic>(async(c,t)=>{var s=await c.QuerySingleOrDefaultAsync(new CommandDefinition("select id,farm_id,name from agro360.agriculture_seasons where tenant_id=@TenantId and id=@SeasonId and deleted_at is null",new{tenant.TenantId,SeasonId=seasonId},t,cancellationToken:ct))??throw new NotFoundException("Safra",seasonId);var totals=await c.QuerySingleAsync(new CommandDefinition("""select (select coalesce(sum(a.amount),0) from agro360.cost_allocations a where a.tenant_id=@TenantId and a.season_id=@SeasonId and a.confirmed_at::date<=@Cutoff and a.status='CONFIRMED') appropriated,(select coalesce(sum(e.recognized_amount-e.allocated_amount),0) from agro360.cost_management_entries e where e.tenant_id=@TenantId and e.farm_id=@FarmId and e.status='OPEN' and e.deleted_at is null) pending,(select coalesce(sum(a.amount),0) from agro360.cost_allocations a where a.tenant_id=@TenantId and a.season_id=@SeasonId and a.confirmed_at::date>@Cutoff and a.status='CONFIRMED') after_cutoff,(select coalesce(sum(a.amount),0) from agro360.cost_allocations a where a.tenant_id=@TenantId and a.season_id=@SeasonId and a.reversed_at::date>@Cutoff) reversals_after_cutoff""",new{tenant.TenantId,SeasonId=seasonId,FarmId=(Guid)s.farm_id,Cutoff=cutoff},t,cancellationToken:ct));return new{season=s.name,cutoffDate=cutoff,totals,blocking=((decimal)totals.after_cutoff>0||(decimal)totals.reversals_after_cutoff>0),limitations="Custos sem vínculo inequívoco permanecem pendentes. Pagamentos não bloqueiam o fechamento operacional.",procedure="Fechamento confirmado não é alterado: gere nova apuração ou reabra com permissão."};},ct);

    public async Task<string> ExportCsvAsync(SeasonCostQuery q,CancellationToken ct){var all=q with{Page=1,PageSize=200};var data=await ListAsync(all,ct);var items=(IEnumerable<dynamic>)data.items;var sb=new StringBuilder("Competencia;Fazenda;Categoria;Origem;Documento;Reconhecido;Apropriado;Pendente;Moeda;Situacao\r\n");foreach(var x in items)sb.Append(Csv(x.competence_date)).Append(';').Append(Csv(x.farm_name)).Append(';').Append(Csv(x.category)).Append(';').Append(Csv(x.source_type)).Append(';').Append(Csv(x.source_document)).Append(';').Append(((decimal)x.recognized_amount).ToString("0.0000",CultureInfo.InvariantCulture)).Append(';').Append(((decimal)x.allocated_amount).ToString("0.0000",CultureInfo.InvariantCulture)).Append(';').Append(((decimal)x.available_amount).ToString("0.0000",CultureInfo.InvariantCulture)).Append(';').Append(x.currency).Append(';').Append(x.status).Append("\r\n");return sb.ToString();}

    private async Task<CostAllocationPreviewDto> BuildPreview(NpgsqlConnection c,NpgsqlTransaction t,CostAllocationPreviewCommand x,bool locked,CancellationToken ct){if(x.Destinations.Select(d=>(d.SeasonId,d.FarmId,d.FieldId,d.CostCenterId)).Distinct().Count()!=x.Destinations.Count)throw new DomainException("Um destino não pode aparecer duas vezes.","cost.destination_duplicate");var sql="select recognized_amount,allocated_amount,currency,status,row_version,farm_id from agro360.cost_management_entries where tenant_id=@TenantId and id=@Id and deleted_at is null"+(locked?" for update":"");var e=await c.QuerySingleOrDefaultAsync(new CommandDefinition(sql,new{tenant.TenantId,Id=x.EntryId},t,cancellationToken:ct))??throw new NotFoundException("Lançamento",x.EntryId);if((string)e.status!="OPEN")throw new ConflictException("O lançamento não permite apropriação.");if((long)e.row_version!=x.EntryVersion)throw new ConflictException("O lançamento mudou. Gere uma nova prévia.");var available=(decimal)e.recognized_amount-(decimal)e.allocated_amount;if(x.Amount>available)throw new DomainException("O valor excede o saldo apropriável.","cost.balance_insufficient");string? unit=null;foreach(var d in x.Destinations){if(d.FarmId!=(Guid)e.farm_id)throw new DomainException("O destino deve pertencer à mesma propriedade do lançamento.","cost.destination_farm_invalid");await RequireDestination(c,t,d,ct);if(x.Method.ToUpperInvariant() is "AREA" or "PRODUCTION" or "HOURS"){if(unit is not null&&!string.Equals(unit,d.Unit,StringComparison.OrdinalIgnoreCase))throw new DomainException("Não combine unidades incompatíveis.","cost.unit_incompatible");unit=d.Unit;}}var portions=SeasonCostRules.Allocate(x.Amount,x.Method,x.Destinations.Select(d=>(d.BaseValue,d.Percentage)).ToList());var lines=x.Destinations.Select((d,i)=>new CostAllocationLineDto(d.SeasonId,d.FarmId,d.FieldId,d.CostCenterId,d.BaseValue,d.Unit,portions[i].Percentage,portions[i].Amount,portions[i].Adjustment)).ToList();return new(x.EntryId,(decimal)e.recognized_amount,(decimal)e.allocated_amount,available,x.Amount,(string)e.currency,x.Method.ToUpperInvariant(),(long)e.row_version,"4 casas decimais; AwayFromZero; resíduo aplicado ao último destino",lines);}
    private async Task RequireDestination(NpgsqlConnection c,NpgsqlTransaction t,CostDestinationCommand d,CancellationToken ct){var valid=await c.ExecuteScalarAsync<bool>(new CommandDefinition("""select exists(select 1 from agro360.agriculture_seasons s where s.tenant_id=@TenantId and s.id=@SeasonId and s.farm_id=@FarmId and s.deleted_at is null and s.status not in(4,5) and ( @FieldId is null or exists(select 1 from agro360.geo_fields f where f.tenant_id=s.tenant_id and f.id=@FieldId and f.farm_id=s.farm_id and f.deleted_at is null)) and (@CostCenterId is null or exists(select 1 from agro360.finance_cost_centers cc where cc.tenant_id=s.tenant_id and cc.id=@CostCenterId and cc.active and cc.deleted_at is null)))""",new{tenant.TenantId,d.SeasonId,d.FarmId,d.FieldId,d.CostCenterId},t,cancellationToken:ct));if(!valid)throw new DomainException("Safra, talhão ou centro de custo inválido, encerrado ou fora do tenant.","cost.destination_invalid");}
    private async Task RequireFarm(NpgsqlConnection c,NpgsqlTransaction t,Guid id,CancellationToken ct){var valid=await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.geo_farms where tenant_id=@TenantId and id=@Id and deleted_at is null and (@Scope is null or id=@Scope))",new{tenant.TenantId,Id=id,Scope=tenant.FarmId},t,cancellationToken:ct));if(!valid)throw new ForbiddenException("Propriedade fora do seu escopo.");}
    private DynamicParameters Params(SeasonCostQuery q){var p=new DynamicParameters(q);p.Add("TenantId",tenant.TenantId);p.Add("FarmScope",tenant.FarmId);return p;}
    private static string Where(SeasonCostQuery q)=>"e.tenant_id=@TenantId and e.deleted_at is null and (@FarmScope is null or e.farm_id=@FarmScope) and (@FarmId is null or e.farm_id=@FarmId) and (@Category is null or e.category=@Category) and (@Status is null or (@Status='PENDING' and e.recognized_amount>e.allocated_amount) or e.status=@Status) and (@From is null or e.competence_date>=@From) and (@To is null or e.competence_date<=@To) and (@Search is null or e.description ilike '%'||@Search||'%' or e.source_document ilike '%'||@Search||'%') and (@SeasonId is null or exists(select 1 from agro360.cost_allocations ca where ca.tenant_id=e.tenant_id and ca.entry_id=e.id and ca.season_id=@SeasonId and ca.status='CONFIRMED')) and (@FieldId is null or exists(select 1 from agro360.cost_allocations ca where ca.tenant_id=e.tenant_id and ca.entry_id=e.id and ca.field_id=@FieldId and ca.status='CONFIRMED'))";
    private static string Csv(object? value)=>$"\"{Convert.ToString(value,CultureInfo.InvariantCulture)?.Replace("\"","\"\"")}\"";
    private Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);
    private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> action,CancellationToken ct)=>db.InTenantTransactionAsync(action,ct);
}
