using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Traceability;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class ImmutableLedgerService(DatabaseExecutor db,ITenantContext tenant,ILogger<ImmutableLedgerService> logger):IImmutableLedgerService
{
 public Task<Guid> AppendAsync(string entity,Guid entityId,string eventType,object payload,string status,CancellationToken ct)=>Tx(async(c,t)=>{var json=JsonSerializer.Serialize(payload);var previous=await c.ExecuteScalarAsync<string?>(new CommandDefinition("select current_hash from ledger.events where tenant_id=@TenantId order by sequence desc limit 1 for update",new{tenant.TenantId},t,cancellationToken:ct));var id=Guid.CreateVersion7();var at=DateTimeOffset.UtcNow;var metadata=$"{tenant.TenantId}|{entity}|{entityId}|{eventType}|{at:O}|{tenant.UserId}|{status}";var hash=Sprint10Rules.LedgerHash(previous,json,metadata);await c.ExecuteAsync(new CommandDefinition("insert into ledger.events(id,tenant_id,entity_name,entity_id,event_type,payload,previous_hash,current_hash,occurred_at,user_id,logical_signature,status) values(@Id,@TenantId,@Entity,@EntityId,@EventType,cast(@Payload as jsonb),@Previous,@Hash,@At,@UserId,@Hash,'VALID')",new{Id=id,tenant.TenantId,Entity=entity,EntityId=entityId,EventType=eventType,Payload=json,Previous=previous,Hash=hash,At=at,tenant.UserId},t,cancellationToken:ct));return id;});
 public Task<dynamic> ValidateAsync(CancellationToken ct)=>Tx<dynamic>(async(c,t)=>{var rows=(await c.QueryAsync<LedgerRow>(new CommandDefinition("select sequence,entity_name EntityName,entity_id EntityId,event_type EventType,payload::text Payload,previous_hash PreviousHash,current_hash CurrentHash,occurred_at OccurredAt,user_id UserId,status Status from ledger.events where tenant_id=@TenantId order by sequence",new{tenant.TenantId},t,cancellationToken:ct))).ToList();string? previous=null;foreach(var x in rows){var metadata=$"{tenant.TenantId}|{x.EntityName}|{x.EntityId}|{x.EventType}|{x.OccurredAt:O}|{x.UserId}|{x.Status}";if(x.PreviousHash!=previous||Sprint10Rules.LedgerHash(previous,x.Payload,metadata)!=x.CurrentHash)return new{valid=false,brokenAt=x.Sequence,eventCount=rows.Count};previous=x.CurrentHash;}return new{valid=true,brokenAt=(long?)null,eventCount=rows.Count,lastHash=previous};});
 private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha na fronteira do ledger do tenant {TenantId}",tenant.TenantId);throw;}}
 private sealed record LedgerRow(long Sequence,string EntityName,Guid EntityId,string EventType,string Payload,string? PreviousHash,string CurrentHash,DateTimeOffset OccurredAt,Guid UserId,string Status);
}

public sealed class ControlledPaymentSplitProvider:IPaymentSplitProvider { public Task<string> RegisterAsync(Guid splitId,decimal amount,CancellationToken ct)=>Task.FromResult($"SIM-{splitId:N}-{amount:0.00}"); }

public sealed class Sprint10Service(DatabaseExecutor db,ITenantContext tenant,IImmutableLedgerService ledger,IPaymentSplitProvider provider,ILogger<Sprint10Service> logger):ISprint10Service
{
 public Task<IReadOnlyList<dynamic>> LotsAsync(CancellationToken ct)=>Query("select * from traceability.lots where tenant_id=@TenantId order by created_at desc",ct);
 public Task<Guid> SaveLotAsync(Guid? id,TraceableLotCommand x,CancellationToken ct){Sprint10Rules.RequireOrigin(x.PropertyId,x.Producer);return Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var sql=id is null?"insert into traceability.lots(id,tenant_id,code,product_id,property_id,plot_id,producer,cooperative,harvested_at,quantity,unit,notes,created_by) values(@Id,@TenantId,@Code,@ProductId,@PropertyId,@PlotId,@Producer,@Cooperative,@HarvestedAt,@Quantity,@Unit,@Notes,@UserId)":"update traceability.lots set code=@Code,product_id=@ProductId,property_id=@PropertyId,plot_id=@PlotId,producer=@Producer,cooperative=@Cooperative,harvested_at=@HarvestedAt,quantity=@Quantity,unit=@Unit,notes=@Notes,updated_at=now() where id=@Id and tenant_id=@TenantId";if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException("TraceableLot",key);await ledger.AppendAsync("TraceableLot",key,id is null?"LOT_CREATED":"CRITICAL_DATA_CORRECTED",x,"VALID",ct);return key;});}
 public Task AddLotEventAsync(Guid id,LotEventCommand x,CancellationToken ct)=>Tx(async(c,t)=>{if(x.EventType=="MIX"&&(x.SourceLotId is null||x.CompositionQuantity<=0))throw new DomainException("Mistura exige lote de origem e quantidade.");await c.ExecuteAsync(new CommandDefinition("insert into traceability.lot_events(id,tenant_id,lot_id,event_type,payload,source_lot_id,composition_quantity,occurred_at,created_by) values(@EventId,@TenantId,@Id,@EventType,cast(@Payload as jsonb),@SourceLotId,@CompositionQuantity,now(),@UserId)",new{EventId=Guid.CreateVersion7(),tenant.TenantId,Id=id,x.EventType,x.Payload,x.SourceLotId,x.CompositionQuantity,tenant.UserId},t,cancellationToken:ct));await ledger.AppendAsync("TraceableLot",id,x.EventType,x,"VALID",ct);});
 public Task<IReadOnlyList<dynamic>> TimelineAsync(Guid id,CancellationToken ct)=>Query("select event_type,payload,source_lot_id,composition_quantity,occurred_at from traceability.lot_events where tenant_id=@TenantId and lot_id=@Id union all select event_type,payload,entity_id,null,occurred_at from ledger.events where tenant_id=@TenantId and entity_id=@Id order by occurred_at",ct,new{Id=id});
 public Task<Guid> AddComplianceAsync(ComplianceEventCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var rule=await c.QuerySingleOrDefaultAsync<(int MinimumMinutes,decimal? MinimumTemperature)>(new CommandDefinition("select r.minimum_minutes,r.minimum_temperature from processing.compliance_rules r join traceability.lots l on l.product_id=r.product_id and l.tenant_id=r.tenant_id where l.id=@LotId and l.tenant_id=@TenantId and r.step=@Step and r.active order by r.effective_from desc limit 1",new{tenant.TenantId,x.LotId,x.Step},t,cancellationToken:ct));var compliant=Sprint10Rules.ProcessingComplies(x.StartedAt,x.EndedAt,x.Temperature,rule.MinimumMinutes,rule.MinimumTemperature);var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into processing.compliance_events(id,tenant_id,lot_id,step,responsible,started_at,ended_at,temperature,equipment,evidence,status,notes,created_by) values(@Id,@TenantId,@LotId,@Step,@Responsible,@StartedAt,@EndedAt,@Temperature,@Equipment,@Evidence,@Status,@Notes,@UserId)",new{Id=id,tenant.TenantId,x.LotId,x.Step,x.Responsible,x.StartedAt,x.EndedAt,Duration=(int)(x.EndedAt-x.StartedAt).TotalMinutes,x.Temperature,x.Equipment,x.Evidence,Status=compliant?"APPROVED":"BLOCKED",x.Notes,tenant.UserId},t,cancellationToken:ct));if(!compliant)throw new DomainException("Etapa não atende à regra configurada.","processing.non_compliant");await ledger.AppendAsync("ComplianceEvent",id,"PROCESSING_APPROVED",x,"VALID",ct);return id;});
 public async Task<dynamic?> CertificateAsync(string code,CancellationToken ct) { try { var json=await db.InSystemTransactionAsync((c,t)=>c.ExecuteScalarAsync<string?>(new CommandDefinition("select traceability.public_certificate(@Code)::text",new{Code=code},t,cancellationToken:ct)),ct); return json is null?null:JsonSerializer.Deserialize<JsonElement>(json); } catch(Exception ex) { logger.LogError(ex,"Falha na consulta pública de certificado {Code}",code); throw; } }
 public Task<(Guid Id,string Code)> CreateCertificateAsync(CertificateCommand x,CancellationToken ct)=>Tx(async(c,t)=>{if(!await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from traceability.lots where tenant_id=@TenantId and id=@LotId and producer<>'' )",new{tenant.TenantId,x.LotId},t,cancellationToken:ct)))throw new DomainException("Lote não possui rastreabilidade mínima.");var id=Guid.CreateVersion7();var code=Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(12)).ToLowerInvariant();await c.ExecuteAsync(new CommandDefinition("insert into traceability.certificates(id,tenant_id,lot_id,code,issued_at,created_by) values(@Id,@TenantId,@LotId,@Code,now(),@UserId)",new{Id=id,tenant.TenantId,x.LotId,Code=code,tenant.UserId},t,cancellationToken:ct));await ledger.AppendAsync("Certificate",id,"CERTIFICATE_ISSUED",new{x.LotId,code},"VALID",ct);return(id,code);});
 public Task<IReadOnlyList<dynamic>> RoutesAsync(CancellationToken ct)=>Query("select r.*,jsonb_agg(s order by s.position) segments from regional_logistics.routes r left join regional_logistics.route_segments s on s.route_id=r.id where r.tenant_id=@TenantId group by r.id order by r.created_at desc",ct);
 public Task<Guid> AddRouteAsync(RouteCommand x,CancellationToken ct)=>Insert("regional_logistics.routes","code,name,modal,origin_point_id,destination_point_id,estimated_cost,estimated_minutes,notes","@Code,@Name,@Modal,@OriginPointId,@DestinationPointId,@EstimatedCost,@EstimatedMinutes,@Notes",x,ct);
 public Task<Guid> AddTripAsync(TripRegionalCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var blocked=await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from regional_logistics.route_segments where route_id=@RouteId and tenant_id=@TenantId and road_condition='INTERDICTED')",new{tenant.TenantId,x.RouteId},t,cancellationToken:ct));Sprint10Rules.RequireRouteAuthorization(blocked?"INTERDICTED":"GOOD",x.InterdictionAuthorized);return await Insert("regional_logistics.trips","route_id,number,vehicle_id,planned_start,interdiction_authorized,status","@RouteId,@Number,@VehicleId,@PlannedStart,@InterdictionAuthorized,'PLANNED'",x,ct);});
 public Task AddOccurrenceAsync(Guid tripId,RegionalOccurrenceCommand x,CancellationToken ct)=>Tx(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("insert into regional_logistics.occurrences(id,tenant_id,trip_id,type,description,occurred_at,latitude,longitude,created_by) values(@Id,@TenantId,@TripId,@Type,@Description,@OccurredAt,@Latitude,@Longitude,@UserId)",new{Id=Guid.CreateVersion7(),tenant.TenantId,TripId=tripId,x.Type,x.Description,x.OccurredAt,x.Latitude,x.Longitude,tenant.UserId},t,cancellationToken:ct));});
 public Task<IReadOnlyList<dynamic>> PartnersAsync(CancellationToken ct)=>Query("select * from sales_network.partners where tenant_id=@TenantId order by name",ct);
 public Task<Guid> AddPartnerAsync(PartnerCommand x,CancellationToken ct)=>Insert("sales_network.partners","name,type,document,contact,active","@Name,@Type,@Document,@Contact,@Active",x,ct);
 public Task<Guid> AddCommissionRuleAsync(CommissionRuleCommand x,CancellationToken ct)=>Tx(async(c,t)=>{var id=await Insert("sales_network.commission_rules","partner_id,role,calculation_type,value,effective_from,effective_to","@PartnerId,@Role,@CalculationType,@Value,@EffectiveFrom,@EffectiveTo",x,ct);await ledger.AppendAsync("CommissionRule",id,"COMMISSION_RULE_CHANGED",x,"VALID",ct);return id;});
 public Task<dynamic> CalculateSplitAsync(SplitCalculationCommand x,CancellationToken ct)=>Tx<dynamic>(async(c,t)=>{var amounts=x.Participants.Select(p=>new{p.PartnerId,p.Role,Amount=Sprint10Rules.Commission(x.GrossAmount,p.Value,p.Percentage)}).ToList();Sprint10Rules.ValidateSplit(x.GrossAmount,amounts.Select(a=>a.Amount));var id=Guid.CreateVersion7();await c.ExecuteAsync(new CommandDefinition("insert into sales_network.revenue_splits(id,tenant_id,sale_id,gross_amount,status,created_by) values(@Id,@TenantId,@SaleId,@GrossAmount,'CALCULATED',@UserId)",new{Id=id,tenant.TenantId,x.SaleId,x.GrossAmount,tenant.UserId},t,cancellationToken:ct));foreach(var a in amounts)await c.ExecuteAsync(new CommandDefinition("insert into sales_network.split_items(id,tenant_id,split_id,partner_id,role,amount,status) values(@Id,@TenantId,@SplitId,@PartnerId,@Role,@Amount,'PENDING')",new{Id=Guid.CreateVersion7(),tenant.TenantId,SplitId=id,a.PartnerId,a.Role,a.Amount},t,cancellationToken:ct));await ledger.AppendAsync("RevenueSplit",id,"PAYMENT_SPLIT_CALCULATED",x,"VALID",ct);return new{id,grossAmount=x.GrossAmount,participants=amounts};});
 public Task ApproveSplitAsync(Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var amount=await c.ExecuteScalarAsync<decimal>(new CommandDefinition("update sales_network.revenue_splits set status='APPROVED',approved_at=now() where id=@Id and tenant_id=@TenantId and status='CALCULATED' returning gross_amount",new{Id=id,tenant.TenantId},t,cancellationToken:ct));var reference=await provider.RegisterAsync(id,amount,ct);await c.ExecuteAsync(new CommandDefinition("update sales_network.revenue_splits set provider_reference=@Reference where id=@Id",new{Id=id,Reference=reference},t,cancellationToken:ct));await ledger.AppendAsync("RevenueSplit",id,"PAYMENT_SPLIT_APPROVED",new{reference,amount},"VALID",ct);});
 public Task<dynamic> DashboardAsync(CancellationToken ct)=>Tx<dynamic>(async(c,t)=>await c.QuerySingleAsync(new CommandDefinition("select (select count(*) from traceability.lots where tenant_id=@TenantId) tracked_lots,(select count(*) from processing.compliance_events where tenant_id=@TenantId and status<>'APPROVED') non_compliant_lots,(select count(*) from traceability.certificates where tenant_id=@TenantId) certificates,(select count(*) from ledger.events where tenant_id=@TenantId) critical_events,(select count(*) from regional_logistics.trips where tenant_id=@TenantId and status='IN_PROGRESS') active_trips,(select count(*) from sales_network.revenue_splits where tenant_id=@TenantId and status='CALCULATED') pending_splits",new{tenant.TenantId},t,cancellationToken:ct)));
 private Task<Guid> Insert(string table,string columns,string values,object x,CancellationToken ct)=>Tx(async(c,t)=>{var id=Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);await c.ExecuteAsync(new CommandDefinition($"insert into {table}(id,tenant_id,{columns},created_by) values(@Id,@TenantId,{values},@UserId)",p,t,cancellationToken:ct));return id;});
 private Task<IReadOnlyList<dynamic>> Query(string sql,CancellationToken ct,object? extra=null)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>{var p=new DynamicParameters(extra);p.Add("TenantId",tenant.TenantId);return(await c.QueryAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))).AsList();});
 private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){logger.LogError(ex,"Falha na fronteira Sprint 10 do tenant {TenantId}",tenant.TenantId);throw;}}
 private Task Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
