using Agro360.Application.Contracts;
using Agro360.Domain.People;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class SstService(DatabaseExecutor db, ITenantContext tenant) : ISstService
{
    public Task<SstDashboard> DashboardAsync(CancellationToken ct) => db.InTenantTransactionAsync((c,t) => c.QuerySingleAsync<SstDashboard>("""
select
 (select count(*) from agro360.sst_workers where tenant_id=@TenantId and deleted_at is null and status='ACTIVE') activeworkers,
 (select count(distinct worker_id) from agro360.sst_training_attendance where tenant_id=@TenantId and status in('EXPIRED','PENDING')) workerswithpendingitems,
 (select count(*) from agro360.sst_epi_deliveries where tenant_id=@TenantId and status='DELIVERED') epidelivered,
 (select count(*) from agro360.sst_epi_deliveries where tenant_id=@TenantId and status='DELIVERED' and replace_on<current_date) epiexpired,
 (select count(*) from agro360.sst_epi_deliveries where tenant_id=@TenantId and status='DELIVERED' and replace_on between current_date and current_date+30) epiduesoon,
 (select count(*) from agro360.sst_training_attendance where tenant_id=@TenantId and status='EXPIRED') trainingexpired,
 (select count(*) from agro360.sst_training_attendance where tenant_id=@TenantId and valid_until between current_date and current_date+30 and status='COMPLETED') trainingduesoon,
 (select count(*) from agro360.sst_medical_exam_controls where tenant_id=@TenantId and valid_until<current_date and status<>'CANCELLED') examsexpired,
 (select count(*) from agro360.sst_medical_exam_controls where tenant_id=@TenantId and valid_until between current_date and current_date+30 and status<>'CANCELLED') examsduesoon,
 (select count(*) from agro360.sst_risks where tenant_id=@TenantId and status='ACTIVE' and risk_level>=16) criticalrisks,
 (select count(*) from agro360.sst_incidents where tenant_id=@TenantId and status not in('CLOSED','CANCELLED')) openincidents,
 (select count(*) from agro360.sst_incidents where tenant_id=@TenantId and severity>=4 and status not in('CLOSED','CANCELLED')) seriousincidents,
 (select count(*) from agro360.sst_incidents where tenant_id=@TenantId and type='NEAR_MISS') nearmisses,
 (select count(*) from agro360.sst_action_plans where tenant_id=@TenantId and due_on<current_date and status not in('COMPLETED','CANCELLED')) overdueactions,
 (select count(*) from agro360.sst_checklist_runs where tenant_id=@TenantId and result='FAILED') failedchecklists,
 greatest(0,100-coalesce((select count(*) from agro360.operations_operational_alerts where tenant_id=@TenantId and module='SST' and status='OPEN'),0)*2)::numeric compliancepercent
""",new{tenant.TenantId},t),ct);

    public Task<IReadOnlyList<SstLookup>> LookupsAsync(string kind,string? search,CancellationToken ct) => db.InTenantTransactionAsync(async(c,t) => {
        var table=kind switch { "roles"=>"sst_job_roles", "areas"=>"sst_work_areas", "workers"=>"sst_workers", "epis"=>"sst_epi_catalog", "trainings"=>"sst_training_catalog", "checklists"=>"sst_checklist_templates", _=>throw new ArgumentException("Lookup inválido.") };
        var active=kind=="workers"?"and status='ACTIVE'":"and status='ACTIVE'";
        return (IReadOnlyList<SstLookup>)(await c.QueryAsync<SstLookup>($"select id,name from agro360.sst_{table} where tenant_id=@TenantId and deleted_at is null {active} and (@Search is null or name ilike '%'||@Search||'%') order by name limit 50",new{tenant.TenantId,Search=search},t)).ToArray();
    },ct);

    public Task<IReadOnlyList<SstWorker>> WorkersAsync(string? search,string? status,int page,int pageSize,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SstWorker>)(await c.QueryAsync<SstWorker>("select w.id,w.name,w.internal_code internalcode,r.name rolename,a.name areaname,w.status,w.admission_date admissiondate,w.employment_type employmenttype from agro360.sst_workers w join agro360.sst_job_roles r on r.tenant_id=w.tenant_id and r.id=w.job_role_id join agro360.sst_work_areas a on a.tenant_id=w.tenant_id and a.id=w.work_area_id where w.tenant_id=@TenantId and w.deleted_at is null and (@Search is null or w.name ilike '%'||@Search||'%' or w.internal_code ilike '%'||@Search||'%') and (@Status is null or w.status=@Status) order by w.name limit @Take offset @Skip",Page(search,status,page,pageSize),t)).ToArray(),ct);
    public Task<Guid> CreateWorkerAsync(SstWorkerCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{await EnsureLinks(c,t,("sst_job_roles",command.JobRoleId),("sst_work_areas",command.WorkAreaId));var duplicate=await c.ExecuteScalarAsync<bool>("select exists(select 1 from agro360.sst_workers where tenant_id=@TenantId and deleted_at is null and ((@Document is not null and document=@Document) or (@InternalCode is not null and internal_code=@InternalCode)))",new{tenant.TenantId,command.Document,command.InternalCode},t);if(duplicate)throw new InvalidOperationException("Documento ou código interno já cadastrado.");var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.sst_workers(id,tenant_id,name,document,internal_code,job_role_id,work_area_id,property_id,status,admission_date,employment_type,contact,notes,created_by,updated_by) values(@Id,@TenantId,@Name,@Document,@InternalCode,@JobRoleId,@WorkAreaId,@PropertyId,@Status,@AdmissionDate,@EmploymentType,@Contact,@Notes,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,command.Name,command.Document,command.InternalCode,command.JobRoleId,command.WorkAreaId,command.PropertyId,command.Status,command.AdmissionDate,command.EmploymentType,command.Contact,command.Notes},t);return id;},ct);
    public Task<IReadOnlyList<SstRisk>> RisksAsync(string? search,string? status,int page,int pageSize,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SstRisk>)(await c.QueryAsync<SstRisk>("select x.id,x.name,x.type,a.name areaname,r.name rolename,x.severity,x.probability,x.risk_level level,x.status,x.preventive_measure preventivemeasure from agro360.sst_risks x join agro360.sst_work_areas a on a.tenant_id=x.tenant_id and a.id=x.work_area_id left join agro360.sst_job_roles r on r.tenant_id=x.tenant_id and r.id=x.job_role_id where x.tenant_id=@TenantId and x.deleted_at is null and (@Search is null or x.name ilike '%'||@Search||'%') and (@Status is null or x.status=@Status) order by x.risk_level desc limit @Take offset @Skip",Page(search,status,page,pageSize),t)).ToArray(),ct);
    public Task<Guid> CreateRiskAsync(SstRiskCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{await EnsureLinks(c,t,("sst_work_areas",command.WorkAreaId));var level=SstRules.RiskLevel(command.Severity,command.Probability);var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.sst_risks(id,tenant_id,name,description,type,severity,probability,risk_level,work_area_id,job_role_id,operation,preventive_measure,recommended_epi_id,recommended_training_id,status,responsible_id,evidence_document_id,created_by,updated_by) values(@Id,@TenantId,@Name,@Description,@Type,@Severity,@Probability,@Level,@WorkAreaId,@JobRoleId,@Operation,@PreventiveMeasure,@RecommendedEpiId,@RecommendedTrainingId,@Status,@ResponsibleId,@EvidenceDocumentId,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,command.Name,command.Description,command.Type,command.Severity,command.Probability,level,command.WorkAreaId,command.JobRoleId,command.Operation,command.PreventiveMeasure,command.RecommendedEpiId,command.RecommendedTrainingId,command.Status,command.ResponsibleId,command.EvidenceDocumentId},t);if(command.Status=="ACTIVE"&&SstRules.IsCritical(level)){await Alert(c,t,id,"Risco crítico ativo",command.PreventiveMeasure is null?"CRITICAL":"HIGH");}return id;},ct);
    public Task<Guid> DeliverEpiAsync(EpiDeliveryCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var worker=await c.QuerySingleOrDefaultAsync<string>("select status from agro360.sst_workers where tenant_id=@TenantId and id=@WorkerId and deleted_at is null",new{tenant.TenantId,command.WorkerId},t);var epi=await c.QuerySingleOrDefaultAsync<bool?>("select status='ACTIVE' from agro360.sst_epi_catalog where tenant_id=@TenantId and id=@EpiId and deleted_at is null",new{tenant.TenantId,command.EpiId},t);if(worker is null||epi is null)throw new KeyNotFoundException("Trabalhador ou EPI não encontrado.");SstRules.ValidateEpiDelivery(worker,epi.Value,command.Quantity,command.DeliveredOn,command.ReplaceOn);var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.sst_epi_deliveries(id,tenant_id,worker_id,epi_id,quantity,delivered_on,replace_on,reason,responsible_id,acceptance,evidence_document_id,status,created_by,updated_by) values(@Id,@TenantId,@WorkerId,@EpiId,@Quantity,@DeliveredOn,@ReplaceOn,@Reason,@UserId,@Acceptance,@EvidenceDocumentId,'DELIVERED',@UserId,@UserId);insert into agro360.sst_epi_delivery_events(id,tenant_id,delivery_id,event_type,description,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,'DELIVERED','Entrega registrada',@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,command.WorkerId,command.EpiId,command.Quantity,command.DeliveredOn,command.ReplaceOn,command.Reason,command.Acceptance,command.EvidenceDocumentId},t);return id;},ct);
    public Task<IReadOnlyList<SstIncident>> IncidentsAsync(string? search,string? status,int page,int pageSize,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SstIncident>)(await c.QueryAsync<SstIncident>("select i.id,i.code,i.type,i.occurred_at occurredat,i.location,a.name areaname,i.description,i.severity,i.status,i.investigation_required investigationrequired from agro360.sst_incidents i join agro360.sst_work_areas a on a.tenant_id=i.tenant_id and a.id=i.work_area_id where i.tenant_id=@TenantId and i.deleted_at is null and (@Search is null or i.code ilike '%'||@Search||'%' or i.description ilike '%'||@Search||'%') and (@Status is null or i.status=@Status) order by i.occurred_at desc limit @Take offset @Skip",Page(search,status,page,pageSize),t)).ToArray(),ct);
    public Task<Guid> CreateIncidentAsync(SstIncidentCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SstRules.ValidateIncident(command.Description,command.Severity,command.InvestigationRequired);await EnsureLinks(c,t,("sst_work_areas",command.WorkAreaId));if(command.WorkerId is not null)await EnsureLinks(c,t,("sst_workers",command.WorkerId.Value));var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.sst_incidents(id,tenant_id,type,occurred_at,location,work_area_id,worker_id,description,severity,probable_cause,immediate_action,responsible_id,status,investigation_required,corrective_action_required,external_communication_required,created_by,updated_by) values(@Id,@TenantId,@Type,@OccurredAt,@Location,@WorkAreaId,@WorkerId,@Description,@Severity,@ProbableCause,@ImmediateAction,@ResponsibleId,'OPEN',@InvestigationRequired,@CorrectiveActionRequired,@ExternalCommunicationRequired,@UserId,@UserId);insert into agro360.sst_incident_events(id,tenant_id,incident_id,event_type,description,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,'OPENED','Ocorrência registrada',@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,command.Type,command.OccurredAt,command.Location,command.WorkAreaId,command.WorkerId,command.Description,command.Severity,command.ProbableCause,command.ImmediateAction,command.ResponsibleId,command.InvestigationRequired,command.CorrectiveActionRequired,command.ExternalCommunicationRequired},t);if(command.Severity>=4)await Alert(c,t,id,"Incidente grave requer investigação","CRITICAL");return id;},ct);
    public Task<Guid> ExecuteChecklistAsync(SstChecklistRunCommand command,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var items=(await c.QueryAsync<(Guid Id,bool Required,bool EvidenceRequired)>("select id,required,evidence_required evidencerequired from agro360.sst_checklist_items where tenant_id=@TenantId and template_id=@TemplateId order by sequence",new{tenant.TenantId,command.TemplateId},t)).ToArray();if(items.Length==0)throw new KeyNotFoundException("Checklist não encontrado ou sem itens.");SstRules.ValidateChecklist(items.Select(i=>{var a=command.Answers.FirstOrDefault(y=>y.ItemId==i.Id);return(i.Required,a is not null&&!string.IsNullOrWhiteSpace(a.Answer),i.EvidenceRequired,a?.EvidenceDocumentId is not null);}));var id=Guid.NewGuid();await c.ExecuteAsync("insert into agro360.sst_checklist_runs(id,tenant_id,template_id,worker_id,location,status,result,completed_at,completed_by,created_by,updated_by) values(@Id,@TenantId,@TemplateId,@WorkerId,@Location,'COMPLETED','APPROVED',now(),@UserId,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,command.TemplateId,command.WorkerId,command.Location},t);foreach(var a in command.Answers)await c.ExecuteAsync("insert into agro360.sst_checklist_answers(id,tenant_id,run_id,item_id,answer,evidence_document_id,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,@ItemId,@Answer,@EvidenceDocumentId,@UserId,@UserId)",new{tenant.TenantId,tenant.UserId,id,a.ItemId,a.Answer,a.EvidenceDocumentId},t);return id;},ct);
    private object Page(string? search,string? status,int page,int size)=>new{tenant.TenantId,Search=search,Status=status,Take=Math.Clamp(size,1,100),Skip=(Math.Max(page,1)-1)*Math.Clamp(size,1,100)};
    private async Task EnsureLinks(System.Data.IDbConnection c,System.Data.IDbTransaction t,params (string Table,Guid Id)[] links){foreach(var command in links)if(!await c.ExecuteScalarAsync<bool>($"select exists(select 1 from agro360.sst_{command.Table} where tenant_id=@TenantId and id=@Id and deleted_at is null)",new{tenant.TenantId,command.Id},t))throw new KeyNotFoundException("Relacionamento não encontrado neste tenant.");}
    private Task<int> Alert(System.Data.IDbConnection c,System.Data.IDbTransaction t,Guid origin,string title,string severity)=>c.ExecuteAsync("insert into agro360.operations_operational_alerts(id,tenant_id,dedup_key,title,description,severity,status,module,origin_type,origin_id,created_by,updated_by) values(gen_random_uuid(),@TenantId,'sst:'||@Origin,@Title,@Title,@Severity,'OPEN','SST','SST',@Origin,@UserId,@UserId) on conflict(tenant_id,dedup_key) do nothing",new{tenant.TenantId,tenant.UserId,Origin=origin,Title=title,Severity=severity},t);
}
