using Agro360.Application.Contracts;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class StockControlService(DatabaseExecutor database, ITenantContext tenant) : IStockControlService
{
    public Task<Guid> CreateTransferAsync(CreateStockTransferCommand command, CancellationToken ct)
    {
        if (command.SourceWarehouseId == command.DestinationWarehouseId) throw new DomainException("Origem e destino devem ser diferentes.", "transfer.same_warehouse");
        if (command.Items.Count == 0) throw new DomainException("Informe ao menos um item.", "transfer.items_required");
        return database.InTenantTransactionAsync<Guid>(async (db, tx) =>
        {
            var warehouseCount = await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_warehouses where tenant_id=@TenantId and id=any(@Ids) and farm_id=@FarmId and deleted_at is null", new { tenant.TenantId, Ids = new[] { command.SourceWarehouseId, command.DestinationWarehouseId }, command.FarmId }, tx, cancellationToken: ct));
            if (warehouseCount != 2) throw new DomainException("Os depósitos devem pertencer à unidade e ao cliente autenticado.", "transfer.warehouse_scope");
            var id = Guid.CreateVersion7();
            await db.ExecuteAsync(new CommandDefinition("""
                insert into agro360.inventory_transfers(id,tenant_id,farm_id,source_warehouse_id,destination_warehouse_id,requested_by,responsible_id,expected_on,justification,status,created_by,updated_by)
                values(@Id,@TenantId,@FarmId,@SourceWarehouseId,@DestinationWarehouseId,@UserId,@ResponsibleId,@ExpectedOn,@Justification,'AWAITING_SHIPMENT',@UserId,@UserId)
                """, new { Id=id, tenant.TenantId, command.FarmId, command.SourceWarehouseId, command.DestinationWarehouseId, UserId=tenant.UserId, command.ResponsibleId, command.ExpectedOn, Justification=Guard.Required(command.Justification,nameof(command.Justification),1000) }, tx, cancellationToken:ct));
            foreach (var item in command.Items)
            {
                var product = await db.QuerySingleOrDefaultAsync<(string Unit, bool RequiresLot)>(new CommandDefinition("select base_unit as Unit, requires_lot as RequiresLot from agro360.inventory_products where tenant_id=@TenantId and id=@ProductId and deleted_at is null",new {tenant.TenantId,item.ProductId},tx,cancellationToken:ct));
                if (string.IsNullOrEmpty(product.Unit)) throw new NotFoundException("Produto", item.ProductId);
                if (!string.Equals(product.Unit,item.Unit,StringComparison.OrdinalIgnoreCase)) throw new DomainException("A unidade deve ser a unidade base cadastrada.","transfer.unit_mismatch");
                if (product.RequiresLot && string.IsNullOrWhiteSpace(item.LotNumber)) throw new DomainException("O produto exige lote.","transfer.lot_required");
                await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_transfer_items(id,tenant_id,transfer_id,product_id,lot_number,quantity,unit,blocked) values(@Id,@TenantId,@TransferId,@ProductId,@LotNumber,@Quantity,@Unit,@AllowBlocked)",new {Id=Guid.CreateVersion7(),tenant.TenantId,TransferId=id,item.ProductId,item.LotNumber,Quantity=Guard.Positive(item.Quantity,nameof(item.Quantity)),Unit=product.Unit,item.AllowBlocked},tx,cancellationToken:ct));
            }
            await Event(db,tx,id,"CREATED",command.Justification,ct);
            return id;
        },ct);
    }

    public Task<PagedResult<StockTransferListDto>> ListTransfersAsync(int page,int pageSize,string? status,CancellationToken ct) => database.InTenantTransactionAsync<PagedResult<StockTransferListDto>>(async(db,tx)=>
    {
        page=Math.Max(1,page); pageSize=Math.Clamp(pageSize,1,100);
        using var grid=await db.QueryMultipleAsync(new CommandDefinition("""
            select count(*) from agro360.inventory_transfers where tenant_id=@TenantId and (@Status is null or status=@Status);
            select t.id,t.number,s.name Source,d.name Destination,t.expected_on ExpectedOn,t.status,count(i.id)::int Items,t.version
            from agro360.inventory_transfers t join agro360.inventory_warehouses s on s.tenant_id=t.tenant_id and s.id=t.source_warehouse_id
            join agro360.inventory_warehouses d on d.tenant_id=t.tenant_id and d.id=t.destination_warehouse_id
            left join agro360.inventory_transfer_items i on i.tenant_id=t.tenant_id and i.transfer_id=t.id
            where t.tenant_id=@TenantId and (@Status is null or t.status=@Status) group by t.id,s.name,d.name order by t.number desc limit @Take offset @Skip
            """,new {tenant.TenantId,Status=string.IsNullOrWhiteSpace(status)?null:status,Take=pageSize,Skip=(page-1)*pageSize},tx,cancellationToken:ct));
        var total=await grid.ReadSingleAsync<long>(); var items=(await grid.ReadAsync<StockTransferListDto>()).ToArray(); return new(items,page,pageSize,total);
    },ct);

    public Task<StockTransferDetailDto> GetTransferAsync(Guid id,CancellationToken ct)=>database.InTenantTransactionAsync<StockTransferDetailDto>(async(db,tx)=>
    {
        var h=await db.QuerySingleOrDefaultAsync<TransferHeader>(new CommandDefinition("""select t.id,t.number,t.source_warehouse_id SourceWarehouseId,s.name Source,t.destination_warehouse_id DestinationWarehouseId,d.name Destination,t.expected_on ExpectedOn,t.justification,t.status,t.shipped_at ShippedAt,t.version from agro360.inventory_transfers t join agro360.inventory_warehouses s on s.id=t.source_warehouse_id and s.tenant_id=t.tenant_id join agro360.inventory_warehouses d on d.id=t.destination_warehouse_id and d.tenant_id=t.tenant_id where t.tenant_id=@TenantId and t.id=@Id""",new {tenant.TenantId,Id=id},tx,cancellationToken:ct))??throw new NotFoundException("Transferência",id);
        var items=(await db.QueryAsync<StockTransferItemDto>(new CommandDefinition("select i.id,i.product_id ProductId,p.name Product,i.lot_number LotNumber,i.quantity Shipped,i.received,(i.quantity-i.received) InTransit,i.unit,i.blocked from agro360.inventory_transfer_items i join agro360.inventory_products p on p.id=i.product_id and p.tenant_id=i.tenant_id where i.tenant_id=@TenantId and i.transfer_id=@Id order by p.name,i.lot_number",new {tenant.TenantId,Id=id},tx,cancellationToken:ct))).ToArray();
        var history=(await db.QueryAsync<MaterialRequestEventDto>(new CommandDefinition("select e.type,'' status,coalesce(u.name,'Sistema') actor,e.reason,e.occurred_at OccurredAt from agro360.inventory_transfer_events e left join agro360.identity_users u on u.id=e.actor_id and u.tenant_id=e.tenant_id where e.tenant_id=@TenantId and e.transfer_id=@Id order by e.occurred_at",new {tenant.TenantId,Id=id},tx,cancellationToken:ct))).ToArray();
        return new(h.Id,h.Number,h.SourceWarehouseId,h.Source,h.DestinationWarehouseId,h.Destination,h.ExpectedOn,h.Justification,h.Status,h.ShippedAt,h.Version,items,history);
    },ct);

    public Task ShipAsync(Guid id,TransferActionCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>
    {
        var t=await LockTransfer(db,tx,id,ct); if(t.Status=="IN_TRANSIT"||t.Status=="PARTIALLY_RECEIVED"||t.Status=="RECEIVED") return; if(t.Status!="AWAITING_SHIPMENT") throw new ConflictException("A transferência não está pronta para expedição."); CheckVersion(t.Version,command.Version);
        var items=await db.QueryAsync<ItemRow>(new CommandDefinition("select id,product_id ProductId,lot_number LotNumber,quantity,unit,blocked from agro360.inventory_transfer_items where tenant_id=@TenantId and transfer_id=@Id order by id for update",new {tenant.TenantId,Id=id},tx,cancellationToken:ct));
        foreach(var item in items)
        {
            await EnsureNotCounting(db,tx,t.SourceWarehouseId,item.ProductId,ct); var b=await LockBalance(db,tx,t.SourceWarehouseId,item.ProductId,ct); if(b.Available-b.Reserved<item.Quantity) throw new ConflictException("Saldo disponível insuficiente para expedir.","transfer.insufficient_stock");
            await UpdateBalance(db,tx,b,b.Available-item.Quantity,b.AverageCost,ct);
            await InsertMovement(db,tx,t.SourceWarehouseId,item,"TRANSFER_OUT",item.Quantity,b.AverageCost,b.Available-item.Quantity,id,$"ship:{id}:{item.Id}",ct);
            await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_transfer_items set unit_cost=@Cost where tenant_id=@TenantId and id=@Id",new { Cost=b.AverageCost,tenant.TenantId,item.Id },tx,cancellationToken:ct));
        }
        await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_transfers set status='IN_TRANSIT',shipped_at=now(),shipped_by=@UserId,updated_at=now(),updated_by=@UserId,version=version+1 where tenant_id=@TenantId and id=@Id",new {tenant.TenantId,Id=id,UserId=tenant.UserId},tx,cancellationToken:ct)); await Event(db,tx,id,"SHIPPED",Guard.Required(command.Reason,nameof(command.Reason),1000),ct);
    },ct);

    public Task ReceiveAsync(Guid id,TransferReceiptCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>
    {
        var existing=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_transfer_receipts where tenant_id=@TenantId and idempotency_key=@Key",new {tenant.TenantId,Key=command.IdempotencyKey},tx,cancellationToken:ct)); if(existing>0)return;
        var t=await LockTransfer(db,tx,id,ct); if(t.Status is not ("IN_TRANSIT" or "PARTIALLY_RECEIVED")) throw new ConflictException("A transferência não possui material elegível em trânsito."); CheckVersion(t.Version,command.Version);
        var item=await db.QuerySingleOrDefaultAsync<ItemRow>(new CommandDefinition("select id,product_id ProductId,lot_number LotNumber,quantity,received,unit,blocked,unit_cost UnitCost from agro360.inventory_transfer_items where tenant_id=@TenantId and transfer_id=@Id and id=@ItemId for update",new {tenant.TenantId,Id=id,command.ItemId},tx,cancellationToken:ct))??throw new NotFoundException("Item",command.ItemId);
        var quantity=Guard.Positive(command.Quantity,nameof(command.Quantity)); if(item.Received+quantity>item.Quantity) throw new ConflictException("O recebimento supera a quantidade em trânsito; registre a sobra como ocorrência.","transfer.receipt_exceeds_transit");
        var condition=Guard.Required(command.Condition,nameof(command.Condition),20).ToUpperInvariant(); if(condition is not ("GOOD" or "DAMAGED" or "BLOCKED")) throw new DomainException("Condição inválida.");
        var receipt=Guid.CreateVersion7(); await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_transfer_receipts(id,tenant_id,transfer_id,item_id,quantity,condition,occurrence,idempotency_key,received_by) values(@Receipt,@TenantId,@Id,@ItemId,@Quantity,@Condition,@Occurrence,@Key,@UserId)",new {Receipt=receipt,tenant.TenantId,Id=id,command.ItemId,Quantity=quantity,Condition=condition,command.Occurrence,Key=Guard.Required(command.IdempotencyKey,nameof(command.IdempotencyKey),160),UserId=tenant.UserId},tx,cancellationToken:ct));
        if(condition=="GOOD"&&!item.Blocked)
        {
            await EnsureNotCounting(db,tx,t.DestinationWarehouseId,item.ProductId,ct); var b=await GetOrCreateBalance(db,tx,t.DestinationWarehouseId,item.ProductId,item.Unit,ct); var cost=item.UnitCost??b.AverageCost; var next=b.Available+quantity; var average=next==0?b.AverageCost:((b.Available*b.AverageCost)+(quantity*cost))/next; await UpdateBalance(db,tx,b,next,average,ct); await InsertMovement(db,tx,t.DestinationWarehouseId,item,"TRANSFER_IN",quantity,cost,next,id,$"receive:{receipt}",ct,"STOCK_TRANSFER_RECEIPT");
        }
        await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_transfer_items set received=received+@Quantity where tenant_id=@TenantId and id=@ItemId; update agro360.inventory_transfers set status=case when not exists(select 1 from agro360.inventory_transfer_items where tenant_id=@TenantId and transfer_id=@Id and id<>@ItemId and received<quantity) and @NewReceived=@Shipped then 'RECEIVED' else 'PARTIALLY_RECEIVED' end,updated_at=now(),updated_by=@UserId,version=version+1 where tenant_id=@TenantId and id=@Id",new {Quantity=quantity,tenant.TenantId,command.ItemId,Id=id,NewReceived=item.Received+quantity,Shipped=item.Quantity,UserId=tenant.UserId},tx,cancellationToken:ct)); await Event(db,tx,id,condition=="GOOD"?"RECEIVED":"DIVERGENCE",command.Occurrence,ct);
    },ct);

    public Task CancelTransferAsync(Guid id,TransferActionCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>{var t=await LockTransfer(db,tx,id,ct);CheckVersion(t.Version,command.Version);if(t.Status is not ("DRAFT" or "AWAITING_SHIPMENT"))throw new ConflictException("Após a expedição use retorno; movimentos físicos não são apagados.","transfer.return_required");await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_transfers set status='CANCELLED',version=version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id,UserId=tenant.UserId},tx,cancellationToken:ct));await Event(db,tx,id,"CANCELLED",Guard.Required(command.Reason,nameof(command.Reason),1000),ct);},ct);

    // Inventário usa bloqueio explícito: toda movimentação desta jornada consulta o escopo aberto.
    public Task<Guid> CreateCountAsync(CreatePhysicalCountCommand command,CancellationToken ct)=>database.InTenantTransactionAsync<Guid>(async(db,tx)=>
    { var wh=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_warehouses where tenant_id=@TenantId and id=@Id and deleted_at is null",new{tenant.TenantId,Id=command.WarehouseId},tx,cancellationToken:ct));if(wh!=1)throw new NotFoundException("Depósito",command.WarehouseId);var id=Guid.CreateVersion7();await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_counts(id,tenant_id,warehouse_id,category,product_id,lot_number,material_status,responsible_id,blind,created_by) values(@Id,@TenantId,@WarehouseId,@Category,@ProductId,@LotNumber,@MaterialStatus,@ResponsibleId,@Blind,@UserId)",new{Id=id,tenant.TenantId,command.WarehouseId,command.Category,command.ProductId,command.LotNumber,command.MaterialStatus,command.ResponsibleId,command.Blind,UserId=tenant.UserId},tx,cancellationToken:ct));return id;},ct);
    public Task<PagedResult<PhysicalCountListDto>> ListCountsAsync(int page,int pageSize,string? status,CancellationToken ct)=>database.InTenantTransactionAsync<PagedResult<PhysicalCountListDto>>(async(db,tx)=>{page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);using var g=await db.QueryMultipleAsync(new CommandDefinition("select count(*) from agro360.inventory_counts where tenant_id=@TenantId and (@Status is null or status=@Status); select c.id,c.number,w.name Warehouse,c.status,c.blind,count(i.id)::int TotalItems,count(i.accepted_quantity)::int CountedItems,c.version from agro360.inventory_counts c join agro360.inventory_warehouses w on w.id=c.warehouse_id and w.tenant_id=c.tenant_id left join agro360.inventory_count_items i on i.count_id=c.id and i.tenant_id=c.tenant_id where c.tenant_id=@TenantId and (@Status is null or c.status=@Status) group by c.id,w.name order by c.number desc limit @Take offset @Skip",new{tenant.TenantId,Status=string.IsNullOrWhiteSpace(status)?null:status,Take=pageSize,Skip=(page-1)*pageSize},tx,cancellationToken:ct));var total=await g.ReadSingleAsync<long>();return new((await g.ReadAsync<PhysicalCountListDto>()).ToArray(),page,pageSize,total);},ct);
    public Task OpenCountAsync(Guid id,CountActionCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>{var count=await LockCount(db,tx,id,ct);CheckVersion(count.Version,command.Version);if(count.Status!="PLANNED")throw new ConflictException("Somente inventário planejado pode ser aberto.");var overlap=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_counts where tenant_id=@TenantId and id<>@Id and warehouse_id=@WarehouseId and status in('COUNTING','RECONCILING','AWAITING_APPROVAL') and (product_id is null or @ProductId is null or product_id=@ProductId)",new{tenant.TenantId,Id=id,count.WarehouseId,count.ProductId},tx,cancellationToken:ct));if(overlap>0)throw new ConflictException("Existe inventário incompatível aberto neste escopo.","count.overlap");await db.ExecuteAsync(new CommandDefinition("""insert into agro360.inventory_count_items(id,tenant_id,count_id,product_id,lot_number,unit,reference_quantity,reference_reserved) select gen_random_uuid(),b.tenant_id,@Id,b.product_id,@LotNumber,b.unit,b.available,b.reserved from agro360.inventory_stock_balances b join agro360.inventory_products p on p.id=b.product_id and p.tenant_id=b.tenant_id where b.tenant_id=@TenantId and b.warehouse_id=@WarehouseId and (@ProductId is null or b.product_id=@ProductId) and (@Category is null or p.category=@Category); update agro360.inventory_counts set status='COUNTING',reference_at=now(),opened_at=now(),opened_by=@UserId,version=version+1 where tenant_id=@TenantId and id=@Id""",new{tenant.TenantId,Id=id,count.WarehouseId,count.ProductId,count.Category,count.LotNumber,UserId=tenant.UserId},tx,cancellationToken:ct));},ct);
    public Task RecordCountAsync(Guid id,RecordCountCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>{var count=await LockCount(db,tx,id,ct);CheckVersion(count.Version,command.Version);if(count.Status!="COUNTING")throw new ConflictException("O inventário não está em contagem.");if(!command.Quantity.HasValue)throw new DomainException("Campo vazio significa não contado; informe zero explicitamente quando não houver material.","count.quantity_required");var item=await db.QuerySingleOrDefaultAsync<ItemRow>(new CommandDefinition("select id,product_id ProductId,unit from agro360.inventory_count_items where tenant_id=@TenantId and count_id=@Id and id=@ItemId",new{tenant.TenantId,Id=id,command.ItemId},tx,cancellationToken:ct))??throw new NotFoundException("Item",command.ItemId);if(!string.Equals(item.Unit,command.Unit,StringComparison.OrdinalIgnoreCase))throw new DomainException("Unidade incompatível.");var round=await db.ExecuteScalarAsync<int>(new CommandDefinition("select coalesce(max(round),0)+1 from agro360.inventory_count_entries where tenant_id=@TenantId and item_id=@ItemId",new{tenant.TenantId,command.ItemId},tx,cancellationToken:ct));var entry=Guid.CreateVersion7();await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_count_entries(id,tenant_id,count_id,item_id,round,quantity,unit,note,evidence_url,counted_by) values(@Entry,@TenantId,@Id,@ItemId,@Round,@Quantity,@Unit,@Note,@Evidence,@UserId); update agro360.inventory_counts set version=version+1 where tenant_id=@TenantId and id=@Id",new{Entry=entry,tenant.TenantId,Id=id,command.ItemId,Round=round,Quantity=Guard.NonNegative(command.Quantity.Value,nameof(command.Quantity)),Unit=item.Unit,command.Note,Evidence=command.EvidenceUrl,UserId=tenant.UserId},tx,cancellationToken:ct));},ct);
    public Task ReconcileAsync(Guid id,ReconcileCountCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>{var count=await LockCount(db,tx,id,ct);CheckVersion(count.Version,command.Version);if(count.Status is not ("COUNTING" or "RECONCILING"))throw new ConflictException("Inventário não está disponível para reconciliação.");var quantity=await db.ExecuteScalarAsync<decimal?>(new CommandDefinition("select quantity from agro360.inventory_count_entries where tenant_id=@TenantId and count_id=@Id and item_id=@ItemId and id=@EntryId",new{tenant.TenantId,Id=id,command.ItemId,command.EntryId},tx,cancellationToken:ct));if(!quantity.HasValue)throw new NotFoundException("Contagem",command.EntryId);var decision=Guard.Required(command.Decision,nameof(command.Decision),24).ToUpperInvariant();if(decision is not("ACCEPT" or "RECOUNT" or "ADJUST" or "NO_ACTION"))throw new DomainException("Decisão inválida.");await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_count_items set accepted_entry_id=case when @Decision='RECOUNT' then null else @EntryId end,accepted_quantity=case when @Decision='RECOUNT' then null else @Quantity end,decision=@Decision,justification=@Reason where tenant_id=@TenantId and count_id=@Id and id=@ItemId; update agro360.inventory_counts set status='RECONCILING',version=version+1 where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id,command.ItemId,command.EntryId,Quantity=quantity.Value,Decision=decision,Reason=Guard.Required(command.Justification,nameof(command.Justification),1000)},tx,cancellationToken:ct));},ct);
    public Task ApproveAdjustmentsAsync(Guid id,CountActionCommand command,CancellationToken ct)=>database.InTenantTransactionAsync(async(db,tx)=>{var count=await LockCount(db,tx,id,ct);CheckVersion(count.Version,command.Version);var pending=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_count_items where tenant_id=@TenantId and count_id=@Id and accepted_quantity is null",new{tenant.TenantId,Id=id},tx,cancellationToken:ct));if(pending>0)throw new ConflictException("Existem itens não contados ou aguardando recontagem.","count.pending_items");var items=await db.QueryAsync<CountAdjustmentRow>(new CommandDefinition("select i.id,i.product_id ProductId,i.lot_number LotNumber,i.unit,i.reference_quantity,i.reference_reserved,i.accepted_quantity,p.name from agro360.inventory_count_items i join agro360.inventory_products p on p.id=i.product_id and p.tenant_id=i.tenant_id where i.tenant_id=@TenantId and i.count_id=@Id and i.adjustment_movement_id is null for update",new{tenant.TenantId,Id=id},tx,cancellationToken:ct));foreach(var item in items){var b=await LockBalance(db,tx,count.WarehouseId,item.ProductId,ct);if(b.Available!=item.ReferenceQuantity)throw new ConflictException("O saldo mudou após a abertura; o bloqueio de inventário foi violado.","count.stale_balance");if(item.AcceptedQuantity<item.ReferenceReserved)throw new ConflictException("O saldo físico aceito é inferior às reservas. Trate a insuficiência antes do ajuste.","count.reservation_shortage");var delta=item.AcceptedQuantity-item.ReferenceQuantity;if(delta==0)continue;var movement=await InsertMovement(db,tx,count.WarehouseId,new ItemRow{Id=item.Id,ProductId=item.ProductId,LotNumber=item.LotNumber,Unit=item.Unit},delta>0?"ADJUSTMENT_IN":"ADJUSTMENT_OUT",Math.Abs(delta),b.AverageCost,item.AcceptedQuantity,id,$"count:{id}:{item.Id}",ct,"PHYSICAL_COUNT_ADJUSTMENT");await UpdateBalance(db,tx,b,item.AcceptedQuantity,b.AverageCost,ct);await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_count_items set adjustment_movement_id=@Movement,adjustment_value=@Value,valuation_pending=@Pending where tenant_id=@TenantId and id=@ItemId",new{Movement=movement,Value=b.AverageCost>0?Math.Abs(delta)*b.AverageCost:(decimal?)null,Pending=b.AverageCost<=0,tenant.TenantId,ItemId=item.Id},tx,cancellationToken:ct));}await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_counts set status='COMPLETED',completed_at=now(),completed_by=@UserId,version=version+1 where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id,UserId=tenant.UserId},tx,cancellationToken:ct));},ct);
    public Task<PhysicalCountDetailDto> GetCountAsync(Guid id,CancellationToken ct)=>database.InTenantTransactionAsync<PhysicalCountDetailDto>(async(db,tx)=>{var c=await db.QuerySingleOrDefaultAsync<CountHeader>(new CommandDefinition("select c.id,c.number,c.warehouse_id WarehouseId,w.name Warehouse,c.status,c.blind,c.movement_policy MovementPolicy,c.reference_at ReferenceAt,c.version from agro360.inventory_counts c join agro360.inventory_warehouses w on w.id=c.warehouse_id and w.tenant_id=c.tenant_id where c.tenant_id=@TenantId and c.id=@Id",new{tenant.TenantId,Id=id},tx,cancellationToken:ct))??throw new NotFoundException("Inventário",id);var rows=(await db.QueryAsync<CountItemRow>(new CommandDefinition("select i.id,i.product_id ProductId,p.name Product,i.lot_number LotNumber,i.unit,i.reference_quantity ReferenceQuantity,i.reference_reserved Reserved,i.accepted_quantity AcceptedQuantity,case when i.accepted_quantity is null then null else i.accepted_quantity-i.reference_quantity end Difference,i.decision,i.valuation_pending ValuationPending from agro360.inventory_count_items i join agro360.inventory_products p on p.id=i.product_id and p.tenant_id=i.tenant_id where i.tenant_id=@TenantId and i.count_id=@Id order by p.name",new{tenant.TenantId,Id=id},tx,cancellationToken:ct))).ToArray();var result=new List<PhysicalCountItemDto>();foreach(var r in rows){var entries=(await db.QueryAsync<CountEntryDto>(new CommandDefinition("select e.id,e.round,e.quantity,e.unit,coalesce(u.name,'Sistema') Counter,e.counted_at CountedAt,e.note from agro360.inventory_count_entries e left join agro360.identity_users u on u.id=e.counted_by and u.tenant_id=e.tenant_id where e.tenant_id=@TenantId and e.item_id=@ItemId order by e.round",new{tenant.TenantId,ItemId=r.Id},tx,cancellationToken:ct))).ToArray();result.Add(new(r.Id,r.ProductId,r.Product,r.LotNumber,r.Unit,c.Blind&&c.Status=="COUNTING"?null:r.ReferenceQuantity,r.Reserved,r.AcceptedQuantity,r.Difference,r.Decision,r.ValuationPending,entries));}return new(c.Id,c.Number,c.WarehouseId,c.Warehouse,c.Status,c.Blind,c.MovementPolicy,c.ReferenceAt,c.Version,result);},ct);

    private async Task Event(NpgsqlConnection db,NpgsqlTransaction tx,Guid id,string type,string? reason,CancellationToken ct)=>await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_transfer_events(id,tenant_id,transfer_id,type,reason,actor_id) values(@Event,@TenantId,@Id,@Type,@Reason,@UserId)",new{Event=Guid.CreateVersion7(),tenant.TenantId,Id=id,Type=type,Reason=reason,UserId=tenant.UserId},tx,cancellationToken:ct));
    private async Task<TransferRow> LockTransfer(NpgsqlConnection db,NpgsqlTransaction tx,Guid id,CancellationToken ct)=>await db.QuerySingleOrDefaultAsync<TransferRow>(new CommandDefinition("select id,status,source_warehouse_id SourceWarehouseId,destination_warehouse_id DestinationWarehouseId,version from agro360.inventory_transfers where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},tx,cancellationToken:ct))??throw new NotFoundException("Transferência",id);
    private async Task<CountRow> LockCount(NpgsqlConnection db,NpgsqlTransaction tx,Guid id,CancellationToken ct)=>await db.QuerySingleOrDefaultAsync<CountRow>(new CommandDefinition("select id,status,warehouse_id WarehouseId,product_id ProductId,category,lot_number LotNumber,version from agro360.inventory_counts where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,Id=id},tx,cancellationToken:ct))??throw new NotFoundException("Inventário",id);
    private static void CheckVersion(long actual,long expected){if(actual!=expected)throw new ConflictException("O registro foi alterado por outra pessoa. Recarregue antes de continuar.","concurrency.version");}
    private async Task<BalanceRow> LockBalance(NpgsqlConnection db,NpgsqlTransaction tx,Guid warehouse,Guid product,CancellationToken ct)=>await db.QuerySingleOrDefaultAsync<BalanceRow>(new CommandDefinition("select id,available,reserved,average_cost AverageCost,version from agro360.inventory_stock_balances where tenant_id=@TenantId and warehouse_id=@Warehouse and product_id=@Product for update",new{tenant.TenantId,Warehouse=warehouse,Product=product},tx,cancellationToken:ct))??throw new ConflictException("Não existe saldo para o item.");
    private async Task<BalanceRow> GetOrCreateBalance(NpgsqlConnection db,NpgsqlTransaction tx,Guid warehouse,Guid product,string unit,CancellationToken ct){var b=await db.QuerySingleOrDefaultAsync<BalanceRow>(new CommandDefinition("select id,available,reserved,average_cost AverageCost,version from agro360.inventory_stock_balances where tenant_id=@TenantId and warehouse_id=@Warehouse and product_id=@Product for update",new{tenant.TenantId,Warehouse=warehouse,Product=product},tx,cancellationToken:ct));if(b is not null)return b;b=new(){Id=Guid.CreateVersion7()};await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_stock_balances(id,tenant_id,warehouse_id,product_id,unit,available,reserved,minimum,average_cost,created_at,updated_at,version) values(@Id,@TenantId,@Warehouse,@Product,@Unit,0,0,0,0,now(),now(),0)",new{b.Id,tenant.TenantId,Warehouse=warehouse,Product=product,Unit=unit},tx,cancellationToken:ct));return b;}
    private async Task UpdateBalance(NpgsqlConnection db,NpgsqlTransaction tx,BalanceRow b,decimal available,decimal cost,CancellationToken ct)=>await db.ExecuteAsync(new CommandDefinition("update agro360.inventory_stock_balances set available=@Available,average_cost=@Cost,version=version+1,updated_at=now() where tenant_id=@TenantId and id=@Id and version=@Version",new{Available=available,Cost=cost,tenant.TenantId,b.Id,b.Version},tx,cancellationToken:ct));
    private async Task<Guid> InsertMovement(NpgsqlConnection db,NpgsqlTransaction tx,Guid warehouse,ItemRow item,string type,decimal quantity,decimal cost,decimal after,Guid reference,string key,CancellationToken ct,string referenceType="STOCK_TRANSFER_SHIPMENT"){var movement=Guid.CreateVersion7();await db.ExecuteAsync(new CommandDefinition("insert into agro360.inventory_stock_movements(id,tenant_id,warehouse_id,product_id,movement_type,quantity,unit,unit_cost,total_cost,lot_number,reference_type,reference_id,notes,idempotency_key,balance_after,average_cost_after,balance_version,occurred_at,created_by) values(@Movement,@TenantId,@Warehouse,@Product,@Type,@Quantity,@Unit,@Cost,@Total,@Lot,@ReferenceType,@Reference,@Notes,@Key,@After,@Cost,1,now(),@UserId)",new{Movement=movement,tenant.TenantId,Warehouse=warehouse,Product=item.ProductId,Type=type,Quantity=quantity,Unit=item.Unit,Cost=cost,Total=quantity*cost,Lot=item.LotNumber,ReferenceType=referenceType,Reference=reference,Notes="Operação rastreável de estoque",Key=key,After=after,UserId=tenant.UserId},tx,cancellationToken:ct));return movement;}
    private async Task EnsureNotCounting(NpgsqlConnection db,NpgsqlTransaction tx,Guid warehouse,Guid product,CancellationToken ct){var blocked=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from agro360.inventory_counts where tenant_id=@TenantId and warehouse_id=@Warehouse and status in('COUNTING','RECONCILING','AWAITING_APPROVAL') and (product_id is null or product_id=@Product)",new{tenant.TenantId,Warehouse=warehouse,Product=product},tx,cancellationToken:ct));if(blocked>0)throw new ConflictException("Há inventário aberto com bloqueio de movimentação neste escopo.","count.movement_blocked");}
    private sealed class TransferHeader{public Guid Id{get;set;}public long Number{get;set;}public Guid SourceWarehouseId{get;set;}public string Source{get;set;}="";public Guid DestinationWarehouseId{get;set;}public string Destination{get;set;}="";public DateOnly ExpectedOn{get;set;}public string Justification{get;set;}="";public string Status{get;set;}="";public DateTimeOffset? ShippedAt{get;set;}public long Version{get;set;}}
    private sealed class TransferRow{public Guid Id{get;set;}public string Status{get;set;}="";public Guid SourceWarehouseId{get;set;}public Guid DestinationWarehouseId{get;set;}public long Version{get;set;}}
    private sealed class ItemRow{public Guid Id{get;set;}public Guid ProductId{get;set;}public string? LotNumber{get;set;}public decimal Quantity{get;set;}public decimal Received{get;set;}public string Unit{get;set;}="";public bool Blocked{get;set;}public decimal? UnitCost{get;set;}}
    private sealed class BalanceRow{public Guid Id{get;set;}public decimal Available{get;set;}public decimal Reserved{get;set;}public decimal AverageCost{get;set;}public long Version{get;set;}}
    private sealed class CountRow{public Guid Id{get;set;}public string Status{get;set;}="";public Guid WarehouseId{get;set;}public Guid? ProductId{get;set;}public string? Category{get;set;}public string? LotNumber{get;set;}public long Version{get;set;}}
    private sealed class CountHeader{public Guid Id{get;set;}public long Number{get;set;}public Guid WarehouseId{get;set;}public string Warehouse{get;set;}="";public string Status{get;set;}="";public bool Blind{get;set;}public string MovementPolicy{get;set;}="";public DateTimeOffset? ReferenceAt{get;set;}public long Version{get;set;}}
    private sealed class CountItemRow{public Guid Id{get;set;}public Guid ProductId{get;set;}public string Product{get;set;}="";public string? LotNumber{get;set;}public string Unit{get;set;}="";public decimal ReferenceQuantity{get;set;}public decimal Reserved{get;set;}public decimal? AcceptedQuantity{get;set;}public decimal? Difference{get;set;}public string? Decision{get;set;}public bool ValuationPending{get;set;}}
    private sealed class CountAdjustmentRow{public Guid Id{get;set;}public Guid ProductId{get;set;}public string? LotNumber{get;set;}public string Unit{get;set;}="";public decimal ReferenceQuantity{get;set;}public decimal ReferenceReserved{get;set;}public decimal AcceptedQuantity{get;set;}}
}
