using System.Text.Json;
using Agro360.Application.Contracts;
using Agro360.Domain.Storage;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Agro360.Infrastructure.Services;

public sealed class StorageService(DatabaseExecutor db,ITenantContext tenant,ILogger<StorageService> logger):IStorageService
{
 public Task<IReadOnlyList<dynamic>> ListAsync(string resource,CancellationToken ct)=>Query($"select * from agro360.storage_{Table(resource)} where tenant_id=@TenantId order by created_at desc",ct);
 public Task<dynamic?> GetAsync(string resource,Guid id,CancellationToken ct)=>Tx(async(c,t)=>await c.QuerySingleOrDefaultAsync(new CommandDefinition($"select * from agro360.storage_{Table(resource)} where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,Id=id},t,cancellationToken:ct)));
 public Task<Guid> SaveStructureAsync(Guid? id,StorageStructureCommand command,CancellationToken ct){StorageRules.Capacity(command.TotalCapacity,0);if(!new[]{"AVAILABLE","IN_USE","FULL","MAINTENANCE","INTERDICTED","INACTIVE"}.Contains(command.Status))throw new DomainException("Status operacional inválido.");return Save(id,"structures",command,"code,name,type,location,total_capacity,available_capacity,unit,allowed_product_id,status,property_id,responsible,notes","@Code,@Name,@Type,@Location,@TotalCapacity,@TotalCapacity,@Unit,@AllowedProductId,@Status,@PropertyId,@Responsible,@Notes",ct);}
 public Task<Guid> SaveReceiptAsync(Guid? id,ReceiptCommandV9 command,CancellationToken ct){if(command.ProductId==Guid.Empty)throw new DomainException("Produto é obrigatório.","agro360.storage_product_required");return Save(id,"receipts",command,"number,entry_type,product_id,season_id,plot_id,origin_property_id,supplier,carrier,driver,vehicle,plate,destination_structure_id,unloading_location,notes,status,entered_at","@Number,@EntryType,@ProductId,@SeasonId,@PlotId,@OriginPropertyId,@Supplier,@Carrier,@Driver,@Vehicle,@Plate,@DestinationStructureId,@UnloadingLocation,@Notes,'AWAITING_WEIGHING',now()",ct);}
 public Task WeighAsync(Guid id,WeighReceiptCommand command,CancellationToken ct){var net=StorageRules.NetWeight(command.GrossWeight,command.Tare);return ExecuteAudit("update agro360.storage_receipts set gross_weight=@GrossWeight,tare=@Tare,net_weight=@Net,final_weight=@Net,status='WEIGHED',updated_at=now() where tenant_id=@TenantId and id=@Id and status not in('UNLOADED','CANCELLED')",new{command.GrossWeight,command.Tare,Net=net},"weigh","Receipt",id,ct);}
 public Task ClassifyAsync(Guid id,ClassificationCommand command,CancellationToken ct){if(new decimal[]{command.Moisture,command.Impurity,command.Damaged,command.Burnt,command.Broken,command.Green??0,command.Protein??0,command.Acidity??0}.Any(v=>v<0))throw new DomainException("Percentuais não podem ser negativos.");return Tx(async(c,t)=>{var p=new DynamicParameters(command);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("ClassificationId",Guid.CreateVersion7());p.Add("UserId",tenant.UserId);await c.ExecuteAsync(new CommandDefinition("insert into agro360.storage_quality_classifications(id,tenant_id,receipt_id,moisture,impurity,damaged,burnt,broken,green,hectoliter_weight,protein,acidity,temperature,result,report,responsible,notes,created_by) select @ClassificationId,@TenantId,@Id,@Moisture,@Impurity,@Damaged,@Burnt,@Broken,@Green,@HectoliterWeight,@Protein,@Acidity,@Temperature,case when exists(select 1 from agro360.storage_quality_parameters where tenant_id=@TenantId and product_id=r.product_id and active and reject_value is not null and ((name='MOISTURE' and @Moisture>reject_value) or (name='IMPURITY' and @Impurity>reject_value))) then 'REJECTED' else 'APPROVED' end,@Report,@UserId::text,@Notes,@UserId from agro360.storage_receipts r where r.id=@Id and r.tenant_id=@TenantId; update agro360.storage_receipts r set status='CLASSIFIED',quality_result=q.result,technical_discount=coalesce((select sum(discount_percent) from agro360.storage_quality_parameters p where p.tenant_id=@TenantId and p.product_id=r.product_id and p.active and ((p.name='MOISTURE' and @Moisture>p.warning_value) or (p.name='IMPURITY' and @Impurity>p.warning_value))),0),final_weight=greatest(0,net_weight*(1-coalesce((select sum(discount_percent) from agro360.storage_quality_parameters p where p.tenant_id=@TenantId and p.product_id=r.product_id and p.active and ((p.name='MOISTURE' and @Moisture>p.warning_value) or (p.name='IMPURITY' and @Impurity>p.warning_value))),0)/100)) from agro360.storage_quality_classifications q where r.id=@Id and r.tenant_id=@TenantId and q.id=@ClassificationId",p,t,cancellationToken:ct));await Audit(c,t,"classify","Receipt",id,command,ct);});}
 public Task ReceiptStatusAsync(Guid id,string status,string? reason,CancellationToken ct)=>Tx(async(c,t)=>{if(status=="UNLOADED")await c.ExecuteAsync(new CommandDefinition("select agro360.storage_unload_receipt(@TenantId,@Id,@UserId)",new{tenant.TenantId,Id=id,tenant.UserId},t,cancellationToken:ct));else {var allowed=status=="APPROVED"?"status='CLASSIFIED' and quality_result<>'REJECTED'":status=="CANCELLED"?"status<>'UNLOADED'":"true";var n=await c.ExecuteAsync(new CommandDefinition($"update agro360.storage_receipts set status=@Status,cancel_reason=@Reason,updated_at=now() where tenant_id=@TenantId and id=@Id and {allowed}",new{tenant.TenantId,Id=id,Status=status,Reason=reason},t,cancellationToken:ct));if(n==0)throw new ConflictException("Transição de romaneio não permitida.");}await Audit(c,t,status.ToLowerInvariant(),"Receipt",id,new{reason},ct);});
 public Task<Guid> SaveQualityParameterAsync(Guid? id,QualityParameterCommand command,CancellationToken ct){if(command.WarningValue<0||command.RejectValue<0||command.DiscountPercent<0)throw new DomainException("Parâmetros de qualidade não podem ser negativos.");return Save(id,"quality_parameters",command,"product_id,name,warning_value,reject_value,discount_percent,active","@ProductId,@Name,@WarningValue,@RejectValue,@DiscountPercent,@Active",ct);}
 public Task TransferLotAsync(Guid id,TransferLotCommand command,CancellationToken ct)=>Tx(async(c,t)=>{await c.ExecuteAsync(new CommandDefinition("select agro360.storage_transfer_lot(@TenantId,@Id,@DestinationStructureId,@Quantity,@UserId,@Notes,@AllowOverflow)",new{tenant.TenantId,Id=id,command.DestinationStructureId,command.Quantity,tenant.UserId,command.Notes,command.AllowOverflow},t,cancellationToken:ct));await Audit(c,t,"transfer","StoredLot",id,command,ct);});
 public Task SetLotBlockedAsync(Guid id,bool blocked,string? reason,CancellationToken ct)=>ExecuteAudit("update agro360.storage_lots set status=@Status,block_reason=@Reason,updated_at=now() where tenant_id=@TenantId and id=@Id and status<>'CLOSED'",new{Status=blocked?"BLOCKED":"AVAILABLE",Reason=reason},blocked?"block":"unblock","StoredLot",id,ct);
 public Task<Guid> CreateProcessingAsync(ProcessingOrderCommand command,CancellationToken ct)=>Save(null,"processing_orders",command,"input_lot_id,output_product_id,input_quantity,process,cost,responsible,notes,status","@InputLotId,@OutputProductId,@InputQuantity,@Process,@Cost,@Responsible,@Notes,'PLANNED'",ct);
 public Task ProcessingStatusAsync(Guid id,string status,CompleteProcessingCommand? completion,string? reason,CancellationToken ct)=>Tx(async(c,t)=>{if(status=="COMPLETED"){if(completion is null||completion.OutputQuantity<=0||completion.TechnicalLoss<0)throw new DomainException("Conclusão exige saída e perda válidas.");await c.ExecuteAsync(new CommandDefinition("select agro360.storage_complete_processing(@TenantId,@Id,@OutputQuantity,@TechnicalLoss,@Justification,@UserId)",new{tenant.TenantId,Id=id,completion.OutputQuantity,completion.TechnicalLoss,completion.Justification,tenant.UserId},t,cancellationToken:ct));}else await c.ExecuteAsync(new CommandDefinition("update agro360.storage_processing_orders set status=@Status,cancel_reason=@Reason,started_at=case when @Status='IN_PROGRESS' then now() else started_at end,updated_at=now() where tenant_id=@TenantId and id=@Id and status not in('COMPLETED','CANCELLED')",new{tenant.TenantId,Id=id,Status=status,Reason=reason},t,cancellationToken:ct));await Audit(c,t,status.ToLowerInvariant(),"ProcessingOrder",id,(object?)completion??new{reason},ct);});
 public Task<Guid> CreateShipmentAsync(ShipmentCommand command,CancellationToken ct){if(command.RequestedQuantity<=0)throw new DomainException("Quantidade solicitada deve ser positiva.");return Save(null,"shipments",command,"number,contract_id,customer,product_id,lot_id,requested_quantity,destination,carrier,driver,vehicle,plate,status","@Number,@ContractId,@Customer,@ProductId,@LotId,@RequestedQuantity,@Destination,@Carrier,@Driver,@Vehicle,@Plate,'DRAFT'",ct);}
 public Task LoadShipmentAsync(Guid id,LoadShipmentCommand command,CancellationToken ct){var net=StorageRules.NetWeight(command.GrossWeight,command.Tare);return ExecuteAudit("update agro360.storage_shipments set loaded_quantity=@LoadedQuantity,gross_weight=@GrossWeight,tare=@Tare,net_weight=@Net,status='LOADED',loaded_at=now(),updated_at=now() where tenant_id=@TenantId and id=@Id and status in('DRAFT','SEPARATED','LOADING')",new{command.LoadedQuantity,command.GrossWeight,command.Tare,Net=net},"load","Shipment",id,ct);}
 public Task ShipmentStatusAsync(Guid id,string status,string? reason,CancellationToken ct)=>Tx(async(c,t)=>{if(status=="DISPATCHED")await c.ExecuteAsync(new CommandDefinition("select agro360.storage_dispatch_shipment(@TenantId,@Id,@UserId)",new{tenant.TenantId,Id=id,tenant.UserId},t,cancellationToken:ct));else {if(status=="CANCELLED"&&string.IsNullOrWhiteSpace(reason))throw new DomainException("Cancelamento exige justificativa.");await c.ExecuteAsync(new CommandDefinition("update agro360.storage_shipments set status=@Status,cancel_reason=@Reason,updated_at=now() where tenant_id=@TenantId and id=@Id and status<>'DISPATCHED'",new{tenant.TenantId,Id=id,Status=status,Reason=reason},t,cancellationToken:ct));}await Audit(c,t,status.ToLowerInvariant(),"Shipment",id,new{reason},ct);});
 public Task<dynamic> DashboardAsync(CancellationToken ct)=>Tx<dynamic>(async(c,t)=>await c.QuerySingleAsync(new CommandDefinition("select * from agro360.storage_dashboard(@TenantId)",new{tenant.TenantId},t,cancellationToken:ct)));
 private Task<Guid> Save(Guid? id,string table,object x,string columns,string values,CancellationToken ct)=>Tx(async(c,t)=>{var key=id??Guid.CreateVersion7();var p=new DynamicParameters(x);p.Add("Id",key);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var sql=id is null?$"insert into agro360.storage_{table}(id,tenant_id,{columns},created_by) values(@Id,@TenantId,{values},@UserId)":$"update agro360.storage_{table} set ({columns})=({values}),updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId";if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new NotFoundException(table,key);await Audit(c,t,id is null?"create":"update",table,key,x,ct);return key;});
 private Task<bool> ExecuteAudit(string sql,object x,string action,string entity,Guid id,CancellationToken ct)=>Tx(async(c,t)=>{var p=new DynamicParameters(x);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);if(await c.ExecuteAsync(new CommandDefinition(sql,p,t,cancellationToken:ct))==0)throw new ConflictException("Operação não permitida no estado atual.");await Audit(c,t,action,entity,id,x,ct);});
 private Task<IReadOnlyList<dynamic>> Query(string sql,CancellationToken ct)=>Tx<IReadOnlyList<dynamic>>(async(c,t)=>(await c.QueryAsync(new CommandDefinition(sql,new{tenant.TenantId},t,cancellationToken:ct))).AsList());
 private static string Table(string r)=>r switch{"structures"=>"structures","receipts"=>"receipts","quality-parameters"=>"quality_parameters","lots"=>"lots","processing-orders"=>"processing_orders","shipments"=>"shipments",_=>throw new ArgumentException("Recurso inválido.")};
 private Task Audit(NpgsqlConnection c,NpgsqlTransaction t,string action,string entity,Guid id,object value,CancellationToken ct)=>c.WriteAuditAsync(t,tenant,action,entity,id,null,JsonSerializer.Serialize(value),ct);
 private async Task<T> Tx<T>(Func<NpgsqlConnection,NpgsqlTransaction,Task<T>> work){try{return await db.InTenantTransactionAsync(work,CancellationToken.None);}catch(Exception ex){InfrastructureLogMessages.StorageBoundaryFailed(logger,tenant.TenantId,ex);throw;}}
 private Task<bool> Tx(Func<NpgsqlConnection,NpgsqlTransaction,Task> work)=>Tx(async(c,t)=>{await work(c,t);return true;});
}
