using Agro360.Application.Contracts;
using Agro360.Domain.Support;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class SupportCustomerSuccessService(DatabaseExecutor db, ITenantContext tenant) : ISupportCustomerSuccessService
{
 public Task<SupportDashboard> DashboardAsync(CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleAsync<SupportDashboard>("select count(*) filter(where status not in('CLOSED','CANCELLED')) opentickets,count(*) filter(where severity='CRITICAL' and status not in('CLOSED','CANCELLED')) criticaltickets,count(*) filter(where resolution_due_at<now() and status not in('RESOLVED','CLOSED','CANCELLED')) breachedtickets,count(*) filter(where status='REOPENED') reopenedtickets,coalesce(avg(extract(epoch from(first_responded_at-opened_at))/3600) filter(where first_responded_at is not null),0) averagefirstresponsehours,coalesce(avg(extract(epoch from(resolved_at-opened_at))/3600) filter(where resolved_at is not null),0) averageresolutionhours,coalesce(100*count(*) filter(where resolved_at<=resolution_due_at)/nullif(count(*) filter(where resolved_at is not null),0),100) slacompliancepercent,(select count(*) from support.customer_feedback where tenant_id=@TenantId) feedbackcount,(select avg(score) from support.customer_feedback where tenant_id=@TenantId and type='NPS') npsaverage,(select count(*) from support.implementation_projects where tenant_id=@TenantId and status='ACTIVE') activeimplementations,(select count(*) from support.implementation_projects where tenant_id=@TenantId and due_on<current_date and status='ACTIVE') lateimplementations,(select count(*) from support.training_assignments where tenant_id=@TenantId and status='PENDING') pendingtrainings,(select count(*) from support.product_backlog_items where tenant_id=@TenantId and status not in('DELIVERED','REJECTED','ARCHIVED')) openbacklog,(select count(*) from support.product_backlog_items where tenant_id=@TenantId and status='DELIVERED') deliveredbacklog from support.support_tickets where tenant_id=@TenantId",new{tenant.TenantId},t),ct);
 public Task<IReadOnlyList<SupportLookup>> TenantsAsync(string? search,CancellationToken ct)=>db.InSystemTransactionAsync(async(c,t)=>(IReadOnlyList<SupportLookup>)(await c.QueryAsync<SupportLookup>("select id,name from tenancy.tenants where status='ACTIVE' and (@Search is null or name ilike '%'||@Search||'%') order by name limit 30",new{Search=search},t)).ToArray(),ct);
 public Task<IReadOnlyList<SupportLookup>> AgentsAsync(string? search,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SupportLookup>)(await c.QueryAsync<SupportLookup>("select id,name from identity.users where tenant_id=@TenantId and status='ACTIVE' and (@Search is null or name ilike '%'||@Search||'%') order by name limit 30",new{tenant.TenantId,Search=search},t)).ToArray(),ct);
 public Task<IReadOnlyList<SupportTicket>> TicketsAsync(string? search,string? status,string? priority,int page,int pageSize,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SupportTicket>)(await c.QueryAsync<SupportTicket>(TicketSelect+" where x.tenant_id=@TenantId and (@Search is null or x.title ilike '%'||@Search||'%' or x.public_code ilike '%'||@Search||'%') and (@Status is null or x.status=@Status) and (@Priority is null or x.priority=@Priority) order by x.opened_at desc limit @Take offset @Skip",new{tenant.TenantId,Search=search,Status=status,Priority=priority,Take=Math.Clamp(pageSize,1,100),Skip=(Math.Max(page,1)-1)*Math.Clamp(pageSize,1,100)},t)).ToArray(),ct);
 public Task<SupportTicket?> TicketAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>c.QuerySingleOrDefaultAsync<SupportTicket>(TicketSelect+" where x.tenant_id=@TenantId and x.id=@Id",new{tenant.TenantId,id},t),ct);
 public Task<Guid> CreateTicketAsync(TicketCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(!SupportRules.Priorities.Contains(x.Priority))throw new ArgumentException("Prioridade inválida.");var policy=await c.QueryFirstOrDefaultAsync<(int First,int Resolution)>("select first_response_minutes first,resolution_minutes resolution from support.support_sla_policies where (tenant_id=@TenantId or tenant_id is null) and active and (category is null or category=@Category) and priority=@Priority and severity=@Severity order by tenant_id nulls last limit 1",new{tenant.TenantId,x.Category,x.Priority,x.Severity},t);if(policy.First<=0)policy=(480,2880);var due=SupportRules.CalculateSla(DateTimeOffset.UtcNow,policy.First,policy.Resolution);var id=Guid.NewGuid();await c.ExecuteAsync("insert into support.support_tickets(id,tenant_id,requester_id,requester_profile,channel,category,subcategory,module,title,description,priority,severity,status,first_response_due_at,resolution_due_at,created_by,updated_by) values(@Id,@TenantId,@UserId,'USER',@Channel,@Category,@Subcategory,@Module,@Title,@Description,@Priority,@Severity,'OPEN',@First,@Resolution,@UserId,@UserId)",new{id,tenant.TenantId,tenant.UserId,x.Channel,x.Category,x.Subcategory,x.Module,x.Title,x.Description,x.Priority,x.Severity,due.FirstResponse,due.Resolution},t);await Event(c,t,id,"CREATED","Chamado aberto");if(x.Severity=="CRITICAL")await CreateAlert(c,t,id,"Chamado crítico sem triagem");return id;},ct);
 public Task TransitionTicketAsync(Guid id,TicketTransition x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SupportRules.ValidateTransition(x.Status,x.Reason,x.Resolution);var ticket=await c.QuerySingleOrDefaultAsync<(string Status,string Priority)>("select status,priority from support.support_tickets where tenant_id=@TenantId and id=@Id for update",new{tenant.TenantId,id},t);if(ticket==default)throw new KeyNotFoundException("Chamado não encontrado.");if(x.Status=="IN_PROGRESS"&&x.AssigneeId is null)throw new ArgumentException("Defina um responsável antes de iniciar o atendimento.");await c.ExecuteAsync("update support.support_tickets set status=@Status,assignee_id=coalesce(@AssigneeId,assignee_id),area=coalesce(@Area,area),cancellation_reason=case when @Status='CANCELLED' then @Reason else cancellation_reason end,resolution_response=case when @Status='RESOLVED' then @Resolution else resolution_response end,first_responded_at=case when @Status='IN_PROGRESS' then coalesce(first_responded_at,now()) else first_responded_at end,resolved_at=case when @Status='RESOLVED' then now() else resolved_at end,closed_at=case when @Status='CLOSED' then now() else closed_at end,closed_by=case when @Status='CLOSED' then @UserId else closed_by end,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,x.Status,x.Reason,x.Resolution,x.AssigneeId,x.Area,tenant.UserId},t);await Event(c,t,id,"STATUS_CHANGED",$"{ticket.Status} → {x.Status}. {x.Reason}" );},ct);
 public Task CommentAsync(Guid id,TicketCommentCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var n=await c.ExecuteAsync("insert into support.support_ticket_comments(id,tenant_id,ticket_id,author_id,body,internal,created_by,updated_by) select gen_random_uuid(),@TenantId,id,@UserId,@Body,@Internal,@UserId,@UserId from support.support_tickets where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,tenant.UserId,x.Body,x.Internal},t);if(n==0)throw new KeyNotFoundException("Chamado não encontrado.");await Event(c,t,id,x.Internal?"INTERNAL_COMMENT":"CUSTOMER_REPLY",x.Internal?"Comentário interno registrado":"Resposta enviada ao cliente");},ct);
 public Task<IReadOnlyList<SupportEvent>> EventsAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SupportEvent>)(await c.QueryAsync<SupportEvent>("select e.id,e.event_type eventtype,e.description,u.name actorname,e.created_at createdat from support.support_ticket_events e join identity.users u on u.id=e.created_by where e.tenant_id=@TenantId and e.ticket_id=@Id order by e.created_at desc",new{tenant.TenantId,id},t)).ToArray(),ct);
 public Task<IReadOnlyList<SlaPolicy>> SlaAsync(CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<SlaPolicy>)(await c.QueryAsync<SlaPolicy>("select id,name,plan,contract_type contracttype,category,priority,severity,first_response_minutes firstresponseminutes,resolution_minutes resolutionminutes,pause_waiting_customer pausewaitingcustomer,active from support.support_sla_policies where tenant_id=@TenantId or tenant_id is null order by name",new{tenant.TenantId},t)).ToArray(),ct);
 public Task<Guid> SaveSlaAsync(SlaPolicyCommand x,CancellationToken ct)=>Insert("support_sla_policies","name,plan,contract_type,category,priority,severity,first_response_minutes,resolution_minutes,pause_waiting_customer,active","@Name,@Plan,@ContractType,@Category,@Priority,@Severity,@FirstResponseMinutes,@ResolutionMinutes,@PauseWaitingCustomer,@Active",x,ct);
 public Task<IReadOnlyList<KnowledgeArticle>> ArticlesAsync(string? search,string? module,bool publicOnly,CancellationToken ct)=>Query<KnowledgeArticle>("select id,slug,title,type,module,audience,status,views,helpful,not_helpful nothelpful,published_at publishedat from support.knowledge_articles where (tenant_id=@TenantId or tenant_id is null) and deleted_at is null and (@PublicOnly=false or status='PUBLISHED') and (@Search is null or title ilike '%'||@Search||'%' or content ilike '%'||@Search||'%') and (@Module is null or module=@Module) order by published_at desc nulls last",new{tenant.TenantId,Search=search,Module=module,PublicOnly=publicOnly},ct);
 public Task<Guid> CreateArticleAsync(ArticleCommand x,CancellationToken ct)=>Insert("knowledge_articles","slug,title,content,type,module,audience,status,global","lower(regexp_replace(@Title,'[^a-zA-Z0-9]+','-','g'))||'-'||substr(gen_random_uuid()::text,1,8),@Title,@Content,@Type,@Module,@Audience,'DRAFT',@Global",x,ct);
 public Task PublishArticleAsync(Guid id,bool archive,CancellationToken ct)=>Update(id,"knowledge_articles","status=case when @Archive then 'ARCHIVED' else 'PUBLISHED' end,published_at=case when @Archive then published_at else now() end",new{Archive=archive},ct);
 public Task RateArticleAsync(Guid id,ArticleFeedbackCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{await c.ExecuteAsync("insert into support.knowledge_article_feedback(id,tenant_id,article_id,user_id,helpful,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,@UserId,@Helpful,@UserId,@UserId) on conflict(article_id,user_id) do update set helpful=excluded.helpful,updated_at=now(),updated_by=@UserId",new{tenant.TenantId,id,tenant.UserId,x.Helpful},t);await c.ExecuteAsync("update support.knowledge_articles set helpful=(select count(*) from support.knowledge_article_feedback where article_id=@Id and helpful),not_helpful=(select count(*) from support.knowledge_article_feedback where article_id=@Id and not helpful) where id=@Id and (tenant_id=@TenantId or tenant_id is null)",new{tenant.TenantId,id},t);},ct);
 public Task<IReadOnlyList<ImplementationProject>> ImplementationsAsync(CancellationToken ct)=>Query<ImplementationProject>("select p.id,p.name,t.name tenantname,p.status,p.starts_on startson,p.due_on dueon,coalesce(round(100.0*count(ph.id) filter(where ph.status='COMPLETED')/nullif(count(ph.id),0)),0)::int progress,count(r.id) filter(where r.status='OPEN')::int openrisks from support.implementation_projects p join tenancy.tenants t on t.id=p.tenant_id left join support.implementation_project_phases ph on ph.project_id=p.id left join support.implementation_project_risks r on r.project_id=p.id where p.tenant_id=@TenantId group by p.id,t.name order by p.created_at desc",new{tenant.TenantId},ct);
 public Task<Guid> CreateImplementationAsync(ImplementationCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{if(x.TenantId!=tenant.TenantId)throw new UnauthorizedAccessException("Tenant não autorizado.");if(x.DueOn<x.StartsOn)throw new ArgumentException("Prazo deve ser posterior ao início.");var id=await InsertCore(c,t,"implementation_projects","name,starts_on,due_on,owner_id,status","@Name,@StartsOn,@DueOn,@OwnerId,'ACTIVE'",x);var phases=new[]{"KICKOFF","DISCOVERY","INITIAL_CONFIGURATION","MIGRATION","TRAINING","HOMOLOGATION","GO_LIVE","STABILIZATION","CLOSURE"};for(var i=0;i<phases.Length;i++)await c.ExecuteAsync("insert into support.implementation_project_phases(id,tenant_id,project_id,name,sequence,status,due_on,mandatory,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Id,@Name,@Sequence,'PENDING',@Due,true,@UserId,@UserId)",new{tenant.TenantId,id,Name=phases[i],Sequence=i+1,Due=x.StartsOn.AddDays((i+1)*(x.DueOn.DayNumber-x.StartsOn.DayNumber)/phases.Length),tenant.UserId},t);return id;},ct);
 public Task CompletePhaseAsync(Guid id,PhaseCompletionCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var phase=await c.QuerySingleOrDefaultAsync<(string Name,Guid ProjectId)>("select name,project_id projectid from support.implementation_project_phases where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id},t);if(phase==default)throw new KeyNotFoundException("Fase não encontrada.");var homologated=await c.ExecuteScalarAsync<bool>("select exists(select 1 from support.implementation_project_phases where tenant_id=@TenantId and project_id=@ProjectId and name='HOMOLOGATION' and status='COMPLETED')",new{tenant.TenantId,phase.ProjectId},t);SupportRules.ValidatePhaseCompletion(phase.Name,homologated,x.ChecklistCompleted,x.Evidence);await c.ExecuteAsync("update support.implementation_project_phases set status='COMPLETED',completed_at=now(),evidence=@Evidence,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,x.Evidence,tenant.UserId},t);},ct);
 public Task<IReadOnlyList<TrainingTrack>> TrainingsAsync(CancellationToken ct)=>Query<TrainingTrack>("select t.id,t.name,t.profile,t.mandatory,t.active,count(a.id)::int assignments,count(a.id) filter(where a.status='COMPLETED')::int completed from support.training_tracks t left join support.training_assignments a on a.track_id=t.id where t.tenant_id=@TenantId group by t.id order by t.name",new{tenant.TenantId},ct);
 public Task<Guid> CreateTrainingAsync(TrainingCommand x,CancellationToken ct)=>Insert("training_tracks","name,profile,mandatory,active,validity_days","@Name,@Profile,@Mandatory,@Active,@ValidityDays",x,ct);
 public Task CompleteTrainingAsync(Guid id,TrainingCompletionCommand x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{SupportRules.ValidateScore(x.Rating,1,5);var n=await c.ExecuteAsync("update support.training_assignments set status='COMPLETED',completed_at=now(),rating=@Rating,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,x.Rating,tenant.UserId},t);if(n==0)throw new KeyNotFoundException("Participação não encontrada.");},ct);
 public Task<IReadOnlyList<CustomerFeedback>> FeedbackAsync(CancellationToken ct)=>Query<CustomerFeedback>("select id,type,module,score,message,severity,status,created_at createdat from support.customer_feedback where tenant_id=@TenantId order by created_at desc",new{tenant.TenantId},ct);
 public Task<Guid> CreateFeedbackAsync(FeedbackCommand x,CancellationToken ct){if(x.Score is not null)SupportRules.ValidateScore(x.Score.Value,0,10);return Insert("customer_feedback","type,module,score,message,severity,status,ticket_id","@Type,@Module,@Score,@Message,@Severity,'OPEN',@TicketId",x,ct);}
 public Task<Guid> ConvertFeedbackAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var f=await c.QuerySingleOrDefaultAsync<(string Message,string? Module)>("select message,module from support.customer_feedback where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id},t);if(f==default)throw new KeyNotFoundException("Feedback não encontrado.");var backlog=await InsertCore(c,t,"product_backlog_items","title,description,origin,module,priority,impact,status","left(@Message,180),@Message,'FEEDBACK',@Module,'NORMAL','MEDIUM','NEW'",new{f.Message,f.Module});await c.ExecuteAsync("update support.customer_feedback set status='CONVERTED',backlog_item_id=@Backlog where tenant_id=@TenantId and id=@Id",new{tenant.TenantId,id,Backlog=backlog},t);return backlog;},ct);
 public Task<IReadOnlyList<BacklogItem>> BacklogAsync(CancellationToken ct)=>Query<BacklogItem>("select id,title,origin,module,priority,impact,status,decision_reason decisionreason from support.product_backlog_items where tenant_id=@TenantId order by created_at desc",new{tenant.TenantId},ct);
 public Task<Guid> CreateBacklogAsync(BacklogCommand x,CancellationToken ct)=>Insert("product_backlog_items","title,description,origin,module,priority,impact,estimated_hours,status","@Title,@Description,@Origin,@Module,@Priority,@Impact,@EstimatedHours,'NEW'",x,ct);
 public Task<IReadOnlyList<ReleaseNote>> ReleasesAsync(CancellationToken ct)=>Query<ReleaseNote>("select r.id,r.version,r.title,r.module,r.audience,r.status,r.published_at publishedat,(rr.id is not null) read from support.release_notes r left join support.release_note_reads rr on rr.release_note_id=r.id and rr.user_id=@UserId where (r.tenant_id=@TenantId or r.global) and r.status<>'ARCHIVED' order by r.published_at desc nulls last",new{tenant.TenantId,tenant.UserId},ct);
 public Task<Guid> CreateReleaseAsync(ReleaseNoteCommand x,CancellationToken ct)=>Insert("release_notes","version,title,content,module,audience,publish_at,status","@Version,@Title,@Content,@Module,@Audience,@PublishAt,'DRAFT'",x,ct);
 public Task PublishReleaseAsync(Guid id,CancellationToken ct)=>Update(id,"release_notes","status='PUBLISHED',published_at=now()",new{},ct);
 public Task ReadReleaseAsync(Guid id,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{await c.ExecuteAsync("insert into support.release_note_reads(id,tenant_id,release_note_id,user_id,read_at,created_by,updated_by) select gen_random_uuid(),@TenantId,id,@UserId,now(),@UserId,@UserId from support.release_notes where id=@Id and (tenant_id=@TenantId or global) on conflict(release_note_id,user_id) do nothing",new{tenant.TenantId,id,tenant.UserId},t);},ct);
 private const string TicketSelect="select x.id,x.public_code publiccode,u.name requestername,x.requester_profile requesterprofile,x.channel,x.category,x.subcategory,x.module,x.title,x.description,x.priority,x.severity,x.status,a.name assigneename,x.first_response_due_at firstresponsedueat,x.resolution_due_at resolutiondueat,x.opened_at openedat,x.first_responded_at firstrespondedat,x.resolved_at resolvedat,x.closed_at closedat,x.cancellation_reason cancellationreason,x.rating,(x.resolution_due_at<now() and x.status not in('RESOLVED','CLOSED','CANCELLED')) slabreached from support.support_tickets x join identity.users u on u.id=x.requester_id left join identity.users a on a.id=x.assignee_id";
 private Task<IReadOnlyList<T>> Query<T>(string sql,object p,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>(IReadOnlyList<T>)(await c.QueryAsync<T>(sql,p,t)).ToArray(),ct);
 private Task<Guid> Insert(string table,string columns,string values,object x,CancellationToken ct)=>db.InTenantTransactionAsync((c,t)=>InsertCore(c,t,table,columns,values,x),ct);
 private async Task<Guid> InsertCore(System.Data.IDbConnection c,System.Data.IDbTransaction t,string table,string columns,string values,object x){var id=Guid.NewGuid();var p=new DynamicParameters(x);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);await c.ExecuteAsync($"insert into support.{table}(id,tenant_id,{columns},created_by,updated_by) values(@Id,@TenantId,{values},@UserId,@UserId)",p,t);return id;}
 private Task Update(Guid id,string table,string set,object x,CancellationToken ct)=>db.InTenantTransactionAsync(async(c,t)=>{var p=new DynamicParameters(x);p.Add("Id",id);p.Add("TenantId",tenant.TenantId);p.Add("UserId",tenant.UserId);var n=await c.ExecuteAsync($"update support.{table} set {set},updated_at=now(),updated_by=@UserId where id=@Id and (tenant_id=@TenantId or tenant_id is null)",p,t);if(n==0)throw new KeyNotFoundException("Registro não encontrado.");},ct);
 private Task Event(System.Data.IDbConnection c,System.Data.IDbTransaction t,Guid ticket,string type,string? description)=>c.ExecuteAsync("insert into support.support_ticket_events(id,tenant_id,ticket_id,event_type,description,created_by,updated_by) values(gen_random_uuid(),@TenantId,@Ticket,@Type,@Description,@UserId,@UserId)",new{tenant.TenantId,Ticket=ticket,Type=type,Description=description,tenant.UserId},t);
 private Task CreateAlert(System.Data.IDbConnection c,System.Data.IDbTransaction t,Guid ticket,string title)=>c.ExecuteAsync("insert into operations.operational_alerts(id,tenant_id,dedup_key,title,description,severity,status,module,origin_type,origin_id,created_by,updated_by) values(gen_random_uuid(),@TenantId,'support:'||@Ticket,@Title,@Title,'CRITICAL','OPEN','SUPPORT','SUPPORT_TICKET',@Ticket,@UserId,@UserId) on conflict(tenant_id,dedup_key) do nothing",new{tenant.TenantId,Ticket=ticket,Title=title,tenant.UserId},t);
}
