using Agro360.Application.Contracts;
using Agro360.Domain.Operations;
using Agro360.Infrastructure.Persistence;
using Agro360.Multitenancy;
using Agro360.SharedKernel;
using Dapper;

namespace Agro360.Infrastructure.Services;

public sealed class WorkManagementService(DatabaseExecutor database, ITenantContext tenant) : IWorkManagementService
{
    internal sealed record OperationOccurrenceReadRow(string Key, Guid OriginId, string OriginType, string Title, string Module, string OrganizationName, string? UnitName, string? ResponsibleName, DateTimeOffset? DueAt, string Priority, string Reason, string ActionLabel, string SafeLink, string InteractionStatus, DateTimeOffset UpdatedAt, long FullCount);
    private Task<T> Tx<T>(Func<System.Data.Common.DbConnection, System.Data.Common.DbTransaction, Task<T>> work, CancellationToken ct) => database.InTenantTransactionAsync(work, ct);
    public Task<IReadOnlyList<WorkLookup>> ActiveUsersAsync(string? search, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<WorkLookup>)(await c.QueryAsync<WorkLookup>(new CommandDefinition("select id,name name from agro360.identity_users where tenant_id=@TenantId and status='ACTIVE' and (@Search is null or name ilike '%'||@Search||'%') order by name limit 50", new { tenant.TenantId, Search = string.IsNullOrWhiteSpace(search) ? null : search.Trim() }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<PagedResult<OperationalTaskRow>> TasksAsync(string? search, string? status, string? priority, string? moduleCode, Guid? responsibleId, DateTimeOffset? startDate, DateTimeOffset? endDate, int page, int pageSize, CancellationToken ct) => Tx(async (c, t) => { page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100); var p = new { tenant.TenantId, Search = string.IsNullOrWhiteSpace(search) ? null : search.Trim(), Status = status?.ToUpperInvariant(), Priority = priority?.ToUpperInvariant(), Module = moduleCode?.ToUpperInvariant(), ResponsibleId = responsibleId, From = startDate, To = endDate, Limit = pageSize, Offset = (page - 1) * pageSize }; const string where = " where x.tenant_id=@TenantId and x.deleted_at is null and (@Search is null or x.title ilike '%'||@Search||'%' or x.description ilike '%'||@Search||'%') and (@Status is null or (@Status='OVERDUE' and x.status not in ('COMPLETED','CANCELLED') and x.due_at<now()) or x.status=@Status) and (@Priority is null or x.priority=@Priority) and (@Module is null or x.module=@Module) and (@ResponsibleId is null or x.responsible_id=@ResponsibleId) and (@From is null or x.due_at>=@From) and (@To is null or x.due_at<=@To)"; using var grid = await c.QueryMultipleAsync(new CommandDefinition("select count(*) from agro360.operations_operational_tasks x" + where + "; select x.id,x.title,x.description,u.name ResponsibleName,x.priority,case when x.status not in ('COMPLETED','CANCELLED') and x.due_at<now() then 'OVERDUE' else x.status end Status,x.due_at DueAt,x.module,x.entity_type EntityType,x.entity_id EntityId,x.created_at CreatedAt from agro360.operations_operational_tasks x join agro360.identity_users u on u.id=x.responsible_id and u.tenant_id=x.tenant_id" + where + " order by x.due_at limit @Limit offset @Offset", p, t, cancellationToken: ct)); var total = await grid.ReadSingleAsync<long>(); return new PagedResult<OperationalTaskRow>((await grid.ReadAsync<OperationalTaskRow>()).ToArray(), page, pageSize, total); }, ct);
    public Task<Guid> CreateTaskAsync(TaskCommand command, CancellationToken ct) { WorkManagementRules.ValidateTask(command.Title, command.ResponsibleId, command.DueAt, command.Priority); return Tx(async (c, t) => { if (!await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.identity_users where id=@ResponsibleId and tenant_id=@TenantId and status='ACTIVE')", new { command.ResponsibleId, tenant.TenantId }, t, cancellationToken: ct))) throw new DomainException("Responsável inativo ou inexistente.", "task.responsible_inactive"); var id = Guid.CreateVersion7(); await c.ExecuteAsync(new CommandDefinition("insert into agro360.operations_operational_tasks(id,tenant_id,title,description,responsible_id,priority,due_at,module,entity_type,entity_id,created_by) values(@Id,@TenantId,@Title,@Description,@ResponsibleId,@Priority,@DueAt,@Module,@EntityType,@EntityId,@UserId);insert into agro360.operations_operational_task_events(id,tenant_id,task_id,event_type,notes,created_by) values(gen_random_uuid(),@TenantId,@Id,'CREATED','Tarefa criada',@UserId);insert into agro360.operations_notifications(id,tenant_id,user_id,type,module,severity,title,message,safe_link,created_by) values(gen_random_uuid(),@TenantId,@ResponsibleId,'TASK',@Module,@Severity,'Nova tarefa atribuída',@Title,'/Tasks/Details?id='||@Id,@UserId)", new { Id = id, tenant.TenantId, Title = command.Title.Trim(), Description = command.Description.Trim(), command.ResponsibleId, Priority = command.Priority.ToUpperInvariant(), command.DueAt, Module = command.Module.ToUpperInvariant(), command.EntityType, command.EntityId, tenant.UserId, Severity = command.Priority.ToUpperInvariant() }, t, cancellationToken: ct)); return id; }, ct); }
    public Task ChangeTaskAsync(Guid id, TaskTransition command, CancellationToken ct) { var status = command.Status.ToUpperInvariant(); WorkManagementRules.ValidateTaskTransition(status, command.Reason); return database.InTenantTransactionAsync(async (c, t) => { if (await c.ExecuteAsync(new CommandDefinition("update agro360.operations_operational_tasks set status=@Status,completion_description=case when @Status='COMPLETED' then @Reason end,cancellation_reason=case when @Status='CANCELLED' then @Reason end,completed_at=case when @Status='COMPLETED' then now() end,cancelled_at=case when @Status='CANCELLED' then now() end,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId and deleted_at is null;insert into agro360.operations_operational_task_events(id,tenant_id,task_id,event_type,notes,created_by) select gen_random_uuid(),@TenantId,@Id,@Status,@Reason,@UserId where exists(select 1 from agro360.operations_operational_tasks where id=@Id and tenant_id=@TenantId)", new { Id = id, tenant.TenantId, Status = status, command.Reason, tenant.UserId }, t, cancellationToken: ct)) == 0) throw new NotFoundException("Tarefa", id); }, ct); }
    public Task<IReadOnlyList<TaskEventRow>> TaskHistoryAsync(Guid id, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<TaskEventRow>)(await c.QueryAsync<TaskEventRow>(new CommandDefinition("select e.event_type EventType,e.notes,u.name ActorName,e.created_at CreatedAt from agro360.operations_operational_task_events e join agro360.identity_users u on u.id=e.created_by and u.tenant_id=e.tenant_id where e.tenant_id=@TenantId and e.task_id=@Id order by e.created_at desc", new { tenant.TenantId, Id = id }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<IReadOnlyList<AlertRow>> AlertsAsync(string? severity, string? status, string? moduleCode, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<AlertRow>)(await c.QueryAsync<AlertRow>(new CommandDefinition("select id,title,description,severity,status,module,origin_type OriginType,origin_id OriginId,created_at CreatedAt,resolved_at ResolvedAt from agro360.operations_operational_alerts where tenant_id=@TenantId and (@Severity is null or severity=@Severity) and (@Status is null or status=@Status) and (@Module is null or module=@Module) order by case severity when 'CRITICAL' then 1 when 'HIGH' then 2 else 3 end,created_at desc limit 500", new { tenant.TenantId, Severity = severity?.ToUpperInvariant(), Status = status?.ToUpperInvariant(), Module = moduleCode?.ToUpperInvariant() }, t, cancellationToken: ct))).ToArray(), ct);
    public Task ChangeAlertAsync(Guid id, string action, CancellationToken ct) => database.InTenantTransactionAsync(async (c, t) => { var status = action.ToLowerInvariant() switch { "read" => "READ", "resolve" => "RESOLVED", _ => throw new DomainException("Ação de alerta inválida.", "alert.action_invalid") }; if (await c.ExecuteAsync(new CommandDefinition("update agro360.operations_operational_alerts set status=@Status,read_at=case when @Status='READ' then now() else read_at end,resolved_at=case when @Status='RESOLVED' then now() else resolved_at end,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId;insert into agro360.operations_operational_alert_events(id,tenant_id,alert_id,event_type,created_by) select gen_random_uuid(),@TenantId,@Id,@Status,@UserId where exists(select 1 from agro360.operations_operational_alerts where id=@Id and tenant_id=@TenantId)", new { Id = id, tenant.TenantId, Status = status, tenant.UserId }, t, cancellationToken: ct)) == 0) throw new NotFoundException("Alerta", id); }, ct);
    public Task<int> EvaluateRulesAsync(CancellationToken ct) => Tx(async (c, t) => await c.ExecuteScalarAsync<int>(new CommandDefinition("select agro360.operations_evaluate_operational_rules(@TenantId,@UserId)", new { tenant.TenantId, tenant.UserId }, t, cancellationToken: ct)), ct);
    public Task<IReadOnlyList<RuleRow>> RulesAsync(CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<RuleRow>)(await c.QueryAsync<RuleRow>(new CommandDefinition("select id,name,description,module,type,severity,action,active,last_executed_at LastExecutedAt from agro360.operations_operational_rules where tenant_id=@TenantId order by name", new { tenant.TenantId }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<Guid> SaveRuleAsync(Guid? id, RuleCommand command, CancellationToken ct) => Tx(async (c, t) => { if (string.IsNullOrWhiteSpace(command.Name) || string.IsNullOrWhiteSpace(command.ConditionJson) || !command.ConditionJson.TrimStart().StartsWith('{')) throw new DomainException("Nome e condição JSON válida são obrigatórios.", "rule.invalid"); var ruleId = id ?? Guid.CreateVersion7(); await c.ExecuteAsync(new CommandDefinition("insert into agro360.operations_operational_rules(id,tenant_id,name,description,module,type,condition_json,severity,action,active,created_by) values(@Id,@TenantId,@Name,@Description,@Module,@Type,cast(@ConditionJson as jsonb),@Severity,@Action,@Active,@UserId) on conflict(tenant_id,id) do update set name=excluded.name,description=excluded.description,module=excluded.module,type=excluded.type,condition_json=excluded.condition_json,severity=excluded.severity,action=excluded.action,active=excluded.active,updated_at=now(),updated_by=@UserId", new { Id = ruleId, tenant.TenantId, command.Name, command.Description, Module = command.Module.ToUpperInvariant(), Type = command.Type.ToUpperInvariant(), command.ConditionJson, Severity = command.Severity.ToUpperInvariant(), Action = command.Action.ToUpperInvariant(), command.Active, tenant.UserId }, t, cancellationToken: ct)); return ruleId; }, ct);
    public Task<IReadOnlyList<WorkflowRow>> WorkflowsAsync(string? status, string? moduleCode, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<WorkflowRow>)(await c.QueryAsync<WorkflowRow>(new CommandDefinition("select w.id,d.name,d.module,w.entity_type EntityType,w.entity_id EntityId,w.status,r.name RequesterName,a.name ApproverName,w.opened_at OpenedAt,w.decided_at DecidedAt from agro360.operations_workflow_instances w join agro360.operations_workflow_definitions d on d.id=w.definition_id and d.tenant_id=w.tenant_id join agro360.identity_users r on r.id=w.requested_by and r.tenant_id=w.tenant_id join agro360.identity_users a on a.id=w.current_approver_id and a.tenant_id=w.tenant_id where w.tenant_id=@TenantId and (@Status is null or w.status=@Status) and (@Module is null or d.module=@Module) order by w.opened_at desc", new { tenant.TenantId, Status = status?.ToUpperInvariant(), Module = moduleCode?.ToUpperInvariant() }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<Guid> CreateWorkflowAsync(WorkflowCommand command, CancellationToken ct) => Tx(async (c, t) => { if (command.EntityId == Guid.Empty || command.ApproverId == Guid.Empty) throw new DomainException("Entidade e aprovador são obrigatórios.", "agro360.workflow_invalid"); var definition = await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from agro360.operations_workflow_definitions where tenant_id=@TenantId and name=@Name and active limit 1", new { tenant.TenantId, command.Name }, t, cancellationToken: ct)); if (definition is null) { definition = Guid.CreateVersion7(); await c.ExecuteAsync(new CommandDefinition("insert into agro360.operations_workflow_definitions(id,tenant_id,name,module,entity_type,segregation_required,created_by) values(@Id,@TenantId,@Name,@Module,@EntityType,@SegregationRequired,@UserId)", new { Id = definition, tenant.TenantId, command.Name, Module = command.Module.ToUpperInvariant(), command.EntityType, command.SegregationRequired, tenant.UserId }, t, cancellationToken: ct)); } var id = Guid.CreateVersion7(); await c.ExecuteAsync(new CommandDefinition("insert into agro360.operations_workflow_instances(id,tenant_id,definition_id,entity_type,entity_id,status,requested_by,current_approver_id,opened_at,created_by) values(@Id,@TenantId,@Definition,@EntityType,@EntityId,'OPEN',@UserId,@ApproverId,now(),@UserId);insert into agro360.operations_notifications(id,tenant_id,user_id,type,module,severity,title,message,safe_link,created_by) values(gen_random_uuid(),@TenantId,@ApproverId,'APPROVAL',@Module,'HIGH','Aprovação pendente',@Name,'/Workflows/Details?id='||@Id,@UserId)", new { Id = id, tenant.TenantId, Definition = definition, command.EntityType, command.EntityId, tenant.UserId, command.ApproverId, Module = command.Module.ToUpperInvariant(), command.Name }, t, cancellationToken: ct)); return id; }, ct);
    public Task DecideWorkflowAsync(Guid id, WorkflowDecisionCommand command, bool canApprove, CancellationToken ct) { var decision = command.Decision.ToUpperInvariant(); WorkManagementRules.ValidateDecision(decision, command.Comment); if (!canApprove) throw new DomainException("Usuário sem permissão para aprovar.", "agro360.workflow_permission_denied"); return database.InTenantTransactionAsync(async (c, t) => { var item = await c.QuerySingleOrDefaultAsync<(Guid ApproverId, Guid RequesterId, bool Segregation)>(new CommandDefinition("select w.current_approver_id ApproverId,w.requested_by RequesterId,d.segregation_required Segregation from agro360.operations_workflow_instances w join agro360.operations_workflow_definitions d on d.id=w.definition_id and d.tenant_id=w.tenant_id where w.id=@Id and w.tenant_id=@TenantId and w.status in ('OPEN','IN_REVIEW') for update", new { Id = id, tenant.TenantId }, t, cancellationToken: ct)); if (item == default) throw new NotFoundException("Workflow", id); if (item.ApproverId != tenant.UserId) throw new DomainException("Aprovação atribuída a outro usuário.", "agro360.workflow_wrong_approver"); if (item.Segregation && item.RequesterId == tenant.UserId) throw new DomainException("Segregação impede autoaprovação.", "agro360.workflow_self_approval"); await c.ExecuteAsync(new CommandDefinition("update agro360.operations_workflow_instances set status=@Decision,decided_at=now(),decided_by=@UserId,updated_at=now(),updated_by=@UserId where id=@Id and tenant_id=@TenantId;insert into agro360.operations_workflow_decisions(id,tenant_id,instance_id,decision,comment,decided_by,decided_at,created_by) values(gen_random_uuid(),@TenantId,@Id,@Decision,@Comment,@UserId,now(),@UserId)", new { Id = id, tenant.TenantId, Decision = decision, command.Comment, tenant.UserId }, t, cancellationToken: ct)); }, ct); }
    public Task<IReadOnlyList<NotificationRow>> NotificationsAsync(string? type, string? moduleCode, string? severity, DateTimeOffset? startDate, DateTimeOffset? endDate, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<NotificationRow>)(await c.QueryAsync<NotificationRow>(new CommandDefinition("select id,type,module,severity,title,message,safe_link SafeLink,created_at CreatedAt,read_at ReadAt from agro360.operations_notifications where tenant_id=@TenantId and user_id=@UserId and (@Type is null or type=@Type) and (@Module is null or module=@Module) and (@Severity is null or severity=@Severity) and (@From is null or created_at>=@From) and (@To is null or created_at<=@To) order by created_at desc limit 500", new { tenant.TenantId, tenant.UserId, Type = type?.ToUpperInvariant(), Module = moduleCode?.ToUpperInvariant(), Severity = severity?.ToUpperInvariant(), From = startDate, To = endDate }, t, cancellationToken: ct))).ToArray(), ct);
    public Task ReadNotificationAsync(Guid? id, CancellationToken ct) => database.InTenantTransactionAsync(async (c, t) => { await c.ExecuteAsync(new CommandDefinition("update agro360.operations_notifications set read_at=coalesce(read_at,now()),updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and user_id=@UserId and (@Id is null or id=@Id)", new { tenant.TenantId, tenant.UserId, Id = id }, t, cancellationToken: ct)); }, ct);
    public Task<IReadOnlyList<CalendarRow>> CalendarAsync(DateTimeOffset startDate, DateTimeOffset endDate, string? moduleCode, Guid? responsibleId, string? priority, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<CalendarRow>)(await c.QueryAsync<CalendarRow>(new CommandDefinition("select id,type,title,starts_at StartsAt,ends_at EndsAt,module,priority,safe_link SafeLink from agro360.operations_calendar_events where tenant_id=@TenantId and starts_at between @From and @To and (@Module is null or module=@Module) and (@ResponsibleId is null or responsible_id=@ResponsibleId) and (@Priority is null or priority=@Priority) order by starts_at", new { tenant.TenantId, From = startDate, To = endDate, Module = moduleCode?.ToUpperInvariant(), ResponsibleId = responsibleId, Priority = priority?.ToUpperInvariant() }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<IReadOnlyList<OutboxRow>> OutboxAsync(string? status, string? channel, CancellationToken ct) => Tx(async (c, t) => (IReadOnlyList<OutboxRow>)(await c.QueryAsync<OutboxRow>(new CommandDefinition("select id,channel,status,attempts,last_error LastError,created_at CreatedAt,processed_at ProcessedAt from agro360.operations_communication_outbox where tenant_id=@TenantId and (@Status is null or status=@Status) and (@Channel is null or channel=@Channel) order by created_at desc limit 500", new { tenant.TenantId, Status = status?.ToUpperInvariant(), Channel = channel?.ToUpperInvariant() }, t, cancellationToken: ct))).ToArray(), ct);
    public Task<WorkDashboard> DashboardAsync(CancellationToken ct) => Tx((c, t) => c.QuerySingleAsync<WorkDashboard>(new CommandDefinition("select count(*) filter(where status not in('COMPLETED','CANCELLED')) OpenTasks,count(*) filter(where status not in('COMPLETED','CANCELLED') and due_at<now()) OverdueTasks,count(*) filter(where priority='CRITICAL' and status not in('COMPLETED','CANCELLED')) CriticalTasks,(select count(*) from agro360.operations_operational_alerts where tenant_id=@TenantId and severity='CRITICAL' and status<>'RESOLVED') CriticalAlerts,(select count(*) from agro360.operations_workflow_instances where tenant_id=@TenantId and status in('OPEN','IN_REVIEW')) PendingApprovals,(select count(*) from agro360.operations_notifications where tenant_id=@TenantId and user_id=@UserId and read_at is null) UnreadNotifications,(select count(*) from agro360.inventory_stock_balances where tenant_id=@TenantId and available<minimum) CriticalStocks,greatest(0,100-(count(*) filter(where status not in('COMPLETED','CANCELLED') and due_at<now())*5)::int-(select count(*)::int*10 from agro360.operations_operational_alerts where tenant_id=@TenantId and severity='CRITICAL' and status<>'RESOLVED')) HealthScore from agro360.operations_operational_tasks where tenant_id=@TenantId and deleted_at is null", new { tenant.TenantId, tenant.UserId }, t, cancellationToken: ct)), ct);

    public Task<PagedResult<OperationOccurrenceRow>> OperationCenterAsync(OperationOccurrenceQuery query, CancellationToken ct) => Tx(async (c, t) =>
    {
        var page = Math.Max(1, query.Page);
        var pageSize = Math.Clamp(query.PageSize, 1, 100);
        var offset = checked((long)(page - 1) * pageSize);
        var p = new { tenant.TenantId, tenant.UserId, Search = string.IsNullOrWhiteSpace(query.Search) ? null : query.Search.Trim(), Module = query.Module?.Trim().ToUpperInvariant(), Priority = query.Priority?.Trim().ToUpperInvariant(), InteractionStatus = query.InteractionStatus?.Trim().ToUpperInvariant(), Scope = query.Scope?.Trim().ToUpperInvariant(), query.ResponsibleId, Limit = pageSize, Offset = offset };
        const string common = """
        with user_permissions as (
          select distinct p.code from agro360.identity_users u join agro360.identity_user_roles ur on ur.tenant_id=u.tenant_id and ur.user_id=u.id join agro360.identity_role_permissions rp on rp.tenant_id=ur.tenant_id and rp.role_id=ur.role_id join agro360.identity_permissions p on p.id=rp.permission_id
          where u.tenant_id=@TenantId and u.id=@UserId and u.status='ACTIVE' and u.deleted_at is null
        ), occurrences as (
          select 'APPROVAL:'||w.id key,w.id origin_id,'APPROVAL' origin_type,'Aprovação de '||lower(w.entity_type) title,d.module,t.name organization_name,null::text unit_name,a.name source_responsible_name,null::timestamptz due_at,'NONE' due_kind,null::text due_source,'HIGH' priority,'Decisão pendente do aprovador designado.' reason,'Analisar aprovação' action_label,'/Work?tab=workflows&id='||w.id safe_link,w.updated_at
          from agro360.operations_workflow_instances w join agro360.operations_workflow_definitions d on d.tenant_id=w.tenant_id and d.id=w.definition_id join agro360.identity_users a on a.tenant_id=w.tenant_id and a.id=w.current_approver_id join agro360.tenancy_tenants t on t.id=w.tenant_id
          where w.tenant_id=@TenantId and w.status in('OPEN','IN_REVIEW') and exists(select 1 from user_permissions where code='work.approve')
          union all
          select 'PURCHASE:'||o.id,o.id,'PURCHASE','Compra aguardando entrega','PURCHASING',t.name,null,null,null,'NONE',null,'MEDIUM','Há saldo aprovado ainda não recebido.','Acompanhar entrega','/Procurement?purchaseId='||o.id,coalesce(o.updated_at,o.created_at)
          from agro360.purchasing_purchase_orders o join agro360.tenancy_tenants t on t.id=o.tenant_id where o.tenant_id=@TenantId and o.status in('APPROVED','PARTIALLY_RECEIVED') and exists(select 1 from user_permissions where code='purchasing.read') and exists(select 1 from agro360.purchasing_purchase_items i where i.tenant_id=o.tenant_id and i.purchase_id=o.id and i.received_quantity<i.quantity)
          union all
          select 'RECEIPT_DIVERGENCE:'||r.id,r.id,'RECEIPT','Recebimento '||r.number||' com divergência','PURCHASING',t.name,null,u.name,null,'NONE',null,'HIGH','Existe divergência aberta; qualidade é tratada separadamente.','Conferir divergência','/Procurement?receiptId='||r.id,r.updated_at
          from agro360.procurement_receipts r join agro360.identity_users u on u.tenant_id=r.tenant_id and u.id=r.responsible_id join agro360.tenancy_tenants t on t.id=r.tenant_id where r.tenant_id=@TenantId and r.deleted_at is null and exists(select 1 from user_permissions where code='purchasing.read') and exists(select 1 from agro360.procurement_receipt_divergences d where d.tenant_id=r.tenant_id and d.receipt_id=r.id and d.deleted_at is null and d.status='OPEN')
          union all
          select 'QUALITY:'||r.id,r.id,'QUALITY','Material de '||r.number||' aguardando inspeção','INVENTORY',t.name,null,u.name,null,'NONE',null,'HIGH','Material bloqueado até decisão de qualidade.','Registrar decisão de qualidade','/Procurement?receiptId='||r.id,r.updated_at
          from agro360.procurement_receipts r join agro360.identity_users u on u.tenant_id=r.tenant_id and u.id=r.responsible_id join agro360.tenancy_tenants t on t.id=r.tenant_id where r.tenant_id=@TenantId and r.deleted_at is null and exists(select 1 from user_permissions where code in('inventory.read','production.quality')) and exists(select 1 from agro360.procurement_receipt_items i where i.tenant_id=r.tenant_id and i.receipt_id=r.id and i.deleted_at is null and i.quality_status='PENDING')
          union all
          select 'SHIPMENT:'||s.id,s.id,'SHIPMENT','Expedição '||s.number||' pendente','LOGISTICS',t.name,null,null,min(o.expected_delivery)::timestamptz,case when min(o.expected_delivery) is null then 'NONE' else 'OPERATIONAL' end,case when min(o.expected_delivery) is null then null else 'Previsão de entrega do pedido' end,case when s.status='RETURN_PENDING' then 'HIGH' else 'MEDIUM' end,case when s.status='RETURN_PENDING' then 'Há retorno físico pendente de recebimento ou destinação.' else 'A expedição ou entrega ainda possui saldo.' end,case when s.status='RETURN_PENDING' then 'Receber retorno' else 'Abrir expedição' end,'/Logistics?shipmentId='||s.id,s.updated_at
          from agro360.fulfillment_shipments s join agro360.tenancy_tenants t on t.id=s.tenant_id left join agro360.fulfillment_shipment_items si on si.tenant_id=s.tenant_id and si.shipment_id=s.id left join agro360.sales_order_items oi on oi.tenant_id=si.tenant_id and oi.id=si.order_item_id left join agro360.sales_orders o on o.tenant_id=oi.tenant_id and o.id=oi.order_id where s.tenant_id=@TenantId and s.deleted_at is null and s.status not in('RECONCILED','CANCELLED') and exists(select 1 from user_permissions where code in('logistics.read','logistics.fulfillment.read')) group by s.id,t.name
          union all
          select 'MAINTENANCE:'||m.id,m.id,'MAINTENANCE','Manutenção prevista: '||a.identification,'MAINTENANCE',t.name,null,u.name,m.scheduled_for::timestamptz,'OPERATIONAL','Data programada da ordem',case when m.scheduled_for<current_date then 'HIGH' else 'MEDIUM' end,case when m.scheduled_for<current_date then 'Ordem de manutenção vencida.' else 'Ordem programada ainda aberta.' end,'Abrir manutenção','/Fleet?maintenanceId='||m.id,coalesce(m.updated_at,m.created_at)
          from agro360.fleet_maintenance_orders m join agro360.fleet_assets a on a.tenant_id=m.tenant_id and a.id=m.asset_id join agro360.tenancy_tenants t on t.id=m.tenant_id left join agro360.identity_users u on u.tenant_id=m.tenant_id and u.id=m.responsible_id where m.tenant_id=@TenantId and m.status not in('COMPLETED','CANCELLED') and m.scheduled_for<=current_date+7 and exists(select 1 from user_permissions where code in('maintenance.read','fleet.read'))
          union all
          select 'PAYABLE:'||f.id,f.id,'PAYABLE','Obrigação financeira: '||f.supplier_name,'FINANCE',t.name,null,null,f.due_on::timestamptz,'CONTRACTUAL','Vencimento do título',case when f.due_on<current_date then 'CRITICAL' else 'HIGH' end,case when f.due_on<current_date then 'Título vencido com saldo em aberto.' else 'Título próximo do vencimento.' end,'Abrir financeiro','/Finance?payableId='||f.id,coalesce(f.updated_at,f.created_at)
          from agro360.finance_payables f join agro360.tenancy_tenants t on t.id=f.tenant_id where f.tenant_id=@TenantId and f.status in('OPEN','PARTIAL') and f.balance>0 and f.due_on<=current_date+7 and exists(select 1 from user_permissions where code='finance.read')
        ), visible as (
          select o.*,s.assigned_to responsible_id,coalesce(assigned.name,o.source_responsible_name) responsible_name,coalesce(s.assignment_version,0) assignment_version,(r.user_id is not null) viewed_by_me,case when s.assigned_to is not null then 'ASSIGNED' when r.user_id is not null then 'VIEWED' else 'NEW' end interaction_status
          from occurrences o left join agro360.operation_occurrence_states s on s.tenant_id=@TenantId and s.occurrence_key=o.key left join agro360.operation_occurrence_reads r on r.tenant_id=@TenantId and r.occurrence_key=o.key and r.user_id=@UserId left join agro360.identity_users assigned on assigned.tenant_id=@TenantId and assigned.id=s.assigned_to
        ), filtered as (select * from visible where (@Search is null or title ilike '%'||@Search||'%' or reason ilike '%'||@Search||'%') and (@Module is null or module=@Module) and (@Priority is null or priority=@Priority) and (@InteractionStatus is null or interaction_status=@InteractionStatus) and (@ResponsibleId is null or responsible_id=@ResponsibleId) and (@Scope is null or @Scope='ALL' or (@Scope='MINE' and responsible_id=@UserId) or (@Scope='TEAM' and responsible_id is not null)) )
        """;
        using var grid = await c.QueryMultipleAsync(new CommandDefinition(common + "select count(*) from filtered;" + common + "select key,origin_id OriginId,origin_type OriginType,title,module,organization_name OrganizationName,unit_name UnitName,responsible_id ResponsibleId,responsible_name ResponsibleName,due_at DueAt,due_kind DueKind,due_source DueSource,priority,reason,action_label ActionLabel,safe_link SafeLink,interaction_status InteractionStatus,viewed_by_me ViewedByMe,assignment_version AssignmentVersion,updated_at UpdatedAt from filtered order by case priority when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 else 4 end,due_at nulls last,updated_at desc,key limit @Limit offset @Offset", p, t, cancellationToken: ct));
        var total = await grid.ReadSingleAsync<long>();
        var rows = (await grid.ReadAsync<OperationOccurrenceRow>()).ToArray();
        return new PagedResult<OperationOccurrenceRow>(rows, page, pageSize, total);
    }, ct);

    public Task<PagedResult<EligibleOccurrenceUser>> EligibleOccurrenceUsersAsync(string key, string? search, int page, int pageSize, CancellationToken ct)
    {
        var (type, _) = ParseOccurrenceKey(key); page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 50); var permission = PermissionsFor(type);
        return Tx(async (c,t) => { var p = new { tenant.TenantId, Search=string.IsNullOrWhiteSpace(search)?null:search.Trim(), Permissions=permission, Limit=pageSize, Offset=checked((long)(page-1)*pageSize) }; const string where=" where u.tenant_id=@TenantId and u.status='ACTIVE' and u.deleted_at is null and (@Search is null or u.name ilike '%'||@Search||'%' or u.email ilike '%'||@Search||'%') and exists(select 1 from agro360.identity_user_roles ur join agro360.identity_role_permissions rp on rp.tenant_id=ur.tenant_id and rp.role_id=ur.role_id join agro360.identity_permissions p on p.id=rp.permission_id where ur.tenant_id=u.tenant_id and ur.user_id=u.id and p.code=any(@Permissions))"; using var g=await c.QueryMultipleAsync(new CommandDefinition("select count(*) from agro360.identity_users u"+where+"; select u.id,u.name,u.email FunctionalIdentification from agro360.identity_users u"+where+" order by u.name,u.id limit @Limit offset @Offset",p,t,cancellationToken:ct)); var total=await g.ReadSingleAsync<long>(); return new PagedResult<EligibleOccurrenceUser>((await g.ReadAsync<EligibleOccurrenceUser>()).ToArray(),page,pageSize,total); },ct);
    }

    public Task MarkOccurrenceViewedAsync(string key, CancellationToken ct)
    {
        var (type, originId)=ParseOccurrenceKey(key); return ChangeOccurrenceStateAsync(key,type,originId,null,ct);
    }
    public Task AssignOccurrenceAsync(string key, OccurrenceAssignmentCommand command, CancellationToken ct)
    {
        var (type, originId)=ParseOccurrenceKey(key); if (command.ResponsibleId is null && string.IsNullOrWhiteSpace(command.Reason)) throw new DomainException("Informe o motivo da retirada.","operation.assignment_reason_required"); return ChangeOccurrenceStateAsync(key,type,originId,command,ct);
    }
    private Task ChangeOccurrenceStateAsync(string key,string type,Guid originId,OccurrenceAssignmentCommand? command,CancellationToken ct) => database.InTenantTransactionAsync(async(c,t) =>
    {
        var permissions=PermissionsFor(type);
        if(!await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.identity_users u join agro360.identity_user_roles ur on ur.tenant_id=u.tenant_id and ur.user_id=u.id join agro360.identity_role_permissions rp on rp.tenant_id=ur.tenant_id and rp.role_id=ur.role_id join agro360.identity_permissions p on p.id=rp.permission_id where u.tenant_id=@TenantId and u.id=@UserId and u.status='ACTIVE' and u.deleted_at is null and p.code=any(@Permissions))",new{tenant.TenantId,tenant.UserId,Permissions=permissions},t,cancellationToken:ct))) throw new DomainException("Você não possui acesso à origem.","operation.origin_permission_denied");
        await c.ExecuteAsync(new CommandDefinition("insert into agro360.operation_occurrence_states(tenant_id,occurrence_key,created_by,updated_by) values(@TenantId,@Key,@UserId,@UserId) on conflict do nothing",new{tenant.TenantId,Key=key,tenant.UserId},t,cancellationToken:ct));
        if(command is null) { var changed=await c.ExecuteAsync(new CommandDefinition("insert into agro360.operation_occurrence_reads(tenant_id,occurrence_key,user_id) values(@TenantId,@Key,@UserId) on conflict(tenant_id,occurrence_key,user_id) do update set last_viewed_at=now(),view_count=agro360.operation_occurrence_reads.view_count+1",new{tenant.TenantId,Key=key,tenant.UserId},t,cancellationToken:ct)); if(changed>0) await c.ExecuteAsync(new CommandDefinition("insert into agro360.operation_occurrence_events(tenant_id,occurrence_key,event_type,actor_id) select @TenantId,@Key,'VIEWED',@UserId where not exists(select 1 from agro360.operation_occurrence_events where tenant_id=@TenantId and occurrence_key=@Key and event_type='VIEWED' and actor_id=@UserId)",new{tenant.TenantId,Key=key,tenant.UserId},t,cancellationToken:ct)); return; }
        if(command.ResponsibleId is not null && !await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from agro360.identity_users u where u.tenant_id=@TenantId and u.id=@ResponsibleId and u.status='ACTIVE' and u.deleted_at is null and exists(select 1 from agro360.identity_user_roles ur join agro360.identity_role_permissions rp on rp.tenant_id=ur.tenant_id and rp.role_id=ur.role_id join agro360.identity_permissions p on p.id=rp.permission_id where ur.tenant_id=u.tenant_id and ur.user_id=u.id and p.code=any(@Permissions)))",new{tenant.TenantId,command.ResponsibleId,Permissions=permissions},t,cancellationToken:ct))) throw new DomainException("Pessoa inelegível para acompanhar esta origem.","operation.responsible_invalid");
        var previous=await c.QuerySingleAsync<Guid?>(new CommandDefinition("select assigned_to from agro360.operation_occurrence_states where tenant_id=@TenantId and occurrence_key=@Key for update",new{tenant.TenantId,Key=key},t,cancellationToken:ct));
        if(previous==command.ResponsibleId) return;
        var n=await c.ExecuteAsync(new CommandDefinition("update agro360.operation_occurrence_states set assigned_to=@ResponsibleId,assigned_at=case when @ResponsibleId is null then null else now() end,assignment_reason=@Reason,assignment_version=assignment_version+1,updated_at=now(),updated_by=@UserId where tenant_id=@TenantId and occurrence_key=@Key and assignment_version=@ExpectedVersion",new{tenant.TenantId,Key=key,command.ResponsibleId,Reason=command.Reason?.Trim(),command.ExpectedVersion,tenant.UserId},t,cancellationToken:ct));
        if(n==0) throw new ConflictException("A atribuição foi alterada por outra pessoa. Recarregue e confirme novamente.","operation.assignment_stale");
        var eventType=command.ResponsibleId is null?"UNASSIGNED":previous is null?"ASSIGNED":"TRANSFERRED"; await c.ExecuteAsync(new CommandDefinition("insert into agro360.operation_occurrence_events(tenant_id,occurrence_key,event_type,actor_id,responsible_id,reason) values(@TenantId,@Key,@EventType,@UserId,@ResponsibleId,@Reason)",new{tenant.TenantId,Key=key,EventType=eventType,tenant.UserId,command.ResponsibleId,Reason=command.Reason?.Trim()},t,cancellationToken:ct));
    },ct);
    private static (string Type,Guid Id) ParseOccurrenceKey(string key) { if(string.IsNullOrWhiteSpace(key)||key.Length>180){throw new DomainException("Identificador da pendência inválido.","operation.occurrence_key_invalid");} var parts=key.Split(':',2); if(parts.Length!=2||!Guid.TryParseExact(parts[1],"D",out var id)||PermissionsFor(parts[0]).Length==0) throw new DomainException("Identificador da pendência inválido.","operation.occurrence_key_invalid"); return(parts[0],id); }
    private static string[] PermissionsFor(string type)=>type switch { "APPROVAL"=>["work.approve"], "PURCHASE" or "RECEIPT_DIVERGENCE"=>["purchasing.read"], "QUALITY"=>["inventory.read","production.quality"], "SHIPMENT"=>["logistics.read","logistics.fulfillment.read"], "MAINTENANCE"=>["maintenance.read","fleet.read"], "PAYABLE"=>["finance.read"], _=>[] };

}
