using System.Security.Claims;using Agro360.Application;using Agro360.Application.Contracts;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Agro360.Api.Controllers;
[ApiController,Authorize]
public abstract class EcosystemControllerBase(IEcosystemService service):ControllerBase{protected IEcosystemService Service{get;}=service;protected Guid Actor()=>Guid.TryParse(User.FindFirstValue("sub"),out var id)?id:throw new UnauthorizedAccessException();}
[Route("api/ecosystem")]
public sealed class EcosystemController(IEcosystemService s):EcosystemControllerBase(s){
 [HttpGet("dashboard"),Authorize(Policy=Permissions.IntegrationsRead)]public Task<EcosystemDashboard>Dashboard(CancellationToken ct)=>Service.DashboardAsync(ct);
 [HttpGet("marketplace/modules"),Authorize(Policy=Permissions.MarketplaceRead)]public Task<IReadOnlyList<MarketplaceModule>>Modules(CancellationToken ct)=>Service.ModulesAsync(ct);
 [HttpPost("marketplace/modules"),Authorize(Roles="Super Admin Plataforma")]public async Task<IActionResult>CreateModule(MarketplaceModuleCommand x,CancellationToken ct){var id=await Service.CreateModuleAsync(x,Actor(),ct);return Created($"/api/ecosystem/marketplace/modules/{id}",new{id});}
 [HttpPost("marketplace/requests"),Authorize(Policy=Permissions.MarketplaceRead)]public async Task<IActionResult>Request(ModuleActivationCommand x,CancellationToken ct){var id=await Service.RequestModuleAsync(x,Actor(),ct);return Created($"/api/ecosystem/marketplace/requests/{id}",new{id});}
 [HttpPost("marketplace/requests/{id:guid}/approve"),Authorize(Roles="Super Admin Plataforma")]public Task Decide(Guid id,ReasonCommand x,CancellationToken ct)=>Service.DecideModuleAsync(id,true,x.Reason,Actor(),ct);
 [HttpPost("marketplace/requests/{id:guid}/reject"),Authorize(Roles="Super Admin Plataforma")]public Task Reject(Guid id,ReasonCommand x,CancellationToken ct)=>Service.DecideModuleAsync(id,false,x.Reason,Actor(),ct);
 [HttpGet("partners"),Authorize(Policy=Permissions.PartnersManage)]public Task<object>Partners(CancellationToken ct)=>Service.PartnersAsync(ct);[HttpPost("partners"),Authorize(Policy=Permissions.PartnersManage)]public async Task<IActionResult>Partner(PartnerCommand x,CancellationToken ct){var id=await Service.CreatePartnerAsync(x,Actor(),ct);return Created($"/api/ecosystem/partners/{id}",new{id});}
 [HttpPost("partners/{id:guid}/block"),Authorize(Roles="Super Admin Plataforma")]public Task Block(Guid id,ReasonCommand x,CancellationToken ct)=>Service.SetPartnerBlockedAsync(id,true,x.Reason,Actor(),ct);[HttpPost("partner-access"),Authorize(Policy=Permissions.PartnersManage)]public async Task<IActionResult>Grant(PartnerAccessCommand x,CancellationToken ct){var id=await Service.GrantPartnerAsync(x,Actor(),ct);return Created($"/api/ecosystem/partner-access/{id}",new{id});}[HttpPost("partner-access/{id:guid}/revoke"),Authorize(Policy=Permissions.PartnersManage)]public Task Revoke(Guid id,ReasonCommand x,CancellationToken ct)=>Service.RevokePartnerAsync(id,x.Reason,Actor(),ct);
 [HttpGet("apps"),Authorize(Policy=Permissions.ApiKeysManage)]public Task<object>Apps(CancellationToken ct)=>Service.AppsAsync(ct);[HttpPost("apps"),Authorize(Policy=Permissions.ApiKeysManage)]public async Task<IActionResult>App(ExternalAppCommand x,CancellationToken ct){var id=await Service.CreateAppAsync(x,Actor(),ct);return Created($"/api/ecosystem/apps/{id}",new{id});}[HttpPost("api-keys"),Authorize(Policy=Permissions.ApiKeysManage)]public Task<PlatformApiKeyCreated>Key(PlatformApiKeyCommand x,CancellationToken ct)=>Service.CreateKeyAsync(x,Actor(),ct);[HttpPost("api-keys/{id:guid}/revoke"),Authorize(Policy=Permissions.ApiKeysManage)]public Task RevokeKey(Guid id,CancellationToken ct)=>Service.RevokeKeyAsync(id,Actor(),ct);
 [HttpGet("webhooks"),Authorize(Policy=Permissions.IntegrationsRead)]public Task<object>Webhooks(CancellationToken ct)=>Service.WebhooksAsync(ct);[HttpPost("webhooks"),Authorize(Policy=Permissions.IntegrationsWrite)]public async Task<IActionResult>Webhook(WebhookSubscriptionCommand x,CancellationToken ct){var id=await Service.CreateWebhookAsync(x,Actor(),ct);return Created($"/api/ecosystem/webhooks/{id}",new{id});}
 [HttpGet("audit"),Authorize(Policy=Permissions.IntegrationsAudit)]public Task<object>Audit(CancellationToken ct)=>Service.LogsAsync(ct);[HttpGet("developer-docs"),Authorize(Policy=Permissions.IntegrationsRead)]public Task<object>Docs(CancellationToken ct)=>Service.DeveloperDocsAsync(ct);[HttpGet("commercial-catalog"),Authorize(Policy=Permissions.MarketplaceRead)]public Task<object>Catalog(CancellationToken ct)=>Service.CommercialCatalogAsync(ct);
}
