using Agro360.Application;
using Agro360.Application.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Agro360.Api.Controllers;

[ApiController, Route("api/rural-hr"), Authorize(Policy = Permissions.RuralHrRead)]
public sealed class RuralHrController(IRuralHrService service, ILogger<RuralHrController> logger) : ControllerBase
{
    private static readonly Dictionary<string, string> Kinds = new(StringComparer.OrdinalIgnoreCase) { { "people", "PERSON" }, { "teams", "TEAM" }, { "time-entries", "TIME_ENTRY" }, { "allocations", "ALLOCATION" }, { "labor-costs", "LABOR_COST" }, { "trainings", "TRAINING" }, { "ppe", "PPE" }, { "safety-risks", "RISK" }, { "incidents", "INCIDENT" }, { "corrective-actions", "CORRECTIVE_ACTION" }, { "accommodations", "ACCOMMODATION" }, { "transport", "TRANSPORT" } };
    [HttpGet("{resource}")] public Task<IReadOnlyList<RuralHrRecord>> List(string resource, [FromQuery] string? status, CancellationToken ct) => service.ListAsync(Kind(resource), status, ct);
    [HttpPost("records"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> CreateRecord([FromBody] RuralHrGenericRecordCommand x, CancellationToken ct) => await Boundary(async () => { var id = await service.SaveGenericAsync(null, x, ct); return Created($"api/rural-hr/records/{id}", new { id }); });
    [HttpPost("{resource:regex(^(teams|allocations|labor-costs|trainings|ppe|safety-risks|incidents|corrective-actions|accommodations|transport)$)}"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Create(string resource, RuralHrCommand x, CancellationToken ct) => await Boundary(async () => { var id = await service.SaveAsync(null, x with { Kind = Kind(resource) }, ct); return Created($"{Request.Path}/{id}", new { id }); });
    [HttpPut("{resource}/{id:guid}"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Update(string resource, Guid id, RuralHrCommand x, CancellationToken ct) => await Boundary(async () => { await service.SaveAsync(id, x with { Kind = Kind(resource) }, ct); return NoContent(); });
    [HttpPost("people"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Person(PersonCommand x, CancellationToken ct) => Created($"api/rural-hr/people/{await service.AddPersonAsync(x, ct)}", null);
    [HttpPost("time-entries/register"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Register(TimeEntryCommand x, CancellationToken ct) => Created($"api/rural-hr/time-entries/{await service.RegisterTimeAsync(x, ct)}", null);
    [HttpPost("time-entries/{id:guid}/end"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> End(Guid id, [FromBody] EndTimeRequest? request, CancellationToken ct) { await service.EndTimeAsync(id, request?.EndedAt, request?.Justification, ct); return NoContent(); }
    [HttpPost("transport/schedule"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Transport(TransportCommand x, CancellationToken ct) => Created($"api/rural-hr/transport/{await service.AddTransportAsync(x, ct)}", null);
    [HttpGet("lookups/{kind}")] public Task<IReadOnlyList<LookupOption>> Lookups(string kind, [FromQuery] Guid? scopeId, CancellationToken ct) => service.LookupAsync(kind, scopeId, ct);
    [HttpPost("allocations/plan"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> PlanAllocation(RuralHrAllocationCommand x, CancellationToken ct) => await Boundary(async () => Created($"api/rural-hr/allocations/{await service.SaveAllocationAsync(null, x, ct)}", null));
    [HttpPut("allocations/{id:guid}/replan"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> ReplanAllocation(Guid id, RuralHrAllocationCommand x, CancellationToken ct) => await Boundary(async () => { await service.SaveAllocationAsync(id, x, ct); return NoContent(); });
    [HttpPost("allocations/{id:guid}/cancel-plan"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> CancelAllocation(Guid id, RuralHrStatusChangeCommand x, CancellationToken ct) => await Boundary(async () => { await service.CancelAllocationAsync(id, x.Reason ?? x.Justification ?? "", ct); return NoContent(); });
    [HttpPost("time-entries/{id:guid}/confirm"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> ConfirmTime(Guid id, CancellationToken ct) => await Boundary(async () => { await service.ConfirmTimeAsync(id, ct); return NoContent(); });
    [HttpPost("time-entries/{id:guid}/correct"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> CorrectTime(Guid id, RuralHrTimeCorrectionCommand x, CancellationToken ct) => await Boundary(async () => { await service.CorrectTimeAsync(id, x, ct); return NoContent(); });
    [HttpGet("tariffs")] public Task<IReadOnlyList<RuralHrTariff>> Tariffs(CancellationToken ct) => service.ListTariffsAsync(ct);
    [HttpPost("tariffs"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> SaveTariff(RuralHrTariffCommand x, CancellationToken ct) => await Boundary(async () => Created($"api/rural-hr/tariffs/{await service.SaveTariffAsync(x, ct)}", null));
    [HttpPost("time-entries/{id:guid}/appropriate"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> Appropriate(Guid id, RuralHrIdempotencyCommand x, CancellationToken ct) => await Boundary(async () => Ok(await service.AppropriateLaborAsync(id, x.IdempotencyKey, ct)));
    [HttpGet("operations-board")] public Task<RuralHrOperationsBoard> Operations([FromQuery] RuralHrBoardQuery query, CancellationToken ct) => service.OperationsBoardAsync(query, ct);
    [HttpGet("data-reviews")] public Task<IReadOnlyList<RuralHrDataReview>> Reviews(CancellationToken ct) => service.ListDataReviewsAsync(ct);
    [HttpGet("projection-issues")] public Task<IReadOnlyList<RuralHrProjectionIssue>> ProjectionIssues(CancellationToken ct) => service.ProjectionIssuesAsync(ct);
    [HttpPost("tariffs/{id:guid}/close"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> CloseTariff(Guid id, RuralHrTariffCloseCommand x, CancellationToken ct) => await Boundary(async () => { await service.CloseTariffAsync(id, x.ValidTo, x.Reason, ct); return NoContent(); });
    [HttpPost("data-reviews/{id:guid}/resolve"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> ResolveReview(Guid id, RuralHrResolutionCommand x, CancellationToken ct) => await Boundary(async () => { await service.ResolveDataReviewAsync(id, x.Resolution, x.Reason, ct); return NoContent(); });
    [HttpGet("plan-reviews"), Authorize(Policy = Permissions.CommercialSaasWrite)] public Task<IReadOnlyList<RuralHrPlanReview>> PlanReviews(CancellationToken ct) => service.ListPlanReviewsAsync(ct);
    [HttpPost("plan-reviews/{id:guid}/resolve"), Authorize(Policy = Permissions.CommercialSaasWrite)] public async Task<IActionResult> ResolvePlan(Guid id, RuralHrResolutionCommand x, CancellationToken ct) => await Boundary(async () => { await service.ResolvePlanReviewAsync(id, x.Resolution, x.Reason, ct); return NoContent(); });
    [HttpPost("constraints/validate"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> ValidateConstraints(CancellationToken ct) => await Boundary(async () => Ok(await service.ValidatePendingConstraintsAsync(ct)));
    [HttpPost("{resource}/{id:guid}/activate"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Activate(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "ACTIVE", ct);
    [HttpPost("{resource}/{id:guid}/deactivate"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Deactivate(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "INACTIVE", ct);
    [HttpPost("{resource}/{id:guid}/dispatch"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Dispatch(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "IN_FIELD", ct);
    [HttpPost("{resource}/{id:guid}/start"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Start(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, Kind(resource) switch { "CORRECTIVE_ACTION" => "IN_PROGRESS", "TRANSPORT" => "IN_TRANSIT", _ => "ACTIVE" }, ct);
    [HttpPost("{resource}/{id:guid}/investigate"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Investigate(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "INVESTIGATING", ct);
    [HttpPost("{resource}/{id:guid}/complete"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Complete(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "COMPLETED", ct);
    [HttpPost("{resource}/{id:guid}/close"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Close(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "CLOSED", ct);
    [HttpPost("{resource}/{id:guid}/cancel"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Cancel(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "CANCELLED", ct);
    [HttpPost("{resource}/{id:guid}/deliver"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Deliver(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "DELIVERED", ct);
    [HttpPost("{resource}/{id:guid}/return"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Return(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "RETURNED", ct);
    [HttpPost("{resource}/{id:guid}/discard"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Discard(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "DISCARDED", ct);
    [HttpPost("{resource}/{id:guid}/report"), Authorize(Policy = Permissions.RuralHrWrite)] public Task<IActionResult> Report(string resource, Guid id, CancellationToken ct) => ChangeStatus(resource, id, "OPEN", ct);
    [HttpPost("{resource}/{id:guid}/change-status"), Authorize(Policy = Permissions.RuralHrWrite)] public async Task<IActionResult> CustomChangeStatus(string resource, Guid id, [FromBody] RuralHrStatusChangeCommand command, CancellationToken ct) { if (string.Equals(resource, "records", StringComparison.OrdinalIgnoreCase)) { await service.ChangeStatusAsync(id, command.Status, ct); return NoContent(); } return await ChangeStatus(resource, id, command.Status, ct); }
    [HttpGet("dashboard")] public Task<RuralHrDashboard> Dashboard(CancellationToken ct) => service.DashboardAsync(ct);
    [HttpGet("{resource}/export")] public async Task<IActionResult> Export(string resource, CancellationToken ct) => File(await service.ExportAsync(Kind(resource), ct), "text/csv", $"{resource}.csv");
    private static string Kind(string resource) => Kinds.TryGetValue(resource, out var kind) ? kind : throw new KeyNotFoundException("Recurso de RH Rural não encontrado.");
    private async Task<IActionResult> ChangeStatus(string resource, Guid id, string status, CancellationToken ct) { if (string.Equals(resource, "records", StringComparison.OrdinalIgnoreCase)) { await service.ChangeStatusAsync(id, status, ct); return NoContent(); } var kind = Kind(resource); await service.ChangeStatusAsync(id, kind, status, ct); return NoContent(); }
    private async Task<IActionResult> Boundary(Func<Task<IActionResult>> operation) { try { return await operation(); } catch (Exception ex) { ApiLogMessages.RuralHrBoundaryFailed(logger, ex); throw; } }
}
