using System.Security.Claims;
using Agro360.Application.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace Agro360.Api.Controllers;

[ApiController,Authorize]
public abstract class SaasControllerBase(ISaasService service):ControllerBase { protected ISaasService Service{get;}=service; protected Guid UserId()=>Guid.TryParse(User.FindFirstValue("sub"),out var id)?id:throw new UnauthorizedAccessException("Identidade inválida."); }
[Route("api/platform"),Authorize(Roles="Super Admin Plataforma")]
public sealed class PlatformController(ISaasService s):SaasControllerBase(s){
 [HttpGet("tenants")]public Task<IReadOnlyList<TenantSummary>> Tenants(CancellationToken ct)=>Service.GetTenantsAsync(ct); [HttpPost("tenants")]public async Task<IActionResult>Create(TenantCommand x,CancellationToken ct){var id=await Service.CreateTenantAsync(x,UserId(),ct);return CreatedAtAction(nameof(Tenants),new{id});} [HttpPut("tenants/{id:guid}")]public async Task<IActionResult>Update(Guid id,TenantUpdateCommand x,CancellationToken ct){await Service.UpdateTenantAsync(id,x,UserId(),ct);return NoContent();}
 [HttpPost("tenants/{id:guid}/suspend")]public Task<IActionResult>Suspend(Guid id,CancellationToken ct)=>Status(id,"SUSPENDED",null,ct); [HttpPost("tenants/{id:guid}/block")]public Task<IActionResult>Block(Guid id,ReasonCommand x,CancellationToken ct)=>Status(id,"BLOCKED",x.Reason,ct); [HttpPost("tenants/{id:guid}/activate")]public Task<IActionResult>Activate(Guid id,CancellationToken ct)=>Status(id,"ACTIVE",null,ct); private async Task<IActionResult>Status(Guid id,string status,string? reason,CancellationToken ct){await Service.SetTenantStatusAsync(id,status,reason,UserId(),ct);return NoContent();}
 [HttpGet("plans"),AllowAnonymous]public Task<IReadOnlyList<PlanSummary>>Plans(CancellationToken ct)=>Service.GetPlansAsync(ct); [HttpPost("plans")]public async Task<IActionResult>CreatePlan(PlanCommand x,CancellationToken ct){var id=await Service.CreatePlanAsync(x,UserId(),ct);return CreatedAtAction(nameof(Plans),new{id});}[HttpPut("plans/{id:guid}")]public async Task<IActionResult>UpdatePlan(Guid id,PlanCommand x,CancellationToken ct){await Service.UpdatePlanAsync(id,x,UserId(),ct);return NoContent();}
 [HttpGet("usage")]public Task<IReadOnlyList<UsageSummary>>Usage(CancellationToken ct)=>Service.GetPlatformUsageAsync(ct);[HttpGet("dashboard")]public Task<PlatformDashboard>Dashboard(CancellationToken ct)=>Service.GetDashboardAsync(ct);
}
[Route("api/account")]
public sealed class AccountController(ISaasService s):SaasControllerBase(s){[HttpGet("organization")]public Task<TenantSummary>Organization(CancellationToken ct)=>Service.GetOrganizationAsync(ct);[HttpPut("organization")]public async Task<IActionResult>Organization(TenantUpdateCommand x,CancellationToken ct){await Service.UpdateOrganizationAsync(x,UserId(),ct);return NoContent();}[HttpGet("plan")]public Task<PlanSummary>Plan(CancellationToken ct)=>Service.GetCurrentPlanAsync(ct);[HttpGet("usage")]public Task<UsageSummary>Usage(CancellationToken ct)=>Service.GetUsageAsync(ct);[HttpPost("upgrade-requests")]public async Task<IActionResult>Upgrade(UpgradeRequestCommand x,CancellationToken ct){var id=await Service.RequestUpgradeAsync(x,UserId(),ct);return Created("/api/account/upgrade-requests",new{id});}}
[Route("api/users")]public sealed class UsersController(ISaasService s):SaasControllerBase(s){[HttpGet]public Task<IReadOnlyList<UserSummary>>List(CancellationToken ct)=>Service.GetUsersAsync(ct);[HttpPost]public async Task<IActionResult>Create(UserCommand x,CancellationToken ct){var id=await Service.SaveUserAsync(null,x,UserId(),ct);return Created("/api/users",new{id});}[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,UserCommand x,CancellationToken ct){await Service.SaveUserAsync(id,x,UserId(),ct);return NoContent();}[HttpPost("{id:guid}/activate")]public Task<IActionResult>Activate(Guid id,CancellationToken ct)=>Set(id,true,ct);[HttpPost("{id:guid}/deactivate")]public Task<IActionResult>Deactivate(Guid id,CancellationToken ct)=>Set(id,false,ct);private async Task<IActionResult>Set(Guid id,bool active,CancellationToken ct){await Service.SetUserActiveAsync(id,active,UserId(),ct);return NoContent();}}
[Route("api/roles")]public sealed class RolesController(ISaasService s):SaasControllerBase(s){[HttpGet]public Task<IReadOnlyList<RoleSummary>>List(CancellationToken ct)=>Service.GetRolesAsync(ct);[HttpPost]public async Task<IActionResult>Create(RoleCommand x,CancellationToken ct){var id=await Service.SaveRoleAsync(null,x,UserId(),ct);return Created("/api/roles",new{id});}[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,RoleCommand x,CancellationToken ct){await Service.SaveRoleAsync(id,x,UserId(),ct);return NoContent();}}
[Route("api/invitations")]public sealed class InvitationsController(ISaasService s):SaasControllerBase(s){[HttpGet]public Task<IReadOnlyList<InvitationSummary>>List(CancellationToken ct)=>Service.GetInvitationsAsync(ct);[HttpPost]public async Task<IActionResult>Create(InvitationCommand x,CancellationToken ct){var id=await Service.InviteAsync(x,UserId(),ct);return Created("/api/invitations",new{id});}[HttpPost("{id:guid}/resend")]public Task<IActionResult>Resend(Guid id,CancellationToken ct)=>Change(id,"resend",ct);[HttpPost("{id:guid}/cancel")]public Task<IActionResult>Cancel(Guid id,CancellationToken ct)=>Change(id,"cancel",ct);private async Task<IActionResult>Change(Guid id,string action,CancellationToken ct){await Service.ChangeInvitationAsync(id,action,UserId(),ct);return NoContent();}}
[Route("api/security")]public sealed class SecurityController(ISaasService s):SaasControllerBase(s){[HttpGet("sessions")]public Task<IReadOnlyList<SessionSummary>>Sessions(CancellationToken ct)=>Service.GetSessionsAsync(ct);[HttpPost("sessions/{id:guid}/revoke")]public async Task<IActionResult>RevokeSession(Guid id,CancellationToken ct){await Service.RevokeSessionAsync(id,UserId(),ct);return NoContent();}[HttpGet("devices")]public Task<IReadOnlyList<DeviceSummary>>Devices(CancellationToken ct)=>Service.GetDevicesAsync(ct);[HttpPost("devices/{id:guid}/revoke")]public async Task<IActionResult>RevokeDevice(Guid id,CancellationToken ct){await Service.RevokeDeviceAsync(id,UserId(),ct);return NoContent();}}
[Route("api/notifications")]public sealed class NotificationsController(ISaasService s):SaasControllerBase(s){[HttpGet]public Task<IReadOnlyList<NotificationSummary>>List(string? type,string? priority,CancellationToken ct)=>Service.GetNotificationsAsync(type,priority,ct);[HttpPost("{id:guid}/read")]public Task<IActionResult>Read(Guid id,CancellationToken ct)=>Change(id,"read",ct);[HttpPost("{id:guid}/archive")]public Task<IActionResult>Archive(Guid id,CancellationToken ct)=>Change(id,"archive",ct);private async Task<IActionResult>Change(Guid id,string action,CancellationToken ct){await Service.ChangeNotificationAsync(id,action,ct);return NoContent();}}
[Route("api/settings/organization")]public sealed class OrganizationSettingsController(ISaasService s):SaasControllerBase(s){[HttpGet]public Task<OrganizationSettings>Get(CancellationToken ct)=>Service.GetSettingsAsync(ct);[HttpPut]public async Task<IActionResult>Put(OrganizationSettings x,CancellationToken ct){await Service.UpdateSettingsAsync(x,UserId(),ct);return NoContent();}}
