using Agro360.Application; using Agro360.Application.Contracts; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc;
namespace Agro360.Api.Controllers;
[ApiController,Route("api/storage"),Authorize]
public sealed class StorageController(IStorageService service):ControllerBase
{
 [HttpGet("structures"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Structures(CancellationToken ct)=>service.ListAsync("structures",ct);
 [HttpPost("structures"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> AddStructure(StorageStructureCommand x,CancellationToken ct)=>Created("api/storage/structures",new{id=await service.SaveStructureAsync(null,x,ct)});
 [HttpPut("structures/{id:guid}"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> EditStructure(Guid id,StorageStructureCommand x,CancellationToken ct){await service.SaveStructureAsync(id,x,ct);return NoContent();}
 [HttpGet("receipts"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Receipts(CancellationToken ct)=>service.ListAsync("receipts",ct); [HttpGet("receipts/{id:guid}"),Authorize(Policy=Permissions.StorageRead)] public async Task<IActionResult> Receipt(Guid id,CancellationToken ct)=>Ok(await service.GetAsync("receipts",id,ct));
 [HttpPost("receipts"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> AddReceipt(ReceiptCommandV9 x,CancellationToken ct)=>Created("api/storage/receipts",new{id=await service.SaveReceiptAsync(null,x,ct)}); [HttpPut("receipts/{id:guid}"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> EditReceipt(Guid id,ReceiptCommandV9 x,CancellationToken ct){await service.SaveReceiptAsync(id,x,ct);return NoContent();}
 [HttpPost("receipts/{id:guid}/weigh"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Weigh(Guid id,WeighReceiptCommand x,CancellationToken ct){await service.WeighAsync(id,x,ct);return NoContent();} [HttpPost("receipts/{id:guid}/classify"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Classify(Guid id,ClassificationCommand x,CancellationToken ct){await service.ClassifyAsync(id,x,ct);return NoContent();}
 [HttpPost("receipts/{id:guid}/approve"),Authorize(Policy=Permissions.StorageWrite)] public Task<IActionResult> Approve(Guid id,CancellationToken ct)=>Status(id,"APPROVED",null,ct); [HttpPost("receipts/{id:guid}/unload"),Authorize(Policy=Permissions.StorageWrite)] public Task<IActionResult> Unload(Guid id,CancellationToken ct)=>Status(id,"UNLOADED",null,ct); [HttpPost("receipts/{id:guid}/cancel"),Authorize(Policy=Permissions.StorageWrite)] public Task<IActionResult> Cancel(Guid id,ReasonCommand x,CancellationToken ct)=>Status(id,"CANCELLED",x.Reason,ct);
 [HttpGet("quality-parameters"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Quality(CancellationToken ct)=>service.ListAsync("quality-parameters",ct); [HttpPost("quality-parameters"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> AddQuality(QualityParameterCommand x,CancellationToken ct)=>Created("api/storage/quality-parameters",new{id=await service.SaveQualityParameterAsync(null,x,ct)}); [HttpPut("quality-parameters/{id:guid}"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> EditQuality(Guid id,QualityParameterCommand x,CancellationToken ct){await service.SaveQualityParameterAsync(id,x,ct);return NoContent();}
 [HttpGet("lots"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Lots(CancellationToken ct)=>service.ListAsync("lots",ct); [HttpGet("lots/{id:guid}"),Authorize(Policy=Permissions.StorageRead)] public async Task<IActionResult> Lot(Guid id,CancellationToken ct)=>Ok(await service.GetAsync("lots",id,ct)); [HttpPost("lots/{id:guid}/transfer"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Transfer(Guid id,TransferLotCommand x,CancellationToken ct){await service.TransferLotAsync(id,x,ct);return NoContent();} [HttpPost("lots/{id:guid}/block"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Block(Guid id,ReasonCommand x,CancellationToken ct){await service.SetLotBlockedAsync(id,true,x.Reason,ct);return NoContent();} [HttpPost("lots/{id:guid}/unblock"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Unblock(Guid id,CancellationToken ct){await service.SetLotBlockedAsync(id,false,null,ct);return NoContent();}
 [HttpGet("processing-orders"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Processing(CancellationToken ct)=>service.ListAsync("processing-orders",ct); [HttpPost("processing-orders"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> AddProcessing(ProcessingOrderCommand x,CancellationToken ct)=>Created("api/storage/processing-orders",new{id=await service.CreateProcessingAsync(x,ct)}); [HttpPost("processing-orders/{id:guid}/start"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Start(Guid id,CancellationToken ct){await service.ProcessingStatusAsync(id,"IN_PROGRESS",null,null,ct);return NoContent();} [HttpPost("processing-orders/{id:guid}/complete"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Complete(Guid id,CompleteProcessingCommand x,CancellationToken ct){await service.ProcessingStatusAsync(id,"COMPLETED",x,null,ct);return NoContent();} [HttpPost("processing-orders/{id:guid}/cancel"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> CancelProcessing(Guid id,ReasonCommand x,CancellationToken ct){await service.ProcessingStatusAsync(id,"CANCELLED",null,x.Reason,ct);return NoContent();}
 [HttpGet("shipments"),Authorize(Policy=Permissions.StorageRead)] public Task<IReadOnlyList<dynamic>> Shipments(CancellationToken ct)=>service.ListAsync("shipments",ct); [HttpPost("shipments"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> AddShipment(ShipmentCommand x,CancellationToken ct)=>Created("api/storage/shipments",new{id=await service.CreateShipmentAsync(x,ct)}); [HttpPost("shipments/{id:guid}/load"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Load(Guid id,LoadShipmentCommand x,CancellationToken ct){await service.LoadShipmentAsync(id,x,ct);return NoContent();} [HttpPost("shipments/{id:guid}/dispatch"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> Dispatch(Guid id,CancellationToken ct){await service.ShipmentStatusAsync(id,"DISPATCHED",null,ct);return NoContent();} [HttpPost("shipments/{id:guid}/cancel"),Authorize(Policy=Permissions.StorageWrite)] public async Task<IActionResult> CancelShipment(Guid id,ReasonCommand x,CancellationToken ct){await service.ShipmentStatusAsync(id,"CANCELLED",x.Reason,ct);return NoContent();}
 [HttpGet("dashboard"),Authorize(Policy=Permissions.StorageRead)] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(await service.DashboardAsync(ct));
 private async Task<IActionResult> Status(Guid id,string status,string? reason,CancellationToken ct){await service.ReceiptStatusAsync(id,status,reason,ct);return NoContent();}
}
