namespace Agro360.ArchitectureTests;
public sealed class SaasGovernanceTests
{
 [Fact] public void SaasUiNeverRequestsTechnicalIds(){var root=FindRoot();var text=File.ReadAllText(Path.Combine(root,"src/Hosts/Agro360.Web/Pages/Saas/Index.cshtml"))+File.ReadAllText(Path.Combine(root,"src/Hosts/Agro360.Web/wwwroot/js/agro360.saas_js"));Assert.DoesNotContain("name=\"tenantId\"",text,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("name=\"planId\"",text,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("name=\"roleId\"",text,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void SqlIsStandaloneAndContainsSaasModules(){var sql=File.ReadAllText(Path.Combine(FindRoot(),"database/agro360-postgres-full.sql"));Assert.DoesNotContain("\\i ",sql);Assert.Contains("create schema if not exists agro360",sql,StringComparison.OrdinalIgnoreCase);Assert.Contains("'Essencial'",sql);Assert.Contains("agro360.audit_saas_events",sql);}
 [Fact] public void ExpectedEndpointsAreDeclared(){var api=File.ReadAllText(Path.Combine(FindRoot(),"src/Hosts/Agro360.Api/Controllers/SaasControllers.cs"));foreach(var route in new[]{"api/platform","tenants","plans","usage","dashboard","api/account","upgrade-requests","api/users","api/roles","api/invitations","api/security","sessions","devices","api/notifications","api/settings/organization"})Assert.Contains(route,api);}
 [Fact] public void TenantBlockEndpointUsesBlockedStatus(){var api=File.ReadAllText(Path.Combine(FindRoot(),"src/Hosts/Agro360.Api/Controllers/SaasControllers.cs"));Assert.Contains("Block(Guid id,ReasonCommand x,CancellationToken ct)=>Status(id,\"BLOCKED\"",api);}
 [Fact] public void TenantBlockPersistsTimestampAndActivationClearsReason(){var service=File.ReadAllText(Path.Combine(FindRoot(),"src/Modules/Agro360.Infrastructure/Services/SaasService.cs"));Assert.Contains("@Status in ('SUSPENDED','BLOCKED')",service);Assert.Contains("block_reason=case when @Status='ACTIVE' then null",service);}
 [Fact] public void UserStatusChangeIsAudited(){var service=File.ReadAllText(Path.Combine(FindRoot(),"src/Modules/Agro360.Infrastructure/Services/SaasService.cs"));Assert.Contains("'USER_STATUS_CHANGED'",service);}
 private static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null&&!File.Exists(Path.Combine(d.FullName,"MNSOFT.Agro360.sln")))d=d.Parent;return d?.FullName??throw new DirectoryNotFoundException();}
}
