namespace Agro360.ArchitectureTests;

public sealed class Sprint22CommercialTests
{
    private static readonly string Root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../"));
    [Fact] public void FullSqlContainsCommercialSchema() { var sql = File.ReadAllText(Path.Combine(Root, "database/agro360-postgres-full.sql")); Assert.Contains("create table if not exists agro360.crm_customers", sql); Assert.Contains("create table if not exists agro360.sales_commissions", sql); Assert.Contains("create table if not exists agro360.sales_split_participants", sql); Assert.DoesNotContain("\\i ", sql); }
    [Fact] public void CommercialFormNeverRequestsTechnicalIds() { var view = File.ReadAllText(Path.Combine(Root, "src/Hosts/Agro360.Web/Pages/Commercial/Index.cshtml")); Assert.DoesNotContain("tenant_id", view, StringComparison.OrdinalIgnoreCase); Assert.Contains("data-lookup=\"segments\"", view); Assert.Contains("data-lookup=\"representatives\"", view); }
    [Fact] public void DapperQueriesAreTenantScoped() { var service = File.ReadAllText(Path.Combine(Root, "src/Modules/Agro360.Infrastructure/Services/Commercial360Service.cs")); Assert.Contains("tenant_id=@TenantId", service); Assert.DoesNotContain("select *", service, StringComparison.OrdinalIgnoreCase); }
    [Fact] public void OrderPolicyComesFromServerAndTransitionsAreGuarded() { var contract = File.ReadAllText(Path.Combine(Root, "src/Modules/Agro360.Application/Contracts/Commercial360Contracts.cs")); var service = File.ReadAllText(Path.Combine(Root, "src/Modules/Agro360.Infrastructure/Services/Commercial360Service.cs")); var rules = File.ReadAllText(Path.Combine(Root, "src/Modules/Agro360.Domain/Commercial/CommercialRules.cs")); var sql = File.ReadAllText(Path.Combine(Root, "database/agro360-postgres-full.sql")); Assert.DoesNotContain("MaximumDiscount", contract); Assert.Contains("sales_price_table_items", service); Assert.Contains("base_price BasePrice", service); Assert.Contains("pricing_snapshot", service); Assert.Contains("for update", service); Assert.Contains("ValidateOrderTransition", service); Assert.Contains("EffectiveDiscount", rules); Assert.Contains("MidpointRounding.AwayFromZero", rules); Assert.Contains("price_table_id uuid", sql); }
}
