namespace Agro360.ArchitectureTests;
public sealed class Sprint46EcosystemTests
{
 private static readonly string Root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../../"));
 [Fact]public void ApiKeysAreHashedAndTenantScoped(){var s=File.ReadAllText(Path.Combine(Root,"src/Modules/Agro360.Infrastructure/Services/EcosystemService.cs"));Assert.Contains("SHA256.HashData",s);Assert.Contains("key_hash",s);Assert.DoesNotContain("key_plain",s);Assert.Contains("tenant.TenantId",s);Assert.Contains("EcosystemRules.Scopes",s);}
 [Fact]public void ControllersHavePermissionsAndRealActions(){var s=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Api/Controllers/EcosystemController.cs"));foreach(var route in new[]{"marketplace/modules","marketplace/requests","partners","partner-access","api-keys","webhooks","audit","developer-docs","commercial-catalog"})Assert.Contains(route,s);Assert.Contains("Authorize",s);}
 [Fact]public void DatabaseHasTenantSecurityDeliveryAndAudit(){var s=File.ReadAllText(Path.Combine(Root,"database/agro360-postgres-full.sql"));foreach(var table in new[]{"platform_marketplace_modules","platform_marketplace_requests","platform_partner_accounts","platform_partner_tenant_access","platform_external_apps","platform_api_keys","platform_api_scopes","platform_api_request_logs","platform_webhook_subscriptions","platform_webhook_events","platform_webhook_deliveries","platform_developer_docs","platform_commercial_catalog","platform_integration_audit_events"})Assert.Contains(table,s);Assert.Contains("enable row level security",s);Assert.Contains("maximum_attempts",s);}
 [Fact]public void NewScreenIsLocalizedAndHelpful(){var page=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Web/Pages/Ecosystem/Index.cshtml"));var js=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Web/wwwroot/js/ecosystem.js"));Assert.Contains("Como usar esta tela",page);foreach(var culture in new[]{"pt-BR","en-US","es-ES"})Assert.Contains(culture,js);Assert.Contains("/api/ecosystem/",js);}
}
