namespace Agro360.ArchitectureTests;
public sealed class Sprint18CooperativeTests
{
 private static readonly string Root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../../"));
 [Fact]public void Controllers_delegate_and_are_secured(){var c=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Api/Controllers/CooperativeControllers.cs"));Assert.Contains("ICooperativeService",c);Assert.Contains("Authorize(Policy=Permissions.CooperativeRead)",c);Assert.DoesNotContain("Dapper",c);foreach(var route in new[]{"api/cooperative","api/technical-assistance","api/production-programs","api/marketplace","api/collective-purchases","api/agro-contracts","api/bonuses","api/rural-credit/pre-analyses","api/producer-portal/dashboard"})Assert.Contains(route,c);}
 [Fact]public void Forms_use_lookups_not_technical_ids(){var h=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Web/Pages/Cooperatives/Index.cshtml"));Assert.DoesNotContain("name=\"id\"",h,StringComparison.OrdinalIgnoreCase);foreach(var lookup in new[]{"data-lookup=\"members\"","data-lookup=\"properties\"","data-lookup=\"traceability\""})Assert.Contains(lookup,h);Assert.Contains("required",h);}
 [Fact]public void All_screens_are_available(){var h=File.ReadAllText(Path.Combine(Root,"src/Hosts/Agro360.Web/Pages/Cooperatives/Index.cshtml"));foreach(var screen in new[]{"Cooperados","Assistência Técnica","Visitas","Recomendações","Programas de Produção","Marketplace","Ofertas","Demandas","Compras Coletivas","Contratos","Bonificações","Repasses","Pré-análise de Crédito","Portal do Produtor","Dashboard Cooperativo"})Assert.Contains(screen,h);}
 [Fact]public void Full_sql_is_standalone_multitenant(){var sql=File.ReadAllText(Path.Combine(Root,"database/agro360-postgres-full.sql"));Assert.Contains("create schema if not exists agro360",sql);Assert.Contains("enable row level security",sql);Assert.Contains("unique(tenant_id,document)",sql);Assert.DoesNotContain("\\i",sql);}
}
