namespace Agro360.ArchitectureTests;

public sealed class Sprint38IndustrialProductionTests
{
    [Fact] public void FullSqlContainsTenantScopedIndustrialFoundation() { var sql = File.ReadAllText(Path.Combine(Root(), "database", "agro360-postgres-full.sql")); foreach (var table in new[] { "production_industrial_plants", "production_lines", "production_work_centers", "production_shifts", "production_recipes", "production_recipe_versions", "production_orders", "production_step_records", "production_material_consumptions", "production_batches", "production_batch_traceability", "production_losses", "production_stoppages", "production_quality_checks", "production_costs", "production_reports_exports" }) Assert.Contains($"agro360.{table}", sql); Assert.Contains("tenant_id", sql); Assert.Contains("force row level security", sql); }
    [Fact] public void FormsDoNotRequestTechnicalIds() { var view = File.ReadAllText(Path.Combine(Root(), "src", "Hosts", "Agro360.Web", "Pages", "Production", "Index.cshtml")); Assert.DoesNotContain("type=\"text\" name=\"tenantId\"", view); Assert.Contains("data-lookup=\"products\"", view); Assert.Contains("data-lookup=\"operators\"", view); }
    [Fact] public void ApiExposesRealOperationalEndpoints() { var controller = File.ReadAllText(Path.Combine(Root(), "src", "Hosts", "Agro360.Api", "Controllers", "IndustrialProductionController.cs")); foreach (var endpoint in new[] { "recipes", "orders", "records", "consumptions", "quality", "stoppages", "traceability", "reports" }) Assert.Contains(endpoint, controller); }
    [Fact] public void RecordsLockAndValidateOperationalState() { var service = File.ReadAllText(Path.Combine(Root(), "src", "Modules", "Agro360.Infrastructure", "Services", "IndustrialProductionService.cs")); Assert.Contains("for update", service); Assert.Contains("production_order_record_forbidden", service); Assert.Contains("minimum_temperature", service); Assert.Contains("conformity_status", service); Assert.Contains("ProductionStepLookup", service); Assert.DoesNotContain("step == default", service); }
    [Fact] public void QualityCompletionUsesEffectiveBatchStatus() { var service = File.ReadAllText(Path.Combine(Root(), "src", "Modules", "Agro360.Infrastructure", "Services", "IndustrialProductionService.cs")); Assert.Contains("b.quality_status<>'APPROVED'", service); Assert.Contains("order_id=@OrderId", service); Assert.Contains("production_quality_status_invalid", service); }
    [Fact] public void IntegratedProcessingSeparatesReservationConsumptionAndRelease() { var service = File.ReadAllText(Path.Combine(Root(), "src", "Modules", "Agro360.Infrastructure", "Services", "IndustrialProductionService.cs")); Assert.Contains("production_material_reservations", service); Assert.Contains("production_reservation_consumptions", service); Assert.Contains("production_receipt_quality_pending", service); Assert.Contains("for update", service); Assert.Contains("production-batch:", service); Assert.DoesNotContain("CancellationToken.None", service); }
    [Fact] public void GenericStatusEndpointCannotBypassOperationalActions() { var controller = File.ReadAllText(Path.Combine(Root(), "src", "Hosts", "Agro360.Api", "Controllers", "IndustrialProductionController.cs")); Assert.DoesNotContain("orders/{id:guid}/status", controller); foreach (var action in new[] { "/release", "/start", "/complete", "/cancel" }) Assert.Contains(action, controller); }
    private static string Root() { var d = new DirectoryInfo(AppContext.BaseDirectory); while (d is not null && !File.Exists(Path.Combine(d.FullName, "MNSOFT.Agro360.sln"))) d = d.Parent; return d?.FullName ?? throw new InvalidOperationException(); }
}
