using Agro360.SharedKernel;
namespace Agro360.Domain.Production;

public static class IndustrialProductionRules
{
    public static readonly string[] OrderStatuses = ["DRAFT", "PLANNED", "AWAITING_MATERIALS", "RELEASED", "IN_PRODUCTION", "PAUSED", "IN_QUALITY", "COMPLETED", "BLOCKED", "CANCELLED", "CLOSED"];
    public static decimal Yield(decimal produced, decimal consumed) { if (produced < 0 || consumed <= 0) throw new DomainException("Quantidades inválidas para rendimento.", "production.yield_invalid"); return decimal.Round(produced / consumed * 100, 2); }
    public static decimal BasicCost(decimal materials, decimal losses, decimal labor, decimal machine, decimal produced) { if (materials < 0 || losses < 0 || labor < 0 || machine < 0 || produced <= 0) throw new DomainException("Valores inválidos para custo industrial.", "production.cost_invalid"); return decimal.Round((materials + losses + labor + machine) / produced, 4); }
    public static void Recipe(decimal baseQuantity, decimal expectedYield, IEnumerable<(Guid ItemId, decimal Quantity, string Unit)> items) { if (baseQuantity <= 0 || expectedYield <= 0) throw new DomainException("Quantidade base e rendimento esperado devem ser positivos.", "production.recipe_quantity_invalid"); if (!items.Any() || items.Any(x => x.ItemId == Guid.Empty || x.Quantity <= 0 || string.IsNullOrWhiteSpace(x.Unit))) throw new DomainException("A formulação exige insumos válidos.", "production.recipe_items_required"); }
    public static void Order(Guid productId, Guid recipeVersionId, decimal quantity, string unit) { if (productId == Guid.Empty || recipeVersionId == Guid.Empty) throw new DomainException("Produto final e formulação são obrigatórios.", "production.order_recipe_required"); if (quantity <= 0 || string.IsNullOrWhiteSpace(unit)) throw new DomainException("Quantidade positiva e unidade são obrigatórias.", "production.order_quantity_invalid"); }
    public static void Record(Guid operatorId, decimal produced, decimal consumed, decimal loss, string? lossReason) { if (operatorId == Guid.Empty) throw new DomainException("Responsável pelo apontamento é obrigatório.", "production.operator_required"); if (produced < 0 || consumed < 0 || loss < 0) throw new DomainException("Quantidades negativas são proibidas.", "production.negative_quantity"); if (loss > 0 && string.IsNullOrWhiteSpace(lossReason)) throw new DomainException("Perda exige motivo.", "production.loss_reason_required"); }
    public static void Reservation(decimal quantity, string unit, string idempotencyKey) { if (quantity <= 0) throw new DomainException("A quantidade deve ser positiva.", "production.quantity_invalid"); if (string.IsNullOrWhiteSpace(unit)) throw new DomainException("A unidade é obrigatória.", "production.unit_required"); if (string.IsNullOrWhiteSpace(idempotencyKey) || idempotencyKey.Length > 160) throw new DomainException("Informe uma chave idempotente válida.", "production.idempotency_key_invalid"); }
    public static void Output(decimal quantity, string unit, string outputType, string? reason, string idempotencyKey) { Reservation(quantity, unit, idempotencyKey); var type = outputType.ToUpperInvariant(); if (type is not ("MAIN" or "COPRODUCT" or "LOSS" or "SCRAP")) throw new DomainException("Tipo de resultado inválido.", "production.output_type_invalid"); if (type is "LOSS" or "SCRAP" && string.IsNullOrWhiteSpace(reason)) throw new DomainException("Perda ou refugo exige motivo.", "production.output_reason_required"); }
    public static void Transition(string current, string next, string? reason, bool hasItems, bool hasRecord, bool stockReserved, bool reservationRequired, bool criticalComplete, bool qualityApproved) { var allowed = (current, next) switch { ("PLANNED", "RELEASED") or ("AWAITING_MATERIALS", "RELEASED") or ("RELEASED", "IN_PRODUCTION") or ("IN_PRODUCTION", "PAUSED") or ("PAUSED", "IN_PRODUCTION") or ("IN_PRODUCTION", "COMPLETED") or ("BLOCKED", "CANCELLED") => true, (_, "CANCELLED") when current is not ("COMPLETED" or "CLOSED" or "CANCELLED") => true, _ => false }; if (!allowed) throw new DomainException("Transição de estado não permitida.", "production.transition_invalid"); if (!OrderStatuses.Contains(next)) throw new DomainException("Status inválido.", "production.status_invalid"); if (next == "RELEASED" && !hasItems) throw new DomainException("Não é possível liberar ordem sem itens.", "production.items_required"); if (next == "IN_PRODUCTION" && reservationRequired && !stockReserved) throw new DomainException("Estoque reservado é obrigatório para iniciar.", "production.stock_required"); if (next is "COMPLETED" or "CLOSED" && !hasRecord) throw new DomainException("A ordem exige apontamento concluído.", "production.record_required"); if (next is "COMPLETED" or "CLOSED" && (!criticalComplete || !qualityApproved)) throw new DomainException("Etapa crítica e qualidade devem estar conformes.", "production.quality_required"); if (next == "CANCELLED" && string.IsNullOrWhiteSpace(reason)) throw new DomainException("Cancelamento exige motivo.", "production.cancel_reason_required"); if (current is "CANCELLED" or "CLOSED") throw new DomainException("Ordem encerrada não aceita transição.", "production.order_final"); }
}
