FROM mcr.microsoft.com/dotnet/sdk:10.0-noble AS build
WORKDIR /src
COPY . .
RUN dotnet restore src/Hosts/Agro360.Worker/Agro360.Worker.csproj
RUN dotnet publish src/Hosts/Agro360.Worker/Agro360.Worker.csproj -c Release --no-restore -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0-noble AS final
WORKDIR /app
COPY --from=build /app/publish .
USER $APP_UID
ENTRYPOINT ["dotnet", "Agro360.Worker.dll"]
