begin;
create schema if not exists crm;
create schema if not exists sales;
create sequence if not exists sales.order_number_seq;

insert into identity.permissions(code,module,description) values
('commercial.read','Commercial','Consultar CRM e comercial.'),('commercial.orders.approve','Commercial','Aprovar e cancelar pedidos.'),
('commercial.customers.override-block','Commercial','Vender para cliente bloqueado.'),('commercial.commissions.manage','Commercial','Gerenciar comissões.'),
('commercial.splits.approve','Commercial','Aprovar acordos de split.') on conflict(code) do update set description=excluded.description;

create table if not exists crm.customer_segments(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),name varchar(80) not null,status varchar(16) not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,name));
create table if not exists sales.regions(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),name varchar(120) not null,status varchar(16) not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,name));
create table if not exists sales.representatives(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),supervisor_id uuid,name varchar(180) not null,type varchar(30) not null check(type in('REPRESENTATIVE','PARTNER','FIELD_TECHNICIAN','INTERNAL_SELLER','SUPERVISOR')),email varchar(254),phone varchar(40),default_commission numeric(7,4) not null default 0 check(default_commission between 0 and 100),status varchar(16) not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE','BLOCKED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,supervisor_id) references sales.representatives(tenant_id,id));
create table if not exists sales.representative_regions(tenant_id uuid not null,representative_id uuid not null,region_id uuid not null,primary key(tenant_id,representative_id,region_id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),foreign key(tenant_id,region_id) references sales.regions(tenant_id,id));
create table if not exists sales.portfolios(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),representative_id uuid,name varchar(120) not null,status varchar(16) not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id));
create table if not exists crm.customers(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),segment_id uuid not null,representative_id uuid,portfolio_id uuid,name varchar(180) not null,type varchar(16) not null check(type in('CUSTOMER','PROSPECT')),tax_document varchar(14),email varchar(254),phone varchar(40),source varchar(80),classification varchar(40),status varchar(16) not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE','BLOCKED')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,tax_document),foreign key(tenant_id,segment_id) references crm.customer_segments(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),foreign key(tenant_id,portfolio_id) references sales.portfolios(tenant_id,id),check(tax_document is null or tax_document~'^[0-9]{11,14}$'));
create table if not exists crm.contacts(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),customer_id uuid not null,name varchar(180) not null,role varchar(80),email varchar(254),phone varchar(40),status varchar(16) not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id));
create table if not exists crm.relationship_history(id uuid primary key,tenant_id uuid not null,customer_id uuid not null,kind varchar(40) not null,description text not null,occurred_at timestamptz not null default now(),created_by uuid,foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id));
create table if not exists sales.opportunities(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),customer_id uuid not null,product_id uuid,representative_id uuid,name varchar(180) not null,estimated_value numeric(18,2) not null check(estimated_value>=0),probability int not null check(probability between 0 and 100),stage varchar(24) not null check(stage in('NEW_LEAD','QUALIFICATION','PROPOSAL','NEGOTIATION','WON','LOST')),expected_close date,source varchar(80),next_action text,loss_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id),foreign key(tenant_id,product_id) references inventory.products(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),check(stage<>'LOST' or loss_reason is not null));
create table if not exists sales.opportunity_history(id uuid primary key,tenant_id uuid not null,opportunity_id uuid not null,from_stage varchar(24),to_stage varchar(24) not null,justification text,changed_at timestamptz not null default now(),changed_by uuid,foreign key(tenant_id,opportunity_id) references sales.opportunities(tenant_id,id));
create table if not exists sales.activities(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),customer_id uuid not null,representative_id uuid,name varchar(40) not null,type varchar(30) not null check(type in('VISIT','CALL','MEETING','DEMONSTRATION','NEGOTIATION','FOLLOW_UP','TASK')),scheduled_at timestamptz not null,status varchar(20) not null check(status in('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED')),channel varchar(180),result text,next_action text,notes text,cancellation_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),check(status<>'COMPLETED' or result is not null),check(status<>'CANCELLED' or cancellation_reason is not null));
create table if not exists sales.price_tables(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),segment_id uuid not null,name varchar(140) not null,valid_from date not null,valid_to date not null,status varchar(16) not null default 'ACTIVE',is_default boolean not null default false,payment_terms text,freight_policy text,commission_policy text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,segment_id) references crm.customer_segments(tenant_id,id),check(valid_to>=valid_from));
create unique index if not exists uq_price_table_default on sales.price_tables(tenant_id,segment_id,valid_from,valid_to) where is_default and status='ACTIVE' and deleted_at is null;
create table if not exists sales.price_table_items(id uuid primary key,tenant_id uuid not null,price_table_id uuid not null,product_id uuid not null,unit varchar(20) not null,base_price numeric(18,4) not null check(base_price>=0),maximum_discount numeric(7,4) not null default 0 check(maximum_discount between 0 and 100),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,unique(tenant_id,price_table_id,product_id),foreign key(tenant_id,price_table_id) references sales.price_tables(tenant_id,id),foreign key(tenant_id,product_id) references inventory.products(tenant_id,id));
create table if not exists sales.contracts(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),customer_id uuid not null,product_id uuid,representative_id uuid,name varchar(180) not null,type varchar(30) not null check(type in('FUTURE_SALE','RECURRING_SUPPLY','EXPORT','COOPERATIVE','INSTITUTIONAL_PURCHASE','PARTNERSHIP')),contracted_quantity numeric(20,6) not null check(contracted_quantity>0),delivered_quantity numeric(20,6) not null default 0,contracted_value numeric(18,2) not null check(contracted_value>=0),valid_from date not null,valid_to date not null,payment_terms text,delivery_frequency varchar(50),status varchar(20) not null check(status in('DRAFT','ACTIVE','EXPIRED','CANCELLED')),notes text,cancellation_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id),foreign key(tenant_id,product_id) references inventory.products(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),check(delivered_quantity<=contracted_quantity),check(valid_to>=valid_from),check(status<>'CANCELLED' or cancellation_reason is not null));
create table if not exists sales.orders(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),customer_id uuid not null,representative_id uuid,property_id uuid,contract_id uuid,order_number varchar(40) not null,status varchar(24) not null check(status in('DRAFT','UNDER_REVIEW','APPROVED','FULFILLMENT','INVOICED','DELIVERED','CANCELLED')),total_amount numeric(18,2) not null check(total_amount>=0),freight numeric(18,2) not null default 0 check(freight>=0),payment_terms text,expected_delivery date,notes text,cancellation_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,order_number),foreign key(tenant_id,customer_id) references crm.customers(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),foreign key(tenant_id,contract_id) references sales.contracts(tenant_id,id),check(status<>'CANCELLED' or cancellation_reason is not null));
create unique index if not exists uq_stock_lots_tenant_id on inventory.stock_lots(tenant_id,id);
create table if not exists sales.order_items(id uuid primary key,tenant_id uuid not null,order_id uuid not null,product_id uuid not null,lot_id uuid,quantity numeric(20,6) not null check(quantity>0),unit varchar(20) not null,unit_price numeric(18,4) not null check(unit_price>=0),discount_percentage numeric(7,4) not null default 0 check(discount_percentage between 0 and 100),total_amount numeric(18,2) not null check(total_amount>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,id),foreign key(tenant_id,order_id) references sales.orders(tenant_id,id),foreign key(tenant_id,product_id) references inventory.products(tenant_id,id),foreign key(tenant_id,lot_id) references inventory.stock_lots(tenant_id,id));
create table if not exists sales.commission_plans(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),name varchar(140) not null,status varchar(16) not null default 'ACTIVE',valid_from date not null,valid_to date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id));
create table if not exists sales.commission_rules(id uuid primary key,tenant_id uuid not null,plan_id uuid not null,name varchar(140) not null,basis_type varchar(30) not null,trigger_type varchar(40) not null,product_id uuid,customer_id uuid,percentage numeric(7,4),fixed_value numeric(18,2),status varchar(16) not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,plan_id) references sales.commission_plans(tenant_id,id),check((percentage is null)<>(fixed_value is null)),check(percentage between 0 and 100 or percentage is null),check(fixed_value>=0 or fixed_value is null));
create table if not exists sales.commissions(id uuid primary key,tenant_id uuid not null,order_id uuid not null,rule_id uuid not null,representative_id uuid not null,basis numeric(18,2) not null check(basis>=0),percentage numeric(7,4),fixed_value numeric(18,2),amount numeric(18,2) not null check(amount>=0),status varchar(20) not null check(status in('EXPECTED','APPROVED','BLOCKED','PAID','CANCELLED','REVERSED')),status_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,order_id,rule_id,representative_id),foreign key(tenant_id,order_id) references sales.orders(tenant_id,id),foreign key(tenant_id,rule_id) references sales.commission_rules(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id));
create table if not exists sales.commission_history(id uuid primary key,tenant_id uuid not null,commission_id uuid not null,from_status varchar(20),to_status varchar(20) not null,reason text,amount numeric(18,2) not null,changed_at timestamptz not null default now(),changed_by uuid,foreign key(tenant_id,commission_id) references sales.commissions(tenant_id,id));
create table if not exists sales.split_agreements(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),order_id uuid,contract_id uuid,name varchar(180) not null,status varchar(20) not null check(status in('DRAFT','APPROVED','ACTIVE','CANCELLED')),status_reason text,release_rule varchar(80),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,order_id) references sales.orders(tenant_id,id),foreign key(tenant_id,contract_id) references sales.contracts(tenant_id,id));
create table if not exists sales.split_participants(id uuid primary key,tenant_id uuid not null,agreement_id uuid not null,participant_id uuid not null,participant_type varchar(30) not null,percentage numeric(7,4),fixed_value numeric(18,2),priority int not null default 0,created_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,agreement_id,participant_id),foreign key(tenant_id,agreement_id) references sales.split_agreements(tenant_id,id),check((percentage is null)<>(fixed_value is null)),check(percentage between 0 and 100 or percentage is null),check(fixed_value>=0 or fixed_value is null));
create table if not exists sales.split_entries(id uuid primary key,tenant_id uuid not null,agreement_id uuid not null,order_id uuid,participant_id uuid not null,amount numeric(18,2) not null check(amount>=0),status varchar(20) not null check(status in('EXPECTED','RELEASED','PAID','CANCELLED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(tenant_id,agreement_id) references sales.split_agreements(tenant_id,id));
create table if not exists sales.targets(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),representative_id uuid not null,name varchar(140) not null,period_start date not null,period_end date not null,target_amount numeric(18,2) not null check(target_amount>=0),achieved_amount numeric(18,2) not null default 0 check(achieved_amount>=0),status varchar(16) not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid,updated_by uuid,deleted_at timestamptz,unique(tenant_id,id),foreign key(tenant_id,representative_id) references sales.representatives(tenant_id,id),check(period_end>=period_start));
create table if not exists sales.commercial_events(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),event_type varchar(60) not null,aggregate_id uuid not null,payload jsonb not null default '{}',created_at timestamptz not null default now(),created_by uuid);

create index if not exists ix_crm_customers_tenant_status on crm.customers(tenant_id,status,name) where deleted_at is null;
create index if not exists ix_sales_opportunities_funnel on sales.opportunities(tenant_id,stage,representative_id) where deleted_at is null;
create index if not exists ix_sales_activities_due on sales.activities(tenant_id,status,scheduled_at) where deleted_at is null;
create index if not exists ix_sales_orders_status on sales.orders(tenant_id,status,created_at desc) where deleted_at is null;
create index if not exists ix_sales_contracts_status on sales.contracts(tenant_id,status,valid_to) where deleted_at is null;
create index if not exists ix_sales_commissions_status on sales.commissions(tenant_id,status,representative_id) where deleted_at is null;
create index if not exists ix_sales_splits_status on sales.split_agreements(tenant_id,status,updated_at desc) where deleted_at is null;
do $$ declare t text; begin foreach t in array array['customer_segments','customers','contacts'] loop execute format('alter table crm.%I enable row level security',t);execute format('drop policy if exists tenant_isolation on crm.%I',t);execute format('create policy tenant_isolation on crm.%I using (tenant_id=platform.current_tenant_id()) with check (tenant_id=platform.current_tenant_id())',t);end loop; foreach t in array array['regions','representatives','portfolios','opportunities','activities','price_tables','contracts','orders','commission_plans','commission_rules','commissions','split_agreements','targets'] loop execute format('alter table sales.%I enable row level security',t);execute format('drop policy if exists tenant_isolation on sales.%I',t);execute format('create policy tenant_isolation on sales.%I using (tenant_id=platform.current_tenant_id()) with check (tenant_id=platform.current_tenant_id())',t);end loop; end $$;
commit;
