-- Sprint 30 — integrações externas, import/export e fundação fiscal (PostgreSQL 16+)
begin;
create schema if not exists fiscal;

-- O legado integrations.integrations continua compatível; estes nomes formam o contrato canônico novo.
create table if not exists integrations.integration_connectors(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),name varchar(120) not null,type varchar(32) not null check(type in('ERP','FISCAL','LOGISTICS','FINANCIAL','MARKETPLACE','BI','COOPERATIVE','EXTERNAL_PORTAL','GOVERNMENT','WEBHOOK','EXTERNAL_API','OTHER')),provider varchar(80),endpoint_url varchar(1000),authentication_type varchar(30) not null default 'NONE',status varchar(30) not null default 'NOT_CONFIGURED' check(status in('NOT_CONFIGURED','ACTIVE','INACTIVE','ERROR')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,name),check(endpoint_url is null or endpoint_url ~ '^https?://'));
create table if not exists integrations.integration_connector_settings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,connector_id uuid not null,setting_key varchar(100) not null,setting_value jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,connector_id,setting_key),foreign key(tenant_id,connector_id) references integrations.integration_connectors(tenant_id,id) on delete cascade);
create table if not exists integrations.integration_credentials(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,connector_id uuid not null,secret_reference varchar(500) not null,key_version int not null default 1 check(key_version>0),expires_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,connector_id) references integrations.integration_connectors(tenant_id,id));
create table if not exists integrations.integration_outbox(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,connector_id uuid not null,idempotency_key varchar(160) not null,event_type varchar(100) not null,payload jsonb not null,status varchar(20) not null default 'PENDING' check(status in('PENDING','PROCESSING','SENT','FAILED','CANCELLED')),attempts int not null default 0 check(attempts between 0 and 20),available_at timestamptz not null default now(),last_error varchar(1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,connector_id,idempotency_key),foreign key(tenant_id,connector_id) references integrations.integration_connectors(tenant_id,id));
create table if not exists integrations.integration_inbox(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,connector_id uuid not null,idempotency_key varchar(160) not null,payload_hash char(64) not null,status varchar(20) not null default 'RECEIVED' check(status in('RECEIVED','PROCESSING','PROCESSED','FAILED','IGNORED')),received_at timestamptz not null default now(),processed_at timestamptz,last_error varchar(1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,connector_id,idempotency_key),foreign key(tenant_id,connector_id) references integrations.integration_connectors(tenant_id,id));
create table if not exists integrations.integration_retry_attempts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,outbox_id uuid not null,attempt_number int not null check(attempt_number between 1 and 20),status varchar(20) not null,response_code int,error_code varchar(80),safe_error varchar(1000),attempted_at timestamptz not null default now(),next_attempt_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,outbox_id,attempt_number),foreign key(tenant_id,outbox_id) references integrations.integration_outbox(tenant_id,id));

create table if not exists integrations.external_api_applications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),name varchar(120) not null,status varchar(20) not null default 'ACTIVE' check(status in('ACTIVE','SUSPENDED','REVOKED')),rate_limit_per_minute int not null default 60 check(rate_limit_per_minute between 1 and 10000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id,id),unique(tenant_id,name));
create table if not exists integrations.external_api_keys(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,application_id uuid not null,key_prefix varchar(20) not null,key_hash char(64) not null unique,status varchar(20) not null default 'ACTIVE' check(status in('ACTIVE','REVOKED','EXPIRED')),expires_at timestamptz,last_used_at timestamptz,revoked_at timestamptz,revoked_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,application_id) references integrations.external_api_applications(tenant_id,id));
create table if not exists integrations.external_api_scopes(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,application_id uuid not null,scope varchar(80) not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,application_id,scope),foreign key(tenant_id,application_id) references integrations.external_api_applications(tenant_id,id));
create table if not exists integrations.external_api_request_logs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,application_id uuid not null,method varchar(10) not null,path varchar(500) not null,status_code int not null,duration_ms int not null check(duration_ms>=0),correlation_id varchar(100) not null,occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,application_id) references integrations.external_api_applications(tenant_id,id));

alter table integrations.api_keys add column if not exists revoked_at timestamptz, add column if not exists revoked_by uuid;
alter table integrations.webhook_events drop constraint if exists webhook_events_status_check;
alter table integrations.webhook_events add constraint webhook_events_status_check check(status in('PENDING','PROCESSING','SENT','FAILED','CANCELLED'));

create table if not exists integrations.import_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),entity_type varchar(40) not null,status varchar(20) not null default 'UPLOADED' check(status in('UPLOADED','MAPPING','VALIDATING','READY','PROCESSING','COMPLETED','PARTIAL','FAILED','CANCELLED')),total_rows int not null default 0 check(total_rows>=0),valid_rows int not null default 0 check(valid_rows>=0),error_rows int not null default 0 check(error_rows>=0),progress smallint not null default 0 check(progress between 0 and 100),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,id));
create table if not exists integrations.import_job_files(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,import_job_id uuid not null,file_name varchar(240) not null,content_type varchar(100) not null,storage_reference varchar(500) not null,sha256 char(64) not null,size_bytes bigint not null check(size_bytes>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,import_job_id) references integrations.import_jobs(tenant_id,id));
create table if not exists integrations.import_job_mappings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,import_job_id uuid not null,source_column varchar(160) not null,target_field varchar(160) not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,import_job_id,target_field),foreign key(tenant_id,import_job_id) references integrations.import_jobs(tenant_id,id));
create table if not exists integrations.import_job_rows(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,import_job_id uuid not null,row_number int not null check(row_number>0),data jsonb not null,valid boolean not null,errors jsonb not null default '[]',natural_key varchar(300),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,import_job_id,row_number),foreign key(tenant_id,import_job_id) references integrations.import_jobs(tenant_id,id));
create table if not exists integrations.export_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),entity_type varchar(40) not null,format varchar(10) not null check(format in('CSV','JSON','XLSX','PDF')),filters jsonb not null default '{}',status varchar(20) not null default 'PENDING' check(status in('PENDING','PROCESSING','COMPLETED','FAILED','EXPIRED')),row_count int not null default 0 check(row_count>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,id));
create table if not exists integrations.export_job_files(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,export_job_id uuid not null,file_name varchar(240) not null,storage_reference varchar(500) not null,sha256 char(64) not null,size_bytes bigint not null check(size_bytes>=0),expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,export_job_id) references integrations.export_jobs(tenant_id,id));

create table if not exists fiscal.fiscal_documents(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),document_type varchar(30) not null check(document_type in('NFE','NFCE','NFSE','CTE','MDFE','PRODUCER_INVOICE','FISCAL_WAYBILL','TRANSPORT_DOCUMENT','EXPORT_DOCUMENT','OTHER')),access_key varchar(44),number varchar(30),series varchar(10),issuer_document varchar(20) not null,recipient_document varchar(20) not null,total_amount numeric(18,2) not null check(total_amount>=0),status varchar(30) not null default 'DRAFT' check(status in('DRAFT','IMPORTED','INTERNALLY_VALIDATED','PENDING_SUBMISSION','SENT_TO_PROVIDER','AUTHORIZED','REJECTED','CANCELLED','DENIED','VOIDED','INTEGRATION_ERROR')),provider_protocol varchar(100),provider_response_hash char(64),rejection_reason varchar(1000),cancellation_reason varchar(1000),order_id uuid,contract_id uuid,lot_id uuid,delivery_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id,id));
create unique index if not exists ux_fiscal_access_key on fiscal.fiscal_documents(tenant_id,access_key) where access_key is not null;
create table if not exists fiscal.fiscal_document_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_id uuid not null,line_number int not null check(line_number>0),description varchar(300) not null,ncm varchar(8),cfop varchar(4),unit varchar(10) not null,quantity numeric(18,4) not null check(quantity>0),unit_value numeric(18,6) not null check(unit_value>=0),total_value numeric(18,2) not null check(total_value>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,document_id,line_number),foreign key(tenant_id,document_id) references fiscal.fiscal_documents(tenant_id,id));
create table if not exists fiscal.fiscal_document_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_id uuid not null,event_type varchar(50) not null,from_status varchar(30),to_status varchar(30),safe_message varchar(1000),provider_protocol varchar(100),occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,document_id) references fiscal.fiscal_documents(tenant_id,id));
create table if not exists fiscal.fiscal_document_xml_files(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_id uuid not null,storage_reference varchar(500) not null,sha256 char(64) not null,size_bytes bigint not null check(size_bytes>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,document_id,sha256),foreign key(tenant_id,document_id) references fiscal.fiscal_documents(tenant_id,id));
create table if not exists fiscal.fiscal_drafts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),order_id uuid not null,status varchar(20) not null default 'DRAFT' check(status in('DRAFT','PENDING','READY','QUEUED','CANCELLED')),total_amount numeric(18,2) not null check(total_amount>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,id),unique(tenant_id,order_id));
create table if not exists fiscal.fiscal_draft_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,draft_id uuid not null,product_id uuid not null,description varchar(300) not null,quantity numeric(18,4) not null check(quantity>0),unit_value numeric(18,6) not null check(unit_value>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,draft_id) references fiscal.fiscal_drafts(tenant_id,id));
create table if not exists fiscal.fiscal_pending_issues(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,draft_id uuid not null,code varchar(80) not null,message varchar(500) not null,blocking boolean not null default true,resolved_at timestamptz,resolved_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,draft_id) references fiscal.fiscal_drafts(tenant_id,id));
create table if not exists fiscal.fiscal_product_settings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),product_id uuid not null,ncm varchar(8),default_cfop varchar(4),fiscal_unit varchar(10) not null,origin smallint not null check(origin between 0 and 8),internal_code varchar(60) not null,barcode varchar(14),taxation jsonb not null default '{}',notes varchar(1000),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,product_id),unique(tenant_id,internal_code));
create table if not exists fiscal.fiscal_participant_settings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),participant_type varchar(20) not null check(participant_type in('CUSTOMER','PRODUCER','SUPPLIER','CARRIER')),participant_id uuid not null,tax_document varchar(20) not null,state_registration varchar(30),municipal_registration varchar(30),taxpayer_type varchar(20) not null,fiscal_address jsonb not null,fiscal_email varchar(254),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,participant_type,participant_id));
create table if not exists fiscal.fiscal_integration_providers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),name varchar(120) not null,environment varchar(20) not null check(environment in('HOMOLOGATION','PRODUCTION')),endpoint_url varchar(1000),credential_reference varchar(500),certificate_reference varchar(500),status varchar(30) not null default 'NOT_CONFIGURED' check(status in('NOT_CONFIGURED','ACTIVE','INACTIVE','ERROR')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,unique(tenant_id,id),check(endpoint_url is null or endpoint_url ~ '^https://'));

create index if not exists ix_connector_queue on integrations.integration_connectors(tenant_id,status,type,updated_at desc);
create index if not exists ix_outbox_queue_s30 on integrations.integration_outbox(tenant_id,status,available_at);
create index if not exists ix_api_apps_status on integrations.external_api_applications(tenant_id,status,created_at desc);
create index if not exists ix_api_requests_app on integrations.external_api_request_logs(tenant_id,application_id,occurred_at desc);
create index if not exists ix_import_jobs_queue on integrations.import_jobs(tenant_id,status,created_at desc);
create index if not exists ix_export_jobs_queue on integrations.export_jobs(tenant_id,status,created_at desc);
create index if not exists ix_fiscal_documents_queue on fiscal.fiscal_documents(tenant_id,status,document_type,created_at desc);
create index if not exists ix_fiscal_drafts_queue on fiscal.fiscal_drafts(tenant_id,status,created_at desc);
create index if not exists ix_fiscal_issues_open on fiscal.fiscal_pending_issues(tenant_id,draft_id,blocking) where resolved_at is null;

do $$ declare sch text; tab text; begin foreach sch in array array['integrations','fiscal'] loop for tab in select tablename from pg_tables where schemaname=sch and exists(select 1 from information_schema.columns where table_schema=sch and table_name=tablename and column_name='tenant_id') loop execute format('alter table %I.%I enable row level security',sch,tab); execute format('alter table %I.%I force row level security',sch,tab); if not exists(select 1 from pg_policies where schemaname=sch and tablename=tab and policyname=tab||'_tenant') then execute format('create policy %I on %I.%I using (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid) with check (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',tab||'_tenant',sch,tab); end if; end loop; end loop; end $$;
insert into identity.permissions(code,module,description) values ('external-api.manage','API Externa','Gerenciar aplicações, chaves e escopos.'),('fiscal.read','Fiscal','Consultar documentos fiscais e XML autorizado.'),('fiscal.write','Fiscal','Importar documentos e preparar rascunhos fiscais.'),('fiscal.xml.download','Fiscal','Baixar XML fiscal protegido.'),('exports.create','Integrações','Gerar exportações de dados do tenant.') on conflict(code) do update set module=excluded.module,description=excluded.description;
insert into platform.schema_versions(version,description,installed_at) values('3.0.0','Sprint 30 - Integracoes, API externa, webhooks, import/export e fiscal',now()) on conflict(version) do nothing;
commit;
