-- Sprint 47 — CRM, ciclo comercial SaaS e Customer Success (PostgreSQL 15+)
create sequence if not exists commercial.proposal_public_code_seq;
create sequence if not exists commercial.contract_public_code_seq;

create table if not exists commercial.crm_leads(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),name varchar(160) not null,company varchar(160),document varchar(20),email varchar(254),segment varchar(60) not null,source varchar(60) not null,status varchar(24) not null default 'NEW' check(status in('NEW','QUALIFYING','QUALIFIED','PROPOSAL_SENT','NEGOTIATING','WON','LOST','SUSPENDED','CANCELLED')),revenue_potential numeric(18,2) not null default 0 check(revenue_potential>=0),owner_id uuid references identity.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id,id));
create unique index if not exists ux_crm_leads_document on commercial.crm_leads(tenant_id,document) where document is not null and deleted_at is null;
create unique index if not exists ux_crm_leads_email on commercial.crm_leads(tenant_id,lower(email)) where email is not null and deleted_at is null;
create index if not exists ix_crm_leads_pipeline on commercial.crm_leads(tenant_id,status,owner_id,created_at desc);
create table if not exists commercial.crm_contacts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,lead_id uuid not null,name varchar(160) not null,email varchar(254),phone varchar(30),role varchar(80),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,foreign key(tenant_id,lead_id) references commercial.crm_leads(tenant_id,id),unique(tenant_id,id));
create table if not exists commercial.crm_opportunities(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,lead_id uuid not null,title varchar(180) not null,status varchar(24) not null default 'NEW' check(status in('NEW','QUALIFYING','QUALIFIED','PROPOSAL_SENT','NEGOTIATING','WON','LOST','SUSPENDED','CANCELLED')),revenue_potential numeric(18,2) not null check(revenue_potential>=0),probability numeric(5,2) not null check(probability between 0 and 100),owner_id uuid references identity.users(id),expected_close_on date,loss_reason varchar(1000),won_tenant_id uuid references tenancy.tenants(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,foreign key(tenant_id,lead_id) references commercial.crm_leads(tenant_id,id),unique(tenant_id,id),check(status<>'LOST' or length(trim(loss_reason))>0));
create index if not exists ix_crm_opportunities_pipeline on commercial.crm_opportunities(tenant_id,status,owner_id,expected_close_on);
create table if not exists commercial.crm_activities(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,opportunity_id uuid not null,type varchar(40) not null,description varchar(2000) not null,next_step varchar(1000),due_at timestamptz,completed_at timestamptz,responsible_id uuid references identity.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,foreign key(tenant_id,opportunity_id) references commercial.crm_opportunities(tenant_id,id));
create index if not exists ix_crm_activities_due on commercial.crm_activities(tenant_id,responsible_id,due_at) where completed_at is null;

create table if not exists commercial.commercial_proposals(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),public_code varchar(24) not null default ('PROP-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('commercial.proposal_public_code_seq')::text,6,'0')),lead_id uuid,customer_tenant_id uuid references tenancy.tenants(id),plan_id uuid references saas.plans(id),status varchar(20) not null default 'DRAFT' check(status in('DRAFT','IN_REVIEW','SENT','ACCEPTED','REJECTED','EXPIRED','CANCELLED')),users int not null check(users>0),units int not null check(units>0),monthly_value numeric(18,2) not null check(monthly_value>=0),annual_value numeric(18,2) not null check(annual_value>=0),discount numeric(18,2) not null default 0 check(discount>=0),implementation_value numeric(18,2) not null default 0 check(implementation_value>=0),support_value numeric(18,2) not null default 0 check(support_value>=0),total numeric(18,2) not null check(total>=0),valid_until date not null,notes varchar(4000),rejection_reason varchar(1000),accepted_at timestamptz,accepted_by uuid references identity.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,foreign key(tenant_id,lead_id) references commercial.crm_leads(tenant_id,id),unique(tenant_id,id),unique(public_code),check(lead_id is not null or customer_tenant_id is not null),check(total=round(monthly_value+implementation_value+support_value-discount,2)),check(status<>'REJECTED' or length(trim(rejection_reason))>0));
create index if not exists ix_proposals_status on commercial.commercial_proposals(tenant_id,status,valid_until,customer_tenant_id);
create table if not exists commercial.commercial_proposal_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,proposal_id uuid not null,module_code varchar(80) not null,item_type varchar(20) not null check(item_type in('INCLUDED','ADDITIONAL')),description varchar(300) not null,quantity int not null default 1 check(quantity>0),unit_value numeric(18,2) not null default 0 check(unit_value>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,foreign key(tenant_id,proposal_id) references commercial.commercial_proposals(tenant_id,id));
create table if not exists commercial.commercial_contracts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),public_code varchar(24) not null default ('CONT-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('commercial.contract_public_code_seq')::text,6,'0')),proposal_id uuid not null,customer_tenant_id uuid not null references tenancy.tenants(id),plan_id uuid not null references saas.plans(id),status varchar(30) not null check(status in('DRAFT','ACTIVE','AWAITING_SIGNATURE','SUSPENDED','CANCELLED','ENDED','RENEWED')),monthly_value numeric(18,2) not null check(monthly_value>=0),annual_value numeric(18,2) not null check(annual_value>=0),starts_on date not null,ends_on date not null,renewal_contract_id uuid references commercial.commercial_contracts(id),sla varchar(60) not null,blocking_rule varchar(1000),suspension_reason varchar(1000),cancellation_reason varchar(1000),notes varchar(4000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,foreign key(tenant_id,proposal_id) references commercial.commercial_proposals(tenant_id,id),unique(tenant_id,id),unique(public_code),check(ends_on>starts_on),check(status<>'CANCELLED' or length(trim(cancellation_reason))>0));
create index if not exists ix_contracts_tenant_status on commercial.commercial_contracts(tenant_id,status,customer_tenant_id,ends_on);
create table if not exists commercial.commercial_contract_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,contract_id uuid not null,event_type varchar(40) not null,old_values jsonb,new_values jsonb,reason varchar(1000),created_at timestamptz not null default now(),created_by uuid not null,foreign key(tenant_id,contract_id) references commercial.commercial_contracts(tenant_id,id));

alter table support.knowledge_articles add column if not exists language varchar(10) not null default 'pt-BR';
create table if not exists support.knowledge_base_categories(id uuid primary key default gen_random_uuid(),tenant_id uuid references tenancy.tenants(id),name varchar(120) not null,language varchar(10) not null,internal boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id,name,language));
create index if not exists ix_knowledge_language on support.knowledge_articles(tenant_id,language,status,module,audience) where deleted_at is null;

create table if not exists support.customer_success_accounts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),owner_id uuid references identity.users(id),risk varchar(16) not null default 'LOW' check(risk in('LOW','MEDIUM','HIGH')),next_meeting_at timestamptz,action_summary varchar(2000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz,unique(tenant_id));
create table if not exists support.customer_success_health_scores(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),score int not null check(score between 0 and 100),adoption_percent numeric(5,2) not null,critical_tickets int not null,overdue_invoices int not null,nps int,rule_version varchar(20) not null default 'S47-1',calculated_at timestamptz not null default now(),created_at timestamptz not null default now(),created_by uuid not null);
create index if not exists ix_cs_health on support.customer_success_health_scores(tenant_id,calculated_at desc,score);
create table if not exists support.customer_success_action_plans(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),title varchar(180) not null,description varchar(3000) not null,responsible_id uuid references identity.users(id),due_on date,status varchar(20) not null check(status in('OPEN','IN_PROGRESS','DONE','CANCELLED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null,deleted_at timestamptz);
create table if not exists support.communication_outbox(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenancy.tenants(id),channel varchar(20) not null check(channel in('EMAIL','WHATSAPP','WEBHOOK')),recipient varchar(254) not null,template varchar(80) not null,payload jsonb not null,status varchar(30) not null default 'PENDING_NOT_CONFIGURED' check(status in('PENDING','PENDING_NOT_CONFIGURED','SENT','FAILED')),provider varchar(80),attempts int not null default 0,last_error varchar(2000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null,updated_by uuid not null);
create index if not exists ix_communication_outbox on support.communication_outbox(tenant_id,status,created_at);

alter table commercial.crm_leads enable row level security; alter table commercial.crm_opportunities enable row level security; alter table commercial.commercial_proposals enable row level security; alter table commercial.commercial_contracts enable row level security;
drop policy if exists tenant_isolation on commercial.crm_leads; create policy tenant_isolation on commercial.crm_leads using(tenant_id=current_setting('app.tenant_id',true)::uuid) with check(tenant_id=current_setting('app.tenant_id',true)::uuid);
drop policy if exists tenant_isolation on commercial.crm_opportunities; create policy tenant_isolation on commercial.crm_opportunities using(tenant_id=current_setting('app.tenant_id',true)::uuid) with check(tenant_id=current_setting('app.tenant_id',true)::uuid);
drop policy if exists tenant_isolation on commercial.commercial_proposals; create policy tenant_isolation on commercial.commercial_proposals using(tenant_id=current_setting('app.tenant_id',true)::uuid) with check(tenant_id=current_setting('app.tenant_id',true)::uuid);
drop policy if exists tenant_isolation on commercial.commercial_contracts; create policy tenant_isolation on commercial.commercial_contracts using(tenant_id=current_setting('app.tenant_id',true)::uuid) with check(tenant_id=current_setting('app.tenant_id',true)::uuid);
insert into platform.schema_versions(version,description) values('4.7.0','Sprint 47 - CRM e ciclo completo do cliente SaaS') on conflict(version) do nothing;
