-- Sprint 48 — governança, migração, LGPD, segurança, auditoria e performance (PostgreSQL 15+)
create schema if not exists governance;

create table if not exists governance.data_import_batches(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),module varchar(40) not null,file_name varchar(255) not null,status varchar(32) not null check(status in('UPLOADED','VALIDATING','REQUIRES_CONFIRMATION','VALIDATED','PROCESSING','COMPLETED','FAILED','CANCELLED')),total_rows int not null default 0 check(total_rows>=0),valid_rows int not null default 0 check(valid_rows>=0),error_rows int not null default 0 check(error_rows>=0),confirmed_critical boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references identity.users(id),updated_by uuid references identity.users(id),deleted_at timestamptz);
create table if not exists governance.data_import_batch_rows(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),batch_id uuid not null references governance.data_import_batches(id),row_number int not null check(row_number>0),payload jsonb not null,status varchar(24) not null,created_at timestamptz not null default now(),created_by uuid references identity.users(id),unique(batch_id,row_number));
create table if not exists governance.data_import_mappings(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),batch_id uuid not null references governance.data_import_batches(id),source_column varchar(128) not null,target_field varchar(128) not null,created_at timestamptz not null default now(),created_by uuid references identity.users(id),unique(batch_id,source_column));
create table if not exists governance.data_import_errors(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),batch_id uuid not null references governance.data_import_batches(id),row_number int not null,column_name varchar(128) not null,error_code varchar(64) not null,message varchar(500) not null,severity varchar(16) not null check(severity in('INFO','WARNING','CRITICAL')),created_at timestamptz not null default now(),created_by uuid references identity.users(id));
create table if not exists governance.data_quality_rules(id uuid primary key,tenant_id uuid references tenancy.tenants(id),code varchar(80) not null,name varchar(160) not null,module varchar(40) not null,severity varchar(16) not null,active boolean not null default true,configuration jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references identity.users(id),updated_by uuid references identity.users(id),deleted_at timestamptz,unique(tenant_id,code));
create table if not exists governance.data_quality_findings(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),rule_id uuid references governance.data_quality_rules(id),module varchar(40) not null,entity varchar(80) not null,entity_id uuid,severity varchar(16) not null,status varchar(24) not null default 'OPEN',summary varchar(500) not null,justification varchar(1000),reviewed_by uuid references identity.users(id),reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references identity.users(id),updated_by uuid references identity.users(id),deleted_at timestamptz);
create table if not exists governance.data_quality_actions(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),finding_id uuid not null references governance.data_quality_findings(id),previous_status varchar(24),new_status varchar(24) not null,justification varchar(1000) not null,created_at timestamptz not null default now(),created_by uuid not null references identity.users(id));
create table if not exists governance.data_export_requests(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),modules text[] not null,period_from date,period_to date,format varchar(8) not null check(format in('CSV','JSON')),status varchar(24) not null,justification varchar(1000),requested_by uuid not null references identity.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references identity.users(id),updated_by uuid references identity.users(id),deleted_at timestamptz);
create table if not exists governance.data_export_files(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),request_id uuid not null references governance.data_export_requests(id),storage_key varchar(500) not null,content_type varchar(100) not null,size_bytes bigint not null check(size_bytes>=0),sha256 varchar(64) not null,expires_at timestamptz,created_at timestamptz not null default now(),created_by uuid references identity.users(id));
create table if not exists governance.lgpd_requests(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),type varchar(40) not null,subject_name varchar(200) not null,subject_document varchar(14) not null,legal_basis varchar(120) not null,purpose varchar(500) not null,status varchar(32) not null check(status in('OPEN','IN_REVIEW','AWAITING_VALIDATION','FULFILLED','REFUSED','CANCELLED')),decision_reason varchar(1000),handled_by uuid references identity.users(id),handled_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references identity.users(id),updated_by uuid references identity.users(id),deleted_at timestamptz);
create table if not exists governance.lgpd_request_events(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),request_id uuid not null references governance.lgpd_requests(id),event_type varchar(50) not null,details jsonb not null default '{}',created_at timestamptz not null default now(),created_by uuid not null references identity.users(id));
create table if not exists governance.security_login_events(id uuid primary key,tenant_id uuid references tenancy.tenants(id),user_id uuid references identity.users(id),identifier_hash varchar(64),success boolean not null,reason varchar(120),ip inet,user_agent varchar(500),created_at timestamptz not null default now());
create table if not exists governance.security_sessions(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),user_id uuid not null references identity.users(id),refresh_token_hash varchar(255) not null,ip inet,user_agent varchar(500),last_seen_at timestamptz not null,expires_at timestamptz not null,revoked_at timestamptz,revoked_by uuid references identity.users(id),created_at timestamptz not null default now());
create table if not exists governance.security_password_policies(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),minimum_length int not null default 12,require_upper boolean not null default true,require_lower boolean not null default true,require_number boolean not null default true,require_symbol boolean not null default true,max_failed_attempts int not null default 5,lockout_minutes int not null default 30,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references identity.users(id),updated_by uuid references identity.users(id),unique(tenant_id));
create table if not exists governance.advanced_audit_events(id uuid primary key,tenant_id uuid references tenancy.tenants(id),user_id uuid references identity.users(id),module varchar(60) not null,entity varchar(100) not null,entity_id uuid,action varchar(80) not null,before_data jsonb,after_data jsonb,ip inet,user_agent varchar(500),origin varchar(30) not null,correlation_id varchar(100) not null,justification varchar(1000),created_at timestamptz not null default now());
create table if not exists governance.performance_query_events(id uuid primary key,tenant_id uuid references tenancy.tenants(id),query_name varchar(120) not null,module varchar(60) not null,duration_ms bigint not null,rows_returned int not null,correlation_id varchar(100),created_at timestamptz not null default now());
create table if not exists governance.governance_report_exports(id uuid primary key,tenant_id uuid not null references tenancy.tenants(id),report_type varchar(80) not null,filters jsonb not null default '{}',status varchar(24) not null,storage_key varchar(500),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references identity.users(id),updated_by uuid references identity.users(id));

create index if not exists ix_import_batches_tenant_status_date on governance.data_import_batches(tenant_id,status,created_at desc) where deleted_at is null;
create index if not exists ix_import_errors_batch_severity on governance.data_import_errors(tenant_id,batch_id,severity,row_number);
create index if not exists ix_quality_findings_tenant_status_severity on governance.data_quality_findings(tenant_id,status,severity,created_at desc) where deleted_at is null;
create index if not exists ix_exports_tenant_status_date on governance.data_export_requests(tenant_id,status,created_at desc) where deleted_at is null;
create index if not exists ix_lgpd_tenant_status_date on governance.lgpd_requests(tenant_id,status,created_at desc) where deleted_at is null;
create index if not exists ix_sessions_tenant_user_active on governance.security_sessions(tenant_id,user_id,last_seen_at desc) where revoked_at is null;
create index if not exists ix_login_events_tenant_user_date on governance.security_login_events(tenant_id,user_id,created_at desc);
create index if not exists ix_audit_tenant_module_date on governance.advanced_audit_events(tenant_id,module,created_at desc);
create index if not exists ix_performance_tenant_duration_date on governance.performance_query_events(tenant_id,duration_ms desc,created_at desc);
alter table governance.data_import_batches enable row level security; alter table governance.data_import_errors enable row level security; alter table governance.data_quality_findings enable row level security; alter table governance.data_export_requests enable row level security; alter table governance.lgpd_requests enable row level security; alter table governance.security_sessions enable row level security; alter table governance.advanced_audit_events enable row level security;
do $$ declare t text; begin foreach t in array array['data_import_batches','data_import_errors','data_quality_findings','data_export_requests','lgpd_requests','security_sessions','advanced_audit_events'] loop execute format('drop policy if exists tenant_isolation on governance.%I',t); execute format('create policy tenant_isolation on governance.%I using (tenant_id=current_setting(''app.tenant_id'',true)::uuid) with check (tenant_id=current_setting(''app.tenant_id'',true)::uuid)',t); end loop; end $$;
insert into platform.schema_versions(version,description) values('4.8.0','Sprint 48 - governança, importação, LGPD, segurança e performance') on conflict(version) do nothing;
