using System.ComponentModel.DataAnnotations;
namespace Agro360.Application.Contracts;

public sealed record FleetLookup(Guid Id,string Name);
public sealed record FleetDashboard(int AvailableAssets,int OperatingAssets,int MaintenanceAssets,int UnavailableAssets,int OverdueMaintenances,int UpcomingMaintenances,int OpenWorkOrders,int CriticalWorkOrders,int OverdueWorkOrders,decimal MonthFuelQuantity,decimal MonthFuelCost,int OpenDowntimes,decimal DowntimeHours,decimal AvailabilityPercent,decimal TotalCost);
public sealed record FleetAsset(Guid Id,string InternalCode,string Name,string Type,string Status,string? Brand,string? Model,string? Plate,decimal Odometer,decimal HourMeter,string? PropertyName,string? CostCenterName);
public sealed record FleetAssetCommand([Required,MaxLength(40)]string InternalCode,[Required,MaxLength(160)]string Name,[Required]Guid AssetTypeId,[Required]string Status,[MaxLength(80)]string? Brand,[MaxLength(80)]string? Model,[Range(1900,2200)]int? Year,[MaxLength(20)]string? Plate,[MaxLength(80)]string? SerialNumber,Guid? PropertyId,Guid? CostCenterId,[Range(0,double.MaxValue)]decimal Odometer,[Range(0,double.MaxValue)]decimal HourMeter,[Range(0,double.MaxValue)]decimal? FuelCapacity,Guid? MainOperatorId,DateOnly? AcquiredOn,[Range(0,double.MaxValue)]decimal? AcquisitionValue,[MaxLength(2000)]string? Notes,string? MeterJustification);
public sealed record FleetOperatorCommand([Required,MaxLength(160)]string Name,[MaxLength(40)]string? Document,[Required,MaxLength(40)]string EmploymentType,[Required,MaxLength(80)]string Role,[Required]string Status,Guid? PropertyId,[MaxLength(80)]string? LicenseCategories,DateOnly? LicenseExpiresOn,[MaxLength(2000)]string? Notes);
public sealed record MaintenancePlanCommand([Required]Guid AssetId,[Required,MaxLength(80)]string MaintenanceType,[Required,MaxLength(2000)]string Description,[Range(0.01,double.MaxValue)]decimal Periodicity,[Required]string ControlUnit,DateTimeOffset? NextExecutionAt,decimal? NextMeter,[Required]string Status,Guid? ResponsibleId,[Range(0,double.MaxValue)]decimal EstimatedCost,[Required,MinLength(1)]IReadOnlyList<string> Checklist);
public sealed record WorkOrder(Guid Id,string Code,string AssetName,string Type,string Priority,string Status,DateTimeOffset OpenedAt,DateTimeOffset? DueAt,string Description,decimal Cost);
public sealed record WorkOrderCommand([Required]Guid AssetId,[Required]string Type,[Required]string Priority,Guid? ResponsibleId,DateTimeOffset? DueAt,[Required,MaxLength(4000)]string Description,bool BlockAsset);
public sealed record WorkOrderTransitionCommand([Required]string Status,[MaxLength(4000)]string? Diagnosis,[MaxLength(4000)]string? ServicesPerformed,[MaxLength(1000)]string? Reason,decimal? Odometer,decimal? HourMeter,string? MeterJustification);
public sealed record RefuelingCommand([Required]Guid AssetId,Guid? OperatorId,[Required]Guid FuelTypeId,[Range(0.001,double.MaxValue)]decimal Quantity,[Range(0,double.MaxValue)]decimal UnitPrice,DateTimeOffset OccurredAt,decimal? Odometer,decimal? HourMeter,[MaxLength(160)]string? Location,Guid? PropertyId,Guid? CostCenterId,Guid? EvidenceDocumentId,[MaxLength(2000)]string? Notes,string? MeterJustification);
public sealed record DowntimeCommand([Required]Guid AssetId,[Required]string Type,DateTimeOffset StartedAt,DateTimeOffset? EndedAt,[Required,MaxLength(2000)]string Reason,[Required]Guid ResponsibleId,[MaxLength(2000)]string? OperationalImpact,Guid? SeasonId,Guid? FieldId,Guid? RouteId,bool MakesUnavailable);
public interface IFleetService
{
 Task<FleetDashboard> DashboardAsync(CancellationToken ct); Task<IReadOnlyList<FleetLookup>> LookupsAsync(string kind,string? search,CancellationToken ct);
 Task<IReadOnlyList<FleetAsset>> AssetsAsync(string? search,string? status,int page,int pageSize,CancellationToken ct); Task<Guid> SaveAssetAsync(Guid? id,FleetAssetCommand command,CancellationToken ct);
 Task<Guid> CreateOperatorAsync(FleetOperatorCommand command,CancellationToken ct); Task<Guid> CreateMaintenancePlanAsync(MaintenancePlanCommand command,CancellationToken ct);
 Task<IReadOnlyList<WorkOrder>> WorkOrdersAsync(string? search,string? status,int page,int pageSize,CancellationToken ct); Task<Guid> OpenWorkOrderAsync(WorkOrderCommand command,CancellationToken ct); Task TransitionWorkOrderAsync(Guid id,WorkOrderTransitionCommand command,bool meterOverride,CancellationToken ct);
 Task<Guid> RefuelAsync(RefuelingCommand command,bool meterOverride,CancellationToken ct); Task<Guid> OpenDowntimeAsync(DowntimeCommand command,CancellationToken ct);
}
