namespace Agro360.Application.Contracts;

public sealed record ProcurementSupplierCommand(string LegalName, string? TradeName, string? TaxDocument, string? StateRegistration, string Type, string Category, string? Email, string? Phone, string? Address, string? City, string? State, string Country, string? MainContact, string? PaymentTerms, int AverageDeliveryDays, string Status, string? RejectionReason, string? Notes, string[] Tags);
public sealed record HomologationCommand(DateOnly ValidUntil, bool Fiscal, bool Sanitary, bool Environmental, bool Certifications, bool DeliveryCapacity, bool QualityHistory, bool Commercial, bool Compliance, bool OperationalRisk, string? Reason);
public sealed record CatalogItemCommand(string Name, string Code, string Category, string Unit, string Type, string? Description, bool Active, decimal? MinimumStock, Guid? CostCenterId, bool RequiresLot, bool RequiresExpiry, bool RequiresDocument, bool RequiresInspection, bool RequiresApprovedSupplier, string? Notes, Guid? RelatedProductId = null);
public sealed record RequisitionItemCommand(Guid CatalogItemId, decimal Quantity, string Unit, string? Notes);
public sealed record RequisitionCommand(Guid? CostCenterId, Guid? PropertyId, string Origin, string Justification, string Priority, DateOnly NeededOn, IReadOnlyList<RequisitionItemCommand> Items, bool Submit = false);
public sealed record RequisitionDecisionCommand(long Version, string Decision, string? Reason);
public sealed record RequisitionTransitionCommand(long Version, string? Reason);
public sealed record PurchaseOrderLineCommand(Guid CatalogItemId, decimal Quantity, string Unit, decimal UnitPrice, decimal Discount, Guid? RequisitionItemId = null);
public sealed record PurchaseOrderCommand(Guid SupplierId, Guid? RequisitionId, Guid? QuotationId, Guid? CostCenterId, Guid? PropertyId, string PaymentTerms, DateOnly DeliveryOn, string DeliveryAddress, decimal Freight, decimal Taxes, IReadOnlyList<PurchaseOrderLineCommand> Items);
public sealed record ReceiptLineCommand(Guid PurchaseOrderItemId, decimal Quantity, string? SupplierLot, DateOnly? ExpiresOn, string? Notes);
public sealed record ProcurementReceiptCommand(Guid PurchaseOrderId, DateTimeOffset ReceivedAt, string? InvoiceDocument, bool OverrideExcess, string? ExcessJustification, IReadOnlyList<ReceiptLineCommand> Items, string? IdempotencyKey = null, Guid? WarehouseId = null, Guid? FinanceAccountId = null, DateOnly? FirstDueOn = null, int Installments = 1);
public sealed record ReceiptQualityDecisionCommand(decimal AcceptedQuantity, decimal RejectedQuantity, string Result, string? Reason, string? EvidenceReference, string IdempotencyKey);
public sealed record BillingLineCommand(Guid PurchaseOrderItemId, Guid ReceiptItemId, string Description, decimal Quantity, string Unit, decimal UnitPrice, decimal Discount);
public sealed record PurchaseInvoiceMatchCommand(Guid PurchaseOrderId, string DocumentNumber, string? DocumentSeries, DateOnly IssuedOn, string Currency,
    decimal GoodsTotal, decimal Discount, decimal Freight, decimal AdditionalAmount, decimal Total, string IdempotencyKey,
    IReadOnlyList<BillingLineCommand> Items);
public sealed record MatchDivergenceDecisionCommand(string Decision, string Justification, string? EvidenceReference);
public sealed record MatchToleranceCommand(decimal QuantityPercent, decimal QuantityAbsolute, decimal PricePercent, decimal PriceAbsolute,
    decimal TotalPercent, decimal TotalAbsolute, decimal ExcessPercent, decimal ExcessAbsolute, int DeliveryDays, bool SeparationOfDuties, long? Version);
public sealed record ProcurementQuery(string? Search = null, string? Status = null, string? Category = null, DateOnly? From = null, DateOnly? To = null, int Page = 1, int PageSize = 30);
public interface IProcurementService
{
    Task<dynamic> DashboardAsync(CancellationToken ct); Task<IReadOnlyList<dynamic>> SuppliersAsync(ProcurementQuery q, CancellationToken ct); Task<Guid> SaveSupplierAsync(Guid? id, ProcurementSupplierCommand x, CancellationToken ct); Task HomologateAsync(Guid supplierId, bool approve, HomologationCommand x, CancellationToken ct);
    Task<IReadOnlyList<dynamic>> CatalogAsync(ProcurementQuery q, CancellationToken ct); Task<Guid> SaveCatalogItemAsync(Guid? id, CatalogItemCommand x, CancellationToken ct); Task<Guid> CreateRequisitionAsync(RequisitionCommand x, CancellationToken ct); Task<IReadOnlyList<dynamic>> RequisitionsAsync(ProcurementQuery q, CancellationToken ct); Task<dynamic> RequisitionAsync(Guid id, CancellationToken ct); Task SubmitRequisitionAsync(Guid id, RequisitionTransitionCommand x, CancellationToken ct); Task DecideRequisitionAsync(Guid id, RequisitionDecisionCommand x, CancellationToken ct); Task CancelRequisitionAsync(Guid id, RequisitionTransitionCommand x, CancellationToken ct); Task<IReadOnlyList<dynamic>> ApprovalQueueAsync(ProcurementQuery q, CancellationToken ct);
    Task<Guid> CreateOrderAsync(PurchaseOrderCommand x, CancellationToken ct); Task<IReadOnlyList<dynamic>> OrdersAsync(ProcurementQuery q, CancellationToken ct); Task ApproveOrderAsync(Guid id, string? comment, CancellationToken ct); Task CancelOrderAsync(Guid id, RequisitionTransitionCommand x, CancellationToken ct); Task<Guid> ReceiveAsync(ProcurementReceiptCommand x, CancellationToken ct); Task<IReadOnlyList<dynamic>> ReceiptsAsync(ProcurementQuery q, CancellationToken ct); Task<dynamic> ReceiptAsync(Guid id, CancellationToken ct); Task<Guid> DecideQualityAsync(Guid receiptItemId, ReceiptQualityDecisionCommand x, CancellationToken ct); Task<IReadOnlyList<dynamic>> PendingOrderItemsAsync(Guid orderId, CancellationToken ct); Task<dynamic> ReceiptOptionsAsync(CancellationToken ct); Task<byte[]> ExportAsync(string report, ProcurementQuery q, CancellationToken ct);
    Task<Guid> MatchInvoiceAsync(PurchaseInvoiceMatchCommand command, CancellationToken ct); Task<IReadOnlyList<dynamic>> InvoiceMatchesAsync(ProcurementQuery query, CancellationToken ct); Task<dynamic> InvoiceMatchAsync(Guid id, CancellationToken ct); Task<IReadOnlyList<dynamic>> MatchOptionsAsync(Guid orderId, CancellationToken ct); Task ResolveMatchDivergenceAsync(Guid id, MatchDivergenceDecisionCommand command, CancellationToken ct); Task<dynamic> MatchToleranceAsync(CancellationToken ct); Task<Guid> SaveMatchToleranceAsync(MatchToleranceCommand command, CancellationToken ct);
}
public interface IProcurementStockGateway { Task RegisterPurchaseReceiptAsync(Guid receiptId, CancellationToken ct); }
public interface IProcurementFinanceGateway { Task RegisterPayableForecastAsync(Guid purchaseOrderId, CancellationToken ct); }
public interface IProcurementDocumentGateway { Task RequireEvidenceAsync(string entity, Guid entityId, string requirement, CancellationToken ct); }
public interface IProcurementQualityGateway { Task RequestInspectionAsync(Guid receiptItemId, CancellationToken ct); }
